[package]
name = "litchi-ole-common"
description = "Shared validated structures for legacy binary Office formats."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
litchi-cfb = { workspace = true }
litchi-codepage = { workspace = true }
quick-xml = { workspace = true }

[lints]
workspace = true
