//! Build a small RTF document using the public `write::Writer` API and write it to disk.
//!
//! This example demonstrates direct streaming of RTF control words through
//! `write::Writer` plus the higher-level helpers (`write_hyperlink`, `write_note`,
//! `write_revision`). The resulting file is also re-parsed with
//! `Document::parse` to round-trip the bytes through the parser.
//!
//! Run from the workspace root:
//!
//! ```bash
//! cargo run -p litchi-rtf --example write_rtf
//! ```

use litchi_rtf::Document;
use litchi_rtf::field::{Field, FieldType};
use litchi_rtf::review::{Note, Revision};
use litchi_rtf::text::Formatting;
use litchi_rtf::write::{Charset, Options, TabWidth, Writer};
use std::borrow::Cow;
use std::num::NonZeroU16;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut output: Vec<u8> = Vec::new();

    // Use explicit options instead of `Writer::new` to demonstrate the
    // configuration surface (code page, default font, etc.).
    let options = Options {
        charset: Charset::ansi(1252)?,
        indent: false,
        default_font: 0,
        default_tab_width: TabWidth::Override(720),
    };
    let mut writer = Writer::with_options(&mut output, options);

    // RTF preamble: \rtf1, charset, default font, font/color tables, ...
    writer.write_document_header()?;

    // Title
    writer.write_str("{\\b\\fs32 litchi-rtf write_rtf example\\par}\\par")?;

    // Body paragraph with a hyperlink
    writer.write_str("{\\fs24 Visit ")?;
    writer.write_hyperlink("https://github.com/DevExzh/litchi", "the Litchi repository")?;
    writer.write_str(" for the source.\\par}\\par")?;

    // Footnote attached to the next paragraph
    writer.write_str("{\\fs24 RTF supports footnotes")?;
    let footnote = Note::footnote(
        Cow::Borrowed("1"),
        Cow::Borrowed("Generated by the litchi-rtf write_rtf example."),
    );
    writer.write_note(&footnote)?;
    writer.write_str(".\\par}\\par")?;

    // Tracked-change insertion
    writer.write_str("{\\fs24 This sentence contains ")?;
    let revision = Revision::insertion(
        Cow::Borrowed("litchi-rtf"),
        Cow::Borrowed("a tracked insertion"),
    );
    writer.write_revision(&revision)?;
    writer.write_str(".\\par}\\par")?;

    // PAGE field
    let page_field = Field::new(FieldType::Page, Cow::Borrowed("PAGE"), Cow::Borrowed("1"));
    writer.write_str("{\\fs20 Page ")?;
    writer.write_field(&page_field)?;
    writer.write_str(" of document.\\par}\\par")?;

    // A short emphasised paragraph using an explicit `Formatting` value to
    // show that the model types are usable from this crate as a library.
    let emphasis = Formatting {
        bold: true,
        italic: true,
        font_size: NonZeroU16::new(28).expect("non-zero"),
        ..Default::default()
    };
    writer.write_str("{")?;
    if emphasis.bold {
        writer.write_str("\\b")?;
    }
    if emphasis.italic {
        writer.write_str("\\i")?;
    }
    writer.write_str(&format!(
        "\\fs{} Bold + italic line via Formatting.\\par",
        emphasis.font_size.get()
    ))?;
    writer.write_str("}\\par")?;

    // Close the root group and flush the inner writer.
    writer.write_str("}")?;
    writer.flush()?;

    let out_path = std::env::temp_dir().join("litchi_rtf_write_example.rtf");
    std::fs::write(&out_path, &output)?;

    println!("Wrote {} bytes to {}", output.len(), out_path.display());

    // Round-trip: parse the output back so the example also exercises the reader.
    let rtf_text = std::str::from_utf8(&output)?;
    let parsed = Document::parse(rtf_text)?;
    println!("Round-trip text length    : {}", parsed.text().len());
    println!("Round-trip paragraph count: {}", parsed.paragraph_count());
    println!("Round-trip note count     : {}", parsed.notes().len());
    println!("Round-trip field count    : {}", parsed.fields().len());

    Ok(())
}
