[package]
name = "litchi-formula-fuzz"
version = "0.0.0"
edition = "2024"
publish = false
authors = ["Ryker Zhu <ryker.zhu@outlook.com>"]
license = "Apache-2.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
litchi-formula = { path = ".." }

[[bin]]
name = "convert_formula"
path = "fuzz_targets/convert_formula.rs"
test = false
doc = false
bench = false

[profile.release]
debug = 1
codegen-units = 1
lto = "thin"

[workspace]
