//! Retained execution-budget leases for generated form-control state.

use std::sync::Arc;

use litchi_core::{ExecutionContext, ExecutionError, Reservation, Resource};

use crate::error::{Error, Result, invalid};
pub(crate) use crate::source_payload::{
    ARC_HEADER_BYTES, RETAINED_BUDGET_HOLD_STORAGE_BYTES, RetainedBudgetHold,
    SOURCE_PAYLOAD_ARC_STORAGE_BYTES, retained_budget_hold,
};

/// Reserve generated bytes and owner objects for the lifetime of the returned
/// clone-shared lease. A missing context keeps the existing unmanaged path.
pub(crate) fn reserve_generated(
    context: Option<&ExecutionContext>,
    memory_bytes: usize,
    objects: usize,
    scope: &'static str,
) -> Result<Option<Arc<RetainedBudgetHold>>> {
    let Some(context) = context else {
        return Ok(None);
    };
    let memory_bytes = memory_bytes
        .checked_add(RETAINED_BUDGET_HOLD_STORAGE_BYTES)
        .ok_or_else(|| invalid("form-control retained budget size overflow"))?;
    let memory = reserve_one(context, Resource::Memory, memory_bytes, scope)?;
    let objects = reserve_one(context, Resource::Objects, objects, scope)?;
    Ok(Some(retained_budget_hold(memory, objects)))
}

fn reserve_one(
    context: &ExecutionContext,
    resource: Resource,
    amount: usize,
    scope: &'static str,
) -> Result<Option<Reservation>> {
    if amount == 0 {
        return Ok(None);
    }
    let amount = u64::try_from(amount)
        .map_err(|_| invalid("form-control retained budget amount overflow"))?;
    context
        .reserve(resource, amount)
        .map(Some)
        .map_err(|error| map_execution_error(error, scope))
}

fn map_execution_error(error: ExecutionError, _scope: &'static str) -> Error {
    match error {
        ExecutionError::ResourceLimit(limit) => Error::ResourceLimit(limit),
        other => Error::Package(litchi_opc::OpcError::Execution(other)),
    }
}
