[package]
name = "litchi-keynote-fuzz"
version = "0.0.0"
edition = "2024"
publish = false
authors = ["Ryker Zhu <ryker.zhu@outlook.com>"]
license = "Apache-2.0"

[package.metadata]
cargo-fuzz = true

[workspace]

[[bin]]
name = "keynote_slide_audio_position"
path = "fuzz_targets/keynote_slide_audio_position.rs"
test = false
doc = false
bench = false

[[bin]]
name = "keynote_slide_media_properties"
path = "fuzz_targets/keynote_slide_media_properties.rs"
test = false
doc = false
bench = false

[[bin]]
name = "keynote_slide_audio_creation"
path = "fuzz_targets/keynote_slide_audio_creation.rs"
test = false
doc = false
bench = false

[[bin]]
name = "keynote_slide_movie_creation"
path = "fuzz_targets/keynote_slide_movie_creation.rs"
test = false
doc = false
bench = false

[[bin]]
name = "keynote_slide_movie_geometry"
path = "fuzz_targets/keynote_slide_movie_geometry.rs"
test = false
doc = false
bench = false

[dependencies]
libfuzzer-sys = "0.4"
litchi-iwa-common = { path = "../../litchi-iwa-common" }
litchi-keynote = { path = ".." }

[profile.release]
debug = 1
codegen-units = 1
lto = "thin"
