//! Building-block and AutoText field models.

use super::{Field, Switch};

use crate::error::Result;

use super::super::codec::{
    field_instruction_remainder, parse_auto_text_field_parts, parse_auto_text_list_field_parts,
};

/// The stored kind of a Word building-block field.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AutoTextKind {
    /// A historical `GLOSSARY` field.
    Glossary,
    /// An `AUTOTEXT` field.
    AutoText,
}

/// A typed, inert Word `GLOSSARY` or `AUTOTEXT` field.
///
/// ECMA-376 Part 1 §17.16.5.5 defines `AUTOTEXT`; `GLOSSARY` is its
/// historical equivalent. This type retains only the stored category, entry
/// name, switches, cached result, and state. It never looks up a building
/// block, reads a template, inserts content, changes bookmarks, refreshes a
/// field, or accesses an external resource.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AutoText {
    instruction: String,
    kind: AutoTextKind,
    entry_name: String,
    unknown_switches: Vec<Switch>,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
}

impl AutoText {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let Some((kind, entry_name, unknown_switches)) =
            parse_auto_text_field_parts(field.instruction())?
        else {
            return Ok(None);
        };

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            kind,
            entry_name,
            unknown_switches,
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
        }))
    }

    /// Return the complete stored field instruction.
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return whether this stores `GLOSSARY` or `AUTOTEXT` metadata.
    pub fn kind(&self) -> AutoTextKind {
        self.kind
    }

    /// Return the stored building-block entry name without resolving it.
    pub fn entry_name(&self) -> &str {
        &self.entry_name
    }

    /// Return unrecognized stored switches in source order.
    ///
    /// They are retained without interpretation or execution.
    pub fn unknown_switches(&self) -> &[Switch] {
        &self.unknown_switches
    }

    /// Return the cached visible field result, if present.
    ///
    /// This is stored text only and is never regenerated by looking up or
    /// inserting content.
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

/// One recognized stored option of a Word `AUTOTEXTLIST` field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AutoTextListOption {
    /// The `\\s` style name used to limit eligible building blocks.
    Style(String),
    /// The `\\t` stored tip text.
    Tip(String),
}

/// A typed, inert Word `AUTOTEXTLIST` field.
///
/// ECMA-376 Part 1 §17.16.5.6 defines `AUTOTEXTLIST` using optional
/// display text and style/tip switches. This type retains only those stored
/// values, unknown switches, cached result, and state. It never shows a
/// selection UI, looks up eligible building blocks, reads a template, inserts
/// content, or refreshes a field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AutoTextList {
    instruction: String,
    display_text: Option<String>,
    options: Vec<AutoTextListOption>,
    unknown_switches: Vec<Switch>,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
}

impl AutoTextList {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let Some((display_text, options, unknown_switches)) =
            parse_auto_text_list_field_parts(field.instruction())?
        else {
            return Ok(None);
        };

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            display_text,
            options,
            unknown_switches,
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
        }))
    }

    /// Return the complete stored field instruction.
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return the optional stored display text.
    ///
    /// This text is metadata only and never triggers a selection UI.
    pub fn display_text(&self) -> Option<&str> {
        self.display_text.as_deref()
    }

    /// Return recognized stored options in source order.
    ///
    /// This metadata is never used to query, select, or insert a building
    /// block.
    pub fn options(&self) -> &[AutoTextListOption] {
        &self.options
    }

    /// Return unrecognized stored switches in source order.
    ///
    /// They are retained without interpretation or execution.
    pub fn unknown_switches(&self) -> &[Switch] {
        &self.unknown_switches
    }

    /// Return the cached visible field result, if present.
    ///
    /// This is stored text only and is never regenerated by selection or
    /// content insertion.
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

impl Field {
    /// Check whether this is a `GLOSSARY` or `AUTOTEXT` building-block field.
    ///
    /// Recognition is limited to stored metadata. It never looks up a building
    /// block, reads a template, inserts content, changes bookmarks, or refreshes
    /// a field result.
    pub fn is_auto_text_field(&self) -> bool {
        field_instruction_remainder(&self.instruction, "GLOSSARY").is_some()
            || field_instruction_remainder(&self.instruction, "AUTOTEXT").is_some()
    }

    /// Parse this field as inert typed building-block metadata.
    ///
    /// Returns `Ok(None)` for fields other than `GLOSSARY` and `AUTOTEXT`.
    /// The stored kind, entry name, switches, cached content, and dirty/lock
    /// state are metadata only; this method never looks up a building block,
    /// reads a template, inserts content, changes bookmarks, accesses an
    /// external resource, or refreshes a field.
    pub fn auto_text_field(&self) -> Result<Option<AutoText>> {
        AutoText::from_field(self)
    }

    /// Check whether this is an `AUTOTEXTLIST` building-block selection field.
    ///
    /// Recognition is limited to stored metadata. It never shows a selection
    /// UI, looks up eligible building blocks, reads a template, inserts
    /// content, or refreshes a field result.
    pub fn is_auto_text_list_field(&self) -> bool {
        field_instruction_remainder(&self.instruction, "AUTOTEXTLIST").is_some()
    }

    /// Parse this field as inert typed building-block selection metadata.
    ///
    /// Returns `Ok(None)` for fields other than `AUTOTEXTLIST`. The
    /// stored display text, style/tip options, switches, cached content, and
    /// dirty/lock state are metadata only; this method never shows a selection
    /// UI, looks up eligible building blocks, reads a template, inserts
    /// content, accesses an external resource, or refreshes a field.
    pub fn auto_text_list_field(&self) -> Result<Option<AutoTextList>> {
        AutoTextList::from_field(self)
    }
}
