#![expect(
    clippy::shadow_reuse,
    reason = "parser bindings are intentionally refined after validation"
)]
#![expect(
    clippy::struct_field_names,
    reason = "the public model retains established field names"
)]
//! Conditional, formula, and comparison field models.

use super::Field;

use crate::error::{Error, Result};

use super::super::codec::{
    field_instruction_remainder, parse_formula_field_formula, parse_sequence_field_parts,
    parse_set_field_parts,
};

use super::super::MAX_EQUATION_FIELD_INSTRUCTION_BYTES;

/// A typed, inert Word `IF` field.
///
/// ECMA-376 Part 1 §17.16.5.26 defines `IF` using a comparison and two
/// branches. This type retains the unparsed expression and cached result only.
/// It never parses or evaluates an expression, resolves field values, or
/// refreshes a field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct If {
    instruction: String,
    expression: String,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
}

impl If {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let Some(expression) = field_instruction_remainder(field.instruction(), "IF") else {
            return Ok(None);
        };
        let expression = expression.trim();
        if expression.is_empty() {
            return Err(Error::Invalid(
                "IF field is missing its expression".to_string(),
            ));
        }

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            expression: expression.to_string(),
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
        }))
    }

    /// Return the complete stored field instruction.
    #[must_use]
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return the stored expression without parsing or evaluating it.
    #[must_use]
    pub fn expression(&self) -> &str {
        &self.expression
    }

    /// Return the cached visible field result, if present.
    ///
    /// This is stored text only and is never regenerated by field evaluation.
    #[must_use]
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    #[must_use]
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    #[must_use]
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

/// A typed, inert Word `SET` field.
///
/// ECMA-376 Part 1 §17.16.5.57 defines `SET` using a target name and an
/// expression. This type retains the stored target, opaque expression, and
/// cached result only. It never evaluates an expression, looks up or changes a
/// bookmark, changes document state, or refreshes a field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Set {
    instruction: String,
    target_name: String,
    expression: String,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
}

impl Set {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let Some((target_name, expression)) = parse_set_field_parts(field.instruction())? else {
            return Ok(None);
        };

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            target_name,
            expression,
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
        }))
    }

    /// Return the complete stored field instruction.
    #[must_use]
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return the stored target name without looking it up or changing it.
    #[must_use]
    pub fn target_name(&self) -> &str {
        &self.target_name
    }

    /// Return the opaque stored expression text.
    ///
    /// This text is never parsed, evaluated, or used to change document state.
    #[must_use]
    pub fn expression(&self) -> &str {
        &self.expression
    }

    /// Return the cached visible field result, if present.
    ///
    /// This is stored text only and is never regenerated by expression
    /// evaluation.
    #[must_use]
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    #[must_use]
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    #[must_use]
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

/// A typed, inert Word `SEQ` field.
///
/// ECMA-376 Part 1 §17.16.5.56 defines `SEQ` using an identifier, optional
/// bookmark, and optional switches. This type retains those stored values and a
/// cached result only. It never looks up a bookmark, increments or resets a
/// sequence, calculates a number, or refreshes a field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Sequence {
    instruction: String,
    identifier: String,
    bookmark: Option<String>,
    tail: String,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
}

impl Sequence {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let Some((identifier, bookmark, tail)) = parse_sequence_field_parts(field.instruction())?
        else {
            return Ok(None);
        };

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            identifier,
            bookmark,
            tail,
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
        }))
    }

    /// Return the complete stored field instruction.
    #[must_use]
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return the stored sequence identifier without calculating its value.
    #[must_use]
    pub fn identifier(&self) -> &str {
        &self.identifier
    }

    /// Return the optional stored bookmark name without looking it up.
    #[must_use]
    pub fn bookmark(&self) -> Option<&str> {
        self.bookmark.as_deref()
    }

    /// Return opaque stored text after the identifier and optional bookmark.
    ///
    /// This text is never parsed to change or calculate a sequence.
    #[must_use]
    pub fn tail(&self) -> &str {
        &self.tail
    }

    /// Return the cached visible field result, if present.
    ///
    /// This is stored text only and is never regenerated by calculating a
    /// sequence number.
    #[must_use]
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    #[must_use]
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    #[must_use]
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

/// A typed, inert Word `=` formula field.
///
/// ECMA-376 Part 1 §17.16.3.3 defines table formulas using a leading `=`.
/// This type retains the stored formula text and cached result only. It never
/// parses or evaluates a formula, reads table cells or bookmarks, resolves
/// field values, or refreshes a field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Formula {
    instruction: String,
    formula: String,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
}

impl Formula {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let Some(formula) = parse_formula_field_formula(field.instruction())? else {
            return Ok(None);
        };

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            formula,
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
        }))
    }

    /// Return the complete stored field instruction.
    #[must_use]
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return the opaque stored formula text without parsing or evaluating it.
    #[must_use]
    pub fn formula(&self) -> &str {
        &self.formula
    }

    /// Return the cached visible field result, if present.
    ///
    /// This is stored text only and is never regenerated by formula evaluation.
    #[must_use]
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    #[must_use]
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    #[must_use]
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

/// A typed, inert Word `EQ` equation field.
///
/// This type retains only stored equation syntax, a cached result, and field
/// state. It never parses, calculates, formats, renders, or refreshes an
/// equation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Equation {
    instruction: String,
    expression: String,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
}

impl Equation {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let Some(expression) = field_instruction_remainder(field.instruction(), "EQ") else {
            return Ok(None);
        };
        if field.instruction().len() > MAX_EQUATION_FIELD_INSTRUCTION_BYTES {
            return Err(Error::Invalid(format!(
                "EQ field instruction exceeds {MAX_EQUATION_FIELD_INSTRUCTION_BYTES} bytes"
            )));
        }

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            expression: expression.trim().to_string(),
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
        }))
    }

    /// Return the complete stored field instruction.
    #[must_use]
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return the opaque equation expression after the `EQ` keyword.
    ///
    /// This syntax is never parsed, calculated, formatted, or rendered.
    #[must_use]
    pub fn expression(&self) -> &str {
        &self.expression
    }

    /// Return the cached visible field result, if present.
    ///
    /// This is stored text only and is never regenerated from equation syntax.
    #[must_use]
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    #[must_use]
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    #[must_use]
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

/// A typed, inert Word `COMPARE` field.
///
/// ECMA-376 Part 1 §17.16.5.10 defines `COMPARE` using a comparison whose
/// result is 1 or 0. This type retains the unparsed comparison and cached
/// result only. It never parses or evaluates a comparison, resolves nested
/// field values, or refreshes a field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Compare {
    instruction: String,
    comparison: String,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
}

impl Compare {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let Some(comparison) = field_instruction_remainder(field.instruction(), "COMPARE") else {
            return Ok(None);
        };
        let comparison = comparison.trim();
        if comparison.is_empty() {
            return Err(Error::Invalid(
                "COMPARE field is missing its comparison".to_string(),
            ));
        }

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            comparison: comparison.to_string(),
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
        }))
    }

    /// Return the complete stored field instruction.
    #[must_use]
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return the stored comparison without parsing or evaluating it.
    #[must_use]
    pub fn comparison(&self) -> &str {
        &self.comparison
    }

    /// Return the cached visible field result, if present.
    ///
    /// This is stored text only and is never regenerated by field evaluation.
    #[must_use]
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    #[must_use]
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    #[must_use]
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

impl Field {
    /// Check whether this is an `IF` conditional field.
    ///
    /// Recognition is limited to the stored instruction. It never parses or
    /// evaluates an expression, resolves field values, or refreshes the result.
    #[must_use]
    pub fn is_if_field(&self) -> bool {
        field_instruction_remainder(&self.instruction, "IF").is_some()
    }

    /// Parse this field as inert typed `IF` metadata.
    ///
    /// Returns `Ok(None)` for fields other than `IF`. The stored expression,
    /// cached content, and dirty/lock state are metadata only; this method never
    /// parses or evaluates an expression, resolves field values, or refreshes a
    /// field.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation cannot be completed.
    pub fn if_field(&self) -> Result<Option<If>> {
        If::from_field(self)
    }

    /// Check whether this is a `COMPARE` field.
    ///
    /// Recognition is limited to the stored instruction. It never parses or
    /// evaluates a comparison, resolves nested field values, or refreshes the
    /// cached result.
    #[must_use]
    pub fn is_compare_field(&self) -> bool {
        field_instruction_remainder(&self.instruction, "COMPARE").is_some()
    }

    /// Parse this field as inert typed `COMPARE` metadata.
    ///
    /// Returns `Ok(None)` for fields other than `COMPARE`. The stored
    /// comparison, cached content, and dirty/lock state are metadata only; this
    /// method never parses or evaluates a comparison, resolves nested field
    /// values, or refreshes a field.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation cannot be completed.
    pub fn compare_field(&self) -> Result<Option<Compare>> {
        Compare::from_field(self)
    }

    /// Check whether this is a `SET` field.
    ///
    /// Recognition is limited to the stored instruction. It never evaluates an
    /// expression, looks up or changes a bookmark, changes document state, or
    /// refreshes the result.
    #[must_use]
    pub fn is_set_field(&self) -> bool {
        field_instruction_remainder(&self.instruction, "SET").is_some()
    }

    /// Parse this field as inert typed `SET` metadata.
    ///
    /// Returns `Ok(None)` for fields other than `SET`. The stored target,
    /// opaque expression, cached content, and dirty/lock state are metadata
    /// only; this method never evaluates an expression, looks up or changes a
    /// bookmark, changes document state, or refreshes a field.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation cannot be completed.
    pub fn set_field(&self) -> Result<Option<Set>> {
        Set::from_field(self)
    }

    /// Check whether this is a `SEQ` field.
    ///
    /// Recognition is limited to the stored instruction. It never looks up a
    /// bookmark, increments or resets a sequence, calculates a number, or
    /// refreshes the result.
    #[must_use]
    pub fn is_sequence_field(&self) -> bool {
        field_instruction_remainder(&self.instruction, "SEQ").is_some()
    }

    /// Parse this field as inert typed `SEQ` metadata.
    ///
    /// Returns `Ok(None)` for fields other than `SEQ`. The stored identifier,
    /// optional bookmark, opaque tail, cached content, and dirty/lock state are
    /// metadata only; this method never looks up a bookmark, increments or
    /// resets a sequence, calculates a number, or refreshes a field.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation cannot be completed.
    pub fn sequence_field(&self) -> Result<Option<Sequence>> {
        Sequence::from_field(self)
    }

    /// Check whether this is a Word `=` formula field.
    ///
    /// Recognition is limited to the stored instruction. It never parses or
    /// evaluates a formula, reads table cells or bookmarks, resolves field
    /// values, or refreshes the result.
    #[must_use]
    pub fn is_formula_field(&self) -> bool {
        self.instruction.trim_start().starts_with('=')
    }

    /// Parse this field as inert typed formula metadata.
    ///
    /// Returns `Ok(None)` for fields that do not begin with `=`. The stored
    /// formula, cached content, and dirty/lock state are metadata only; this
    /// method never parses or evaluates a formula, reads table cells or
    /// bookmarks, resolves field values, or refreshes a field.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation cannot be completed.
    pub fn formula_field(&self) -> Result<Option<Formula>> {
        Formula::from_field(self)
    }

    /// Check whether this is an `EQ` equation field.
    ///
    /// Recognition is limited to stored field metadata. It never parses,
    /// calculates, formats, renders, or refreshes an equation.
    #[must_use]
    pub fn is_equation(&self) -> bool {
        field_instruction_remainder(&self.instruction, "EQ").is_some()
    }

    /// Parse this field as inert `EQ` equation metadata.
    ///
    /// Returns `Ok(None)` for fields other than `EQ`. The stored expression,
    /// cached content, and dirty/lock state are metadata only; this method never
    /// parses, calculates, formats, renders, or refreshes an equation.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation cannot be completed.
    pub fn equation(&self) -> Result<Option<Equation>> {
        Equation::from_field(self)
    }
}
