#![expect(
    clippy::expect_used,
    reason = "the invariant is established immediately before extraction"
)]
#![expect(
    clippy::shadow_reuse,
    reason = "parser bindings are intentionally refined after validation"
)]
//! Text, numbering, and style-reference field models.

use super::{Field, Switch};

use crate::error::{Error, Result};

use super::super::codec::{
    field_instruction_remainder, has_field_switch, parse_field_operand_and_switches,
    parse_field_switches, parse_style_reference_field_parts,
};

use super::super::{
    MAX_AUTO_NUMBER_FIELD_INSTRUCTION_BYTES, MAX_LIST_NUMBER_FIELD_INSTRUCTION_BYTES,
    MAX_QUOTE_FIELD_INSTRUCTION_BYTES, MAX_SYMBOL_FIELD_INSTRUCTION_BYTES,
};

/// A typed, inert Word `QUOTE` field.
///
/// ECMA-376 Part 1 §17.16.5.49 defines `QUOTE` with a text field argument.
/// This type retains that stored argument, switches, and cached result only. It
/// never interprets character codes, expands nested fields, inserts text, or
/// refreshes a field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Quote {
    instruction: String,
    text: String,
    switches: Vec<Switch>,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
}

impl Quote {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        if field.instruction.len() > MAX_QUOTE_FIELD_INSTRUCTION_BYTES {
            return Err(Error::Invalid(format!(
                "QUOTE field instruction exceeds {MAX_QUOTE_FIELD_INSTRUCTION_BYTES} bytes"
            )));
        }
        let Some((text, switches)) =
            parse_field_operand_and_switches(field.instruction(), "QUOTE")?
        else {
            return Ok(None);
        };
        let text = text.ok_or_else(|| {
            Error::Invalid("QUOTE field is missing its text argument".to_string())
        })?;

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            text,
            switches,
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
        }))
    }

    /// Return the complete stored field instruction.
    #[must_use]
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return the stored text argument without inserting or transforming it.
    #[must_use]
    pub fn text(&self) -> &str {
        &self.text
    }

    /// Return preserved switches in source order without interpreting them.
    #[must_use]
    pub fn switches(&self) -> &[Switch] {
        &self.switches
    }

    /// Check whether a case-insensitive ASCII switch appears in this field.
    #[must_use]
    pub fn has_switch(&self, name: char) -> bool {
        has_field_switch(&self.switches, name)
    }

    /// Return the cached visible field result, if present.
    ///
    /// This is stored text only and is never regenerated by inserting text.
    #[must_use]
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    #[must_use]
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    #[must_use]
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

/// A typed, inert Word `SYMBOL` field.
///
/// ECMA-376 Part 1 §17.16.5.61 defines `SYMBOL` with one stored character
/// argument and optional switches. This type retains that argument, switches,
/// and cached result only. It never converts a character code, looks up a font,
/// inserts a glyph, changes formatting or layout, or refreshes a field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Symbol {
    instruction: String,
    character_argument: String,
    switches: Vec<Switch>,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
}

impl Symbol {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        if field.instruction.len() > MAX_SYMBOL_FIELD_INSTRUCTION_BYTES {
            return Err(Error::Invalid(format!(
                "SYMBOL field instruction exceeds {MAX_SYMBOL_FIELD_INSTRUCTION_BYTES} bytes"
            )));
        }
        let Some((character_argument, switches)) =
            parse_field_operand_and_switches(field.instruction(), "SYMBOL")?
        else {
            return Ok(None);
        };
        let character_argument = character_argument.ok_or_else(|| {
            Error::Invalid("SYMBOL field is missing its character argument".to_string())
        })?;

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            character_argument,
            switches,
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
        }))
    }

    /// Return the complete stored field instruction.
    #[must_use]
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return the stored character argument without converting it to a glyph.
    #[must_use]
    pub fn character_argument(&self) -> &str {
        &self.character_argument
    }

    /// Return preserved switches in source order without interpreting them.
    #[must_use]
    pub fn switches(&self) -> &[Switch] {
        &self.switches
    }

    /// Check whether a case-insensitive ASCII switch appears in this field.
    #[must_use]
    pub fn has_switch(&self, name: char) -> bool {
        has_field_switch(&self.switches, name)
    }

    /// Return the cached visible field result, if present.
    ///
    /// This is stored text only and is never regenerated by mapping a character
    /// code or inserting a glyph.
    #[must_use]
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    #[must_use]
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    #[must_use]
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

/// The legacy Word automatic-numbering field category.
///
/// `AUTONUM`, `AUTONUMLGL`, and `AUTONUMOUT` are retained for
/// document compatibility. This enum preserves the stored field kind only; it
/// does not calculate a number, inspect paragraphs, headings, or styles, or
/// change layout.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AutoNumberKind {
    AutoNum,
    AutoNumLegal,
    AutoNumOutline,
}

impl AutoNumberKind {
    /// The uppercase field keyword stored in a Word field instruction.
    #[must_use]
    pub const fn field_keyword(self) -> &'static str {
        match self {
            Self::AutoNum => "AUTONUM",
            Self::AutoNumLegal => "AUTONUMLGL",
            Self::AutoNumOutline => "AUTONUMOUT",
        }
    }

    fn from_instruction(instruction: &str) -> Option<Self> {
        [Self::AutoNum, Self::AutoNumLegal, Self::AutoNumOutline]
            .into_iter()
            .find(|kind| field_instruction_remainder(instruction, kind.field_keyword()).is_some())
    }
}

/// Typed, inert metadata for a legacy Word automatic-numbering field.
///
/// This type retains the stored kind, switches, cached result, and field state
/// only. It never calculates paragraph numbers, reads heading or style state,
/// changes paragraphs or layout, or refreshes a field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AutoNumber {
    instruction: String,
    kind: AutoNumberKind,
    switches: Vec<Switch>,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
}

impl AutoNumber {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let Some(kind) = AutoNumberKind::from_instruction(field.instruction()) else {
            return Ok(None);
        };
        if field.instruction().len() > MAX_AUTO_NUMBER_FIELD_INSTRUCTION_BYTES {
            return Err(Error::Invalid(format!(
                "{} field instruction exceeds {MAX_AUTO_NUMBER_FIELD_INSTRUCTION_BYTES} bytes",
                kind.field_keyword()
            )));
        }
        let switches = parse_field_switches(field.instruction(), kind.field_keyword())?
            .expect("automatic-number recognition and parsing must agree");

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            kind,
            switches,
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
        }))
    }

    /// Return the complete stored field instruction.
    #[must_use]
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return the recognized automatic-numbering category.
    #[must_use]
    pub const fn kind(&self) -> AutoNumberKind {
        self.kind
    }

    /// Return preserved switches in source order without interpreting them.
    #[must_use]
    pub fn switches(&self) -> &[Switch] {
        &self.switches
    }

    /// Check whether a case-insensitive ASCII switch appears in this field.
    #[must_use]
    pub fn has_switch(&self, name: char) -> bool {
        has_field_switch(&self.switches, name)
    }

    /// Return the stored cached field result, if present.
    ///
    /// This is stored text only and is never regenerated by calculating a
    /// paragraph number.
    #[must_use]
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    #[must_use]
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    #[must_use]
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

/// Typed, inert metadata for a Word `LISTNUM` field.
///
/// ECMA-376 Part 1 §17.16.5.33 defines `LISTNUM` with an optional list
/// name and switches. This type retains those stored values and cached result
/// only. It never looks up a list, determines a level or start value,
/// calculates a number, changes layout, or refreshes a field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ListNumber {
    instruction: String,
    list_name: Option<String>,
    switches: Vec<Switch>,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
}

impl ListNumber {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        if field.instruction().len() > MAX_LIST_NUMBER_FIELD_INSTRUCTION_BYTES {
            return Err(Error::Invalid(format!(
                "LISTNUM field instruction exceeds {MAX_LIST_NUMBER_FIELD_INSTRUCTION_BYTES} bytes"
            )));
        }
        let Some((list_name, switches)) =
            parse_field_operand_and_switches(field.instruction(), "LISTNUM")?
        else {
            return Ok(None);
        };

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            list_name,
            switches,
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
        }))
    }

    /// Return the complete stored field instruction.
    #[must_use]
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return the stored optional list name without looking it up.
    #[must_use]
    pub fn list_name(&self) -> Option<&str> {
        self.list_name.as_deref()
    }

    /// Return preserved switches in source order without interpreting them.
    #[must_use]
    pub fn switches(&self) -> &[Switch] {
        &self.switches
    }

    /// Check whether a case-insensitive ASCII switch appears in this field.
    #[must_use]
    pub fn has_switch(&self, name: char) -> bool {
        has_field_switch(&self.switches, name)
    }

    /// Return the stored cached field result, if present.
    ///
    /// This is stored text only and is never regenerated by calculating a list
    /// number.
    #[must_use]
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    #[must_use]
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    #[must_use]
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

/// One recognized stored option of a Word `STYLEREF` field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum StyleOption {
    /// The `\\l` request for the nearest styled text following the field.
    FollowingText,
    /// The `\\n` request for the referenced paragraph number.
    ParagraphNumber,
    /// The `\\p` request for the referenced paragraph's relative position.
    RelativePosition,
    /// The `\\r` request for the referenced paragraph number in relative context.
    ParagraphNumberRelativeContext,
    /// The `\\t` request to suppress non-delimiter or non-numerical text.
    SuppressNonNumberText,
    /// The `\\w` request for the referenced paragraph number in full context.
    ParagraphNumberFullContext,
}

/// A typed, inert Word `STYLEREF` field.
///
/// ECMA-376 Part 1 §17.16.5.59 defines `STYLEREF` using a style name and
/// switches. This type retains those stored values and a cached result only. It
/// never looks up styled text, searches document stories, calculates paragraph
/// numbers or relative positions, resolves page layout, or refreshes a field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StyleReference {
    instruction: String,
    style_name: String,
    options: Vec<StyleOption>,
    unknown_switches: Vec<Switch>,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
}

impl StyleReference {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let Some((style_name, options, unknown_switches)) =
            parse_style_reference_field_parts(field.instruction())?
        else {
            return Ok(None);
        };

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            style_name,
            options,
            unknown_switches,
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
        }))
    }

    /// Return the complete stored field instruction.
    #[must_use]
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return the stored style name without looking up text that uses it.
    #[must_use]
    pub fn style_name(&self) -> &str {
        &self.style_name
    }

    /// Return recognized stored options in source order.
    ///
    /// This metadata is never used to search text, calculate a number, or
    /// resolve layout.
    #[must_use]
    pub fn options(&self) -> &[StyleOption] {
        &self.options
    }

    /// Return unrecognized stored switches in source order.
    ///
    /// They are retained without interpretation or execution.
    #[must_use]
    pub fn unknown_switches(&self) -> &[Switch] {
        &self.unknown_switches
    }

    /// Return the cached visible field result, if present.
    ///
    /// This is stored text only and is never regenerated by searching styled
    /// text or resolving layout.
    #[must_use]
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    #[must_use]
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    #[must_use]
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

impl Field {
    /// Check whether this is a `QUOTE` text-insertion field.
    ///
    /// Recognition is limited to the stored instruction. It never interprets
    /// character codes, expands nested fields, inserts text, or refreshes the
    /// cached result.
    #[must_use]
    pub fn is_quote_field(&self) -> bool {
        field_instruction_remainder(&self.instruction, "QUOTE").is_some()
    }

    /// Parse this field as inert typed `QUOTE` metadata.
    ///
    /// Returns `Ok(None)` for fields other than `QUOTE`. The stored text argument,
    /// switches, cached content, and dirty/lock state are metadata only; this
    /// method never interprets character codes, expands nested fields, inserts
    /// text, or refreshes a field.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation cannot be completed.
    pub fn quote_field(&self) -> Result<Option<Quote>> {
        Quote::from_field(self)
    }

    /// Check whether this is a `SYMBOL` field.
    ///
    /// Recognition is limited to the stored instruction. It never maps a
    /// character code, looks up a font, inserts a glyph, changes formatting or
    /// layout, or refreshes the cached result.
    #[must_use]
    pub fn is_symbol_field(&self) -> bool {
        field_instruction_remainder(&self.instruction, "SYMBOL").is_some()
    }

    /// Parse this field as inert typed `SYMBOL` metadata.
    ///
    /// Returns `Ok(None)` for fields other than `SYMBOL`. The stored character
    /// argument, switches, cached content, and dirty/lock state are metadata
    /// only; this method never maps a character code, looks up a font, inserts
    /// a glyph, changes formatting or layout, or refreshes a field.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation cannot be completed.
    pub fn symbol_field(&self) -> Result<Option<Symbol>> {
        Symbol::from_field(self)
    }

    /// Check whether this is a legacy automatic-numbering field.
    ///
    /// Recognition is limited to the stored instruction. It never calculates
    /// paragraph numbers, reads heading or style state, changes layout, or
    /// refreshes the cached result.
    #[must_use]
    pub fn is_auto_number_field(&self) -> bool {
        AutoNumberKind::from_instruction(&self.instruction).is_some()
    }

    /// Parse this field as inert legacy automatic-numbering metadata.
    ///
    /// Returns `Ok(None)` for fields other than `AUTONUM`, `AUTONUMLGL`, and
    /// `AUTONUMOUT`. The stored kind, switches, cached content, and dirty/lock
    /// state are metadata only; this method never calculates a number, reads
    /// paragraph, heading, or style state, changes layout, or refreshes a
    /// field.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation cannot be completed.
    pub fn auto_number_field(&self) -> Result<Option<AutoNumber>> {
        AutoNumber::from_field(self)
    }

    /// Check whether this is a `LISTNUM` field.
    ///
    /// Recognition is limited to the stored instruction. It never looks up a
    /// list, determines a level or start value, calculates a number, changes
    /// layout, or refreshes the cached result.
    #[must_use]
    pub fn is_list_number_field(&self) -> bool {
        field_instruction_remainder(&self.instruction, "LISTNUM").is_some()
    }

    /// Parse this field as inert typed `LISTNUM` metadata.
    ///
    /// Returns `Ok(None)` for fields other than `LISTNUM`. The stored optional
    /// list name, switches, cached content, and dirty/lock state are metadata
    /// only; this method never looks up a list, determines a level or start
    /// value, calculates a number, changes layout, or refreshes a field.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation cannot be completed.
    pub fn list_number_field(&self) -> Result<Option<ListNumber>> {
        ListNumber::from_field(self)
    }

    /// Check whether this is a `STYLEREF` field.
    ///
    /// Recognition is limited to stored field metadata. It never looks up
    /// styled text, searches document stories, calculates paragraph numbers or
    /// relative positions, resolves page layout, or refreshes the result.
    #[must_use]
    pub fn is_style_reference_field(&self) -> bool {
        field_instruction_remainder(&self.instruction, "STYLEREF").is_some()
    }

    /// Parse this field as inert typed `STYLEREF` metadata.
    ///
    /// Returns `Ok(None)` for fields other than `STYLEREF`. The stored style name,
    /// options, switches, cached content, and dirty/lock state are metadata
    /// only; this method never looks up styled text, searches document stories,
    /// calculates paragraph numbers or relative positions, resolves page
    /// layout, or refreshes a field.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation cannot be completed.
    pub fn style_reference_field(&self) -> Result<Option<StyleReference>> {
        StyleReference::from_field(self)
    }
}
