#![expect(
    clippy::shadow_reuse,
    reason = "parser bindings are intentionally refined after validation"
)]
#![expect(
    clippy::struct_field_names,
    reason = "the public model retains established field names"
)]
//! Mail-merge data, control, prompt, and recipient field models.

use super::{Field, Switch};

use crate::error::{Error, Result};

use super::super::codec::{
    field_instruction_remainder, has_field_switch, parse_field_operand_and_switches,
    parse_mail_merge_data_field_parts, parse_mail_merge_recipient_field_parts,
    parse_prompt_field_parts,
};

/// A typed, inert Word `MERGEFIELD` field.
///
/// ECMA-376 Part 1 §17.16.5.35 defines one stored data-column name followed
/// by optional field switches. This type exposes that persisted metadata and
/// the cached result only. It never opens a data source, resolves a record,
/// performs a merge, or refreshes the field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Merge {
    instruction: String,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
    field_name: String,
    switches: Vec<Switch>,
}

impl Merge {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let Some((field_name, switches)) =
            parse_field_operand_and_switches(field.instruction(), "MERGEFIELD")?
        else {
            return Ok(None);
        };
        let field_name = field_name.ok_or_else(|| {
            Error::Invalid("MERGEFIELD field is missing its data-column name".to_string())
        })?;
        if field_name.is_empty() {
            return Err(Error::Invalid(
                "MERGEFIELD field data-column name is empty".to_string(),
            ));
        }

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
            field_name,
            switches,
        }))
    }

    /// Return the complete stored field instruction.
    #[must_use]
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return the stored data-column name without resolving a data source.
    #[must_use]
    pub fn field_name(&self) -> &str {
        &self.field_name
    }

    /// Return the cached visible field result, if present.
    ///
    /// This is stored text only and is never regenerated by a merge.
    #[must_use]
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    #[must_use]
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    #[must_use]
    pub fn is_locked(&self) -> bool {
        self.locked
    }

    /// Return stored field switches in source order without interpreting them.
    #[must_use]
    pub fn switches(&self) -> &[Switch] {
        &self.switches
    }

    /// Check whether a case-insensitive ASCII switch appears in this field.
    #[must_use]
    pub fn has_switch(&self, name: char) -> bool {
        has_field_switch(&self.switches, name)
    }
}

/// A typed, inert Word `DATA` mail-merge source field.
///
/// [MS-DOC] §2.9.90 specifies `DATA datafile [headerfile]` as a field that
/// redirects mail-merge data and header files. This type exposes only those
/// stored operands, switches, cached result, and field state. It never opens,
/// reads, connects to, resolves, or modifies either source; it never selects a
/// record, performs a merge, or refreshes a field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MergeData {
    instruction: String,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
    data_source: String,
    header_source: Option<String>,
    switches: Vec<Switch>,
}

impl MergeData {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let Some((data_source, header_source, switches)) =
            parse_mail_merge_data_field_parts(field.instruction())?
        else {
            return Ok(None);
        };

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
            data_source,
            header_source,
            switches,
        }))
    }

    /// Return the complete stored field instruction.
    #[must_use]
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return the stored mail-merge data-source identifier without opening it.
    #[must_use]
    pub fn data_source(&self) -> &str {
        &self.data_source
    }

    /// Return the optional stored mail-merge header-source identifier.
    ///
    /// This value is never opened or resolved.
    #[must_use]
    pub fn header_source(&self) -> Option<&str> {
        self.header_source.as_deref()
    }

    /// Return the cached visible field result, if present.
    ///
    /// This is stored text only and is never regenerated by a merge.
    #[must_use]
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    #[must_use]
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    #[must_use]
    pub fn is_locked(&self) -> bool {
        self.locked
    }

    /// Return stored field switches in source order without interpreting them.
    #[must_use]
    pub fn switches(&self) -> &[Switch] {
        &self.switches
    }

    /// Check whether a case-insensitive ASCII switch appears in this field.
    #[must_use]
    pub fn has_switch(&self, name: char) -> bool {
        has_field_switch(&self.switches, name)
    }
}

/// The stored kind of a mail-merge counter field.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MergeCounterKind {
    /// A `MERGEREC` field, which stores a selected-record position.
    Record,
    /// A `MERGESEQ` field, which stores a merged-record sequence position.
    Sequence,
}

/// A typed, inert Word `MERGEREC` or `MERGESEQ` field.
///
/// ECMA-376 Part 1 §§17.16.5.36–37 define these zero-argument fields. This
/// type exposes the persisted kind and cached result only. It never selects or
/// counts records, opens a data source, performs a merge, or refreshes a field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MergeCounter {
    instruction: String,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
    kind: MergeCounterKind,
}

impl MergeCounter {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let (kind, field_type, remainder) = if let Some(remainder) =
            field_instruction_remainder(field.instruction(), "MERGEREC")
        {
            (MergeCounterKind::Record, "MERGEREC", remainder)
        } else if let Some(remainder) = field_instruction_remainder(field.instruction(), "MERGESEQ")
        {
            (MergeCounterKind::Sequence, "MERGESEQ", remainder)
        } else {
            return Ok(None);
        };

        if !remainder.trim().is_empty() {
            return Err(Error::Invalid(format!(
                "{field_type} field must not contain arguments or switches"
            )));
        }

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
            kind,
        }))
    }

    /// Return the complete stored field instruction.
    #[must_use]
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return whether this is a `MERGEREC` or `MERGESEQ` field.
    #[must_use]
    pub fn kind(&self) -> MergeCounterKind {
        self.kind
    }

    /// Return the cached visible field result, if present.
    ///
    /// This is stored text only and is never regenerated by a merge.
    #[must_use]
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    #[must_use]
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    #[must_use]
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

/// A typed, inert Word `NEXT` mail-merge control field.
///
/// ECMA-376 Part 1 §17.16.5.38 defines `NEXT` as a zero-argument
/// instruction. This type exposes persisted cached content and state only. It
/// never advances a record, opens a data source, performs a merge, or refreshes
/// a field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MergeNext {
    instruction: String,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
}

impl MergeNext {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let Some(remainder) = field_instruction_remainder(field.instruction(), "NEXT") else {
            return Ok(None);
        };
        if !remainder.trim().is_empty() {
            return Err(Error::Invalid(
                "NEXT field must not contain arguments or switches".to_string(),
            ));
        }

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
        }))
    }

    /// Return the complete stored field instruction.
    #[must_use]
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return the cached visible field result, if present.
    ///
    /// This is stored text only and is never regenerated by a merge.
    #[must_use]
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    #[must_use]
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    #[must_use]
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

/// The stored kind of a conditional mail-merge control field.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MergeControlKind {
    /// A `NEXTIF` field, which can advance a merge record when its comparison is true.
    NextIf,
    /// A `SKIPIF` field, which can omit a merge record when its comparison is true.
    SkipIf,
}

/// A typed, inert Word `NEXTIF` or `SKIPIF` mail-merge control field.
///
/// ECMA-376 Part 1 §§17.16.5.39 and 17.16.5.58 define these controls. This
/// type retains the unparsed comparison and cached result only. It never parses or
/// evaluates a comparison, advances or skips a record, opens a data source,
/// performs a merge, or refreshes a field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MergeControl {
    instruction: String,
    comparison: String,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
    kind: MergeControlKind,
}

impl MergeControl {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let (kind, field_type, comparison) = if let Some(comparison) =
            field_instruction_remainder(field.instruction(), "NEXTIF")
        {
            (MergeControlKind::NextIf, "NEXTIF", comparison)
        } else if let Some(comparison) = field_instruction_remainder(field.instruction(), "SKIPIF")
        {
            (MergeControlKind::SkipIf, "SKIPIF", comparison)
        } else {
            return Ok(None);
        };

        let comparison = comparison.trim();
        if comparison.is_empty() {
            return Err(Error::Invalid(format!(
                "{field_type} field is missing its comparison"
            )));
        }

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            comparison: comparison.to_string(),
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
            kind,
        }))
    }

    /// Return the complete stored field instruction.
    #[must_use]
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return whether this is a `NEXTIF` or `SKIPIF` control.
    #[must_use]
    pub fn kind(&self) -> MergeControlKind {
        self.kind
    }

    /// Return the stored comparison without parsing or evaluating it.
    #[must_use]
    pub fn comparison(&self) -> &str {
        &self.comparison
    }

    /// Return the cached visible field result, if present.
    ///
    /// This is stored text only and is never regenerated by a merge.
    #[must_use]
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    #[must_use]
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    #[must_use]
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

/// The stored kind of a prompt field.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PromptKind {
    /// An `ASK` field that associates a response with a bookmark.
    Ask,
    /// A `FILLIN` field that stores a response as its field result.
    FillIn,
}

/// A typed, inert Word `ASK` or `FILLIN` prompt field.
///
/// ECMA-376 Part 1 §§17.16.5.3 and 17.16.5.19 define these fields. This type
/// exposes stored prompt and default-response metadata only. It never displays
/// a prompt, captures a response, creates or updates a bookmark, performs a
/// merge, or refreshes a field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Prompt {
    instruction: String,
    kind: PromptKind,
    bookmark: Option<String>,
    prompt: Option<String>,
    default_response: Option<String>,
    prompts_once_per_mail_merge: bool,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
}

impl Prompt {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let Some((kind, bookmark, prompt, default_response, prompts_once_per_mail_merge)) =
            parse_prompt_field_parts(field.instruction())?
        else {
            return Ok(None);
        };

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            kind,
            bookmark,
            prompt,
            default_response,
            prompts_once_per_mail_merge,
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
        }))
    }

    /// Return the complete stored field instruction.
    #[must_use]
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return whether this is an `ASK` or `FILLIN` field.
    #[must_use]
    pub fn kind(&self) -> PromptKind {
        self.kind
    }

    /// Return the bookmark name stored by an `ASK` field, if any.
    ///
    /// This is stored metadata only. It is never resolved, created, or updated.
    #[must_use]
    pub fn bookmark(&self) -> Option<&str> {
        self.bookmark.as_deref()
    }

    /// Return the stored prompt text, if any.
    ///
    /// This method returns metadata only and never displays a prompt.
    #[must_use]
    pub fn prompt(&self) -> Option<&str> {
        self.prompt.as_deref()
    }

    /// Return the stored default response, if one was supplied.
    ///
    /// `Some("")` represents an explicitly supplied blank default response. This
    /// is metadata only and is never selected, captured, or written into the
    /// document.
    #[must_use]
    pub fn default_response(&self) -> Option<&str> {
        self.default_response.as_deref()
    }

    /// Whether the stored `\o` switch requests one prompt for a mail merge.
    ///
    /// This request is never acted on: no merge is performed and no data source
    /// is opened.
    #[must_use]
    pub fn prompts_once_per_mail_merge(&self) -> bool {
        self.prompts_once_per_mail_merge
    }

    /// Return the cached visible field result, if present.
    ///
    /// This is stored text only and is never regenerated by field evaluation.
    #[must_use]
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    #[must_use]
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    #[must_use]
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

/// The stored kind of a mail-merge recipient layout field.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RecipientKind {
    /// An `ADDRESSBLOCK` field.
    AddressBlock,
    /// A `GREETINGLINE` field.
    GreetingLine,
}

/// How an `ADDRESSBLOCK` field requests country/region text.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CountryInclusion {
    /// `\\c 0` omits the country/region.
    Omit,
    /// `\\c 1` includes the country/region regardless of exclusions.
    Always,
    /// `\\c 2` includes the country/region unless it matches an excluded
    /// country/region.
    UnlessExcluded,
}

/// A typed, inert Word `ADDRESSBLOCK` or `GREETINGLINE` field.
///
/// ECMA-376 Part 1 §§17.16.5.1 and 17.16.5.24 define these mail-merge
/// recipient layout fields. This type exposes stored layout metadata and the
/// cached result only. It never opens a data source, selects a record,
/// performs a merge, expands placeholders, generates text, or refreshes a
/// field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Recipient {
    instruction: String,
    kind: RecipientKind,
    country_inclusion: Option<CountryInclusion>,
    formats_using_recipient_country: bool,
    excluded_countries: Vec<String>,
    format_template: Option<String>,
    language: Option<String>,
    greeting_fallback_text: Option<String>,
    unknown_switches: Vec<Switch>,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
}

impl Recipient {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let Some((
            kind,
            country_inclusion,
            formats_using_recipient_country,
            excluded_countries,
            format_template,
            language,
            greeting_fallback_text,
            unknown_switches,
        )) = parse_mail_merge_recipient_field_parts(field.instruction())?
        else {
            return Ok(None);
        };

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            kind,
            country_inclusion,
            formats_using_recipient_country,
            excluded_countries,
            format_template,
            language,
            greeting_fallback_text,
            unknown_switches,
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
        }))
    }

    /// Return the complete stored field instruction.
    #[must_use]
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return whether this is an `ADDRESSBLOCK` or `GREETINGLINE` field.
    #[must_use]
    pub fn kind(&self) -> RecipientKind {
        self.kind
    }

    /// Return how an `ADDRESSBLOCK` requests country/region text.
    ///
    /// This is `None` when the instruction has no `\\c` switch or when the
    /// field is a `GREETINGLINE`. The stored request is never used to render
    /// an address.
    #[must_use]
    pub fn country_inclusion(&self) -> Option<CountryInclusion> {
        self.country_inclusion
    }

    /// Whether an `ADDRESSBLOCK` stores the `\\d` request to use the
    /// recipient country's address format.
    ///
    /// This request is metadata only and never causes a record or country
    /// format to be resolved.
    #[must_use]
    pub fn formats_using_recipient_country(&self) -> bool {
        self.formats_using_recipient_country
    }

    /// Return country/region names excluded by an `ADDRESSBLOCK` `\\e` switch.
    ///
    /// ECMA-376 permits repeated `\\e` switches; values are retained in source
    /// order. They are never matched against a recipient record.
    #[must_use]
    pub fn excluded_countries(&self) -> &[String] {
        &self.excluded_countries
    }

    /// Return the stored `\\f` layout template, if any.
    ///
    /// For `ADDRESSBLOCK`, this is the standard address/name placeholder
    /// template. For `GREETINGLINE`, this accepts Word's documented
    /// compatibility form. Placeholder text remains opaque metadata and is
    /// never expanded.
    #[must_use]
    pub fn format_template(&self) -> Option<&str> {
        self.format_template.as_deref()
    }

    /// Return the stored `\\l` language identifier, if any.
    ///
    /// The identifier is not used to choose locale-specific formatting.
    #[must_use]
    pub fn language(&self) -> Option<&str> {
        self.language.as_deref()
    }

    /// Return the stored `GREETINGLINE` fallback text, if any.
    ///
    /// ECMA-376 names `\\c` as this switch; Word-compatible fields can use
    /// `\\e`. Both forms are accepted as stored metadata, but neither is ever
    /// selected or displayed by this API.
    #[must_use]
    pub fn greeting_fallback_text(&self) -> Option<&str> {
        self.greeting_fallback_text.as_deref()
    }

    /// Return switches not specific to the recognized recipient-field kind.
    ///
    /// This includes formatting or producer-specific switches, retained in
    /// source order as inert metadata.
    #[must_use]
    pub fn unknown_switches(&self) -> &[Switch] {
        &self.unknown_switches
    }

    /// Return the cached visible field result, if present.
    ///
    /// This is stored text only and is never regenerated by a merge.
    #[must_use]
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    #[must_use]
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    #[must_use]
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

impl Field {
    /// Check whether this is a `MERGEFIELD` mail-merge field.
    ///
    /// Recognition is limited to the stored field instruction. It never opens
    /// a data source, resolves a record, performs a merge, or refreshes the
    /// cached result.
    #[must_use]
    pub fn is_merge_field(&self) -> bool {
        field_instruction_remainder(&self.instruction, "MERGEFIELD").is_some()
    }

    /// Return the data-source column name from a `MERGEFIELD` instruction.
    ///
    /// Both unquoted names (`MERGEFIELD FirstName`) and quoted names containing
    /// spaces (`MERGEFIELD "Full Name"`) are supported. Field switches following
    /// the name are excluded. This legacy convenience accessor never opens a
    /// data source or performs a merge.
    pub fn merge_field_name(&self) -> Option<&str> {
        let remainder = field_instruction_remainder(&self.instruction, "MERGEFIELD")?.trim_start();
        if remainder.is_empty() || remainder.starts_with('\\') {
            return None;
        }
        if let Some(quoted) = remainder.strip_prefix('"') {
            let end = quoted.find('"')?;
            let name = &quoted[..end];
            return (!name.is_empty()).then_some(name);
        }
        let end = remainder
            .find(char::is_whitespace)
            .unwrap_or(remainder.len());
        let name = &remainder[..end];
        (!name.is_empty()).then_some(name)
    }

    /// Parse this field as inert typed `MERGEFIELD` metadata.
    ///
    /// Returns `Ok(None)` for non-`MERGEFIELD` fields. The result exposes only
    /// the stored field name, switches, cached content, and dirty/lock state;
    /// it never opens a data source, resolves records, performs a merge, or
    /// refreshes the field.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation cannot be completed.
    pub fn merge_field(&self) -> Result<Option<Merge>> {
        Merge::from_field(self)
    }

    /// Check whether this is a `DATA` mail-merge source field.
    ///
    /// Recognition is limited to stored field metadata. It never opens, reads,
    /// connects to, resolves, or modifies a source; it never selects a record,
    /// performs a merge, or refreshes the field.
    #[must_use]
    pub fn is_mail_merge_data(&self) -> bool {
        field_instruction_remainder(&self.instruction, "DATA").is_some()
    }

    /// Parse this field as inert typed `DATA` mail-merge source metadata.
    ///
    /// Returns `Ok(None)` for fields other than `DATA`. The result exposes only
    /// stored source identifiers, switches, cached content, and dirty/lock
    /// state; it never opens, reads, connects to, resolves, or modifies a
    /// source, selects a record, performs a merge, or refreshes a field.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation cannot be completed.
    pub fn mail_merge_data(&self) -> Result<Option<MergeData>> {
        MergeData::from_field(self)
    }

    /// Check whether this is a `MERGEREC` mail-merge counter field.
    ///
    /// Recognition is limited to the stored instruction. It never selects a
    /// record, opens a data source, performs a merge, or refreshes the result.
    #[must_use]
    pub fn is_merge_record(&self) -> bool {
        field_instruction_remainder(&self.instruction, "MERGEREC").is_some()
    }

    /// Check whether this is a `MERGESEQ` mail-merge counter field.
    ///
    /// Recognition is limited to the stored instruction. It never selects a
    /// record, opens a data source, performs a merge, or refreshes the result.
    #[must_use]
    pub fn is_merge_sequence(&self) -> bool {
        field_instruction_remainder(&self.instruction, "MERGESEQ").is_some()
    }

    /// Check whether this is a `MERGEREC` or `MERGESEQ` field.
    #[must_use]
    pub fn is_mail_merge_counter(&self) -> bool {
        self.is_merge_record() || self.is_merge_sequence()
    }

    /// Parse this field as inert typed mail-merge counter metadata.
    ///
    /// Returns `Ok(None)` for fields other than `MERGEREC` and `MERGESEQ`.
    /// The result exposes only stored kind, cached content, and dirty/lock
    /// state; it never selects a record, opens a data source, performs a
    /// merge, or refreshes a field.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation cannot be completed.
    pub fn mail_merge_counter(&self) -> Result<Option<MergeCounter>> {
        MergeCounter::from_field(self)
    }

    /// Check whether this is a `NEXT` mail-merge control field.
    ///
    /// Recognition is limited to the stored instruction. It never advances a
    /// record, opens a data source, performs a merge, or refreshes the result.
    #[must_use]
    pub fn is_mail_merge_next(&self) -> bool {
        field_instruction_remainder(&self.instruction, "NEXT").is_some()
    }

    /// Parse this field as inert typed `NEXT` mail-merge control metadata.
    ///
    /// Returns `Ok(None)` for fields other than `NEXT`. The result exposes only
    /// stored content and dirty/lock state; it never advances a record, opens a
    /// data source, performs a merge, or refreshes a field.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation cannot be completed.
    pub fn mail_merge_next(&self) -> Result<Option<MergeNext>> {
        MergeNext::from_field(self)
    }

    /// Check whether this is a `NEXTIF` mail-merge conditional control field.
    ///
    /// Recognition is limited to the stored instruction. It never evaluates a
    /// comparison, selects a record, opens a data source, performs a merge, or
    /// refreshes the result.
    #[must_use]
    pub fn is_mail_merge_next_if(&self) -> bool {
        field_instruction_remainder(&self.instruction, "NEXTIF").is_some()
    }

    /// Check whether this is a `SKIPIF` mail-merge conditional control field.
    ///
    /// Recognition is limited to the stored instruction. It never evaluates a
    /// comparison, skips a record, opens a data source, performs a merge, or
    /// refreshes the result.
    #[must_use]
    pub fn is_mail_merge_skip_if(&self) -> bool {
        field_instruction_remainder(&self.instruction, "SKIPIF").is_some()
    }

    /// Check whether this is a `NEXTIF` or `SKIPIF` mail-merge control field.
    #[must_use]
    pub fn is_mail_merge_conditional_control(&self) -> bool {
        self.is_mail_merge_next_if() || self.is_mail_merge_skip_if()
    }

    /// Parse this field as inert typed conditional mail-merge control metadata.
    ///
    /// Returns `Ok(None)` for fields other than `NEXTIF` and `SKIPIF`. The unparsed
    /// comparison, cached content, and dirty/lock state are stored metadata
    /// only; this method never evaluates a comparison, changes record
    /// selection, opens a data source, performs a merge, or refreshes a field.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation cannot be completed.
    pub fn mail_merge_conditional_control(&self) -> Result<Option<MergeControl>> {
        MergeControl::from_field(self)
    }

    /// Check whether this is an `ASK` prompt field.
    ///
    /// Recognition is limited to the stored instruction. It never displays a
    /// prompt, captures a response, writes a bookmark, performs a merge, or
    /// refreshes the result.
    #[must_use]
    pub fn is_ask_field(&self) -> bool {
        field_instruction_remainder(&self.instruction, "ASK").is_some()
    }

    /// Check whether this is a `FILLIN` prompt field.
    ///
    /// Recognition is limited to the stored instruction. It never displays a
    /// prompt, captures a response, performs a merge, or refreshes the result.
    #[must_use]
    pub fn is_fill_in_field(&self) -> bool {
        field_instruction_remainder(&self.instruction, "FILLIN").is_some()
    }

    /// Check whether this is an `ASK` or `FILLIN` prompt field.
    #[must_use]
    pub fn is_prompt_field(&self) -> bool {
        self.is_ask_field() || self.is_fill_in_field()
    }

    /// Parse this field as inert typed `ASK` or `FILLIN` metadata.
    ///
    /// Returns `Ok(None)` for fields other than `ASK` and `FILLIN`. The returned
    /// values expose stored prompt, bookmark, default-response, cached-content,
    /// and dirty/lock metadata only. This method never displays a prompt,
    /// captures a response, creates or updates a bookmark, performs a merge,
    /// or refreshes a field.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation cannot be completed.
    pub fn prompt_field(&self) -> Result<Option<Prompt>> {
        Prompt::from_field(self)
    }

    /// Check whether this is an `ADDRESSBLOCK` mail-merge recipient field.
    ///
    /// Recognition is limited to stored field metadata. It never opens a data
    /// source, selects a record, performs a merge, or refreshes the result.
    #[must_use]
    pub fn is_address_block(&self) -> bool {
        field_instruction_remainder(&self.instruction, "ADDRESSBLOCK").is_some()
    }

    /// Check whether this is a `GREETINGLINE` mail-merge recipient field.
    ///
    /// Recognition is limited to stored field metadata. It never opens a data
    /// source, selects a record, performs a merge, or refreshes the result.
    #[must_use]
    pub fn is_greeting_line(&self) -> bool {
        field_instruction_remainder(&self.instruction, "GREETINGLINE").is_some()
    }

    /// Check whether this is an `ADDRESSBLOCK` or `GREETINGLINE` field.
    #[must_use]
    pub fn is_mail_merge_recipient_field(&self) -> bool {
        self.is_address_block() || self.is_greeting_line()
    }

    /// Parse this field as inert typed mail-merge recipient metadata.
    ///
    /// Returns `Ok(None)` for fields other than `ADDRESSBLOCK` and
    /// `GREETINGLINE`. The returned values expose only stored layout,
    /// locale, country, fallback, cached-content, and dirty/lock metadata. This
    /// method never opens a data source, selects a record, performs a merge,
    /// generates text, or refreshes a field.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation cannot be completed.
    pub fn mail_merge_recipient_field(&self) -> Result<Option<Recipient>> {
        Recipient::from_field(self)
    }
}
