//! Opaque, active-content, form, database, and embedded-object field models.

use super::Field;

use crate::error::{Error, Result};

use super::super::codec::field_instruction_remainder;

use super::super::{
    MAX_BARCODE_FIELD_INSTRUCTION_BYTES, MAX_BIDI_OUTLINE_FIELD_INSTRUCTION_BYTES,
    MAX_DATABASE_FIELD_INSTRUCTION_BYTES, MAX_EMBED_FIELD_INSTRUCTION_BYTES,
    MAX_LEGACY_FORM_FIELD_INSTRUCTION_BYTES, MAX_PRIVATE_FIELD_INSTRUCTION_BYTES,
    MAX_SHAPE_FIELD_INSTRUCTION_BYTES,
};

/// The stored kind of an active-content field.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ActiveContentKind {
    /// An `ADDIN` field that stores add-in-created data.
    AddIn,
    /// A `CONTROL` field that represents an OCX control.
    OcxControl,
    /// An `HTMLCONTROL` field that represents an HTML control.
    HtmlControl,
}

/// A typed, inert Word add-in or control field.
///
/// ECMA-376 Part 1 §17.16.5 defines `ADDIN`, `CONTROL`, and
/// `HTMLCONTROL` field instructions. This type retains only the stored
/// category, instruction, cached result, and state. It never loads an add-in,
/// instantiates an OCX or HTML control, invokes code, executes script, renders
/// content, or accesses an external resource.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ActiveContent {
    instruction: String,
    kind: ActiveContentKind,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
}

impl ActiveContent {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let kind = if field_instruction_remainder(field.instruction(), "ADDIN").is_some() {
            ActiveContentKind::AddIn
        } else if field_instruction_remainder(field.instruction(), "CONTROL").is_some() {
            ActiveContentKind::OcxControl
        } else if field_instruction_remainder(field.instruction(), "HTMLCONTROL").is_some() {
            ActiveContentKind::HtmlControl
        } else {
            return Ok(None);
        };

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            kind,
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
        }))
    }

    /// Return the complete stored field instruction.
    ///
    /// This string remains opaque metadata and is never interpreted.
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return whether this stores add-in, OCX-control, or HTML-control metadata.
    pub fn kind(&self) -> ActiveContentKind {
        self.kind
    }

    /// Return the cached visible field result, if present.
    ///
    /// This is stored text only and is never regenerated by loading or running
    /// content.
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

/// A typed, inert Word `PRINT` field.
///
/// Microsoft Word uses this field to store printer-control instructions. This
/// type retains the opaque instruction text, cached result, and field state
/// only. It never interprets printer-control codes, opens a printer, sends
/// output, changes print settings, or refreshes a field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Print {
    instruction: String,
    printer_instructions: String,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
}

impl Print {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let Some(printer_instructions) = field_instruction_remainder(field.instruction(), "PRINT")
        else {
            return Ok(None);
        };

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            printer_instructions: printer_instructions.trim().to_string(),
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
        }))
    }

    /// Return the complete stored field instruction.
    ///
    /// This string remains opaque metadata and is never interpreted or sent to
    /// a printer.
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return the stored printer-instruction text after the `PRINT` keyword.
    ///
    /// This can include printer-control or PostScript text. It is never parsed,
    /// interpreted, or sent to a printer.
    pub fn printer_instructions(&self) -> &str {
        &self.printer_instructions
    }

    /// Return the cached visible field result, if present.
    ///
    /// This is stored text only and is never regenerated by printing.
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

/// A typed, inert Word `EMBED` field.
///
/// Word uses this field to retain an embedded OLE object's stored metadata.
/// This type retains opaque object-instruction text, cached result, and field
/// state only. It never loads, inspects, deserializes, activates, renders, or
/// executes an embedded object, accesses an external resource, or refreshes a
/// field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Embed {
    instruction: String,
    object_instructions: String,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
}

impl Embed {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let Some(object_instructions) = field_instruction_remainder(field.instruction(), "EMBED")
        else {
            return Ok(None);
        };
        if field.instruction().len() > MAX_EMBED_FIELD_INSTRUCTION_BYTES {
            return Err(Error::Invalid(format!(
                "EMBED field instruction exceeds {MAX_EMBED_FIELD_INSTRUCTION_BYTES} bytes"
            )));
        }

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            object_instructions: object_instructions.trim().to_string(),
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
        }))
    }

    /// Return the complete stored field instruction.
    ///
    /// This string remains opaque metadata and is never used to load or
    /// activate an object.
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return the stored opaque object-instruction text after `EMBED`.
    ///
    /// It is never parsed, used to locate an object, or used to load, inspect,
    /// activate, render, or execute object content.
    pub fn object_instructions(&self) -> &str {
        &self.object_instructions
    }

    /// Return the cached visible field result, if present.
    ///
    /// This is stored text only and is never regenerated from an object.
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

/// A typed, inert Word `BARCODE` field.
///
/// This type retains opaque barcode-instruction text, a cached result, and
/// field state only. It never parses or validates barcode data or symbology,
/// generates or renders a barcode, accesses an external resource, or refreshes
/// a field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Barcode {
    instruction: String,
    barcode_instructions: String,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
}

impl Barcode {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let Some(barcode_instructions) =
            field_instruction_remainder(field.instruction(), "BARCODE")
        else {
            return Ok(None);
        };
        if field.instruction().len() > MAX_BARCODE_FIELD_INSTRUCTION_BYTES {
            return Err(Error::Invalid(format!(
                "BARCODE field instruction exceeds {MAX_BARCODE_FIELD_INSTRUCTION_BYTES} bytes"
            )));
        }

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            barcode_instructions: barcode_instructions.trim().to_string(),
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
        }))
    }

    /// Return the complete stored field instruction.
    ///
    /// This string remains opaque metadata and is never used to generate or
    /// render a barcode.
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return the stored opaque barcode-instruction text after `BARCODE`.
    ///
    /// It is never parsed, validated, interpreted, or used to generate or
    /// render barcode content.
    pub fn barcode_instructions(&self) -> &str {
        &self.barcode_instructions
    }

    /// Return the cached visible field result, if present.
    ///
    /// This is stored text only and is never regenerated from barcode data.
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

/// A typed, inert Word `BIDIOUTLINE` field.
///
/// This type retains opaque instruction text, a cached result, and field state
/// only. It never reads right-to-left language, paragraph outline, or layout
/// state; chooses a numbering system; calculates a result; or refreshes a
/// field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BidiOutline {
    instruction: String,
    opaque_instructions: String,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
}

impl BidiOutline {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let Some(opaque_instructions) =
            field_instruction_remainder(field.instruction(), "BIDIOUTLINE")
        else {
            return Ok(None);
        };
        if field.instruction().len() > MAX_BIDI_OUTLINE_FIELD_INSTRUCTION_BYTES {
            return Err(Error::Invalid(format!(
                "BIDIOUTLINE field instruction exceeds {MAX_BIDI_OUTLINE_FIELD_INSTRUCTION_BYTES} bytes"
            )));
        }

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            opaque_instructions: opaque_instructions.trim().to_string(),
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
        }))
    }

    /// Return the complete stored field instruction.
    ///
    /// This string remains opaque metadata and is never used to calculate an
    /// outline number.
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return opaque stored instruction text after `BIDIOUTLINE`.
    ///
    /// It is never parsed, interpreted, or used to resolve language, outline,
    /// numbering, or layout state.
    pub fn opaque_instructions(&self) -> &str {
        &self.opaque_instructions
    }

    /// Return the cached visible field result, if present.
    ///
    /// This is stored text only and is never regenerated from document state.
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

/// A typed, inert Word `SHAPE` drawing-canvas anchor field.
///
/// Word uses this legacy field as a drawing-canvas anchor. This type retains
/// opaque instruction text, a cached result, and field state only. It never
/// locates, links, loads, positions, lays out, or renders a drawing or canvas,
/// or refreshes a field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Shape {
    instruction: String,
    opaque_instructions: String,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
}

impl Shape {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let Some(opaque_instructions) = field_instruction_remainder(field.instruction(), "SHAPE")
        else {
            return Ok(None);
        };
        if field.instruction().len() > MAX_SHAPE_FIELD_INSTRUCTION_BYTES {
            return Err(Error::Invalid(format!(
                "SHAPE field instruction exceeds {MAX_SHAPE_FIELD_INSTRUCTION_BYTES} bytes"
            )));
        }

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            opaque_instructions: opaque_instructions.trim().to_string(),
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
        }))
    }

    /// Return the complete stored field instruction.
    ///
    /// This string remains opaque metadata and is never used to locate or
    /// position a drawing canvas.
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return opaque stored instruction text after `SHAPE`.
    ///
    /// It is never parsed, interpreted, or used to link a field to a drawing,
    /// resolve an anchor, or calculate layout.
    pub fn opaque_instructions(&self) -> &str {
        &self.opaque_instructions
    }

    /// Return the cached visible field result, if present.
    ///
    /// This is stored metadata only and is never regenerated from a drawing
    /// canvas.
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

/// The stored kind of a legacy Word form-code field.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LegacyFormKind {
    /// A `FORMTEXT` text-box form field.
    Text,
    /// A `FORMCHECKBOX` checkbox form field.
    CheckBox,
    /// A `FORMDROPDOWN` drop-down-list form field.
    DropDown,
}

impl LegacyFormKind {
    fn from_instruction(instruction: &str) -> Option<(Self, &str)> {
        for (kind, keyword) in [
            (Self::Text, "FORMTEXT"),
            (Self::CheckBox, "FORMCHECKBOX"),
            (Self::DropDown, "FORMDROPDOWN"),
        ] {
            if let Some(remainder) = field_instruction_remainder(instruction, keyword) {
                return Some((kind, remainder));
            }
        }
        None
    }
}

/// A typed, inert Word legacy form-code field.
///
/// This type retains only the stored text/checkbox/drop-down kind, opaque
/// instruction text, cached result, and field state. It never reads associated
/// form-property XML, fills a form, changes a selection or checkbox state,
/// invokes entry or exit macros, or refreshes a field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LegacyForm {
    instruction: String,
    kind: LegacyFormKind,
    opaque_instructions: String,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
}

impl LegacyForm {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let Some((kind, opaque_instructions)) =
            LegacyFormKind::from_instruction(field.instruction())
        else {
            return Ok(None);
        };
        if field.instruction().len() > MAX_LEGACY_FORM_FIELD_INSTRUCTION_BYTES {
            return Err(Error::Invalid(format!(
                "legacy form-code field instruction exceeds {MAX_LEGACY_FORM_FIELD_INSTRUCTION_BYTES} bytes"
            )));
        }

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            kind,
            opaque_instructions: opaque_instructions.trim().to_string(),
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
        }))
    }

    /// Return the complete stored field instruction.
    ///
    /// This string remains opaque metadata and is never used to change a form
    /// field.
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return whether this is a text, checkbox, or drop-down form-code field.
    pub const fn kind(&self) -> LegacyFormKind {
        self.kind
    }

    /// Return opaque stored instruction text after the form-code keyword.
    ///
    /// It is never parsed, interpreted, or used to fill a form, change a
    /// checkbox or selection, or invoke a macro.
    pub fn opaque_instructions(&self) -> &str {
        &self.opaque_instructions
    }

    /// Return the cached visible field result, if present.
    ///
    /// This is stored metadata only and is never regenerated from form state.
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

/// A typed, inert Word `PRIVATE` conversion-data field.
///
/// Word uses this field to preserve data needed to convert a document back to
/// another file format. This type retains opaque instruction text, a cached
/// result, and field state only. It never converts a document, interprets field
/// data, changes hidden-text visibility or layout, or refreshes a field.
/// Despite its name, `PRIVATE` does not provide confidentiality semantics.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Private {
    instruction: String,
    opaque_instructions: String,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
}

impl Private {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let Some(opaque_instructions) = field_instruction_remainder(field.instruction(), "PRIVATE")
        else {
            return Ok(None);
        };
        if field.instruction().len() > MAX_PRIVATE_FIELD_INSTRUCTION_BYTES {
            return Err(Error::Invalid(format!(
                "PRIVATE field instruction exceeds {MAX_PRIVATE_FIELD_INSTRUCTION_BYTES} bytes"
            )));
        }

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            opaque_instructions: opaque_instructions.trim().to_string(),
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
        }))
    }

    /// Return the complete stored field instruction.
    ///
    /// This string remains opaque metadata and is never used to convert a
    /// document or change hidden-text visibility.
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return opaque stored instruction text after `PRIVATE`.
    ///
    /// It is never parsed, interpreted, or used to convert a document, change
    /// hidden-text visibility, or calculate layout.
    pub fn opaque_instructions(&self) -> &str {
        &self.opaque_instructions
    }

    /// Return the cached stored field result, if present.
    ///
    /// This is stored metadata only and is never regenerated by conversion or
    /// used to change hidden-text visibility.
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

/// A typed, inert Word `DATABASE` query field.
///
/// Word uses this field to query a database and insert a table. This type
/// retains opaque instruction text, a cached result, and field state only. It
/// never opens a data source or database, uses connection information, executes
/// SQL, generates or inserts a table, changes layout, or refreshes a field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Database {
    instruction: String,
    opaque_instructions: String,
    cached_result: Option<String>,
    dirty: bool,
    locked: bool,
}

impl Database {
    fn from_field(field: &Field) -> Result<Option<Self>> {
        let Some(opaque_instructions) =
            field_instruction_remainder(field.instruction(), "DATABASE")
        else {
            return Ok(None);
        };
        if field.instruction().len() > MAX_DATABASE_FIELD_INSTRUCTION_BYTES {
            return Err(Error::Invalid(format!(
                "DATABASE field instruction exceeds {MAX_DATABASE_FIELD_INSTRUCTION_BYTES} bytes"
            )));
        }

        Ok(Some(Self {
            instruction: field.instruction.clone(),
            opaque_instructions: opaque_instructions.trim().to_string(),
            cached_result: field.result.clone(),
            dirty: field.dirty,
            locked: field.locked,
        }))
    }

    /// Return the complete stored field instruction.
    ///
    /// This string remains opaque metadata and is never used to open a data
    /// source, database, or connection.
    pub fn instruction(&self) -> &str {
        &self.instruction
    }

    /// Return opaque stored instruction text after `DATABASE`.
    ///
    /// It is never parsed, interpreted, or used to connect, execute SQL,
    /// generate a table, or calculate layout.
    pub fn opaque_instructions(&self) -> &str {
        &self.opaque_instructions
    }

    /// Return the cached stored field result, if present.
    ///
    /// This is stored metadata only and is never regenerated from a database
    /// query.
    pub fn cached_result(&self) -> Option<&str> {
        self.cached_result.as_deref()
    }

    /// Whether a word processor has marked the cached result stale.
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Whether a word processor has locked this field against refresh.
    pub fn is_locked(&self) -> bool {
        self.locked
    }
}

impl Field {
    /// Check whether this is a `PRINT` field.
    ///
    /// Recognition is limited to the stored instruction. It never interprets
    /// printer-control codes, sends data to a printer, or refreshes the cached
    /// result.
    pub fn is_print_field(&self) -> bool {
        field_instruction_remainder(&self.instruction, "PRINT").is_some()
    }

    /// Parse this field as inert typed `PRINT` metadata.
    ///
    /// Returns `Ok(None)` for fields other than `PRINT`. The stored
    /// printer-instruction text, cached content, and dirty/lock state are
    /// metadata only; this method never interprets the instruction, sends data
    /// to a printer, or refreshes a field.
    pub fn print_field(&self) -> Result<Option<Print>> {
        Print::from_field(self)
    }

    /// Check whether this is an `EMBED` field.
    ///
    /// Recognition is limited to stored field metadata. It never loads,
    /// inspects, activates, renders, or executes an embedded object, or
    /// refreshes the field.
    pub fn is_embed_field(&self) -> bool {
        field_instruction_remainder(&self.instruction, "EMBED").is_some()
    }

    /// Parse this field as inert typed `EMBED` metadata.
    ///
    /// Returns `Ok(None)` for fields other than `EMBED`. The stored opaque object
    /// instruction, cached content, and dirty/lock state are metadata only;
    /// this method never loads, inspects, activates, renders, or executes an
    /// embedded object, or refreshes a field.
    pub fn embed_field(&self) -> Result<Option<Embed>> {
        Embed::from_field(self)
    }

    /// Check whether this is a `BARCODE` field.
    ///
    /// Recognition is limited to stored field metadata. It never parses or
    /// validates barcode data or symbology, generates or renders a barcode, or
    /// refreshes the field.
    pub fn is_barcode_field(&self) -> bool {
        field_instruction_remainder(&self.instruction, "BARCODE").is_some()
    }

    /// Parse this field as inert typed `BARCODE` metadata.
    ///
    /// Returns `Ok(None)` for fields other than `BARCODE`. The stored opaque barcode
    /// instruction, cached content, and dirty/lock state are metadata only;
    /// this method never parses or validates barcode data or symbology,
    /// generates or renders a barcode, or refreshes a field.
    pub fn barcode_field(&self) -> Result<Option<Barcode>> {
        Barcode::from_field(self)
    }

    /// Check whether this is a `BIDIOUTLINE` field.
    ///
    /// Recognition is limited to stored field metadata. It never reads
    /// right-to-left language, paragraph outline, or layout state; chooses a
    /// numbering system; calculates a result; or refreshes the field.
    pub fn is_bidi_outline_field(&self) -> bool {
        field_instruction_remainder(&self.instruction, "BIDIOUTLINE").is_some()
    }

    /// Parse this field as inert typed `BIDIOUTLINE` metadata.
    ///
    /// Returns `Ok(None)` for fields other than `BIDIOUTLINE`. The stored opaque
    /// instruction, cached content, and dirty/lock state are metadata only;
    /// this method never reads right-to-left language, paragraph outline, or
    /// layout state; chooses a numbering system; calculates a result; or
    /// refreshes a field.
    pub fn bidi_outline_field(&self) -> Result<Option<BidiOutline>> {
        BidiOutline::from_field(self)
    }

    /// Check whether this is a `SHAPE` drawing-canvas anchor field.
    ///
    /// Recognition is limited to stored field metadata. It never locates,
    /// links, loads, positions, lays out, or renders a drawing or canvas, or
    /// refreshes the field.
    pub fn is_shape_field(&self) -> bool {
        field_instruction_remainder(&self.instruction, "SHAPE").is_some()
    }

    /// Parse this field as inert typed `SHAPE` drawing-canvas anchor metadata.
    ///
    /// Returns `Ok(None)` for fields other than `SHAPE`. The stored opaque
    /// instruction, cached content, and dirty/lock state are metadata only;
    /// this method never locates, links, loads, positions, lays out, or renders
    /// a drawing or canvas, or refreshes a field.
    pub fn shape_field(&self) -> Result<Option<Shape>> {
        Shape::from_field(self)
    }

    /// Check whether this is a legacy text, checkbox, or drop-down form-code field.
    ///
    /// Recognition is limited to the stored field instruction. It never reads
    /// associated form-property XML, fills a form, changes a selection or
    /// checkbox state, invokes entry or exit macros, or refreshes a field.
    pub fn is_legacy_form_field(&self) -> bool {
        LegacyFormKind::from_instruction(&self.instruction).is_some()
    }

    /// Parse this field as inert typed legacy form-code metadata.
    ///
    /// Returns `Ok(None)` for fields outside the `FORMTEXT`, `FORMCHECKBOX`, and
    /// `FORMDROPDOWN` family. The result exposes only stored kind, opaque
    /// instruction text, cached content, and dirty/lock state; it never reads
    /// associated form-property XML, fills a form, changes a selection or
    /// checkbox state, invokes entry or exit macros, or refreshes a field.
    pub fn legacy_form_field(&self) -> Result<Option<LegacyForm>> {
        LegacyForm::from_field(self)
    }

    /// Check whether this is a `PRIVATE` conversion-data field.
    ///
    /// Recognition is limited to stored field metadata. It never converts a
    /// document, interprets field data, changes hidden-text visibility or
    /// layout, or refreshes a field. `PRIVATE` does not provide confidentiality
    /// semantics.
    pub fn is_private_field(&self) -> bool {
        field_instruction_remainder(&self.instruction, "PRIVATE").is_some()
    }

    /// Parse this field as inert typed `PRIVATE` conversion-data metadata.
    ///
    /// Returns `Ok(None)` for fields other than `PRIVATE`. The stored opaque
    /// instruction, cached content, and dirty/lock state are metadata only;
    /// this method never converts a document, interprets field data, changes
    /// hidden-text visibility or layout, or refreshes a field. `PRIVATE` does
    /// not provide confidentiality semantics.
    pub fn private_field(&self) -> Result<Option<Private>> {
        Private::from_field(self)
    }

    /// Check whether this is a `DATABASE` query field.
    ///
    /// Recognition is limited to stored field metadata. It never opens a data
    /// source or database, uses connection information, executes SQL, generates
    /// or inserts a table, changes layout, or refreshes a field.
    pub fn is_database_field(&self) -> bool {
        field_instruction_remainder(&self.instruction, "DATABASE").is_some()
    }

    /// Parse this field as inert typed `DATABASE` query metadata.
    ///
    /// Returns `Ok(None)` for fields other than `DATABASE`. The stored opaque
    /// instruction, cached content, and dirty/lock state are metadata only;
    /// this method never opens a data source or database, uses connection
    /// information, executes SQL, generates or inserts a table, changes layout,
    /// or refreshes a field.
    pub fn database_field(&self) -> Result<Option<Database>> {
        Database::from_field(self)
    }

    /// Check whether this is an `ADDIN` field.
    ///
    /// Recognition is limited to stored metadata. It never loads an add-in,
    /// invokes code, or refreshes a field result.
    pub fn is_add_in_field(&self) -> bool {
        field_instruction_remainder(&self.instruction, "ADDIN").is_some()
    }

    /// Check whether this is a `CONTROL` field.
    ///
    /// Recognition is limited to stored metadata. It never instantiates an OCX
    /// control, invokes code, renders content, or refreshes a field result.
    pub fn is_control_field(&self) -> bool {
        field_instruction_remainder(&self.instruction, "CONTROL").is_some()
    }

    /// Check whether this is an `HTMLCONTROL` field.
    ///
    /// Recognition is limited to stored metadata. It never instantiates an HTML
    /// control, executes script, renders content, or refreshes a field result.
    pub fn is_html_control_field(&self) -> bool {
        field_instruction_remainder(&self.instruction, "HTMLCONTROL").is_some()
    }

    /// Check whether this is an `ADDIN`, `CONTROL`, or `HTMLCONTROL` field.
    pub fn is_active_content_field(&self) -> bool {
        self.is_add_in_field() || self.is_control_field() || self.is_html_control_field()
    }

    /// Parse this field as inert typed add-in or control metadata.
    ///
    /// Returns `Ok(None)` for other fields. The stored kind, instruction,
    /// cached content, and dirty/lock state are opaque metadata only; this
    /// method never loads an add-in, instantiates a control, invokes code,
    /// executes script, renders content, accesses an external resource, or
    /// refreshes a field.
    pub fn active_content_field(&self) -> Result<Option<ActiveContent>> {
        ActiveContent::from_field(self)
    }
}
