[package]
name = "litchi-py"
version = "0.0.1"
edition = "2024"

[lib]
name = "litchi_py"
crate-type = ["cdylib"]

[dependencies]

# The main litchi library
litchi = { path = "../litchi", default-features = false, features = [
    "doc",
    "ooxml",
    "odf",
    "iwork",
    "rtf",
    "formula",
    "images",
] }
# PyO3 for Python bindings
pyo3 = { version = "0.29", features = ["extension-module", "abi3-py38"] }
