repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: Run rustfmt
        entry: rustfmt -v --config-path . --edition 2024
        language: system
        types: [rust]
        pass_filenames: true
      - id: cargo-sort
        name: Run cargo sort
        entry: cargo sort
        language: system
        files: ^Cargo\.toml$
        pass_filenames: false
      - id: cargo-clippy
        name: Run cargo clippy
        entry: cargo clippy --all-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-test-lib
        name: Run cargo test (lib and tests)
        entry: cargo test --all-features --lib --tests
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-test-doc
        name: Run cargo test (doc tests)
        entry: cargo test --all-features --doc
        language: system
        types: [rust]
        pass_filenames: false