[package]
name = "litchi"
version = "0.0.1"
edition = "2021"
homepage = "https://github.com/DevExzh/litchi"
license = "Apache-2.0"
repository = "https://github.com/DevExzh/litchi"
documentation = "https://docs.rs/litchi"
readme = "README.md"
keywords = ["ole", "ooxml", "excel", "word", "powerpoint", "visio"]
categories = ["data-formats", "office", "document-processing"]

[dependencies]
quick-xml = "0.38"
zip = "5.1"
memchr = "2.7"
atoi_simd = "0.16"
fast-float2 = "0.2"
thiserror = "2.0"
itoa = "1.0"
smallvec = "1.13"
rayon = "1.11"
# Image processing
image = { version = "0.24", default-features = false, features = ["png", "jpeg"] }
bytemuck = { version = "1.14", features = ["derive"] }
flate2 = "1.0"
base64 = "0.22"