[package]
name = "litchi"
version = "0.0.1"
edition = "2024"
homepage = "https://github.com/DevExzh/litchi"
license = "Apache-2.0"
repository = "https://github.com/DevExzh/litchi"
documentation = "https://docs.rs/litchi"
readme = "README.md"
keywords = ["ole", "ooxml", "excel", "word", "powerpoint", "visio"]
categories = ["data-formats", "office", "document-processing"]

[dependencies]
quick-xml = "0.38"
zip = "5.1"
memchr = "2.7"
atoi_simd = "0.16"
fast-float2 = "0.2"
thiserror = "2.0"
itoa = "1.0"
smallvec = "1.13"
rayon = "1.11"
# Image processing
image = { version = "0.25", features = ["default-formats", "rayon"] }
bytemuck = { version = "1.14", features = ["derive"] }
flate2 = "1.0"
base64 = "0.22"
# Formula parsing and conversion
rowan = "0.16"
bumpalo = { version = "3.16", features = ["collections"] }
phf = { version = "0.13", features = ["macros"] }
# YAML serialization for front matter
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
# Character encoding conversion for OLE strings
encoding_rs = "0.8"
# Date time support
chrono = { version = "0", features = ["serde"] }