[package]
name = "litchi"
version = "0.0.1"
edition = "2024"
homepage = "https://github.com/DevExzh/litchi"
license = "Apache-2.0"
repository = "https://github.com/DevExzh/litchi"
documentation = "https://docs.rs/litchi"
readme = "README.md"
keywords = ["ole", "ooxml", "excel", "word", "powerpoint", "visio"]
categories = ["data-formats", "office", "document-processing"]

[dependencies]
# XML parsing
quick-xml = "0.38"
# ZIP archive
zip = "6"
memchr = "2.7"
atoi_simd = "0.16"
fast-float2 = "0.2"
thiserror = "2.0"
itoa = "1.0"
smallvec = "1.15"
rayon = "1.11"
# Image processing
image = { version = "0.25", features = ["default-formats", "rayon"] }
bytemuck = { version = "1.24", features = ["derive"] }
flate2 = "1.1"
base64 = "0.22"
# Formula parsing and conversion
rowan = "0.16"
bumpalo = { version = "3.19", features = ["collections"] }
phf = { version = "0.13", features = ["macros"] }
# YAML serialization for front matter
serde = { version = "1.0", features = ["derive"] }
serde-saphyr = "0"
# Character encoding conversion for OLE strings
encoding_rs = "0.8"
# Date time support
chrono = { version = "0", features = ["serde"] }
# Snappy compression for iWork IWA files
snap = "1.1"
# Lazy static initialization
once_cell = "1.21"
# Protobuf support for iWork formats
prost = { version = "0.14", features = ["derive"] }
prost-types = "0.14"

[build-dependencies]
prost-build = "0.14"
