//! Comprehensive DOC file writer test
//!
//! This example demonstrates all features available in the DOC writer.
//! Tests paragraphs, formatting, tables, and document properties.
//!
//! Run with: cargo run --example comprehensive_doc_test

use litchi::ole::doc::{CharacterFormatting, DocWriter, ParagraphFormatting};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("=== Comprehensive DOC Writer Test ===\n");

    let mut writer = DocWriter::new();

    // ============================================================
    // 1. DOCUMENT PROPERTIES
    // ============================================================
    println!("1. Setting document properties...");
    writer.set_property("Title", "Comprehensive DOC Format Test");
    writer.set_property("Author", "Litchi Library");
    writer.set_property("Subject", "Testing all DOC writing features");
    writer.set_property("Company", "Litchi Project");
    writer.set_property("Comments", "Generated by Litchi comprehensive test");

    // ============================================================
    // 2. TITLE WITH FORMATTING
    // ============================================================
    println!("2. Adding title with formatting...");
    let title_char = CharacterFormatting {
        bold: Some(true),
        font_size: Some(32), // 16pt (size in half-points)
        font_name: Some("Arial".to_string()),
        ..Default::default()
    };

    let title_para = ParagraphFormatting {
        alignment: Some(1), // Center alignment
        ..Default::default()
    };

    writer.add_paragraph_with_format("DOC Format Feature Test Document", title_char, title_para)?;

    // ============================================================
    // 3. SUBTITLE WITH DIFFERENT FORMATTING
    // ============================================================
    println!("3. Adding subtitle...");
    let subtitle_char = CharacterFormatting {
        italic: Some(true),
        font_size: Some(22), // 11pt
        ..Default::default()
    };

    let subtitle_para = ParagraphFormatting {
        alignment: Some(1),     // Center
        space_after: Some(240), // 240 twips spacing after
        ..Default::default()
    };

    writer.add_paragraph_with_format(
        "Testing All Available Features",
        subtitle_char,
        subtitle_para,
    )?;

    // ============================================================
    // 4. INTRODUCTION SECTION
    // ============================================================
    println!("4. Adding introduction section...");
    let section_header = CharacterFormatting {
        bold: Some(true),
        font_size: Some(26), // 13pt
        ..Default::default()
    };

    let section_para = ParagraphFormatting {
        alignment: Some(0), // Left alignment
        space_before: Some(240),
        space_after: Some(120),
        ..Default::default()
    };

    writer.add_paragraph_with_format(
        "1. Introduction",
        section_header.clone(),
        section_para.clone(),
    )?;

    writer.add_paragraph(
        "This document demonstrates the DOC writing capabilities of the Litchi library. \
         It includes various formatting options, paragraph styles, and table structures.",
    )?;

    writer.add_paragraph(
        "The DOC format (Word 97-2003 Binary Format) uses the OLE2 compound file structure \
         with complex internal structures like FIB (File Information Block), piece tables, \
         and SPRM (Single Property Modifier) arrays for formatting.",
    )?;

    // ============================================================
    // 5. PARAGRAPH FORMATTING EXAMPLES
    // ============================================================
    println!("5. Adding paragraph formatting examples...");
    writer.add_paragraph_with_format(
        "2. Paragraph Formatting",
        section_header.clone(),
        section_para.clone(),
    )?;

    // Left-aligned paragraph
    let left_para = ParagraphFormatting {
        alignment: Some(0), // Left
        ..Default::default()
    };
    writer.add_paragraph_with_format(
        "This paragraph is left-aligned (default). It demonstrates the standard text alignment.",
        CharacterFormatting::default(),
        left_para,
    )?;

    // Center-aligned paragraph
    let center_para = ParagraphFormatting {
        alignment: Some(1), // Center
        ..Default::default()
    };
    writer.add_paragraph_with_format(
        "This paragraph is center-aligned. Perfect for titles and headings.",
        CharacterFormatting::default(),
        center_para,
    )?;

    // Right-aligned paragraph
    let right_para = ParagraphFormatting {
        alignment: Some(2), // Right
        ..Default::default()
    };
    writer.add_paragraph_with_format(
        "This paragraph is right-aligned. Often used for dates or signatures.",
        CharacterFormatting::default(),
        right_para,
    )?;

    // Justified paragraph
    let justified_para = ParagraphFormatting {
        alignment: Some(3), // Justify
        ..Default::default()
    };
    writer.add_paragraph_with_format(
        "This paragraph is justified. The text is aligned to both left and right margins, \
         creating a clean, professional look. This is commonly used in formal documents and books.",
        CharacterFormatting::default(),
        justified_para,
    )?;

    // ============================================================
    // 6. INDENTATION EXAMPLES
    // ============================================================
    println!("6. Adding indentation examples...");
    writer.add_paragraph_with_format(
        "3. Indentation",
        section_header.clone(),
        section_para.clone(),
    )?;

    // Left indent
    let left_indent_para = ParagraphFormatting {
        left_indent: Some(720), // 0.5 inch (1440 twips = 1 inch)
        ..Default::default()
    };
    writer.add_paragraph_with_format(
        "This paragraph has a left indent of 0.5 inches.",
        CharacterFormatting::default(),
        left_indent_para,
    )?;

    // First line indent
    let first_line_para = ParagraphFormatting {
        first_line_indent: Some(720), // 0.5 inch
        ..Default::default()
    };
    writer.add_paragraph_with_format(
        "This paragraph has a first-line indent of 0.5 inches. This is commonly used \
         in traditional book formatting where each paragraph starts with an indentation.",
        CharacterFormatting::default(),
        first_line_para,
    )?;

    // Hanging indent (negative first line)
    let hanging_para = ParagraphFormatting {
        left_indent: Some(720),
        first_line_indent: Some(-720), // Negative = hanging indent
        ..Default::default()
    };
    writer.add_paragraph_with_format(
        "This paragraph has a hanging indent, where the first line extends to the left \
         of subsequent lines. Often used for bibliographies and lists.",
        CharacterFormatting::default(),
        hanging_para,
    )?;

    // ============================================================
    // 7. CHARACTER FORMATTING EXAMPLES
    // ============================================================
    println!("7. Adding character formatting examples...");
    writer.add_paragraph_with_format(
        "4. Character Formatting",
        section_header.clone(),
        section_para.clone(),
    )?;

    // Bold text
    let bold_char = CharacterFormatting {
        bold: Some(true),
        ..Default::default()
    };
    writer.add_paragraph_with_format(
        "This text is bold.",
        bold_char,
        ParagraphFormatting::default(),
    )?;

    // Italic text
    let italic_char = CharacterFormatting {
        italic: Some(true),
        ..Default::default()
    };
    writer.add_paragraph_with_format(
        "This text is italic.",
        italic_char,
        ParagraphFormatting::default(),
    )?;

    // Underline text
    let underline_char = CharacterFormatting {
        underline: Some(true),
        ..Default::default()
    };
    writer.add_paragraph_with_format(
        "This text is underlined.",
        underline_char,
        ParagraphFormatting::default(),
    )?;

    // Bold + Italic
    let bold_italic_char = CharacterFormatting {
        bold: Some(true),
        italic: Some(true),
        ..Default::default()
    };
    writer.add_paragraph_with_format(
        "This text is both bold and italic.",
        bold_italic_char,
        ParagraphFormatting::default(),
    )?;

    // All formatting combined
    let all_format_char = CharacterFormatting {
        bold: Some(true),
        italic: Some(true),
        underline: Some(true),
        ..Default::default()
    };
    writer.add_paragraph_with_format(
        "This text combines bold, italic, and underline.",
        all_format_char,
        ParagraphFormatting::default(),
    )?;

    // ============================================================
    // 8. FONT SIZE EXAMPLES
    // ============================================================
    println!("8. Adding font size examples...");
    writer.add_paragraph_with_format(
        "5. Font Sizes",
        section_header.clone(),
        section_para.clone(),
    )?;

    for size in [16, 20, 24, 28, 32, 36] {
        let size_char = CharacterFormatting {
            font_size: Some(size),
            ..Default::default()
        };
        writer.add_paragraph_with_format(
            &format!("This text is {}pt (font_size = {})", size / 2, size),
            size_char,
            ParagraphFormatting::default(),
        )?;
    }

    // ============================================================
    // 9. SPACING EXAMPLES
    // ============================================================
    println!("9. Adding spacing examples...");
    writer.add_paragraph_with_format(
        "6. Paragraph Spacing",
        section_header.clone(),
        section_para.clone(),
    )?;

    let space_before_para = ParagraphFormatting {
        space_before: Some(360), // 0.25 inch
        ..Default::default()
    };
    writer.add_paragraph_with_format(
        "This paragraph has 0.25 inches of space before it.",
        CharacterFormatting::default(),
        space_before_para,
    )?;

    let space_after_para = ParagraphFormatting {
        space_after: Some(360), // 0.25 inch
        ..Default::default()
    };
    writer.add_paragraph_with_format(
        "This paragraph has 0.25 inches of space after it.",
        CharacterFormatting::default(),
        space_after_para,
    )?;

    writer.add_paragraph("Notice the spacing difference in the paragraphs above.")?;

    // ============================================================
    // 10. TABLE EXAMPLES
    // ============================================================
    println!("10. Adding table examples...");
    writer.add_paragraph_with_format("7. Tables", section_header.clone(), section_para.clone())?;

    writer.add_paragraph("Tables allow structured data presentation:")?;

    // Create a 4x3 table (4 rows, 3 columns)
    let table1 = writer.add_table(4, 3)?;

    // Set header row
    writer.set_table_cell_text(table1, 0, 0, "Product")?;
    writer.set_table_cell_text(table1, 0, 1, "Quantity")?;
    writer.set_table_cell_text(table1, 0, 2, "Price")?;

    // Set data rows
    writer.set_table_cell_text(table1, 1, 0, "Widget A")?;
    writer.set_table_cell_text(table1, 1, 1, "100")?;
    writer.set_table_cell_text(table1, 1, 2, "$25.00")?;

    writer.set_table_cell_text(table1, 2, 0, "Widget B")?;
    writer.set_table_cell_text(table1, 2, 1, "250")?;
    writer.set_table_cell_text(table1, 2, 2, "$15.00")?;

    writer.set_table_cell_text(table1, 3, 0, "Widget C")?;
    writer.set_table_cell_text(table1, 3, 1, "75")?;
    writer.set_table_cell_text(table1, 3, 2, "$42.50")?;

    writer.add_paragraph("")?; // Blank line after table

    // Create a 5x2 feature comparison table
    let table2 = writer.add_table(5, 2)?;

    writer.set_table_cell_text(table2, 0, 0, "Feature")?;
    writer.set_table_cell_text(table2, 0, 1, "Status")?;

    writer.set_table_cell_text(table2, 1, 0, "Text Extraction")?;
    writer.set_table_cell_text(table2, 1, 1, "Complete")?;

    writer.set_table_cell_text(table2, 2, 0, "Paragraph Formatting")?;
    writer.set_table_cell_text(table2, 2, 1, "Complete")?;

    writer.set_table_cell_text(table2, 3, 0, "Character Formatting")?;
    writer.set_table_cell_text(table2, 3, 1, "Complete")?;

    writer.set_table_cell_text(table2, 4, 0, "Table Support")?;
    writer.set_table_cell_text(table2, 4, 1, "Complete")?;

    // ============================================================
    // 11. CONCLUSION
    // ============================================================
    println!("11. Adding conclusion...");
    writer.add_paragraph("")?;

    writer.add_paragraph_with_format("8. Conclusion", section_header, section_para)?;

    let conclusion_char = CharacterFormatting {
        italic: Some(true),
        ..Default::default()
    };

    writer.add_paragraph_with_format(
        "This document demonstrates the comprehensive DOC writing capabilities of the Litchi library. \
         All features shown here conform to the Microsoft Word 97-2003 Binary File Format specification.",
        conclusion_char,
        ParagraphFormatting::default(),
    )?;

    let footer_para = ParagraphFormatting {
        alignment: Some(1), // Center
        space_before: Some(480),
        ..Default::default()
    };

    let footer_char = CharacterFormatting {
        font_size: Some(18), // 9pt
        ..Default::default()
    };

    writer.add_paragraph_with_format(
        "Generated by Litchi - High-Performance Office File Library",
        footer_char,
        footer_para,
    )?;

    // ============================================================
    // SAVE FILE
    // ============================================================
    println!("\nSaving to comprehensive_test.doc...");
    writer.save("comprehensive_test.doc")?;

    println!("\n✅ SUCCESS! DOC file created with:");
    println!("   ✓ Document properties (Title, Author, Subject, etc.)");
    println!("   ✓ Multiple formatting styles (Bold, Italic, Underline)");
    println!("   ✓ Various font sizes (8pt to 18pt)");
    println!("   ✓ Paragraph alignments (Left, Center, Right, Justify)");
    println!("   ✓ Indentation (Left, Right, First-line, Hanging)");
    println!("   ✓ Paragraph spacing (Before and After)");
    println!("   ✓ Two tables with structured data");
    println!("   ✓ Section headers and body text");
    println!("\n📝 Open 'comprehensive_test.doc' in Microsoft Word to verify!");

    Ok(())
}
