//! Comprehensive DOC file writer test
//!
//! This example demonstrates all features available in the DOC writer.
//! Tests paragraphs, formatting, tables, and document properties.
//!
//! Run with: cargo run --example comprehensive_doc_test

use litchi::ole::doc::{CharacterFormatting, DocWriter, ParagraphFormatting};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("=== Comprehensive DOC Writer Test ===\n");

    let mut writer = DocWriter::new();

    // ============================================================
    // 1. DOCUMENT PROPERTIES
    // ============================================================
    println!("1. Setting document properties...");
    writer.set_property("Title", "Comprehensive DOC Format Test");
    writer.set_property("Author", "Litchi Library");
    writer.set_property("Subject", "Testing all DOC writing features");
    writer.set_property("Company", "Litchi Project");
    writer.set_property("Comments", "Generated by Litchi comprehensive test");

    // ============================================================
    // 2. TITLE WITH FORMATTING
    // ============================================================
    println!("2. Adding title with formatting...");
    let mut title_char = CharacterFormatting::default();
    title_char.bold = Some(true);
    title_char.font_size = Some(32); // 16pt (size in half-points)
    title_char.font_name = Some("Arial".to_string());

    let mut title_para = ParagraphFormatting::default();
    title_para.alignment = Some(1); // Center alignment

    writer.add_paragraph_with_format("DOC Format Feature Test Document", title_char, title_para)?;

    // ============================================================
    // 3. SUBTITLE WITH DIFFERENT FORMATTING
    // ============================================================
    println!("3. Adding subtitle...");
    let mut subtitle_char = CharacterFormatting::default();
    subtitle_char.italic = Some(true);
    subtitle_char.font_size = Some(22); // 11pt

    let mut subtitle_para = ParagraphFormatting::default();
    subtitle_para.alignment = Some(1); // Center
    subtitle_para.space_after = Some(240); // 240 twips spacing after

    writer.add_paragraph_with_format(
        "Testing All Available Features",
        subtitle_char,
        subtitle_para,
    )?;

    // ============================================================
    // 4. INTRODUCTION SECTION
    // ============================================================
    println!("4. Adding introduction section...");
    let mut section_header = CharacterFormatting::default();
    section_header.bold = Some(true);
    section_header.font_size = Some(26); // 13pt

    let mut section_para = ParagraphFormatting::default();
    section_para.alignment = Some(0); // Left alignment
    section_para.space_before = Some(240);
    section_para.space_after = Some(120);

    writer.add_paragraph_with_format(
        "1. Introduction",
        section_header.clone(),
        section_para.clone(),
    )?;

    writer.add_paragraph(
        "This document demonstrates the DOC writing capabilities of the Litchi library. \
         It includes various formatting options, paragraph styles, and table structures.",
    )?;

    writer.add_paragraph(
        "The DOC format (Word 97-2003 Binary Format) uses the OLE2 compound file structure \
         with complex internal structures like FIB (File Information Block), piece tables, \
         and SPRM (Single Property Modifier) arrays for formatting.",
    )?;

    // ============================================================
    // 5. PARAGRAPH FORMATTING EXAMPLES
    // ============================================================
    println!("5. Adding paragraph formatting examples...");
    writer.add_paragraph_with_format(
        "2. Paragraph Formatting",
        section_header.clone(),
        section_para.clone(),
    )?;

    // Left-aligned paragraph
    let mut left_para = ParagraphFormatting::default();
    left_para.alignment = Some(0); // Left
    writer.add_paragraph_with_format(
        "This paragraph is left-aligned (default). It demonstrates the standard text alignment.",
        CharacterFormatting::default(),
        left_para,
    )?;

    // Center-aligned paragraph
    let mut center_para = ParagraphFormatting::default();
    center_para.alignment = Some(1); // Center
    writer.add_paragraph_with_format(
        "This paragraph is center-aligned. Perfect for titles and headings.",
        CharacterFormatting::default(),
        center_para,
    )?;

    // Right-aligned paragraph
    let mut right_para = ParagraphFormatting::default();
    right_para.alignment = Some(2); // Right
    writer.add_paragraph_with_format(
        "This paragraph is right-aligned. Often used for dates or signatures.",
        CharacterFormatting::default(),
        right_para,
    )?;

    // Justified paragraph
    let mut justified_para = ParagraphFormatting::default();
    justified_para.alignment = Some(3); // Justify
    writer.add_paragraph_with_format(
        "This paragraph is justified. The text is aligned to both left and right margins, \
         creating a clean, professional look. This is commonly used in formal documents and books.",
        CharacterFormatting::default(),
        justified_para,
    )?;

    // ============================================================
    // 6. INDENTATION EXAMPLES
    // ============================================================
    println!("6. Adding indentation examples...");
    writer.add_paragraph_with_format(
        "3. Indentation",
        section_header.clone(),
        section_para.clone(),
    )?;

    // Left indent
    let mut left_indent_para = ParagraphFormatting::default();
    left_indent_para.left_indent = Some(720); // 0.5 inch (1440 twips = 1 inch)
    writer.add_paragraph_with_format(
        "This paragraph has a left indent of 0.5 inches.",
        CharacterFormatting::default(),
        left_indent_para,
    )?;

    // First line indent
    let mut first_line_para = ParagraphFormatting::default();
    first_line_para.first_line_indent = Some(720); // 0.5 inch
    writer.add_paragraph_with_format(
        "This paragraph has a first-line indent of 0.5 inches. This is commonly used \
         in traditional book formatting where each paragraph starts with an indentation.",
        CharacterFormatting::default(),
        first_line_para,
    )?;

    // Hanging indent (negative first line)
    let mut hanging_para = ParagraphFormatting::default();
    hanging_para.left_indent = Some(720);
    hanging_para.first_line_indent = Some(-720); // Negative = hanging indent
    writer.add_paragraph_with_format(
        "This paragraph has a hanging indent, where the first line extends to the left \
         of subsequent lines. Often used for bibliographies and lists.",
        CharacterFormatting::default(),
        hanging_para,
    )?;

    // ============================================================
    // 7. CHARACTER FORMATTING EXAMPLES
    // ============================================================
    println!("7. Adding character formatting examples...");
    writer.add_paragraph_with_format(
        "4. Character Formatting",
        section_header.clone(),
        section_para.clone(),
    )?;

    // Bold text
    let mut bold_char = CharacterFormatting::default();
    bold_char.bold = Some(true);
    writer.add_paragraph_with_format(
        "This text is bold.",
        bold_char,
        ParagraphFormatting::default(),
    )?;

    // Italic text
    let mut italic_char = CharacterFormatting::default();
    italic_char.italic = Some(true);
    writer.add_paragraph_with_format(
        "This text is italic.",
        italic_char,
        ParagraphFormatting::default(),
    )?;

    // Underline text
    let mut underline_char = CharacterFormatting::default();
    underline_char.underline = Some(true);
    writer.add_paragraph_with_format(
        "This text is underlined.",
        underline_char,
        ParagraphFormatting::default(),
    )?;

    // Bold + Italic
    let mut bold_italic_char = CharacterFormatting::default();
    bold_italic_char.bold = Some(true);
    bold_italic_char.italic = Some(true);
    writer.add_paragraph_with_format(
        "This text is both bold and italic.",
        bold_italic_char,
        ParagraphFormatting::default(),
    )?;

    // All formatting combined
    let mut all_format_char = CharacterFormatting::default();
    all_format_char.bold = Some(true);
    all_format_char.italic = Some(true);
    all_format_char.underline = Some(true);
    writer.add_paragraph_with_format(
        "This text combines bold, italic, and underline.",
        all_format_char,
        ParagraphFormatting::default(),
    )?;

    // ============================================================
    // 8. FONT SIZE EXAMPLES
    // ============================================================
    println!("8. Adding font size examples...");
    writer.add_paragraph_with_format(
        "5. Font Sizes",
        section_header.clone(),
        section_para.clone(),
    )?;

    for size in [16, 20, 24, 28, 32, 36] {
        let mut size_char = CharacterFormatting::default();
        size_char.font_size = Some(size);
        writer.add_paragraph_with_format(
            &format!("This text is {}pt (font_size = {})", size / 2, size),
            size_char,
            ParagraphFormatting::default(),
        )?;
    }

    // ============================================================
    // 9. SPACING EXAMPLES
    // ============================================================
    println!("9. Adding spacing examples...");
    writer.add_paragraph_with_format(
        "6. Paragraph Spacing",
        section_header.clone(),
        section_para.clone(),
    )?;

    let mut space_before_para = ParagraphFormatting::default();
    space_before_para.space_before = Some(360); // 0.25 inch
    writer.add_paragraph_with_format(
        "This paragraph has 0.25 inches of space before it.",
        CharacterFormatting::default(),
        space_before_para,
    )?;

    let mut space_after_para = ParagraphFormatting::default();
    space_after_para.space_after = Some(360); // 0.25 inch
    writer.add_paragraph_with_format(
        "This paragraph has 0.25 inches of space after it.",
        CharacterFormatting::default(),
        space_after_para,
    )?;

    writer.add_paragraph("Notice the spacing difference in the paragraphs above.")?;

    // ============================================================
    // 10. TABLE EXAMPLES
    // ============================================================
    println!("10. Adding table examples...");
    writer.add_paragraph_with_format("7. Tables", section_header.clone(), section_para.clone())?;

    writer.add_paragraph("Tables allow structured data presentation:")?;

    // Create a 4x3 table (4 rows, 3 columns)
    let table1 = writer.add_table(4, 3)?;

    // Set header row
    writer.set_table_cell_text(table1, 0, 0, "Product")?;
    writer.set_table_cell_text(table1, 0, 1, "Quantity")?;
    writer.set_table_cell_text(table1, 0, 2, "Price")?;

    // Set data rows
    writer.set_table_cell_text(table1, 1, 0, "Widget A")?;
    writer.set_table_cell_text(table1, 1, 1, "100")?;
    writer.set_table_cell_text(table1, 1, 2, "$25.00")?;

    writer.set_table_cell_text(table1, 2, 0, "Widget B")?;
    writer.set_table_cell_text(table1, 2, 1, "250")?;
    writer.set_table_cell_text(table1, 2, 2, "$15.00")?;

    writer.set_table_cell_text(table1, 3, 0, "Widget C")?;
    writer.set_table_cell_text(table1, 3, 1, "75")?;
    writer.set_table_cell_text(table1, 3, 2, "$42.50")?;

    writer.add_paragraph("")?; // Blank line after table

    // Create a 5x2 feature comparison table
    let table2 = writer.add_table(5, 2)?;

    writer.set_table_cell_text(table2, 0, 0, "Feature")?;
    writer.set_table_cell_text(table2, 0, 1, "Status")?;

    writer.set_table_cell_text(table2, 1, 0, "Text Extraction")?;
    writer.set_table_cell_text(table2, 1, 1, "Complete")?;

    writer.set_table_cell_text(table2, 2, 0, "Paragraph Formatting")?;
    writer.set_table_cell_text(table2, 2, 1, "Complete")?;

    writer.set_table_cell_text(table2, 3, 0, "Character Formatting")?;
    writer.set_table_cell_text(table2, 3, 1, "Complete")?;

    writer.set_table_cell_text(table2, 4, 0, "Table Support")?;
    writer.set_table_cell_text(table2, 4, 1, "Complete")?;

    // ============================================================
    // 11. CONCLUSION
    // ============================================================
    println!("11. Adding conclusion...");
    writer.add_paragraph("")?;

    writer.add_paragraph_with_format("8. Conclusion", section_header, section_para)?;

    let mut conclusion_char = CharacterFormatting::default();
    conclusion_char.italic = Some(true);

    writer.add_paragraph_with_format(
        "This document demonstrates the comprehensive DOC writing capabilities of the Litchi library. \
         All features shown here conform to the Microsoft Word 97-2003 Binary File Format specification.",
        conclusion_char,
        ParagraphFormatting::default(),
    )?;

    let mut footer_para = ParagraphFormatting::default();
    footer_para.alignment = Some(1); // Center
    footer_para.space_before = Some(480);

    let mut footer_char = CharacterFormatting::default();
    footer_char.font_size = Some(18); // 9pt

    writer.add_paragraph_with_format(
        "Generated by Litchi - High-Performance Office File Library",
        footer_char,
        footer_para,
    )?;

    // ============================================================
    // SAVE FILE
    // ============================================================
    println!("\nSaving to comprehensive_test.doc...");
    writer.save("comprehensive_test.doc")?;

    println!("\n✅ SUCCESS! DOC file created with:");
    println!("   ✓ Document properties (Title, Author, Subject, etc.)");
    println!("   ✓ Multiple formatting styles (Bold, Italic, Underline)");
    println!("   ✓ Various font sizes (8pt to 18pt)");
    println!("   ✓ Paragraph alignments (Left, Center, Right, Justify)");
    println!("   ✓ Indentation (Left, Right, First-line, Hanging)");
    println!("   ✓ Paragraph spacing (Before and After)");
    println!("   ✓ Two tables with structured data");
    println!("   ✓ Section headers and body text");
    println!("\n📝 Open 'comprehensive_test.doc' in Microsoft Word to verify!");

    Ok(())
}
