//! Generate focused DOCX, PPTX, and XLSX core-properties Office smoke files.

use std::path::{Path, PathBuf};

use litchi_ooxml::{Props, docx, pptx, xlsx};

type Result<T> = std::result::Result<T, Box<dyn std::error::Error + Send + Sync>>;

fn main() -> Result<()> {
    let directory = std::env::args_os()
        .nth(1)
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("target/office-core-props"));
    std::fs::create_dir_all(&directory)?;

    create_docx(&directory)?;
    create_pptx(&directory)?;
    create_xlsx(&directory)?;

    println!("{}", directory.canonicalize()?.display());
    Ok(())
}

fn create_docx(directory: &Path) -> Result<()> {
    let authored = directory.join("core-props.docx");
    let cleared = directory.join("core-props-cleared.docx");
    let mut package = docx::Package::new()?;
    package
        .document_mut()?
        .add_heading("Litchi core-properties verification", 1)?;
    package
        .document_mut()?
        .add_paragraph_with_text("Word opened a move-authored metadata package.");
    let _ = package.put_props(smoke_props("DOCX"));
    package.save(&authored)?;

    let mut package = docx::Package::open(&authored)?;
    let _ = package.clear_props();
    package.save(&cleared)?;
    Ok(())
}

fn create_pptx(directory: &Path) -> Result<()> {
    let authored = directory.join("core-props.pptx");
    let cleared = directory.join("core-props-cleared.pptx");
    let mut package = pptx::Package::new()?;
    let slide = package.presentation_mut()?.add_slide()?;
    slide.set_title("Litchi core-properties verification");
    slide.add_text_box(
        "PowerPoint opened a move-authored metadata package.",
        914_400,
        1_828_800,
        7_315_200,
        914_400,
    );
    let _ = package.put_props(smoke_props("PPTX"));
    package.save(&authored)?;

    let mut package = pptx::Package::open(&authored)?;
    let _ = package.clear_props();
    package.save(&cleared)?;
    Ok(())
}

fn create_xlsx(directory: &Path) -> Result<()> {
    let authored = directory.join("core-props.xlsx");
    let cleared = directory.join("core-props-cleared.xlsx");
    let mut workbook = xlsx::Workbook::create()?;
    let sheet = workbook.worksheet_mut(0)?;
    sheet.set_name("Verification".to_owned());
    sheet.set_cell_value(1, 1, "Litchi core-properties verification");
    sheet.set_cell_value(2, 1, "Excel opened a move-authored metadata package.");
    let _ = workbook.put_props(smoke_props("XLSX"));
    workbook.save(&authored)?;

    let mut workbook = xlsx::Workbook::open(&authored)?;
    let _ = workbook.clear_props();
    workbook.save(&cleared)?;
    Ok(())
}

fn smoke_props(host: &str) -> Props {
    Props::new()
        .title(format!("Litchi {host} core-properties smoke"))
        .creator("Litchi Office verification")
        .subject("Safe move-owned OOXML metadata CRUD")
        .keywords("litchi,core-properties,crud")
        .description("Generated by the shared litchi-ooxml-common properties facade")
        .category("Interoperability")
        .content_status("Final")
        .language("en-US")
        .revision("2")
        .version("1.0")
}
