//! Generate focused DOCX, PPTX, and XLSX core-properties Office smoke files.

use std::path::{Path, PathBuf};

use litchi::ooxml::{common::Props, docx, pptx, xlsx};
use litchi_ooxml_common::properties;
use litchi_opc::OpcPackage;

type Result<T> = std::result::Result<T, Box<dyn std::error::Error + Send + Sync>>;

fn main() -> Result<()> {
    let directory = std::env::args_os()
        .nth(1)
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("target/office-core-props"));
    std::fs::create_dir_all(&directory)?;

    create_docx(&directory)?;
    create_pptx(&directory)?;
    create_xlsx(&directory)?;

    println!("{}", directory.canonicalize()?.display());
    Ok(())
}

fn create_docx(directory: &Path) -> Result<()> {
    let authored = directory.join("core-props.docx");
    let cleared = directory.join("core-props-cleared.docx");
    let mut package = docx::Package::new()?;
    package
        .document_mut()?
        .add_heading("Litchi core-properties verification", 1)?;
    package
        .document_mut()?
        .add_paragraph_with_text("Word opened a move-authored metadata package.");
    let _ = package.put_props(smoke_props("DOCX"));
    package.save(&authored)?;

    let mut package = docx::Package::open(&authored)?;
    let _ = package.clear_props();
    package.save(&cleared)?;
    Ok(())
}

fn create_pptx(directory: &Path) -> Result<()> {
    let authored = directory.join("core-props.pptx");
    let cleared = directory.join("core-props-cleared.pptx");
    let mut package = pptx::Package::new()?;
    let slide = package.presentation_mut()?.add_slide()?;
    slide.set_title("Litchi core-properties verification");
    slide.add_text_box(
        "PowerPoint opened a move-authored metadata package.",
        914_400,
        1_828_800,
        7_315_200,
        914_400,
    );
    package.save(&authored)?;

    let package = pptx::Package::open(&authored)?;
    let mut graph = package.opc()?.clone();
    let _ = properties::write(&mut graph, smoke_props("PPTX"))?;
    let mut package = pptx::Package::from_opc_package(graph)?;
    package.save(&authored)?;

    let package = pptx::Package::open(&authored)?;
    if properties::read(package.opc()?)?.is_none() {
        return Err("PPTX core properties were not published".into());
    }
    let mut graph = package.opc()?.clone();
    let _ = properties::clear(&mut graph)?;
    let mut package = pptx::Package::from_opc_package(graph)?;
    package.save(&cleared)?;
    Ok(())
}

fn create_xlsx(directory: &Path) -> Result<()> {
    let authored = directory.join("core-props.xlsx");
    let cleared = directory.join("core-props-cleared.xlsx");
    let package = xlsx::Package::create()?;
    package.save(&authored)?;

    let mut graph = OpcPackage::open(&authored)?;
    let _ = properties::write(&mut graph, smoke_props("XLSX"))?;
    let package = xlsx::Package::from_opc(graph)?;
    package.save(&authored)?;

    let graph = OpcPackage::open(&authored)?;
    if properties::read(&graph)?.is_none() {
        return Err("XLSX core properties were not published".into());
    }
    let mut graph = OpcPackage::open(&authored)?;
    let _ = properties::clear(&mut graph)?;
    let package = xlsx::Package::from_opc(graph)?;
    package.save(&cleared)?;
    Ok(())
}

fn smoke_props(host: &str) -> Props {
    Props::new()
        .title(format!("Litchi {host} core-properties smoke"))
        .creator("Litchi Office verification")
        .subject("Safe move-owned OOXML metadata CRUD")
        .keywords("litchi,core-properties,crud")
        .description("Generated by the shared OOXML core-properties facade")
        .category("Interoperability")
        .content_status("Final")
        .language("en-US")
        .revision("2")
        .version("1.0")
}
