//! WordprocessingML glossary documents (building blocks / AutoText).

use litchi_core::sheet::Result;
use litchi_opc::{OpcPackage,PackURI};
use quick_xml::{Reader,XmlVersion,encoding::Decoder,events::{BytesStart,Event}};

const W:&str="http://schemas.openxmlformats.org/wordprocessingml/2006/main";const WS:&str="http://purl.oclc.org/ooxml/wordprocessingml/main";const R:&str="http://schemas.openxmlformats.org/officeDocument/2006/relationships";const RS:&str="http://purl.oclc.org/ooxml/officeDocument/relationships";const REL:&str="http://schemas.openxmlformats.org/officeDocument/2006/relationships/glossaryDocument";const STRICT_REL:&str="http://purl.oclc.org/ooxml/officeDocument/relationships/glossaryDocument";const CT:&str="application/vnd.openxmlformats-officedocument.wordprocessingml.document.glossary+xml";
const MAX:usize=32*1024*1024;const MAX_DEPTH:usize=256;const MAX_NODES:usize=1_000_000;const MAX_PARTS:usize=100_000;const MAX_VALUES:usize=4096;const MAX_STRING:usize=1024*1024;

#[derive(Clone,Copy,Debug,PartialEq,Eq)]pub enum DocPartType{None,Normal,AutoExpand,Toolbar,Speller,FormField,SdtPlaceholder}
#[derive(Clone,Copy,Debug,PartialEq,Eq)]pub enum InsertionBehavior{Content,Paragraph,Page}
#[derive(Clone,Debug,PartialEq,Eq)]pub struct DocPartGallery(String);impl DocPartGallery{pub fn as_str(&self)->&str{&self.0}pub fn parse(v:&str)->Result<Self>{if GALLERIES.contains(&v){Ok(Self(v.into()))}else{Err(invalid(format!("invalid document-part gallery '{v}'")))}}}
#[derive(Clone,Debug,PartialEq,Eq)]pub struct DocPartName{pub value:String,pub decorated:Option<bool>}
#[derive(Clone,Debug,PartialEq,Eq)]pub struct DocPartCategory{pub name:String,pub gallery:DocPartGallery}
#[derive(Clone,Debug,PartialEq,Eq,Default)]pub struct DocPartProperties{pub name:Option<DocPartName>,pub style:Option<String>,pub category:Option<DocPartCategory>,pub all_types:Option<bool>,pub types:Vec<DocPartType>,pub behaviors:Vec<InsertionBehavior>,pub description:Option<String>,pub guid:Option<String>}
#[derive(Clone,Debug,PartialEq,Eq)]pub struct GlossaryEntry{pub properties:Option<DocPartProperties>,/// Full inert `w:docPartBody` subtree.
pub body_xml:Option<Vec<u8>>}
#[derive(Clone,Debug,PartialEq,Eq,Default)]pub struct GlossaryDocument{/// Full inert `w:background` subtree.
pub background_xml:Option<Vec<u8>>,pub entries:Vec<GlossaryEntry>}

impl GlossaryDocument{pub fn parse(xml:&[u8])->Result<Self>{if xml.len()>MAX{return Err(invalid("glossary document exceeds 32 MiB"));}let x=crate::common::mce::process_ooxml(xml)?;if x.len()>MAX{return Err(invalid("processed glossary document exceeds 32 MiB"));}project(&parse_dom(x.as_ref())?)}pub fn to_xml(&self,strict:bool)->Result<Vec<u8>>{validate(self)?;let w=if strict{WS}else{W};let r=if strict{RS}else{R};let mut x=format!(r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:glossaryDocument xmlns:w="{w}" xmlns:r="{r}">"#);if let Some(v)=&self.background_xml{opaque(&mut x,v,strict)?;}if !self.entries.is_empty(){x.push_str("<w:docParts>");for entry in &self.entries{write_entry(&mut x,entry,strict)?;}x.push_str("</w:docParts>");}x.push_str("</w:glossaryDocument>");if x.len()>MAX{return Err(invalid("serialized glossary document exceeds 32 MiB"));}Ok(x.into_bytes())}}

pub fn load_from_package(package:&OpcPackage)->Result<Option<GlossaryDocument>>{let main=package.main_document_part()?;let mut found=main.rels().iter().filter(|x|matches!(x.reltype(),REL|STRICT_REL));let Some(rel)=found.next()else{return Ok(None)};if found.next().is_some(){return Err(invalid("main document has multiple glossary relationships"));}if rel.is_external(){return Err(invalid("glossary relationship cannot be external"));}let uri:PackURI=rel.target_partname()?;let part=package.get_part(&uri)?;if part.content_type()!=CT{return Err(invalid(format!("glossary part '{uri}' has invalid content type '{}'",part.content_type())));}Ok(Some(GlossaryDocument::parse(part.blob())?))}

#[derive(Clone)]struct Attr{q:String,ns:String,l:String,v:String}#[derive(Clone)]enum Content{Node(Node),Text(String),CData(String),Comment(String)}#[derive(Clone)]struct Node{q:String,ns:String,l:String,attrs:Vec<Attr>,bindings:Vec<(String,String)>,content:Vec<Content>}
fn parse_dom(xml:&[u8])->Result<Node>{std::str::from_utf8(xml).map_err(xml_error)?;let mut rd=Reader::from_reader(xml);let mut stack:Vec<Node>=Vec::new();let mut root=None;let mut count=0;loop{let d=rd.decoder();match rd.read_event(){Ok(Event::Start(e))=>{count+=1;if count>MAX_NODES||stack.len()>=MAX_DEPTH{return Err(invalid("glossary XML resource limit exceeded"));}stack.push(make(&e,d,&stack)?);},Ok(Event::Empty(e))=>{count+=1;if count>MAX_NODES{return Err(invalid("glossary node limit exceeded"));}let n=make(&e,d,&stack)?;attach(&mut stack,&mut root,n)?;},Ok(Event::End(_))=>{let n=stack.pop().ok_or_else(||invalid("unexpected glossary closing element"))?;attach(&mut stack,&mut root,n)?;},Ok(Event::Text(t))=>{let v=t.decode().map_err(xml_error)?.into_owned();if let Some(n)=stack.last_mut(){n.content.push(Content::Text(v))}else if !v.trim().is_empty(){return Err(invalid("text outside glossary root"));}},Ok(Event::CData(t))=>if let Some(n)=stack.last_mut(){n.content.push(Content::CData(t.decode().map_err(xml_error)?.into_owned()))}else{return Err(invalid("CDATA outside glossary root"));},Ok(Event::Comment(t))=>if let Some(n)=stack.last_mut(){n.content.push(Content::Comment(t.decode().map_err(xml_error)?.into_owned()))},Ok(Event::GeneralRef(t))=>if let Some(n)=stack.last_mut(){n.content.push(Content::Text(crate::common::xml::decode_xml_reference(&t)?))}else{return Err(invalid("entity outside glossary root"));},Ok(Event::DocType(_)|Event::PI(_))=>return Err(invalid("DTD and processing instructions are rejected")),Ok(Event::Decl(_))=>{},Ok(Event::Eof)=>break,Err(e)=>return Err(xml_error(e))}}if !stack.is_empty(){return Err(invalid("unterminated glossary XML"));}root.ok_or_else(||invalid("missing glossary root"))}
fn make(e:&BytesStart<'_>,d:Decoder,stack:&[Node])->Result<Node>{let q=std::str::from_utf8(e.name().as_ref()).map_err(xml_error)?.to_string();let mut bindings=stack.last().map(|x|x.bindings.clone()).unwrap_or_default();let mut raw=Vec::new();for a in e.attributes().with_checks(true){let a=a.map_err(xml_error)?;raw.push((std::str::from_utf8(a.key.as_ref()).map_err(xml_error)?.to_string(),a.decoded_and_normalized_value(XmlVersion::Implicit1_0,d).map_err(xml_error)?.into_owned()));}for(k,v)in &raw{if k=="xmlns"||k.starts_with("xmlns:"){let key=k.strip_prefix("xmlns:").unwrap_or("").to_string();if let Some(x)=bindings.iter_mut().find(|x|x.0==key){x.1=v.clone()}else{bindings.push((key,v.clone()))}}}let(pr,lo)=split(&q)?;let local=lo.to_string();let ns=resolve(&bindings,pr)?;let mut attrs=Vec::new();for(q,v)in raw{if q=="xmlns"||q.starts_with("xmlns:"){continue}let(pr,lo)=split(&q)?;let ans=if pr.is_empty(){String::new()}else{resolve(&bindings,pr)?};let local=lo.to_string();attrs.push(Attr{q,ns:ans,l:local,v});}Ok(Node{q,ns,l:local,attrs,bindings,content:Vec::new()})}
fn attach(stack:&mut[Node],root:&mut Option<Node>,n:Node)->Result<()>{if let Some(p)=stack.last_mut(){p.content.push(Content::Node(n))}else if root.replace(n).is_some(){return Err(invalid("multiple XML roots"));}Ok(())}

fn project(n:&Node)->Result<GlossaryDocument>{expect(n,"glossaryDocument")?;noattrs(n)?;let c=kids(n)?;let mut out=GlossaryDocument::default();let mut index=0;if c.first().is_some_and(|x|x.l=="background"){out.background_xml=Some(node_xml(c[0],false)?);index=1;}if index<c.len(){let parts=c[index];expect(parts,"docParts")?;noattrs(parts)?;for p in kids(parts)?{if out.entries.len()>=MAX_PARTS{return Err(invalid("glossary entry limit exceeded"));}out.entries.push(parse_entry(p)?);}index+=1;}if index!=c.len(){return Err(invalid("unexpected glossary root child"));}validate(&out)?;Ok(out)}
fn parse_entry(n:&Node)->Result<GlossaryEntry>{expect(n,"docPart")?;noattrs(n)?;let c=kids(n)?;if c.len()>2{return Err(invalid("docPart has too many children"));}let mut properties=None;let mut body_xml=None;let mut i=0;if c.first().is_some_and(|x|x.l=="docPartPr"){properties=Some(parse_properties(c[0])?);i=1;}if i<c.len(){expect(c[i],"docPartBody")?;body_xml=Some(node_xml(c[i],false)?);i+=1;}if i!=c.len(){return Err(invalid("invalid docPart child order"));}Ok(GlossaryEntry{properties,body_xml})}
fn parse_properties(n:&Node)->Result<DocPartProperties>{noattrs(n)?;let mut out=DocPartProperties::default();let mut order=0;for c in kids(n)?{expect_w(c)?;let i=match c.l.as_str(){"name"=>0,"style"=>1,"category"=>2,"types"=>3,"behaviors"=>4,"description"=>5,"guid"=>6,_=>return Err(invalid("unexpected docPartPr child"))};if i<order{return Err(invalid("docPartPr children out of order"));}order=i;match i{0=>{if out.name.is_some(){return Err(invalid("duplicate building-block name"));}out.name=Some(DocPartName{value:wval(c)?,decorated:onoff(c,"decorated")?});only_w(c,&["val","decorated"])?;leaf(c)?;},1=>set(&mut out.style,wval(c)?)?,2=>{if out.category.is_some(){return Err(invalid("duplicate category"));}let k=kids(c)?;if k.len()!=2||k[0].l!="name"||k[1].l!="gallery"{return Err(invalid("category requires name then gallery"));}out.category=Some(DocPartCategory{name:wval(k[0])?,gallery:DocPartGallery::parse(&wval(k[1])?)?});},3=>{if !out.types.is_empty()||out.all_types.is_some(){return Err(invalid("duplicate types"));}out.all_types=onoff(c,"all")?;only_w(c,&["all"])?;for t in kids(c)?{if out.types.len()>=MAX_VALUES{return Err(invalid("type limit exceeded"));}expect(t,"type")?;out.types.push(parse_type(&wval(t)?)?);}},4=>{if !out.behaviors.is_empty(){return Err(invalid("duplicate behaviors"));}noattrs(c)?;for b in kids(c)?{if out.behaviors.len()>=MAX_VALUES{return Err(invalid("behavior limit exceeded"));}expect(b,"behavior")?;out.behaviors.push(parse_behavior(&wval(b)?)?);}},5=>set(&mut out.description,wval(c)?)?,6=>set(&mut out.guid,wval(c)?)?,_=>unreachable!()}}Ok(out)}

fn write_entry(x:&mut String,e:&GlossaryEntry,s:bool)->Result<()>{x.push_str("<w:docPart>");if let Some(p)=&e.properties{write_properties(x,p);}if let Some(b)=&e.body_xml{opaque(x,b,s)?;}x.push_str("</w:docPart>");Ok(())}
fn write_properties(x:&mut String,p:&DocPartProperties){x.push_str("<w:docPartPr>");if let Some(n)=&p.name{x.push_str("<w:name");wattr(x,"val",&n.value);wonoff(x,"decorated",n.decorated);x.push_str("/>");}if let Some(v)=&p.style{leafval(x,"style",v);}if let Some(c)=&p.category{x.push_str("<w:category>");leafval(x,"name",&c.name);leafval(x,"gallery",c.gallery.as_str());x.push_str("</w:category>");}if p.all_types.is_some()||!p.types.is_empty(){x.push_str("<w:types");wonoff(x,"all",p.all_types);x.push('>');for v in &p.types{leafval(x,"type",type_str(*v));}x.push_str("</w:types>");}if !p.behaviors.is_empty(){x.push_str("<w:behaviors>");for v in &p.behaviors{leafval(x,"behavior",behavior_str(*v));}x.push_str("</w:behaviors>");}if let Some(v)=&p.description{leafval(x,"description",v);}if let Some(v)=&p.guid{leafval(x,"guid",v);}x.push_str("</w:docPartPr>");}
fn leafval(x:&mut String,n:&str,v:&str){x.push_str(&format!("<w:{n}"));wattr(x,"val",v);x.push_str("/>")}fn wattr(x:&mut String,n:&str,v:&str){x.push_str(&format!(" w:{n}=\""));esc(x,v);x.push('"')}fn wonoff(x:&mut String,n:&str,v:Option<bool>){if let Some(v)=v{wattr(x,n,if v{"1"}else{"0"})}}

fn validate(v:&GlossaryDocument)->Result<()>{if v.entries.len()>MAX_PARTS{return Err(invalid("glossary entry limit exceeded"));}if let Some(x)=&v.background_xml{parse_dom(x)?;}for e in &v.entries{if let Some(x)=&e.body_xml{parse_dom(x)?;}if let Some(p)=&e.properties{for s in [p.name.as_ref().map(|x|x.value.as_str()),p.style.as_deref(),p.category.as_ref().map(|x|x.name.as_str()),p.description.as_deref(),p.guid.as_deref()].into_iter().flatten(){bounded(s)?;}if p.types.len()>MAX_VALUES||p.behaviors.len()>MAX_VALUES{return Err(invalid("glossary metadata value limit exceeded"));}}}Ok(())}
fn opaque(x:&mut String,b:&[u8],strict:bool)->Result<()>{parse_dom(b)?;let mut s=std::str::from_utf8(b).map_err(xml_error)?.to_string();if strict{s=s.replace(W,WS).replace(R,RS)}else{s=s.replace(WS,W).replace(RS,R)}x.push_str(&s);Ok(())}
fn node_xml(n:&Node,s:bool)->Result<Vec<u8>>{let mut x=String::new();node_write(&mut x,n,s)?;Ok(x.into_bytes())}fn node_write(x:&mut String,n:&Node,s:bool)->Result<()>{x.push('<');x.push_str(&n.q);for(p,u)in &n.bindings{if p.is_empty(){x.push_str(" xmlns=\"")}else{x.push_str(" xmlns:");x.push_str(p);x.push_str("=\"")}esc(x,mapns(u,s));x.push('"');}for a in &n.attrs{x.push(' ');x.push_str(&a.q);x.push_str("=\"");esc(x,&a.v);x.push('"');}if n.content.is_empty(){x.push_str("/>");return Ok(())}x.push('>');for c in &n.content{match c{Content::Node(n)=>node_write(x,n,s)?,Content::Text(v)=>text(x,v),Content::CData(v)=>{x.push_str("<![CDATA[");x.push_str(v);x.push_str("]]>");},Content::Comment(v)=>{x.push_str("<!--");x.push_str(v);x.push_str("-->");}}}x.push_str("</");x.push_str(&n.q);x.push('>');Ok(())}fn mapns<'a>(v:&'a str,s:bool)->&'a str{if s{match v{W=>WS,R=>RS,_=>v}}else{match v{WS=>W,RS=>R,_=>v}}}

fn kids(n:&Node)->Result<Vec<&Node>>{let mut v=Vec::new();for c in &n.content{match c{Content::Node(x)=>v.push(x),Content::Text(x)if x.trim().is_empty()=>{},Content::Comment(_)=>{},_=>return Err(invalid("unexpected text in typed glossary metadata"))}}Ok(v)}fn leaf(n:&Node)->Result<()>{if kids(n)?.is_empty(){Ok(())}else{Err(invalid("glossary metadata leaf has children"))}}fn expect(n:&Node,l:&str)->Result<()>{if(n.ns==W||n.ns==WS)&&n.l==l{Ok(())}else{Err(invalid(format!("expected WordprocessingML {l}")))}}fn expect_w(n:&Node)->Result<()>{if n.ns==W||n.ns==WS{Ok(())}else{Err(invalid("expected WordprocessingML metadata"))}}
fn wval(n:&Node)->Result<String>{let v=wattr_get(n,"val")?.ok_or_else(||invalid("missing w:val"))?;bounded(&v)?;only_w(n,&["val"])?;leaf(n)?;Ok(v)}fn wattr_get(n:&Node,l:&str)->Result<Option<String>>{let mut v=None;for a in &n.attrs{if(a.ns==W||a.ns==WS)&&a.l==l{if v.is_some(){return Err(invalid("duplicate WordprocessingML attribute"));}v=Some(a.v.clone());}}Ok(v)}fn onoff(n:&Node,l:&str)->Result<Option<bool>>{match wattr_get(n,l)?.as_deref(){None=>Ok(None),Some("1"|"true"|"on")=>Ok(Some(true)),Some("0"|"false"|"off")=>Ok(Some(false)),_=>Err(invalid(format!("invalid on/off attribute '{l}'")))}}fn only_w(n:&Node,allowed:&[&str])->Result<()>{for a in &n.attrs{if !((a.ns==W||a.ns==WS)&&allowed.contains(&a.l.as_str())){return Err(invalid(format!("unexpected glossary attribute '{}'",a.q)));}}Ok(())}fn noattrs(n:&Node)->Result<()>{if n.attrs.is_empty(){Ok(())}else{Err(invalid("unexpected glossary attributes"))}}fn set<T>(slot:&mut Option<T>,v:T)->Result<()>{if slot.replace(v).is_some(){Err(invalid("duplicate glossary metadata"))}else{Ok(())}}
fn parse_type(v:&str)->Result<DocPartType>{match v{"none"=>Ok(DocPartType::None),"normal"=>Ok(DocPartType::Normal),"autoExp"=>Ok(DocPartType::AutoExpand),"toolbar"=>Ok(DocPartType::Toolbar),"speller"=>Ok(DocPartType::Speller),"formFld"=>Ok(DocPartType::FormField),"bbPlcHdr"=>Ok(DocPartType::SdtPlaceholder),_=>Err(invalid(format!("invalid document-part type '{v}'")))}}fn type_str(v:DocPartType)->&'static str{match v{DocPartType::None=>"none",DocPartType::Normal=>"normal",DocPartType::AutoExpand=>"autoExp",DocPartType::Toolbar=>"toolbar",DocPartType::Speller=>"speller",DocPartType::FormField=>"formFld",DocPartType::SdtPlaceholder=>"bbPlcHdr"}}
fn parse_behavior(v:&str)->Result<InsertionBehavior>{match v{"content"=>Ok(InsertionBehavior::Content),"p"=>Ok(InsertionBehavior::Paragraph),"pg"=>Ok(InsertionBehavior::Page),_=>Err(invalid(format!("invalid insertion behavior '{v}'")))}}fn behavior_str(v:InsertionBehavior)->&'static str{match v{InsertionBehavior::Content=>"content",InsertionBehavior::Paragraph=>"p",InsertionBehavior::Page=>"pg"}}
const GALLERIES:&[&str]=&["placeholder","any","default","docParts","coverPg","eq","ftrs","hdrs","pgNum","tbls","watermarks","autoTxt","txtBox","pgNumT","pgNumB","pgNumMargins","tblOfContents","bib","custQuickParts","custCoverPg","custEq","custFtrs","custHdrs","custPgNum","custTbls","custWatermarks","custAutoTxt","custTxtBox","custPgNumT","custPgNumB","custPgNumMargins","custTblOfContents","custBib","custom1","custom2","custom3","custom4","custom5"];
fn split(q:&str)->Result<(&str,&str)>{if let Some((p,l))=q.split_once(':'){if l.is_empty()||l.contains(':'){return Err(invalid("invalid QName"));}Ok((p,l))}else{Ok(("",q))}}fn resolve(b:&[(String,String)],p:&str)->Result<String>{if p=="xml"{return Ok("http://www.w3.org/XML/1998/namespace".into());}b.iter().rev().find(|x|x.0==p).map(|x|x.1.clone()).ok_or_else(||invalid(format!("unbound prefix '{p}'")))}fn bounded(v:&str)->Result<()>{if v.len()>MAX_STRING{Err(invalid("glossary metadata string exceeds 1 MiB"))}else{Ok(())}}
fn esc(x:&mut String,v:&str){for c in v.chars(){match c{'&'=>x.push_str("&amp;"),'<'=>x.push_str("&lt;"),'"'=>x.push_str("&quot;"),'\r'=>x.push_str("&#xD;"),'\n'=>x.push_str("&#xA;"),'\t'=>x.push_str("&#x9;"),_=>x.push(c)}}}fn text(x:&mut String,v:&str){for c in v.chars(){match c{'&'=>x.push_str("&amp;"),'<'=>x.push_str("&lt;"),'>'=>x.push_str("&gt;"),_=>x.push(c)}}}fn invalid(v:impl Into<String>)->Box<dyn std::error::Error+Send+Sync>{std::io::Error::new(std::io::ErrorKind::InvalidData,v.into()).into()}fn xml_error(e:impl std::fmt::Display)->Box<dyn std::error::Error+Send+Sync>{invalid(e.to_string())}

#[cfg(test)]mod tests{use super::*;fn f(b:&[u8])->GlossaryDocument{let p=OpcPackage::from_bytes(b).unwrap();load_from_package(&p).unwrap().unwrap()}
 #[test]fn poi_placeholders_and_strict_roundtrip(){let v=f(include_bytes!("../../../../3rdparty/poi/test-data/document/Bug54849.docx"));assert_eq!(v.entries.len(),3);let p=v.entries[0].properties.as_ref().unwrap();assert_eq!(p.types,[DocPartType::SdtPlaceholder]);assert_eq!(p.category.as_ref().unwrap().gallery.as_str(),"placeholder");let x=v.to_xml(true).unwrap();assert_eq!(GlossaryDocument::parse(&x).unwrap().entries.len(),3);}
 #[test]fn libreoffice_multiple_autotext_and_tables_stay_inert(){let v=f(include_bytes!("../../../../3rdparty/libreoffice-core/sw/qa/extras/uiwriter/data/autotext-multiple.dotx"));assert_eq!(v.entries.len(),3);assert_eq!(v.entries[0].properties.as_ref().unwrap().name.as_ref().unwrap().value,"Multiple");let body=std::str::from_utf8(v.entries[2].body_xml.as_deref().unwrap()).unwrap();assert!(body.contains("w:tbl"));assert!(body.contains("jksdjkfdskjfds"));}
 #[test]fn libreoffice_empty_glossary_is_valid(){let v=f(include_bytes!("../../../../3rdparty/libreoffice-core/sw/qa/extras/ooxmlexport/data/testGlossary.docx"));assert!(v.entries.is_empty());assert!(v.to_xml(false).is_ok());}
 #[test]fn strict_mce_and_malformed(){let x=format!(r#"<w:glossaryDocument xmlns:w="{WS}" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:u="urn:u" mc:Ignorable="u"><w:docParts><mc:AlternateContent><mc:Choice Requires="u"><u:x/></mc:Choice><mc:Fallback><w:docPart><w:docPartPr><w:name w:val="MCE"/><w:behaviors><w:behavior w:val="p"/></w:behaviors></w:docPartPr><w:docPartBody><w:p/></w:docPartBody></w:docPart></mc:Fallback></mc:AlternateContent></w:docParts></w:glossaryDocument>"#);assert_eq!(GlossaryDocument::parse(x.as_bytes()).unwrap().entries.len(),1);for bad in [format!(r#"<w:glossaryDocument xmlns:w="{W}"><w:docParts><w:docPart><w:docPartPr><w:behaviors><w:behavior w:val="run"/></w:behaviors></w:docPartPr></w:docPart></w:docParts></w:glossaryDocument>"#),format!(r#"<!DOCTYPE x><w:glossaryDocument xmlns:w="{W}"/>"#)]{assert!(GlossaryDocument::parse(bad.as_bytes()).is_err(),"accepted {bad}");}let mut v=GlossaryDocument::default();v.background_xml=Some(b"<?bad?><w:background/>".to_vec());assert!(v.to_xml(false).is_err());}
}
