// Generated from Apache POI's spec-derived BIFF function metadata.
// Keep this static so published builds do not parse or depend on third-party resources at runtime.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct BuiltInFunctionMetadata {
    index: u16,
    name: &'static str,
    min_params: u8,
    max_params: u8,
}

impl BuiltInFunctionMetadata {
    fn fixed_arity(self) -> Option<usize> {
        (self.min_params == self.max_params).then_some(usize::from(self.min_params))
    }

    fn accepts_arity(self, arity: usize) -> bool {
        (usize::from(self.min_params)..=usize::from(self.max_params)).contains(&arity)
    }
}

const BUILT_IN_FUNCTIONS: &[BuiltInFunctionMetadata] = &[
    BuiltInFunctionMetadata { index: 0, name: "COUNT", min_params: 0, max_params: 30 },
    BuiltInFunctionMetadata { index: 1, name: "IF", min_params: 2, max_params: 3 },
    BuiltInFunctionMetadata { index: 2, name: "ISNA", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 3, name: "ISERROR", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 4, name: "SUM", min_params: 0, max_params: 30 },
    BuiltInFunctionMetadata { index: 5, name: "AVERAGE", min_params: 1, max_params: 30 },
    BuiltInFunctionMetadata { index: 6, name: "MIN", min_params: 1, max_params: 30 },
    BuiltInFunctionMetadata { index: 7, name: "MAX", min_params: 1, max_params: 30 },
    BuiltInFunctionMetadata { index: 8, name: "ROW", min_params: 0, max_params: 1 },
    BuiltInFunctionMetadata { index: 9, name: "COLUMN", min_params: 0, max_params: 1 },
    BuiltInFunctionMetadata { index: 10, name: "NA", min_params: 0, max_params: 0 },
    BuiltInFunctionMetadata { index: 11, name: "NPV", min_params: 2, max_params: 30 },
    BuiltInFunctionMetadata { index: 12, name: "STDEV", min_params: 1, max_params: 30 },
    BuiltInFunctionMetadata { index: 13, name: "DOLLAR", min_params: 1, max_params: 2 },
    BuiltInFunctionMetadata { index: 14, name: "FIXED", min_params: 1, max_params: 3 },
    BuiltInFunctionMetadata { index: 15, name: "SIN", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 16, name: "COS", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 17, name: "TAN", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 18, name: "ATAN", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 19, name: "PI", min_params: 0, max_params: 0 },
    BuiltInFunctionMetadata { index: 20, name: "SQRT", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 21, name: "EXP", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 22, name: "LN", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 23, name: "LOG10", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 24, name: "ABS", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 25, name: "INT", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 26, name: "SIGN", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 27, name: "ROUND", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 28, name: "LOOKUP", min_params: 2, max_params: 3 },
    BuiltInFunctionMetadata { index: 29, name: "INDEX", min_params: 2, max_params: 4 },
    BuiltInFunctionMetadata { index: 30, name: "REPT", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 31, name: "MID", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 32, name: "LEN", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 33, name: "VALUE", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 34, name: "TRUE", min_params: 0, max_params: 0 },
    BuiltInFunctionMetadata { index: 35, name: "FALSE", min_params: 0, max_params: 0 },
    BuiltInFunctionMetadata { index: 36, name: "AND", min_params: 1, max_params: 30 },
    BuiltInFunctionMetadata { index: 37, name: "OR", min_params: 1, max_params: 30 },
    BuiltInFunctionMetadata { index: 38, name: "NOT", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 39, name: "MOD", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 40, name: "DCOUNT", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 41, name: "DSUM", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 42, name: "DAVERAGE", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 43, name: "DMIN", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 44, name: "DMAX", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 45, name: "DSTDEV", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 46, name: "VAR", min_params: 1, max_params: 30 },
    BuiltInFunctionMetadata { index: 47, name: "DVAR", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 48, name: "TEXT", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 49, name: "LINEST", min_params: 1, max_params: 4 },
    BuiltInFunctionMetadata { index: 50, name: "TREND", min_params: 1, max_params: 4 },
    BuiltInFunctionMetadata { index: 51, name: "LOGEST", min_params: 1, max_params: 4 },
    BuiltInFunctionMetadata { index: 52, name: "GROWTH", min_params: 1, max_params: 4 },
    BuiltInFunctionMetadata { index: 53, name: "GOTO", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 55, name: "RETURN", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 56, name: "PV", min_params: 3, max_params: 5 },
    BuiltInFunctionMetadata { index: 57, name: "FV", min_params: 3, max_params: 5 },
    BuiltInFunctionMetadata { index: 58, name: "NPER", min_params: 3, max_params: 5 },
    BuiltInFunctionMetadata { index: 59, name: "PMT", min_params: 3, max_params: 5 },
    BuiltInFunctionMetadata { index: 60, name: "RATE", min_params: 3, max_params: 6 },
    BuiltInFunctionMetadata { index: 61, name: "MIRR", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 62, name: "IRR", min_params: 1, max_params: 2 },
    BuiltInFunctionMetadata { index: 63, name: "RAND", min_params: 0, max_params: 0 },
    BuiltInFunctionMetadata { index: 64, name: "MATCH", min_params: 2, max_params: 3 },
    BuiltInFunctionMetadata { index: 65, name: "DATE", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 66, name: "TIME", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 67, name: "DAY", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 68, name: "MONTH", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 69, name: "YEAR", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 70, name: "WEEKDAY", min_params: 1, max_params: 2 },
    BuiltInFunctionMetadata { index: 71, name: "HOUR", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 72, name: "MINUTE", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 73, name: "SECOND", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 74, name: "NOW", min_params: 0, max_params: 0 },
    BuiltInFunctionMetadata { index: 75, name: "AREAS", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 76, name: "ROWS", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 77, name: "COLUMNS", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 78, name: "OFFSET", min_params: 3, max_params: 5 },
    BuiltInFunctionMetadata { index: 79, name: "ABSREF", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 80, name: "RELREF", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 81, name: "ARGUMENT", min_params: 0, max_params: 3 },
    BuiltInFunctionMetadata { index: 82, name: "SEARCH", min_params: 2, max_params: 3 },
    BuiltInFunctionMetadata { index: 83, name: "TRANSPOSE", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 84, name: "ERROR", min_params: 0, max_params: 2 },
    BuiltInFunctionMetadata { index: 85, name: "STEP", min_params: 0, max_params: 0 },
    BuiltInFunctionMetadata { index: 86, name: "TYPE", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 97, name: "ATAN2", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 98, name: "ASIN", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 99, name: "ACOS", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 100, name: "CHOOSE", min_params: 2, max_params: 30 },
    BuiltInFunctionMetadata { index: 101, name: "HLOOKUP", min_params: 3, max_params: 4 },
    BuiltInFunctionMetadata { index: 102, name: "VLOOKUP", min_params: 3, max_params: 4 },
    BuiltInFunctionMetadata { index: 105, name: "ISREF", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 109, name: "LOG", min_params: 1, max_params: 2 },
    BuiltInFunctionMetadata { index: 110, name: "EXEC", min_params: 1, max_params: 4 },
    BuiltInFunctionMetadata { index: 111, name: "CHAR", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 112, name: "LOWER", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 113, name: "UPPER", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 114, name: "PROPER", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 115, name: "LEFT", min_params: 1, max_params: 2 },
    BuiltInFunctionMetadata { index: 116, name: "RIGHT", min_params: 1, max_params: 2 },
    BuiltInFunctionMetadata { index: 117, name: "EXACT", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 118, name: "TRIM", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 119, name: "REPLACE", min_params: 4, max_params: 4 },
    BuiltInFunctionMetadata { index: 120, name: "SUBSTITUTE", min_params: 3, max_params: 4 },
    BuiltInFunctionMetadata { index: 121, name: "CODE", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 124, name: "FIND", min_params: 2, max_params: 3 },
    BuiltInFunctionMetadata { index: 125, name: "CELL", min_params: 1, max_params: 2 },
    BuiltInFunctionMetadata { index: 126, name: "ISERR", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 127, name: "ISTEXT", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 128, name: "ISNUMBER", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 129, name: "ISBLANK", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 130, name: "T", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 131, name: "N", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 140, name: "DATEVALUE", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 141, name: "TIMEVALUE", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 142, name: "SLN", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 143, name: "SYD", min_params: 4, max_params: 4 },
    BuiltInFunctionMetadata { index: 144, name: "DDB", min_params: 4, max_params: 5 },
    BuiltInFunctionMetadata { index: 148, name: "INDIRECT", min_params: 1, max_params: 2 },
    BuiltInFunctionMetadata { index: 150, name: "CALL", min_params: 1, max_params: 3 },
    BuiltInFunctionMetadata { index: 162, name: "CLEAN", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 163, name: "MDETERM", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 164, name: "MINVERSE", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 165, name: "MMULT", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 167, name: "IPMT", min_params: 4, max_params: 6 },
    BuiltInFunctionMetadata { index: 168, name: "PPMT", min_params: 4, max_params: 6 },
    BuiltInFunctionMetadata { index: 169, name: "COUNTA", min_params: 0, max_params: 30 },
    BuiltInFunctionMetadata { index: 183, name: "PRODUCT", min_params: 0, max_params: 30 },
    BuiltInFunctionMetadata { index: 184, name: "FACT", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 185, name: "GET.CELL", min_params: 1, max_params: 2 },
    BuiltInFunctionMetadata { index: 186, name: "GET.WORKSPACE", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 187, name: "GET.WINDOW", min_params: 1, max_params: 2 },
    BuiltInFunctionMetadata { index: 188, name: "GET.DOCUMENT", min_params: 1, max_params: 2 },
    BuiltInFunctionMetadata { index: 189, name: "DPRODUCT", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 190, name: "ISNONTEXT", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 193, name: "STDEVP", min_params: 1, max_params: 30 },
    BuiltInFunctionMetadata { index: 194, name: "VARP", min_params: 1, max_params: 30 },
    BuiltInFunctionMetadata { index: 195, name: "DSTDEVP", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 196, name: "DVARP", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 197, name: "TRUNC", min_params: 1, max_params: 2 },
    BuiltInFunctionMetadata { index: 198, name: "ISLOGICAL", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 199, name: "DCOUNTA", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 204, name: "USDOLLAR", min_params: 1, max_params: 2 },
    BuiltInFunctionMetadata { index: 205, name: "FINDB", min_params: 2, max_params: 3 },
    BuiltInFunctionMetadata { index: 206, name: "SEARCHB", min_params: 2, max_params: 3 },
    BuiltInFunctionMetadata { index: 207, name: "REPLACEB", min_params: 4, max_params: 4 },
    BuiltInFunctionMetadata { index: 208, name: "LEFTB", min_params: 1, max_params: 2 },
    BuiltInFunctionMetadata { index: 209, name: "RIGHTB", min_params: 1, max_params: 2 },
    BuiltInFunctionMetadata { index: 210, name: "MIDB", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 211, name: "LENB", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 212, name: "ROUNDUP", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 213, name: "ROUNDDOWN", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 214, name: "ASC", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 215, name: "DBCS", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 216, name: "RANK", min_params: 2, max_params: 3 },
    BuiltInFunctionMetadata { index: 219, name: "ADDRESS", min_params: 2, max_params: 5 },
    BuiltInFunctionMetadata { index: 220, name: "DAYS360", min_params: 2, max_params: 3 },
    BuiltInFunctionMetadata { index: 221, name: "TODAY", min_params: 0, max_params: 0 },
    BuiltInFunctionMetadata { index: 222, name: "VDB", min_params: 5, max_params: 7 },
    BuiltInFunctionMetadata { index: 225, name: "END.IF", min_params: 0, max_params: 0 },
    BuiltInFunctionMetadata { index: 227, name: "MEDIAN", min_params: 1, max_params: 30 },
    BuiltInFunctionMetadata { index: 228, name: "SUMPRODUCT", min_params: 1, max_params: 30 },
    BuiltInFunctionMetadata { index: 229, name: "SINH", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 230, name: "COSH", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 231, name: "TANH", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 232, name: "ASINH", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 233, name: "ACOSH", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 234, name: "ATANH", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 235, name: "DGET", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 238, name: "LAST.ERROR", min_params: 0, max_params: 0 },
    BuiltInFunctionMetadata { index: 244, name: "INFO", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 247, name: "DB", min_params: 4, max_params: 5 },
    BuiltInFunctionMetadata { index: 252, name: "FREQUENCY", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 257, name: "EVALUATE", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 261, name: "ERROR.TYPE", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 262, name: "APP.TITLE", min_params: 0, max_params: 1 },
    BuiltInFunctionMetadata { index: 263, name: "WINDOW.TITLE", min_params: 0, max_params: 1 },
    BuiltInFunctionMetadata { index: 264, name: "SAVE.TOOLBAR", min_params: 0, max_params: 2 },
    BuiltInFunctionMetadata { index: 265, name: "ENABLE.TOOL", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 266, name: "PRESS.TOOL", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 267, name: "REGISTER.ID", min_params: 2, max_params: 3 },
    BuiltInFunctionMetadata { index: 268, name: "GET.WORKBOOK", min_params: 1, max_params: 2 },
    BuiltInFunctionMetadata { index: 269, name: "AVEDEV", min_params: 1, max_params: 30 },
    BuiltInFunctionMetadata { index: 270, name: "BETADIST", min_params: 3, max_params: 5 },
    BuiltInFunctionMetadata { index: 271, name: "GAMMALN", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 272, name: "BETAINV", min_params: 3, max_params: 5 },
    BuiltInFunctionMetadata { index: 273, name: "BINOMDIST", min_params: 4, max_params: 4 },
    BuiltInFunctionMetadata { index: 274, name: "CHIDIST", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 275, name: "CHIINV", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 276, name: "COMBIN", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 277, name: "CONFIDENCE", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 278, name: "CRITBINOM", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 279, name: "EVEN", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 280, name: "EXPONDIST", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 281, name: "FDIST", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 282, name: "FINV", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 283, name: "FISHER", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 284, name: "FISHERINV", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 285, name: "FLOOR", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 286, name: "GAMMADIST", min_params: 4, max_params: 4 },
    BuiltInFunctionMetadata { index: 287, name: "GAMMAINV", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 288, name: "CEILING", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 289, name: "HYPGEOMDIST", min_params: 4, max_params: 4 },
    BuiltInFunctionMetadata { index: 290, name: "LOGNORMDIST", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 291, name: "LOGINV", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 292, name: "NEGBINOMDIST", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 293, name: "NORMDIST", min_params: 4, max_params: 4 },
    BuiltInFunctionMetadata { index: 294, name: "NORMSDIST", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 295, name: "NORMINV", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 296, name: "NORMSINV", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 297, name: "STANDARDIZE", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 298, name: "ODD", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 299, name: "PERMUT", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 300, name: "POISSON", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 301, name: "TDIST", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 302, name: "WEIBULL", min_params: 4, max_params: 4 },
    BuiltInFunctionMetadata { index: 303, name: "SUMXMY2", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 304, name: "SUMX2MY2", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 305, name: "SUMX2PY2", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 306, name: "CHITEST", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 307, name: "CORREL", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 308, name: "COVAR", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 309, name: "FORECAST", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 310, name: "FTEST", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 311, name: "INTERCEPT", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 312, name: "PEARSON", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 313, name: "RSQ", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 314, name: "STEYX", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 315, name: "SLOPE", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 316, name: "TTEST", min_params: 4, max_params: 4 },
    BuiltInFunctionMetadata { index: 317, name: "PROB", min_params: 3, max_params: 4 },
    BuiltInFunctionMetadata { index: 318, name: "DEVSQ", min_params: 1, max_params: 30 },
    BuiltInFunctionMetadata { index: 319, name: "GEOMEAN", min_params: 1, max_params: 30 },
    BuiltInFunctionMetadata { index: 320, name: "HARMEAN", min_params: 1, max_params: 30 },
    BuiltInFunctionMetadata { index: 321, name: "SUMSQ", min_params: 0, max_params: 30 },
    BuiltInFunctionMetadata { index: 322, name: "KURT", min_params: 1, max_params: 30 },
    BuiltInFunctionMetadata { index: 323, name: "SKEW", min_params: 1, max_params: 30 },
    BuiltInFunctionMetadata { index: 324, name: "ZTEST", min_params: 2, max_params: 3 },
    BuiltInFunctionMetadata { index: 325, name: "LARGE", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 326, name: "SMALL", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 327, name: "QUARTILE", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 328, name: "PERCENTILE", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 329, name: "PERCENTRANK", min_params: 2, max_params: 3 },
    BuiltInFunctionMetadata { index: 330, name: "MODE", min_params: 1, max_params: 30 },
    BuiltInFunctionMetadata { index: 331, name: "TRIMMEAN", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 332, name: "TINV", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 336, name: "CONCATENATE", min_params: 0, max_params: 30 },
    BuiltInFunctionMetadata { index: 337, name: "POWER", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 342, name: "RADIANS", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 343, name: "DEGREES", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 344, name: "SUBTOTAL", min_params: 2, max_params: 30 },
    BuiltInFunctionMetadata { index: 345, name: "SUMIF", min_params: 2, max_params: 3 },
    BuiltInFunctionMetadata { index: 346, name: "COUNTIF", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 347, name: "COUNTBLANK", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 350, name: "ISPMT", min_params: 4, max_params: 4 },
    BuiltInFunctionMetadata { index: 351, name: "DATEDIF", min_params: 3, max_params: 3 },
    BuiltInFunctionMetadata { index: 352, name: "DATESTRING", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 353, name: "NUMBERSTRING", min_params: 2, max_params: 2 },
    BuiltInFunctionMetadata { index: 354, name: "ROMAN", min_params: 1, max_params: 2 },
    BuiltInFunctionMetadata { index: 358, name: "GETPIVOTDATA", min_params: 2, max_params: 30 },
    BuiltInFunctionMetadata { index: 359, name: "HYPERLINK", min_params: 1, max_params: 2 },
    BuiltInFunctionMetadata { index: 360, name: "PHONETIC", min_params: 1, max_params: 1 },
    BuiltInFunctionMetadata { index: 361, name: "AVERAGEA", min_params: 1, max_params: 30 },
    BuiltInFunctionMetadata { index: 362, name: "MAXA", min_params: 1, max_params: 30 },
    BuiltInFunctionMetadata { index: 363, name: "MINA", min_params: 1, max_params: 30 },
    BuiltInFunctionMetadata { index: 364, name: "STDEVPA", min_params: 1, max_params: 30 },
    BuiltInFunctionMetadata { index: 365, name: "VARPA", min_params: 1, max_params: 30 },
    BuiltInFunctionMetadata { index: 366, name: "STDEVA", min_params: 1, max_params: 30 },
    BuiltInFunctionMetadata { index: 367, name: "VARA", min_params: 1, max_params: 30 },
];

const COMMAND_EQUIVALENT_FUNCTIONS: &[(u16, &str)] = &[
    (0, "BEEP"),
    (1, "OPEN"),
    (2, "OPEN.LINKS"),
    (3, "CLOSE.ALL"),
    (4, "SAVE"),
    (5, "SAVE.AS"),
    (6, "FILE.DELETE"),
    (7, "PAGE.SETUP"),
    (8, "PRINT"),
    (9, "PRINTER.SETUP"),
    (10, "QUIT"),
    (11, "NEW.WINDOW"),
    (12, "ARRANGE.ALL"),
    (13, "WINDOW.SIZE"),
    (14, "WINDOW.MOVE"),
    (15, "FULL"),
    (16, "CLOSE"),
    (17, "RUN"),
    (22, "SET.PRINT.AREA"),
    (23, "SET.PRINT.TITLES"),
    (24, "SET.PAGE.BREAK"),
    (25, "REMOVE.PAGE.BREAK"),
    (26, "FONT"),
    (27, "DISPLAY"),
    (28, "PROTECT.DOCUMENT"),
    (29, "PRECISION"),
    (30, "A1.R1C1"),
    (31, "CALCULATE.NOW"),
    (32, "CALCULATION"),
    (34, "DATA.FIND"),
    (35, "EXTRACT"),
    (36, "DATA.DELETE"),
    (37, "SET.DATABASE"),
    (38, "SET.CRITERIA"),
    (39, "SORT"),
    (40, "DATA.SERIES"),
    (41, "TABLE"),
    (42, "FORMAT.NUMBER"),
    (43, "ALIGNMENT"),
    (44, "STYLE"),
    (45, "BORDER"),
    (46, "CELL.PROTECTION"),
    (47, "COLUMN.WIDTH"),
    (48, "UNDO"),
    (49, "CUT"),
    (50, "COPY"),
    (51, "PASTE"),
    (52, "CLEAR"),
    (53, "PASTE.SPECIAL"),
    (54, "EDIT.DELETE"),
    (55, "INSERT"),
    (56, "FILL.RIGHT"),
    (57, "FILL.DOWN"),
    (61, "DEFINE.NAME"),
    (62, "CREATE.NAMES"),
    (63, "FORMULA.GOTO"),
    (64, "FORMULA.FIND"),
    (65, "SELECT.LAST.CELL"),
    (66, "SHOW.ACTIVE.CELL"),
    (67, "GALLERY.AREA"),
    (68, "GALLERY.BAR"),
    (69, "GALLERY.COLUMN"),
    (70, "GALLERY.LINE"),
    (71, "GALLERY.PIE"),
    (72, "GALLERY.SCATTER"),
    (73, "COMBINATION"),
    (74, "PREFERRED"),
    (75, "ADD.OVERLAY"),
    (76, "GRIDLINES"),
    (77, "SET.PREFERRED"),
    (78, "AXES"),
    (79, "LEGEND"),
    (80, "ATTACH.TEXT"),
    (81, "ADD.ARROW"),
    (82, "SELECT.CHART"),
    (83, "SELECT.PLOT.AREA"),
    (84, "PATTERNS"),
    (85, "MAIN.CHART"),
    (86, "OVERLAY"),
    (87, "SCALE"),
    (88, "FORMAT.LEGEND"),
    (89, "FORMAT.TEXT"),
    (90, "EDIT.REPEAT"),
    (91, "PARSE"),
    (92, "JUSTIFY"),
    (93, "HIDE"),
    (94, "UNHIDE"),
    (95, "WORKSPACE"),
    (96, "FORMULA"),
    (97, "FORMULA.FILL"),
    (98, "FORMULA.ARRAY"),
    (99, "DATA.FIND.NEXT"),
    (100, "DATA.FIND.PREV"),
    (101, "FORMULA.FIND.NEXT"),
    (102, "FORMULA.FIND.PREV"),
    (103, "ACTIVATE"),
    (104, "ACTIVATE.NEXT"),
    (105, "ACTIVATE.PREV"),
    (106, "UNLOCKED.NEXT"),
    (107, "UNLOCKED.PREV"),
    (108, "COPY.PICTURE"),
    (109, "SELECT"),
    (110, "DELETE.NAME"),
    (111, "DELETE.FORMAT"),
    (112, "VLINE"),
    (113, "HLINE"),
    (114, "VPAGE"),
    (115, "HPAGE"),
    (116, "VSCROLL"),
    (117, "HSCROLL"),
    (118, "ALERT"),
    (119, "NEW"),
    (120, "CANCEL.COPY"),
    (121, "SHOW.CLIPBOARD"),
    (122, "MESSAGE"),
    (124, "PASTE.LINK"),
    (125, "APP.ACTIVATE"),
    (126, "DELETE.ARROW"),
    (127, "ROW.HEIGHT"),
    (128, "FORMAT.MOVE"),
    (129, "FORMAT.SIZE"),
    (130, "FORMULA.REPLACE"),
    (131, "SEND.KEYS"),
    (132, "SELECT.SPECIAL"),
    (133, "APPLY.NAMES"),
    (134, "REPLACE.FONT"),
    (135, "FREEZE.PANES"),
    (136, "SHOW.INFO"),
    (137, "SPLIT"),
    (138, "ON.WINDOW"),
    (139, "ON.DATA"),
    (140, "DISABLE.INPUT"),
    (142, "OUTLINE"),
    (143, "LIST.NAMES"),
    (144, "FILE.CLOSE"),
    (145, "SAVE.WORKBOOK"),
    (146, "DATA.FORM"),
    (147, "COPY.CHART"),
    (148, "ON.TIME"),
    (149, "WAIT"),
    (150, "FORMAT.FONT"),
    (151, "FILL.UP"),
    (152, "FILL.LEFT"),
    (153, "DELETE.OVERLAY"),
    (155, "SHORT.MENUS"),
    (159, "SET.UPDATE.STATUS"),
    (161, "COLOR.PALETTE"),
    (162, "DELETE.STYLE"),
    (163, "WINDOW.RESTORE"),
    (164, "WINDOW.MAXIMIZE"),
    (166, "CHANGE.LINK"),
    (167, "CALCULATE.DOCUMENT"),
    (168, "ON.KEY"),
    (169, "APP.RESTORE"),
    (170, "APP.MOVE"),
    (171, "APP.SIZE"),
    (172, "APP.MINIMIZE"),
    (173, "APP.MAXIMIZE"),
    (174, "BRING.TO.FRONT"),
    (175, "SEND.TO.BACK"),
    (185, "MAIN.CHART.TYPE"),
    (186, "OVERLAY.CHART.TYPE"),
    (187, "SELECT.END"),
    (188, "OPEN.MAIL"),
    (189, "SEND.MAIL"),
    (190, "STANDARD.FONT"),
    (191, "CONSOLIDATE"),
    (192, "SORT.SPECIAL"),
    (193, "GALLERY.3D.AREA"),
    (194, "GALLERY.3D.COLUMN"),
    (195, "GALLERY.3D.LINE"),
    (196, "GALLERY.3D.PIE"),
    (197, "VIEW.3D"),
    (198, "GOAL.SEEK"),
    (199, "WORKGROUP"),
    (200, "FILL.GROUP"),
    (201, "UPDATE.LINK"),
    (202, "PROMOTE"),
    (203, "DEMOTE"),
    (204, "SHOW.DETAIL"),
    (206, "UNGROUP"),
    (207, "OBJECT.PROPERTIES"),
    (208, "SAVE.NEW.OBJECT"),
    (209, "SHARE"),
    (210, "SHARE.NAME"),
    (211, "DUPLICATE"),
    (212, "APPLY.STYLE"),
    (213, "ASSIGN.TO.OBJECT"),
    (214, "OBJECT.PROTECTION"),
    (215, "HIDE.OBJECT"),
    (216, "SET.EXTRACT"),
    (217, "CREATE.PUBLISHER"),
    (218, "SUBSCRIBE.TO"),
    (219, "ATTRIBUTES"),
    (220, "SHOW.TOOLBAR"),
    (222, "PRINT.PREVIEW"),
    (223, "EDIT.COLOR"),
    (224, "SHOW.LEVELS"),
    (225, "FORMAT.MAIN"),
    (226, "FORMAT.OVERLAY"),
    (227, "ON.RECALC"),
    (228, "EDIT.SERIES"),
    (229, "DEFINE.STYLE"),
    (240, "LINE.PRINT"),
    (243, "ENTER.DATA"),
    (249, "GALLERY.RADAR"),
    (250, "MERGE.STYLES"),
    (251, "EDITION.OPTIONS"),
    (252, "PASTE.PICTURE"),
    (253, "PASTE.PICTURE.LINK"),
    (254, "SPELLING"),
    (256, "ZOOM"),
    (259, "INSERT.OBJECT"),
    (260, "WINDOW.MINIMIZE"),
    (265, "SOUND.NOTE"),
    (266, "SOUND.PLAY"),
    (267, "FORMAT.SHAPE"),
    (268, "EXTEND.POLYGON"),
    (269, "FORMAT.AUTO"),
    (272, "GALLERY.3D.BAR"),
    (273, "GALLERY.3D.SURFACE"),
    (274, "FILL.AUTO"),
    (276, "CUSTOMIZE.TOOLBAR"),
    (277, "ADD.TOOL"),
    (278, "EDIT.OBJECT"),
    (279, "ON.DOUBLECLICK"),
    (280, "ON.ENTRY"),
    (281, "WORKBOOK.ADD"),
    (282, "WORKBOOK.MOVE"),
    (283, "WORKBOOK.COPY"),
    (284, "WORKBOOK.OPTIONS"),
    (285, "SAVE.WORKSPACE"),
    (288, "CHART.WIZARD"),
    (289, "DELETE.TOOL"),
    (290, "MOVE.TOOL"),
    (291, "WORKBOOK.SELECT"),
    (292, "WORKBOOK.ACTIVATE"),
    (293, "ASSIGN.TO.TOOL"),
    (295, "COPY.TOOL"),
    (296, "RESET.TOOL"),
    (297, "CONSTRAIN.NUMERIC"),
    (298, "PASTE.TOOL"),
    (302, "WORKBOOK.NEW"),
    (305, "SCENARIO.CELLS"),
    (306, "SCENARIO.DELETE"),
    (307, "SCENARIO.ADD"),
    (308, "SCENARIO.EDIT"),
    (309, "SCENARIO.SHOW"),
    (310, "SCENARIO.SHOW.NEXT"),
    (311, "SCENARIO.SUMMARY"),
    (312, "PIVOT.TABLE.WIZARD"),
    (313, "PIVOT.FIELD.PROPERTIES"),
    (314, "PIVOT.FIELD"),
    (315, "PIVOT.ITEM"),
    (316, "PIVOT.ADD.FIELDS"),
    (318, "OPTIONS.CALCULATION"),
    (319, "OPTIONS.EDIT"),
    (320, "OPTIONS.VIEW"),
    (321, "ADDIN.MANAGER"),
    (322, "MENU.EDITOR"),
    (323, "ATTACH.TOOLBARS"),
    (324, "VBAActivate"),
    (325, "OPTIONS.CHART"),
    (328, "VBA.INSERT.FILE"),
    (330, "VBA.PROCEDURE.DEFINITION"),
    (336, "ROUTING.SLIP"),
    (338, "ROUTE.DOCUMENT"),
    (339, "MAIL.LOGON"),
    (342, "INSERT.PICTURE"),
    (343, "EDIT.TOOL"),
    (344, "GALLERY.DOUGHNUT"),
    (350, "CHART.TREND"),
    (352, "PIVOT.ITEM.PROPERTIES"),
    (354, "WORKBOOK.INSERT"),
    (355, "OPTIONS.TRANSITION"),
    (356, "OPTIONS.GENERAL"),
    (370, "FILTER.ADVANCED"),
    (373, "MAIL.ADD.MAILER"),
    (374, "MAIL.DELETE.MAILER"),
    (375, "MAIL.REPLY"),
    (376, "MAIL.REPLY.ALL"),
    (377, "MAIL.FORWARD"),
    (378, "MAIL.NEXT.LETTER"),
    (379, "DATA.LABEL"),
    (380, "INSERT.TITLE"),
    (381, "FONT.PROPERTIES"),
    (382, "MACRO.OPTIONS"),
    (383, "WORKBOOK.HIDE"),
    (384, "WORKBOOK.UNHIDE"),
    (385, "WORKBOOK.DELETE"),
    (386, "WORKBOOK.NAME"),
    (388, "GALLERY.CUSTOM"),
    (390, "ADD.CHART.AUTOFORMAT"),
    (391, "DELETE.CHART.AUTOFORMAT"),
    (392, "CHART.ADD.DATA"),
    (393, "AUTO.OUTLINE"),
    (394, "TAB.ORDER"),
    (395, "SHOW.DIALOG"),
    (396, "SELECT.ALL"),
    (397, "UNGROUP.SHEETS"),
    (398, "SUBTOTAL.CREATE"),
    (399, "SUBTOTAL.REMOVE"),
    (400, "RENAME.OBJECT"),
    (412, "WORKBOOK.SCROLL"),
    (413, "WORKBOOK.NEXT"),
    (414, "WORKBOOK.PREV"),
    (415, "WORKBOOK.TAB.SPLIT"),
    (416, "FULL.SCREEN"),
    (417, "WORKBOOK.PROTECT"),
    (420, "SCROLLBAR.PROPERTIES"),
    (421, "PIVOT.SHOW.PAGES"),
    (422, "TEXT.TO.COLUMNS"),
    (423, "FORMAT.CHARTTYPE"),
    (424, "LINK.FORMAT"),
    (425, "TRACER.DISPLAY"),
    (430, "TRACER.NAVIGATE"),
    (431, "TRACER.CLEAR"),
    (432, "TRACER.ERROR"),
    (433, "PIVOT.FIELD.GROUP"),
    (434, "PIVOT.FIELD.UNGROUP"),
    (435, "CHECKBOX.PROPERTIES"),
    (436, "LABEL.PROPERTIES"),
    (437, "LISTBOX.PROPERTIES"),
    (438, "EDITBOX.PROPERTIES"),
    (439, "PIVOT.REFRESH"),
    (440, "LINK.COMBO"),
    (441, "OPEN.TEXT"),
    (442, "HIDE.DIALOG"),
    (443, "SET.DIALOG.FOCUS"),
    (444, "ENABLE.OBJECT"),
    (445, "PUSHBUTTON.PROPERTIES"),
    (446, "SET.DIALOG.DEFAULT"),
    (447, "FILTER"),
    (448, "FILTER.SHOW.ALL"),
    (449, "CLEAR.OUTLINE"),
    (450, "FUNCTION.WIZARD"),
    (451, "ADD.LIST.ITEM"),
    (452, "SET.LIST.ITEM"),
    (453, "REMOVE.LIST.ITEM"),
    (454, "SELECT.LIST.ITEM"),
    (455, "SET.CONTROL.VALUE"),
    (456, "SAVE.COPY.AS"),
    (458, "OPTIONS.LISTS.ADD"),
    (459, "OPTIONS.LISTS.DELETE"),
    (460, "SERIES.AXES"),
    (461, "SERIES.X"),
    (462, "SERIES.Y"),
    (463, "ERRORBAR.X"),
    (464, "ERRORBAR.Y"),
    (465, "FORMAT.CHART"),
    (466, "SERIES.ORDER"),
    (467, "MAIL.LOGOFF"),
    (468, "CLEAR.ROUTING.SLIP"),
    (469, "APP.ACTIVATE.MICROSOFT"),
    (470, "MAIL.EDIT.MAILER"),
    (471, "ON.SHEET"),
    (472, "STANDARD.WIDTH"),
    (473, "SCENARIO.MERGE"),
    (474, "SUMMARY.INFO"),
    (475, "FIND.FILE"),
    (476, "ACTIVE.CELL.FONT"),
    (477, "ENABLE.TIPWIZARD"),
    (478, "VBA.MAKE.ADDIN"),
    (480, "INSERTDATATABLE"),
    (481, "WORKGROUP.OPTIONS"),
    (482, "MAIL.SEND.MAILER"),
    (485, "AUTOCORRECT"),
    (489, "POST.DOCUMENT"),
    (491, "PICKLIST"),
    (493, "VIEW.SHOW"),
    (494, "VIEW.DEFINE"),
    (495, "VIEW.DELETE"),
    (509, "SHEET.BACKGROUND"),
    (510, "INSERT.MAP.OBJECT"),
    (511, "OPTIONS.MENONO"),
    (517, "MSOCHECKS"),
    (518, "NORMAL"),
    (519, "LAYOUT"),
    (520, "RM.PRINT.AREA"),
    (521, "CLEAR.PRINT.AREA"),
    (522, "ADD.PRINT.AREA"),
    (523, "MOVE.BRK"),
    (545, "HIDECURR.NOTE"),
    (546, "HIDEALL.NOTES"),
    (547, "DELETE.NOTE"),
    (548, "TRAVERSE.NOTES"),
    (549, "ACTIVATE.NOTES"),
    (620, "PROTECT.REVISIONS"),
    (621, "UNPROTECT.REVISIONS"),
    (647, "OPTIONS.ME"),
    (653, "WEB.PUBLISH"),
    (667, "NEWWEBQUERY"),
    (673, "PIVOT.TABLE.CHART"),
    (753, "OPTIONS.SAVE"),
    (755, "OPTIONS.SPELL"),
    (808, "HIDEALL.INKANNOTS"),
];

fn function_metadata(index: u16) -> Option<BuiltInFunctionMetadata> {
    BUILT_IN_FUNCTIONS
        .binary_search_by_key(&index, |metadata| metadata.index)
        .ok()
        .map(|position| BUILT_IN_FUNCTIONS[position])
}

fn command_function_name(index: u16) -> Option<&'static str> {
    COMMAND_EQUIVALENT_FUNCTIONS
        .binary_search_by_key(&index, |(function_index, _)| *function_index)
        .ok()
        .map(|position| COMMAND_EQUIVALENT_FUNCTIONS[position].1)
}
