//! Source-bound inventory and forward-only redaction of external hyperlinks
//! in relationship-owned WordprocessingML stories.
//!
//! This capability is intentionally separate from the established main-only
//! [`crate::sanitize`] and [`crate::redact`] APIs.  It inventories the main,
//! header, footer, footnote, endnote, comments, and glossary stories reachable
//! through the OPC relationship graph.  Only ordinary external hyperlink
//! relationships represented by `w:hyperlink/@r:id` are supported.  Fields,
//! DDE/mail-merge/template references, embedded or macro content, signatures,
//! protection, MCE, and external references outside the selected story
//! hyperlink closure remain explicit refusals.

use crate::error::{Error, Result};
use crate::package::{StoryKind, StoryLimits};
use crate::sanitize::{self, RelationshipState, Wrapper};
use litchi_core::SourceVersion;
use litchi_opc::constants::{content_type as ct, relationship_type as rt};
use litchi_opc::{
    PackURI, PartData, SourceArtifactFingerprint, SourceBackedPackage, SourceLineage,
};
use quick_xml::XmlVersion;
use quick_xml::events::Event;
use quick_xml::name::{Namespace, NamespaceResolver, ResolveResult};
use quick_xml::reader::NsReader;
use std::collections::HashSet;
use std::sync::Arc;

const TRANSITIONAL_RELATIONSHIPS: &str =
    "http://schemas.openxmlformats.org/officeDocument/2006/relationships/";
const STRICT_RELATIONSHIPS: &str = "http://purl.oclc.org/ooxml/officeDocument/relationships/";
const TRANSITIONAL_WORD: &[u8] = b"http://schemas.openxmlformats.org/wordprocessingml/2006/main";
const STRICT_WORD: &[u8] = b"http://purl.oclc.org/ooxml/wordprocessingml/main";
const MCE_NAMESPACE: &[u8] = b"http://schemas.openxmlformats.org/markup-compatibility/2006";
const RELATIONSHIPS_NAMESPACE: &[u8] =
    b"http://schemas.openxmlformats.org/officeDocument/2006/relationships";
const STRICT_RELATIONSHIPS_NAMESPACE: &[u8] =
    b"http://purl.oclc.org/ooxml/officeDocument/relationships";
const TOPOLOGY_MAGIC: &[u8] = b"litchi.docx.conflict.topology.v1\0";

const HARD_MAX_SELECTED_RELATIONSHIPS: usize = 4096;
const HARD_MAX_SELECTOR_BYTES: usize = 16 * 1024 * 1024;
const HARD_MAX_CHANGED_STORIES: usize = 64;

/// Whether unsupported package references should reject a plan immediately or
/// be returned as explicit incomplete diagnostics.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Mode {
    /// Refuse when the package contains any reference class outside this
    /// narrow story-hyperlink closure.
    Strict,
    /// Build a diagnostic-bearing plan for inspection.  Security-sensitive
    /// and ownership-ambiguous classes still make `Plan::apply` fail closed;
    /// this mode never emits a successful incomplete publication.
    BestEffort,
}

/// A bounded story-hyperlink operation policy.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Limits {
    story: StoryLimits,
    xml: sanitize::Limits,
    max_selected_relationships: usize,
    max_selector_bytes: usize,
    max_changed_stories: usize,
}

impl Default for Limits {
    fn default() -> Self {
        Self {
            story: StoryLimits::default(),
            xml: sanitize::Limits::default(),
            max_selected_relationships: HARD_MAX_SELECTED_RELATIONSHIPS,
            max_selector_bytes: 16 * 1024 * 1024,
            max_changed_stories: HARD_MAX_CHANGED_STORIES,
        }
    }
}

impl Limits {
    /// Borrow the bounded OPC story ownership policy.
    #[must_use]
    pub const fn story_limits(self) -> StoryLimits {
        self.story
    }

    /// Borrow the XML scanner policy.
    #[must_use]
    pub const fn xml_limits(self) -> sanitize::Limits {
        self.xml
    }

    /// Maximum selected relationship records.
    #[must_use]
    pub const fn max_selected_relationships(self) -> usize {
        self.max_selected_relationships
    }

    /// Maximum aggregate selector bytes.
    #[must_use]
    pub const fn max_selector_bytes(self) -> usize {
        self.max_selector_bytes
    }

    /// Maximum number of story parts regenerated by one publication.
    #[must_use]
    pub const fn max_changed_stories(self) -> usize {
        self.max_changed_stories
    }

    /// Replace the story ownership policy after validating its hard bounds.
    pub fn with_story_limits(mut self, story: StoryLimits) -> Result<Self> {
        self.story = story.validate()?;
        Ok(self)
    }

    /// Replace the XML scanner policy.
    pub fn with_xml_limits(mut self, xml: sanitize::Limits) -> Result<Self> {
        self.xml = xml;
        Ok(self)
    }

    /// Set the maximum selected relationship records.
    pub fn with_max_selected_relationships(mut self, value: usize) -> Result<Self> {
        if value == 0 || value > HARD_MAX_SELECTED_RELATIONSHIPS {
            return Err(invalid(format!(
                "story hyperlink selected relationship limit must be in 1..={HARD_MAX_SELECTED_RELATIONSHIPS}, got {value}"
            )));
        }
        self.max_selected_relationships = value;
        Ok(self)
    }

    /// Set the maximum aggregate selector bytes.
    pub fn with_max_selector_bytes(mut self, value: usize) -> Result<Self> {
        if value == 0 || value > HARD_MAX_SELECTOR_BYTES {
            return Err(invalid(format!(
                "story hyperlink selector-byte limit must be in 1..={HARD_MAX_SELECTOR_BYTES}, got {value}"
            )));
        }
        self.max_selector_bytes = value;
        Ok(self)
    }

    /// Set the maximum number of regenerated story parts.
    pub fn with_max_changed_stories(mut self, value: usize) -> Result<Self> {
        if value == 0 || value > HARD_MAX_CHANGED_STORIES {
            return Err(invalid(format!(
                "story hyperlink changed-story limit must be in 1..={HARD_MAX_CHANGED_STORIES}, got {value}"
            )));
        }
        self.max_changed_stories = value;
        Ok(self)
    }

    fn validate(self) -> Result<Self> {
        self.story.validate()?;
        if self.max_selected_relationships == 0
            || self.max_selected_relationships > HARD_MAX_SELECTED_RELATIONSHIPS
            || self.max_selector_bytes == 0
            || self.max_selector_bytes > HARD_MAX_SELECTOR_BYTES
            || self.max_changed_stories == 0
            || self.max_changed_stories > HARD_MAX_CHANGED_STORIES
        {
            return Err(invalid("story hyperlink limits exceed their hard bounds"));
        }
        Ok(self)
    }
}

/// Reference classes which are deliberately outside the supported story
/// hyperlink closure.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum UnsupportedClass {
    /// A field, DDE, or instruction-bearing field element was found.
    FieldOrDde,
    /// Markup-compatibility syntax could alter the bytes being edited.
    MarkupCompatibility,
    /// Attached template relationship or element.
    AttachedTemplate,
    /// Mail-merge relationship or settings element.
    MailMerge,
    /// Document or write protection is present.
    Protection,
    /// Macro-enabled or VBA-bearing content is present.
    Macro,
    /// Embedded OLE/package/ActiveX content is present.
    EmbeddedContent,
    /// Digital-signature infrastructure is present.
    Signature,
    /// An external relationship is owned outside a story hyperlink.
    NonStoryExternal,
    /// Story ownership is missing, duplicated, or otherwise ambiguous.
    UnknownOwner,
    /// The source is encrypted or is not a plaintext OPC package.
    EncryptedSource,
}

/// Counted, content-free diagnostic for an incomplete inventory.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Diagnostic {
    class: UnsupportedClass,
    count: usize,
}

impl Diagnostic {
    /// Reference class represented by this diagnostic.
    #[must_use]
    pub const fn class(self) -> UnsupportedClass {
        self.class
    }

    /// Number of occurrences folded into this diagnostic.
    #[must_use]
    pub const fn count(self) -> usize {
        self.count
    }
}

/// One relationship-owned story in the inventory.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct StoryInfo {
    part_name: String,
    kind: StoryKind,
}

impl StoryInfo {
    /// Exact OPC Part URI.
    #[must_use]
    pub fn part_name(&self) -> &str {
        &self.part_name
    }

    /// Semantic Word story role.
    #[must_use]
    pub const fn kind(&self) -> StoryKind {
        self.kind
    }
}

/// One external hyperlink relationship owned by a Word story.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ExternalHyperlinkRelationship {
    part_name: String,
    kind: StoryKind,
    relationship_id: String,
    target_url: String,
    wrapper_count: usize,
}

impl ExternalHyperlinkRelationship {
    /// Exact owning story Part URI.
    #[must_use]
    pub fn part_name(&self) -> &str {
        &self.part_name
    }

    /// Owning story role.
    #[must_use]
    pub const fn kind(&self) -> StoryKind {
        self.kind
    }

    /// Relationship identifier referenced by `w:hyperlink/@r:id`.
    #[must_use]
    pub fn relationship_id(&self) -> &str {
        &self.relationship_id
    }

    /// Inert target URL. Litchi never fetches or executes it.
    #[must_use]
    pub fn target_url(&self) -> &str {
        &self.target_url
    }

    /// Number of wrappers referencing this relationship in the owning story.
    #[must_use]
    pub const fn wrapper_count(&self) -> usize {
        self.wrapper_count
    }
}

/// Complete deterministic story-hyperlink inventory.
#[derive(Clone, Debug)]
pub struct Inventory {
    stories: Arc<Vec<StoryInfo>>,
    relationships: Arc<Vec<ExternalHyperlinkRelationship>>,
    diagnostics: Arc<Vec<Diagnostic>>,
    /// Ranges into `relationships`, aligned with `stories`.
    ///
    /// The public inventory remains an immutable value, while redaction plans
    /// can select the relationships belonging to one story without scanning
    /// every story relationship for each story.  The ranges retain no source
    /// bytes and are bounded by the same relationship/story limits used while
    /// capturing the inventory.
    story_relationships: Arc<Vec<StoryRelationshipRange>>,
    /// Relationship indexes ordered by target URL.  The index stores only
    /// relationship positions, so target strings are not duplicated in the
    /// immutable snapshot.
    target_order: Arc<Vec<usize>>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
struct StoryRelationshipRange {
    start: usize,
    end: usize,
}

impl Inventory {
    /// Number of reachable stories.
    #[must_use]
    pub fn story_count(&self) -> usize {
        self.stories.len()
    }

    /// Number of external story hyperlink relationships.
    #[must_use]
    pub fn relationship_count(&self) -> usize {
        self.relationships.len()
    }

    /// Reachable stories, ordered main-first and then by Part URI.
    #[must_use]
    pub fn stories(&self) -> &[StoryInfo] {
        &self.stories
    }

    /// External hyperlink relationships ordered by Part URI and relationship ID.
    #[must_use]
    pub fn relationships(&self) -> &[ExternalHyperlinkRelationship] {
        &self.relationships
    }

    /// Explicit unsupported-reference diagnostics.
    #[must_use]
    pub fn diagnostics(&self) -> &[Diagnostic] {
        &self.diagnostics
    }

    /// True only when every scanned package reference belongs to this narrow
    /// supported closure.
    #[must_use]
    pub fn is_complete(&self) -> bool {
        self.diagnostics.is_empty()
    }
}

/// Predicted or applied effects of one story-hyperlink redaction.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct EffectReport {
    selected_targets: usize,
    scanned_stories: usize,
    removed_relationships: usize,
    unwrapped_hyperlinks: usize,
}

impl EffectReport {
    /// Number of distinct exact target URLs selected.
    #[must_use]
    pub const fn selected_targets(self) -> usize {
        self.selected_targets
    }

    /// Number of relationship-owned stories scanned.
    #[must_use]
    pub const fn scanned_stories(self) -> usize {
        self.scanned_stories
    }

    /// Number of external relationship records removed.
    #[must_use]
    pub const fn removed_relationships(self) -> usize {
        self.removed_relationships
    }

    /// Number of visible hyperlink wrappers unwrapped.
    #[must_use]
    pub const fn unwrapped_hyperlinks(self) -> usize {
        self.unwrapped_hyperlinks
    }

    /// True when publication copies the exact source artifact.
    #[must_use]
    pub const fn is_noop(self) -> bool {
        self.removed_relationships == 0 && self.unwrapped_hyperlinks == 0
    }
}

/// Explicit report returned by both best-effort plans and successful commits.
#[derive(Clone, Debug)]
pub struct Report {
    effect: EffectReport,
    diagnostics: Arc<Vec<Diagnostic>>,
    mode: Mode,
}

impl Report {
    /// Deterministic mutation effects.
    #[must_use]
    pub const fn effect(&self) -> EffectReport {
        self.effect
    }

    /// Unsupported classes observed during the package scan.
    #[must_use]
    pub fn diagnostics(&self) -> &[Diagnostic] {
        &self.diagnostics
    }

    /// Whether the report certifies the narrow story-hyperlink scope.
    #[must_use]
    pub fn is_complete(&self) -> bool {
        self.diagnostics.is_empty()
    }

    /// Policy used to produce this report.
    #[must_use]
    pub const fn mode(&self) -> Mode {
        self.mode
    }
}

#[derive(Clone, Debug)]
struct StorySource {
    part: PackURI,
    kind: StoryKind,
    root: &'static [u8],
    content_type: String,
    owner: StoryOwnerSource,
    xml: PartData,
    relationships: Arc<Vec<RelationshipState>>,
    wrappers: Arc<Vec<Wrapper>>,
}

#[derive(Clone, Debug)]
struct StoryOwnerSource {
    part: Option<PackURI>,
    relationship_id: String,
    relationship_type: String,
    target_ref: String,
}

/// Exact source-bound story inventory.
#[derive(Clone, Debug)]
pub struct Snapshot {
    source_version: SourceVersion,
    source_lineage: SourceLineage,
    source_fingerprint: SourceArtifactFingerprint,
    limits: Limits,
    stories: Arc<Vec<StorySource>>,
    inventory: Inventory,
}

impl Snapshot {
    /// Borrow the deterministic inventory.
    #[must_use]
    pub const fn inventory(&self) -> &Inventory {
        &self.inventory
    }

    /// Borrow the external story hyperlink records.
    #[must_use]
    pub fn relationships(&self) -> &[ExternalHyperlinkRelationship] {
        self.inventory.relationships()
    }

    /// Borrow unsupported-reference diagnostics without exposing raw package
    /// bytes or field instructions.
    #[must_use]
    pub fn diagnostics(&self) -> &[Diagnostic] {
        self.inventory.diagnostics()
    }

    /// Bounds captured by this exact-source snapshot.
    #[must_use]
    pub const fn limits(&self) -> Limits {
        self.limits
    }

    /// Plan strict removal of exact target URL values.
    pub fn plan_target_urls(&self, target_urls: &[&str]) -> Result<Plan> {
        self.plan_target_urls_with_mode(target_urls, Mode::Strict)
    }

    /// Plan removal under an explicit strict or best-effort policy.
    pub fn plan_target_urls_with_mode(&self, target_urls: &[&str], mode: Mode) -> Result<Plan> {
        if target_urls.is_empty() {
            return Ok(Plan {
                source: self.clone(),
                selections: Vec::new(),
                report: Report {
                    effect: EffectReport {
                        selected_targets: 0,
                        scanned_stories: self.stories.len(),
                        removed_relationships: 0,
                        unwrapped_hyperlinks: 0,
                    },
                    diagnostics: Arc::clone(&self.inventory.diagnostics),
                    mode,
                },
            });
        }
        if mode == Mode::Strict && !self.inventory.is_complete() {
            return Err(unsupported(
                "story_hyperlink_redaction",
                self.inventory.diagnostics(),
            ));
        }
        if target_urls.len() > self.limits.max_selected_relationships {
            return Err(limit(
                "target URL selectors",
                self.limits.max_selected_relationships,
                target_urls.len(),
            ));
        }
        let selector_bytes = target_urls.iter().try_fold(0usize, |total, target| {
            total.checked_add(target.len()).ok_or_else(|| {
                limit(
                    "target URL selector bytes",
                    self.limits.max_selector_bytes,
                    usize::MAX,
                )
            })
        })?;
        if selector_bytes > self.limits.max_selector_bytes {
            return Err(limit(
                "target URL selector bytes",
                self.limits.max_selector_bytes,
                selector_bytes,
            ));
        }
        let mut targets = Vec::new();
        targets
            .try_reserve_exact(target_urls.len())
            .map_err(|source| Error::Allocation {
                resource: "story hyperlink target selectors",
                source,
            })?;
        for target in target_urls {
            let mut owned = String::new();
            owned
                .try_reserve_exact(target.len())
                .map_err(|source| Error::Allocation {
                    resource: "story hyperlink target selector",
                    source,
                })?;
            owned.push_str(target);
            targets.push(owned);
        }
        targets.sort_unstable();
        targets.dedup();

        let mut selections = Vec::new();
        selections
            .try_reserve_exact(self.stories.len())
            .map_err(|source| Error::Allocation {
                resource: "story hyperlink selections",
                source,
            })?;
        let mut removed_relationships = 0usize;
        let mut unwrapped_hyperlinks = 0usize;
        for (story_index, story) in self.stories.iter().enumerate() {
            let mut ids = Vec::new();
            let relationship_range = self
                .inventory
                .story_relationships
                .get(story_index)
                .ok_or_else(|| invalid("story hyperlink relationship index is out of sync"))?;
            for relationship in
                &self.inventory.relationships[relationship_range.start..relationship_range.end]
            {
                if targets.binary_search(&relationship.target_url).is_ok() {
                    if removed_relationships >= self.limits.max_selected_relationships {
                        return Err(limit(
                            "selected story hyperlink relationships",
                            self.limits.max_selected_relationships,
                            removed_relationships.saturating_add(1),
                        ));
                    }
                    ids.try_reserve(1).map_err(|source| Error::Allocation {
                        resource: "story hyperlink relationship selection",
                        source,
                    })?;
                    ids.push(owned_str(
                        &relationship.relationship_id,
                        "story hyperlink relationship selection ID",
                    )?);
                    removed_relationships =
                        removed_relationships.checked_add(1).ok_or_else(|| {
                            invalid("story hyperlink selected relationship count overflows usize")
                        })?;
                    unwrapped_hyperlinks = unwrapped_hyperlinks
                        .checked_add(relationship.wrapper_count)
                        .ok_or_else(|| invalid("story hyperlink wrapper count overflows usize"))?;
                }
            }
            if !ids.is_empty() {
                ids.sort_unstable();
                ids.dedup();
                if selections.len() >= self.limits.max_changed_stories {
                    return Err(limit(
                        "changed story parts",
                        self.limits.max_changed_stories,
                        selections.len().saturating_add(1),
                    ));
                }
                selections.push(StorySelection {
                    part: clone_uri(&story.part)?,
                    ids,
                });
            }
        }
        for target in &targets {
            let present = self
                .inventory
                .target_order
                .binary_search_by(|index| {
                    self.inventory.relationships[*index]
                        .target_url
                        .as_str()
                        .cmp(target.as_str())
                })
                .is_ok();
            if !present {
                return Err(invalid(format!(
                    "story hyperlink target is not present: {target}"
                )));
            }
        }
        if removed_relationships > self.limits.max_selected_relationships {
            return Err(limit(
                "selected story hyperlink relationships",
                self.limits.max_selected_relationships,
                removed_relationships,
            ));
        }
        if selections.len() > self.limits.max_changed_stories {
            return Err(limit(
                "changed story parts",
                self.limits.max_changed_stories,
                selections.len(),
            ));
        }
        Ok(Plan {
            source: self.clone(),
            selections,
            report: Report {
                effect: EffectReport {
                    selected_targets: targets.len(),
                    scanned_stories: self.stories.len(),
                    removed_relationships,
                    unwrapped_hyperlinks,
                },
                diagnostics: Arc::clone(&self.inventory.diagnostics),
                mode,
            },
        })
    }

    fn exact_source_matches(&self, other: &Self) -> bool {
        self.source_lineage == other.source_lineage
            && self.source_version == other.source_version
            && self.source_fingerprint == other.source_fingerprint
            && self.stories.len() == other.stories.len()
            && self
                .stories
                .iter()
                .zip(other.stories.iter())
                .all(|(left, right)| {
                    left.part == right.part
                        && left.kind == right.kind
                        && left.xml.as_bytes() == right.xml.as_bytes()
                        && left.relationships.as_ref() == right.relationships.as_ref()
                })
    }
}

#[derive(Clone, Debug)]
struct StorySelection {
    part: PackURI,
    ids: Vec<String>,
}

/// Non-mutating source-bound redaction plan.
#[derive(Clone, Debug)]
pub struct Plan {
    source: Snapshot,
    selections: Vec<StorySelection>,
    report: Report,
}

impl Plan {
    /// Predicted mutation effects.
    #[must_use]
    pub const fn effect_report(&self) -> EffectReport {
        self.report.effect
    }

    /// Borrow the explicit completeness report.
    #[must_use]
    pub const fn report(&self) -> &Report {
        &self.report
    }

    /// Apply the plan and seal a forward-only commit.
    pub fn apply(self) -> Result<Commit> {
        if !self.selections.is_empty()
            && self.report.mode == Mode::BestEffort
            && !self.report.is_complete()
        {
            // The classes listed by `UnsupportedClass` are all security or
            // ownership-sensitive. Best effort reports them but never edits
            // around them; this is the fail-closed boundary for this tranche.
            return Err(unsupported(
                "story_hyperlink_redaction",
                &self.report.diagnostics,
            ));
        }
        let mut replacements = Vec::new();
        replacements
            .try_reserve_exact(self.selections.len())
            .map_err(|source| Error::Allocation {
                resource: "story hyperlink forward-only replacements",
                source,
            })?;
        for selection in &self.selections {
            let story = self
                .source
                .stories
                .iter()
                .find(|story| story.part == selection.part)
                .ok_or(Error::ExternalHyperlinkRedactionConflict)?;
            let mut wrappers = Vec::new();
            for wrapper in story.wrappers.iter().filter(|wrapper| {
                selection
                    .ids
                    .binary_search(&wrapper.relationship_id)
                    .is_ok()
            }) {
                wrappers
                    .try_reserve(1)
                    .map_err(|source| Error::Allocation {
                        resource: "story hyperlink wrapper ranges",
                        source,
                    })?;
                wrappers.push(clone_wrapper(wrapper)?);
            }
            let rewritten = if wrappers.is_empty() {
                copy_bytes(story.xml.as_bytes(), "story hyperlink unchanged story XML")?
            } else {
                let rewritten = sanitize::rewrite(story.xml.as_bytes(), &wrappers)?;
                if crate::paragraph::extract_word_text(story.xml.as_bytes())?
                    != crate::paragraph::extract_word_text(&rewritten)?
                {
                    return Err(Error::UnsafeEdit {
                        format: "DOCX",
                        operation: "story_hyperlink_redaction",
                        reason: "redaction changed visible story text",
                    });
                }
                rewritten
            };
            let mut retained = Vec::new();
            retained
                .try_reserve_exact(story.relationships.len())
                .map_err(|source| Error::Allocation {
                    resource: "story hyperlink retained relationships",
                    source,
                })?;
            for relationship in story.relationships.iter().filter(|relationship| {
                selection
                    .ids
                    .binary_search_by(|id| id.as_str().cmp(relationship.id()))
                    .is_err()
            }) {
                retained.push(clone_relationship(relationship)?);
            }
            let (remaining, _) = sanitize::scan_story_wrappers(
                &rewritten,
                &retained,
                story_scanner_limits(self.source.limits),
                story.root,
            )?;
            if remaining.iter().any(|wrapper| {
                selection
                    .ids
                    .binary_search(&wrapper.relationship_id)
                    .is_ok()
            }) {
                return Err(Error::UnsafeEdit {
                    format: "DOCX",
                    operation: "story_hyperlink_redaction",
                    reason: "selected story hyperlink wrapper remained after rewrite",
                });
            }
            let mut replacement = Vec::new();
            replacement
                .try_reserve_exact(rewritten.len())
                .map_err(|source| Error::Allocation {
                    resource: "story hyperlink replacement XML",
                    source,
                })?;
            replacement.extend_from_slice(&rewritten);
            let mut removed_ids = Vec::new();
            removed_ids
                .try_reserve_exact(selection.ids.len())
                .map_err(|source| Error::Allocation {
                    resource: "story hyperlink replacement relationship IDs",
                    source,
                })?;
            for id in &selection.ids {
                removed_ids.push(owned_str(
                    id,
                    "story hyperlink replacement relationship ID",
                )?);
            }
            replacements.push(StoryReplacement {
                part: clone_uri(&story.part)?,
                xml: Arc::new(replacement),
                removed_ids,
            });
        }
        Ok(Commit {
            patch: ForwardOnlyPatch {
                source: self.source,
                replacements: Arc::new(replacements),
                report: self.report.clone(),
            },
        })
    }
}

/// Successful forward-only story redaction.
#[derive(Clone, Debug)]
pub struct Commit {
    patch: ForwardOnlyPatch,
}

impl Commit {
    /// Deterministic effects applied by this commit.
    #[must_use]
    pub const fn effect_report(&self) -> EffectReport {
        self.patch.report.effect
    }

    /// Borrow the explicit report, including incomplete diagnostics.
    #[must_use]
    pub const fn report(&self) -> &Report {
        &self.patch.report
    }

    /// Borrow the sealed forward-only patch for the source-backed publisher.
    #[must_use]
    pub(crate) const fn patch(&self) -> &ForwardOnlyPatch {
        &self.patch
    }
}

/// Private source/artifact-bound forward-only patch.
#[derive(Clone, Debug)]
pub(crate) struct ForwardOnlyPatch {
    source: Snapshot,
    replacements: Arc<Vec<StoryReplacement>>,
    report: Report,
}

impl ForwardOnlyPatch {
    pub(crate) fn validate_source(&self, current: &Snapshot) -> Result<()> {
        if self.source.exact_source_matches(current) {
            Ok(())
        } else {
            Err(Error::ExternalHyperlinkRedactionConflict)
        }
    }

    pub(crate) const fn limits(&self) -> Limits {
        self.source.limits
    }
}

#[derive(Clone, Debug)]
struct StoryReplacement {
    part: PackURI,
    xml: Arc<Vec<u8>>,
    removed_ids: Vec<String>,
}

pub(crate) fn publication_parts(commit: &Commit) -> Result<Vec<(PackURI, Vec<u8>, Vec<String>)>> {
    let mut parts = Vec::new();
    parts
        .try_reserve_exact(commit.patch.replacements.len())
        .map_err(|source| Error::Allocation {
            resource: "story hyperlink publication parts",
            source,
        })?;
    for replacement in commit.patch.replacements.iter() {
        let mut xml = Vec::new();
        xml.try_reserve_exact(replacement.xml.len())
            .map_err(|source| Error::Allocation {
                resource: "story hyperlink publication XML",
                source,
            })?;
        xml.extend_from_slice(replacement.xml.as_ref());
        let mut ids = Vec::new();
        ids.try_reserve_exact(replacement.removed_ids.len())
            .map_err(|source| Error::Allocation {
                resource: "story hyperlink publication relationship IDs",
                source,
            })?;
        for id in &replacement.removed_ids {
            ids.push(owned_str(
                id,
                "story hyperlink publication relationship ID",
            )?);
        }
        parts.push((clone_uri(&replacement.part)?, xml, ids));
    }
    Ok(parts)
}

/// Capture the exact source closure behind the public source-backed methods.
pub(crate) fn capture_source(package: &SourceBackedPackage, limits: Limits) -> Result<Snapshot> {
    let limits = limits.validate()?;
    package.check_execution()?;
    let source_version = package.source_version()?;
    let mut diagnostics = Vec::new();
    diagnostics
        .try_reserve_exact(16)
        .map_err(|source| Error::Allocation {
            resource: "story hyperlink diagnostics",
            source,
        })?;
    let mut stories = capture_stories(package, limits, &mut diagnostics)?;
    stories.sort_unstable_by(|left, right| left.part.as_str().cmp(right.part.as_str()));
    if let Some(main) = stories
        .iter()
        .position(|story| story.kind == StoryKind::Main)
    {
        stories.swap(0, main);
    }
    validate_topology_size(&stories, limits.story.max_topology_bytes)?;
    let mut story_infos = Vec::new();
    story_infos
        .try_reserve_exact(stories.len())
        .map_err(|source| Error::Allocation {
            resource: "story hyperlink story inventory",
            source,
        })?;
    let mut relationship_inventory = Vec::new();
    for story in &stories {
        story_infos.push(StoryInfo {
            part_name: owned_uri(&story.part, "story hyperlink story name")?,
            kind: story.kind,
        });
        for relationship in story.relationships.iter().filter(|relationship| {
            relationship.is_external()
                && matches!(
                    relationship.relationship_type(),
                    rt::HYPERLINK | rt::STRICT_HYPERLINK
                )
        }) {
            if relationship_inventory.len() >= limits.xml.max_external_hyperlinks() {
                return Err(limit(
                    "external story hyperlink relationships",
                    limits.xml.max_external_hyperlinks(),
                    relationship_inventory.len().saturating_add(1),
                ));
            }
            relationship_inventory
                .try_reserve(1)
                .map_err(|source| Error::Allocation {
                    resource: "story hyperlink relationship inventory",
                    source,
                })?;
            relationship_inventory.push(ExternalHyperlinkRelationship {
                part_name: owned_uri(&story.part, "story hyperlink owner name")?,
                kind: story.kind,
                relationship_id: owned_str(relationship.id(), "story hyperlink relationship ID")?,
                target_url: owned_str(relationship.target(), "story hyperlink target URL")?,
                wrapper_count: story
                    .wrappers
                    .iter()
                    .filter(|wrapper| wrapper.relationship_id == relationship.id())
                    .count(),
            });
        }
    }
    relationship_inventory.sort_unstable_by(|left, right| {
        left.part_name
            .cmp(&right.part_name)
            .then_with(|| left.relationship_id.cmp(&right.relationship_id))
    });
    let diagnostics = coalesce_diagnostics(diagnostics)?;
    let (story_relationships, target_order) =
        build_relationship_indexes(&story_infos, &relationship_inventory)?;
    let source_fingerprint = package.source_artifact().fingerprint()?;
    let observed = package.source_version()?;
    if observed != source_version {
        return Err(litchi_opc::OpcError::SourceChanged {
            expected: source_version,
            actual: observed,
        }
        .into());
    }
    Ok(Snapshot {
        source_version,
        source_lineage: package.source_lineage(),
        source_fingerprint,
        limits,
        stories: Arc::new(stories),
        inventory: Inventory {
            stories: Arc::new(story_infos),
            relationships: Arc::new(relationship_inventory),
            diagnostics: Arc::new(diagnostics),
            story_relationships,
            target_order,
        },
    })
}

/// Build the immutable lookup structures used by repeated story redaction
/// planning.  Relationship records are already in canonical `(part, id)`
/// order, so each story's contiguous range can be found with two binary
/// searches.  Target validation uses a second order of integer positions and
/// therefore does not clone the target strings.
fn build_relationship_indexes(
    stories: &[StoryInfo],
    relationships: &[ExternalHyperlinkRelationship],
) -> Result<(Arc<Vec<StoryRelationshipRange>>, Arc<Vec<usize>>)> {
    let mut story_relationships = Vec::new();
    story_relationships
        .try_reserve_exact(stories.len())
        .map_err(|source| Error::Allocation {
            resource: "story hyperlink relationship story index",
            source,
        })?;
    for story in stories {
        let start = relationships.partition_point(|relationship| {
            relationship.part_name.as_str() < story.part_name.as_str()
        });
        let end = relationships.partition_point(|relationship| {
            relationship.part_name.as_str() <= story.part_name.as_str()
        });
        story_relationships.push(StoryRelationshipRange { start, end });
    }

    let mut target_order = Vec::new();
    target_order
        .try_reserve_exact(relationships.len())
        .map_err(|source| Error::Allocation {
            resource: "story hyperlink target index",
            source,
        })?;
    target_order.extend(0..relationships.len());
    target_order.sort_unstable_by(|left, right| {
        relationships[*left]
            .target_url
            .cmp(&relationships[*right].target_url)
            .then_with(|| left.cmp(right))
    });

    Ok((Arc::new(story_relationships), Arc::new(target_order)))
}

fn capture_stories(
    package: &SourceBackedPackage,
    limits: Limits,
    diagnostics: &mut Vec<Diagnostic>,
) -> Result<Vec<StorySource>> {
    let main = package.main_document_part()?;
    validate_main_content_type(main.content_type())?;
    let main_rel = package
        .rels()
        .iter()
        .find(|relationship| {
            matches!(
                relationship.reltype(),
                rt::OFFICE_DOCUMENT | rt::STRICT_OFFICE_DOCUMENT
            )
        })
        .ok_or_else(|| invalid("main-document relationship is missing"))?;
    let dialect = dialect_for_relationship(main_rel.reltype())
        .ok_or_else(|| invalid("unsupported main-document relationship dialect"))?;

    let package_part_count = package.iter_parts().count();
    if package_part_count > limits.story.max_package_parts {
        return Err(invalid(format!(
            "DOCX package part count exceeds {}",
            limits.story.max_package_parts
        )));
    }
    validate_package_relationship_dialects(package, dialect)?;

    let main_relationship_count = main.rels().len();
    if main_relationship_count > limits.story.max_relationships_per_owner {
        return Err(invalid("story relationship limit exceeded"));
    }
    if main_relationship_count > limits.story.max_total_relationships {
        return Err(invalid("story hyperlink relationship limit exceeded"));
    }

    let mut seen = HashSet::new();
    seen.try_reserve(limits.story.max_stories)
        .map_err(|source| Error::Allocation {
            resource: "story hyperlink ownership set",
            source,
        })?;
    seen.insert(clone_uri(main.partname())?);
    let mut stories = Vec::new();
    stories
        .try_reserve(limits.story.max_stories)
        .map_err(|source| Error::Allocation {
            resource: "story hyperlink source stories",
            source,
        })?;
    let main_owner = StoryOwnerSource {
        part: None,
        relationship_id: owned_str(main_rel.r_id(), "story hyperlink main relationship ID")?,
        relationship_type: owned_str(main_rel.reltype(), "story hyperlink main relationship type")?,
        target_ref: owned_str(
            main_rel.target_ref(),
            "story hyperlink main relationship target",
        )?,
    };
    stories.push(load_story(
        &main,
        StoryKind::Main,
        dialect,
        main_owner,
        limits,
        diagnostics,
    )?);
    let mut total_story_bytes = stories[0].xml.as_bytes().len();
    if total_story_bytes > limits.story.max_total_story_bytes {
        return Err(invalid(
            "story hyperlink aggregate story byte limit exceeded",
        ));
    }
    let mut singleton = [false; 4];
    let mut total_relationships = main_relationship_count;
    let mut index = 0usize;
    while index < stories.len() {
        package.check_execution()?;
        let owner = package.part(&stories[index].part)?;
        if owner.rels().len() > limits.story.max_relationships_per_owner {
            return Err(invalid("story relationship limit exceeded"));
        }
        for relationship in owner.rels().iter() {
            ensure_relationship_dialect(relationship.reltype(), dialect)?;
            let Some((edge_dialect, kind)) = story_kind_for_relationship(relationship.reltype())
            else {
                continue;
            };
            if edge_dialect != dialect {
                return Err(invalid(
                    "story relationship dialect changes within a package",
                ));
            }
            if relationship.is_external() {
                add_diagnostic(diagnostics, UnsupportedClass::UnknownOwner, 1)?;
                continue;
            }
            if stories[index].kind != StoryKind::Main {
                add_diagnostic(diagnostics, UnsupportedClass::UnknownOwner, 1)?;
                continue;
            }
            if stories.len() >= limits.story.max_stories {
                return Err(invalid("story hyperlink story limit exceeded"));
            }
            if let Some(singleton_index) = singleton_index(kind) {
                if singleton[singleton_index] {
                    add_diagnostic(diagnostics, UnsupportedClass::UnknownOwner, 1)?;
                    continue;
                }
                singleton[singleton_index] = true;
            }
            let target = relationship.target_partname()?;
            let target_part = package.part(&target)?;
            if target_part.content_type() != content_type_for_kind(kind) {
                add_diagnostic(diagnostics, UnsupportedClass::UnknownOwner, 1)?;
                continue;
            }
            if !seen.insert(clone_uri(target_part.partname())?) {
                add_diagnostic(diagnostics, UnsupportedClass::UnknownOwner, 1)?;
                continue;
            }
            let target_relationship_count = target_part.rels().len();
            if target_relationship_count > limits.story.max_relationships_per_owner {
                return Err(invalid("story relationship limit exceeded"));
            }
            total_relationships = total_relationships
                .checked_add(target_relationship_count)
                .ok_or_else(|| invalid("story hyperlink relationship count overflows usize"))?;
            if total_relationships > limits.story.max_total_relationships {
                return Err(invalid("story hyperlink relationship limit exceeded"));
            }
            let owner = StoryOwnerSource {
                part: Some(clone_uri(&stories[index].part)?),
                relationship_id: owned_str(
                    relationship.r_id(),
                    "story hyperlink owner relationship ID",
                )?,
                relationship_type: owned_str(
                    relationship.reltype(),
                    "story hyperlink owner relationship type",
                )?,
                target_ref: owned_str(
                    relationship.target_ref(),
                    "story hyperlink owner relationship target",
                )?,
            };
            let loaded = load_story(&target_part, kind, dialect, owner, limits, diagnostics)?;
            total_story_bytes = total_story_bytes
                .checked_add(loaded.xml.as_bytes().len())
                .ok_or_else(|| invalid("story hyperlink aggregate story byte overflow"))?;
            if total_story_bytes > limits.story.max_total_story_bytes {
                return Err(invalid(
                    "story hyperlink aggregate story byte limit exceeded",
                ));
            }
            stories.push(loaded);
        }
        index = index
            .checked_add(1)
            .ok_or_else(|| invalid("story hyperlink story index overflows usize"))?;
    }

    for part in package.iter_parts() {
        if kind_from_content_type(part.content_type()).is_some() && !seen.contains(part.partname())
        {
            add_diagnostic(diagnostics, UnsupportedClass::UnknownOwner, 1)?;
        }
        inspect_part_security(&part, diagnostics)?;
        for relationship in part.rels().iter() {
            let Some((_edge_dialect, _kind)) = story_kind_for_relationship(relationship.reltype())
            else {
                continue;
            };
            if !is_expected_story_owner(&part, relationship, &stories) {
                add_diagnostic(diagnostics, UnsupportedClass::UnknownOwner, 1)?;
            }
        }
    }
    for member in package.non_part_members() {
        inspect_non_part_security(member.name(), diagnostics)?;
    }
    for relationship in package.rels().iter() {
        ensure_relationship_dialect(relationship.reltype(), dialect)?;
        if relationship.is_external() {
            add_diagnostic(diagnostics, UnsupportedClass::NonStoryExternal, 1)?;
        }
        if story_kind_for_relationship(relationship.reltype()).is_some() {
            add_diagnostic(diagnostics, UnsupportedClass::UnknownOwner, 1)?;
        }
        if is_signature_relationship(relationship.reltype()) {
            add_diagnostic(diagnostics, UnsupportedClass::Signature, 1)?;
        }
    }
    inspect_settings(package, &main, diagnostics)?;
    Ok(stories)
}

fn validate_package_relationship_dialects(
    package: &SourceBackedPackage,
    dialect: Dialect,
) -> Result<()> {
    for relationship in package.rels().iter() {
        ensure_relationship_dialect(relationship.reltype(), dialect)?;
    }
    for part in package.iter_parts() {
        for relationship in part.rels().iter() {
            ensure_relationship_dialect(relationship.reltype(), dialect)?;
        }
    }
    Ok(())
}

fn ensure_relationship_dialect(value: &str, expected: Dialect) -> Result<()> {
    if dialect_for_relationship(value).is_some_and(|actual| actual != expected) {
        return Err(invalid(
            "DOCX package mixes Strict and Transitional relationship types",
        ));
    }
    Ok(())
}

fn is_expected_story_owner(
    part: &litchi_opc::PartView<'_>,
    relationship: &litchi_opc::Relationship,
    stories: &[StorySource],
) -> bool {
    let Ok(target) = relationship.target_partname() else {
        return false;
    };
    stories.iter().any(|story| {
        story.part == target
            && story
                .owner
                .part
                .as_ref()
                .is_some_and(|owner| owner.as_str() == part.partname().as_str())
            && story.owner.relationship_id == relationship.r_id()
            && story.owner.relationship_type == relationship.reltype()
            && story.owner.target_ref == relationship.target_ref()
    })
}

fn load_story(
    part: &litchi_opc::PartView<'_>,
    kind: StoryKind,
    dialect: Dialect,
    owner: StoryOwnerSource,
    limits: Limits,
    diagnostics: &mut Vec<Diagnostic>,
) -> Result<StorySource> {
    // Keep the bounded PartData handle intact.  In particular, managed
    // source-backed packages reject `into_arc()` so the execution-budget
    // reservation cannot escape with an untracked allocation.
    let bytes = part.data()?;
    if bytes.as_bytes().len() > limits.story.max_story_bytes {
        return Err(invalid("story hyperlink story byte limit exceeded"));
    }
    let mut relationships = Vec::new();
    relationships
        .try_reserve_exact(part.rels().len())
        .map_err(|source| Error::Allocation {
            resource: "story hyperlink relationship closure",
            source,
        })?;
    for relationship in part.rels().iter() {
        relationships.push(RelationshipState::new(
            owned_str(relationship.r_id(), "story hyperlink relationship ID")?,
            owned_str(relationship.reltype(), "story hyperlink relationship type")?,
            owned_str(
                relationship.target_ref(),
                "story hyperlink relationship target",
            )?,
            relationship.is_external(),
        ));
        if relationship.is_external()
            && !matches!(relationship.reltype(), rt::HYPERLINK | rt::STRICT_HYPERLINK)
        {
            add_diagnostic(diagnostics, UnsupportedClass::NonStoryExternal, 1)?;
        }
    }
    relationships.sort_unstable_by(|left, right| left.id().cmp(right.id()));
    let scanner_limits = story_scanner_limits(limits);
    validate_story_dialect(
        bytes.as_bytes(),
        kind,
        dialect,
        limits.story.max_xml_prolog_events,
    )?;
    let (wrappers, _) = sanitize::scan_story_wrappers(
        bytes.as_bytes(),
        &relationships,
        scanner_limits,
        story_root(kind),
    )?;
    inspect_story_xml(bytes.as_bytes(), &relationships, diagnostics)?;
    Ok(StorySource {
        part: clone_uri(part.partname())?,
        kind,
        root: story_root(kind),
        content_type: owned_str(part.content_type(), "story hyperlink story content type")?,
        owner,
        xml: bytes,
        relationships: Arc::new(relationships),
        wrappers: Arc::new(wrappers),
    })
}

fn inspect_part_security(
    part: &litchi_opc::PartView<'_>,
    diagnostics: &mut Vec<Diagnostic>,
) -> Result<()> {
    let content_type = part.content_type();
    if contains_ascii_case_insensitive(content_type, "macroenabled")
        || contains_ascii_case_insensitive(content_type, "vba")
        || contains_ascii_case_insensitive(part.partname().as_str(), "vba")
    {
        add_diagnostic(diagnostics, UnsupportedClass::Macro, 1)?;
    }
    let name = part.partname().as_str();
    if contains_ascii_case_insensitive(name, "/embeddings/")
        || contains_ascii_case_insensitive(name, "/activex/")
        || contains_ascii_case_insensitive(content_type, "oleobject")
        || contains_ascii_case_insensitive(content_type, "activex")
        || contains_ascii_case_insensitive(content_type, "officedocument.package")
    {
        add_diagnostic(diagnostics, UnsupportedClass::EmbeddedContent, 1)?;
    }
    if part.rels().iter().any(|relationship| {
        contains_ascii_case_insensitive(relationship.reltype(), "ole")
            || contains_ascii_case_insensitive(relationship.reltype(), "activex")
            || contains_ascii_case_insensitive(relationship.reltype(), "package")
    }) {
        add_diagnostic(diagnostics, UnsupportedClass::EmbeddedContent, 1)?;
    }
    if contains_ascii_case_insensitive(name, "/_xmlsignatures/")
        || contains_ascii_case_insensitive(content_type, "signature")
        || part.rels().iter().any(|relationship| {
            contains_ascii_case_insensitive(relationship.reltype(), "signature")
        })
    {
        add_diagnostic(diagnostics, UnsupportedClass::Signature, 1)?;
    }
    if part
        .rels()
        .iter()
        .any(|relationship| relationship.is_external())
        && kind_from_content_type(part.content_type()).is_none()
    {
        add_diagnostic(diagnostics, UnsupportedClass::NonStoryExternal, 1)?;
    }
    Ok(())
}

fn inspect_non_part_security(name: &str, diagnostics: &mut Vec<Diagnostic>) -> Result<()> {
    if contains_ascii_case_insensitive(name, "vbaproject")
        || contains_ascii_case_insensitive(name, "/vba/")
        || starts_with_ascii_case_insensitive(name, "vba/")
    {
        add_diagnostic(diagnostics, UnsupportedClass::Macro, 1)?;
    }
    if contains_ascii_case_insensitive(name, "/embeddings/")
        || contains_ascii_case_insensitive(name, "/activex/")
        || starts_with_ascii_case_insensitive(name, "embeddings/")
        || starts_with_ascii_case_insensitive(name, "activex/")
    {
        add_diagnostic(diagnostics, UnsupportedClass::EmbeddedContent, 1)?;
    }
    if contains_ascii_case_insensitive(name, "/_xmlsignatures/")
        || starts_with_ascii_case_insensitive(name, "_xmlsignatures/")
        || contains_ascii_case_insensitive(name, "signature")
    {
        add_diagnostic(diagnostics, UnsupportedClass::Signature, 1)?;
    }
    Ok(())
}

fn inspect_settings(
    package: &SourceBackedPackage,
    main: &litchi_opc::PartView<'_>,
    diagnostics: &mut Vec<Diagnostic>,
) -> Result<()> {
    let mut settings = None;
    for relationship in main.rels().iter() {
        if relationship.reltype().ends_with("/settings") && !relationship.is_external() {
            if settings.is_some() {
                add_diagnostic(diagnostics, UnsupportedClass::UnknownOwner, 1)?;
                continue;
            }
            settings = Some(package.part(&relationship.target_partname()?)?);
        }
    }
    let Some(settings) = settings else {
        return Ok(());
    };
    let data = settings.data()?;
    inspect_settings_xml(data.as_bytes(), diagnostics)?;
    if settings
        .rels()
        .iter()
        .any(|relationship| relationship.reltype().contains("attachedTemplate"))
    {
        add_diagnostic(diagnostics, UnsupportedClass::AttachedTemplate, 1)?;
    }
    if settings.rels().iter().any(|relationship| {
        relationship.reltype().contains("mailMerge") || relationship.reltype().contains("recipient")
    }) {
        add_diagnostic(diagnostics, UnsupportedClass::MailMerge, 1)?;
    }
    Ok(())
}

fn inspect_settings_xml(xml: &[u8], diagnostics: &mut Vec<Diagnostic>) -> Result<()> {
    if xml
        .windows(MCE_NAMESPACE.len())
        .any(|window| window == MCE_NAMESPACE)
    {
        add_diagnostic(diagnostics, UnsupportedClass::MarkupCompatibility, 1)?;
    }
    let mut reader = NsReader::from_reader(xml);
    loop {
        let event = reader
            .read_resolved_event()
            .map_err(|error| Error::Xml(error.to_string()))?;
        match event {
            (namespace, Event::Start(element)) | (namespace, Event::Empty(element)) => {
                if is_mce_namespace(&namespace) {
                    add_diagnostic(diagnostics, UnsupportedClass::MarkupCompatibility, 1)?;
                }
                if is_word_namespace(&namespace) {
                    match element.local_name().as_ref() {
                        b"documentProtection" | b"writeProtection" => {
                            add_diagnostic(diagnostics, UnsupportedClass::Protection, 1)?;
                        },
                        b"attachedTemplate" => {
                            add_diagnostic(diagnostics, UnsupportedClass::AttachedTemplate, 1)?;
                        },
                        b"mailMerge" => {
                            add_diagnostic(diagnostics, UnsupportedClass::MailMerge, 1)?;
                        },
                        _ => {},
                    }
                }
            },
            (_, Event::DocType(_) | Event::PI(_)) => {
                add_diagnostic(diagnostics, UnsupportedClass::MarkupCompatibility, 1)?;
            },
            (_, Event::Eof) => break,
            _ => {},
        }
    }
    Ok(())
}

fn inspect_story_xml(
    xml: &[u8],
    relationships: &[RelationshipState],
    diagnostics: &mut Vec<Diagnostic>,
) -> Result<()> {
    if xml
        .windows(MCE_NAMESPACE.len())
        .any(|window| window == MCE_NAMESPACE)
    {
        add_diagnostic(diagnostics, UnsupportedClass::MarkupCompatibility, 1)?;
    }
    let mut reader = NsReader::from_reader(xml);
    reader.config_mut().check_end_names = true;
    let mut hyperlink_depth = None;
    let mut depth = 0usize;
    loop {
        let decoder = reader.decoder();
        let event = reader
            .read_event()
            .map_err(|error| Error::Xml(error.to_string()))?
            .into_owned();
        let resolver = reader.resolver().clone();
        let (namespace, event) = resolver.resolve_event(event);
        match event {
            Event::Start(element) => {
                inspect_story_element(
                    &element,
                    &namespace,
                    &resolver,
                    decoder,
                    relationships,
                    hyperlink_depth.is_some(),
                    diagnostics,
                )?;
                depth = depth
                    .checked_add(1)
                    .ok_or_else(|| invalid("story XML depth overflow"))?;
                if is_word_namespace(&namespace) && element.local_name().as_ref() == b"hyperlink" {
                    if has_external_hyperlink_id(&element, &resolver, decoder, relationships)? {
                        hyperlink_depth = Some(depth);
                    }
                }
            },
            Event::Empty(element) => inspect_story_element(
                &element,
                &namespace,
                &resolver,
                decoder,
                relationships,
                hyperlink_depth.is_some(),
                diagnostics,
            )?,
            Event::End(_) => {
                if hyperlink_depth == Some(depth) {
                    hyperlink_depth = None;
                }
                depth = depth
                    .checked_sub(1)
                    .ok_or_else(|| invalid("story XML end depth underflow"))?;
            },
            Event::DocType(_) | Event::PI(_) => {
                add_diagnostic(diagnostics, UnsupportedClass::MarkupCompatibility, 1)?;
            },
            Event::Eof => break,
            _ => {},
        }
    }
    Ok(())
}

fn inspect_story_element(
    element: &quick_xml::events::BytesStart<'_>,
    namespace: &ResolveResult<'_>,
    resolver: &NamespaceResolver,
    decoder: quick_xml::encoding::Decoder,
    relationships: &[RelationshipState],
    inside_hyperlink: bool,
    diagnostics: &mut Vec<Diagnostic>,
) -> Result<()> {
    if is_mce_namespace(namespace) {
        add_diagnostic(diagnostics, UnsupportedClass::MarkupCompatibility, 1)?;
    }
    let is_word = is_word_namespace(namespace);
    if is_word
        && matches!(
            element.local_name().as_ref(),
            b"fldSimple" | b"fldChar" | b"instrText" | b"delInstrText"
        )
    {
        add_diagnostic(diagnostics, UnsupportedClass::FieldOrDde, 1)?;
    }
    if inside_hyperlink && !is_word {
        add_diagnostic(diagnostics, UnsupportedClass::UnknownOwner, 1)?;
    }
    for attribute in element.attributes() {
        let attribute = attribute.map_err(|error| Error::Xml(error.to_string()))?;
        let (attribute_namespace, attribute_local) = resolver.resolve_attribute(attribute.key);
        if is_mce_namespace(&attribute_namespace) {
            add_diagnostic(diagnostics, UnsupportedClass::MarkupCompatibility, 1)?;
        }
        if is_relationships_namespace(&attribute_namespace) {
            let value = attribute
                .decoded_and_normalized_value(XmlVersion::Explicit1_0, decoder)
                .map_err(|error| Error::Xml(error.to_string()))?;
            if let Ok(index) =
                relationships.binary_search_by(|candidate| candidate.id().cmp(value.as_ref()))
            {
                if relationships[index].is_external()
                    && (!is_word
                        || element.local_name().as_ref() != b"hyperlink"
                        || attribute_local.as_ref() != b"id")
                {
                    add_diagnostic(diagnostics, UnsupportedClass::NonStoryExternal, 1)?;
                }
            }
        }
    }
    Ok(())
}

fn has_external_hyperlink_id(
    element: &quick_xml::events::BytesStart<'_>,
    resolver: &NamespaceResolver,
    decoder: quick_xml::encoding::Decoder,
    relationships: &[RelationshipState],
) -> Result<bool> {
    for attribute in element.attributes() {
        let attribute = attribute.map_err(|error| Error::Xml(error.to_string()))?;
        let (namespace, local) = resolver.resolve_attribute(attribute.key);
        if is_relationships_namespace(&namespace) && local.as_ref() == b"id" {
            let value = attribute
                .decoded_and_normalized_value(XmlVersion::Explicit1_0, decoder)
                .map_err(|error| Error::Xml(error.to_string()))?;
            return Ok(relationships
                .binary_search_by(|candidate| candidate.id().cmp(value.as_ref()))
                .ok()
                .is_some_and(|index| relationships[index].is_external()));
        }
    }
    Ok(false)
}

fn validate_topology_size(stories: &[StorySource], limit: usize) -> Result<()> {
    let main = stories
        .first()
        .ok_or_else(|| invalid("story hyperlink inventory is empty"))?;
    if main.owner.part.is_some() {
        return Err(invalid(
            "story hyperlink main story has an unexpected owner",
        ));
    }
    let mut size = TOPOLOGY_MAGIC.len();
    for value in [
        main.owner.relationship_id.as_bytes(),
        main.owner.relationship_type.as_bytes(),
        main.owner.target_ref.as_bytes(),
    ] {
        size = topology_field_size(size, value.len())?;
    }
    size = topology_size(size, 8)?;
    for story in stories {
        size = topology_field_size(size, story.part.as_str().len())?;
        size = topology_field_size(size, story.content_type.len())?;
    }
    size = topology_size(size, 8)?;
    for story in stories.iter().skip(1) {
        let owner = story
            .owner
            .part
            .as_ref()
            .ok_or_else(|| invalid("story hyperlink subsidiary story has no owner"))?;
        for value in [
            owner.as_str().len(),
            story.owner.relationship_id.len(),
            story.owner.relationship_type.len(),
            story.owner.target_ref.len(),
            story.part.as_str().len(),
        ] {
            size = topology_field_size(size, value)?;
        }
        size = topology_size(size, 1)?;
    }
    if size > limit {
        return Err(invalid(format!(
            "DOCX story hyperlink topology exceeds {limit} bytes"
        )));
    }
    Ok(())
}

fn topology_field_size(size: usize, field: usize) -> Result<usize> {
    topology_size(topology_size(size, 8)?, field)
}

fn topology_size(size: usize, added: usize) -> Result<usize> {
    size.checked_add(added)
        .ok_or_else(|| invalid("story hyperlink topology size overflows usize"))
}

fn validate_story_dialect(
    xml: &[u8],
    kind: StoryKind,
    dialect: Dialect,
    max_prolog_events: usize,
) -> Result<()> {
    let mut reader = NsReader::from_reader(xml);
    reader.config_mut().check_end_names = true;
    reader.config_mut().check_comments = true;
    let mut prolog_events = 0usize;
    let mut depth = 0usize;
    let mut roots = 0usize;
    loop {
        if roots == 0 {
            prolog_events = prolog_events
                .checked_add(1)
                .ok_or_else(|| invalid("story XML prolog event count overflows usize"))?;
            if prolog_events > max_prolog_events {
                return Err(invalid(format!(
                    "story XML prolog exceeds {max_prolog_events} events"
                )));
            }
        }
        let event = reader
            .read_event()
            .map_err(|error| Error::Xml(error.to_string()))?
            .into_owned();
        let resolver = reader.resolver().clone();
        let (namespace, event) = resolver.resolve_event(event);
        match event {
            Event::Start(element) => {
                validate_dialect_namespace(&namespace, dialect)?;
                validate_dialect_attributes(&element, dialect, &resolver)?;
                if roots == 0 {
                    if !is_expected_word_namespace(&namespace, dialect)
                        || element.local_name().as_ref() != story_root(kind)
                    {
                        return Err(invalid(
                            "story XML namespace or root does not match its owner",
                        ));
                    }
                    roots = roots
                        .checked_add(1)
                        .ok_or_else(|| invalid("story XML root count overflows usize"))?;
                } else if depth == 0 {
                    return Err(invalid("story XML contains more than one root"));
                }
                depth = depth
                    .checked_add(1)
                    .ok_or_else(|| invalid("story XML depth overflows usize"))?;
            },
            Event::Empty(element) => {
                validate_dialect_namespace(&namespace, dialect)?;
                validate_dialect_attributes(&element, dialect, &resolver)?;
                if roots == 0 {
                    if !is_expected_word_namespace(&namespace, dialect)
                        || element.local_name().as_ref() != story_root(kind)
                    {
                        return Err(invalid(
                            "story XML namespace or root does not match its owner",
                        ));
                    }
                    roots = roots
                        .checked_add(1)
                        .ok_or_else(|| invalid("story XML root count overflows usize"))?;
                } else if depth == 0 {
                    return Err(invalid("story XML contains more than one root"));
                }
            },
            Event::End(_) => {
                validate_dialect_namespace(&namespace, dialect)?;
                depth = depth
                    .checked_sub(1)
                    .ok_or_else(|| invalid("story XML has an unexpected end tag"))?;
            },
            Event::Decl(_) | Event::Comment(_) => {},
            Event::Text(text) if text.as_ref().iter().all(u8::is_ascii_whitespace) => {},
            Event::DocType(_) | Event::PI(_) | Event::GeneralRef(_) => {
                return Err(invalid("story XML prolog contains unsupported syntax"));
            },
            Event::Text(_) | Event::CData(_) if depth != 0 => {},
            Event::Eof => {
                if roots != 1 || depth != 0 {
                    return Err(invalid("story XML root is missing or unterminated"));
                }
                return Ok(());
            },
            _ => return Err(invalid("story XML has content outside its root")),
        }
    }
}

fn validate_dialect_namespace(namespace: &ResolveResult<'_>, dialect: Dialect) -> Result<()> {
    if (is_word_namespace(namespace) || is_relationships_namespace(namespace))
        && !is_expected_word_namespace(namespace, dialect)
        && !is_expected_relationship_namespace(namespace, dialect)
    {
        return Err(invalid(
            "story XML mixes Strict and Transitional qualified names",
        ));
    }
    Ok(())
}

fn validate_dialect_attributes(
    element: &quick_xml::events::BytesStart<'_>,
    dialect: Dialect,
    resolver: &NamespaceResolver,
) -> Result<()> {
    for attribute in element.attributes() {
        let attribute = attribute.map_err(|error| Error::Xml(error.to_string()))?;
        let (namespace, _) = resolver.resolve_attribute(attribute.key);
        validate_dialect_namespace(&namespace, dialect)?;
    }
    Ok(())
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Dialect {
    Transitional,
    Strict,
}

impl Dialect {
    const fn word(self) -> &'static [u8] {
        match self {
            Self::Transitional => TRANSITIONAL_WORD,
            Self::Strict => STRICT_WORD,
        }
    }

    const fn relationships(self) -> &'static [u8] {
        match self {
            Self::Transitional => RELATIONSHIPS_NAMESPACE,
            Self::Strict => STRICT_RELATIONSHIPS_NAMESPACE,
        }
    }
}

fn is_expected_word_namespace(namespace: &ResolveResult<'_>, dialect: Dialect) -> bool {
    matches!(namespace, ResolveResult::Bound(Namespace(value)) if *value == dialect.word())
}

fn is_expected_relationship_namespace(namespace: &ResolveResult<'_>, dialect: Dialect) -> bool {
    matches!(namespace, ResolveResult::Bound(Namespace(value)) if *value == dialect.relationships())
}

fn dialect_for_relationship(value: &str) -> Option<Dialect> {
    if value.starts_with(TRANSITIONAL_RELATIONSHIPS) {
        Some(Dialect::Transitional)
    } else if value.starts_with(STRICT_RELATIONSHIPS) {
        Some(Dialect::Strict)
    } else {
        None
    }
}

fn story_kind_for_relationship(value: &str) -> Option<(Dialect, StoryKind)> {
    let dialect = dialect_for_relationship(value)?;
    let suffix = value.strip_prefix(match dialect {
        Dialect::Transitional => TRANSITIONAL_RELATIONSHIPS,
        Dialect::Strict => STRICT_RELATIONSHIPS,
    })?;
    let kind = match suffix {
        "header" => StoryKind::Header,
        "footer" => StoryKind::Footer,
        "footnotes" => StoryKind::Footnotes,
        "endnotes" => StoryKind::Endnotes,
        "comments" => StoryKind::Comments,
        "glossaryDocument" => StoryKind::Glossary,
        _ => return None,
    };
    Some((dialect, kind))
}

fn kind_from_content_type(value: &str) -> Option<StoryKind> {
    match value {
        ct::WML_DOCUMENT_MAIN
        | ct::WML_TEMPLATE_MAIN
        | ct::WML_DOCUMENT_MACRO_MAIN
        | ct::WML_TEMPLATE_MACRO_MAIN => Some(StoryKind::Main),
        ct::WML_HEADER => Some(StoryKind::Header),
        ct::WML_FOOTER => Some(StoryKind::Footer),
        ct::WML_FOOTNOTES => Some(StoryKind::Footnotes),
        ct::WML_ENDNOTES => Some(StoryKind::Endnotes),
        ct::WML_COMMENTS => Some(StoryKind::Comments),
        ct::WML_DOCUMENT_GLOSSARY => Some(StoryKind::Glossary),
        _ => None,
    }
}

fn validate_main_content_type(value: &str) -> Result<()> {
    if kind_from_content_type(value) == Some(StoryKind::Main) {
        Ok(())
    } else {
        Err(invalid(
            "main document has an unsupported WordprocessingML content type",
        ))
    }
}

const fn content_type_for_kind(kind: StoryKind) -> &'static str {
    match kind {
        StoryKind::Header => ct::WML_HEADER,
        StoryKind::Footer => ct::WML_FOOTER,
        StoryKind::Footnotes => ct::WML_FOOTNOTES,
        StoryKind::Endnotes => ct::WML_ENDNOTES,
        StoryKind::Comments => ct::WML_COMMENTS,
        StoryKind::Glossary => ct::WML_DOCUMENT_GLOSSARY,
        StoryKind::Main => ct::WML_DOCUMENT_MAIN,
    }
}

const fn story_root(kind: StoryKind) -> &'static [u8] {
    match kind {
        StoryKind::Main => b"document",
        StoryKind::Header => b"hdr",
        StoryKind::Footer => b"ftr",
        StoryKind::Footnotes => b"footnotes",
        StoryKind::Endnotes => b"endnotes",
        StoryKind::Comments => b"comments",
        StoryKind::Glossary => b"glossaryDocument",
    }
}

const fn singleton_index(kind: StoryKind) -> Option<usize> {
    match kind {
        StoryKind::Footnotes => Some(0),
        StoryKind::Endnotes => Some(1),
        StoryKind::Comments => Some(2),
        StoryKind::Glossary => Some(3),
        StoryKind::Main | StoryKind::Header | StoryKind::Footer => None,
    }
}

fn is_word_namespace(namespace: &ResolveResult<'_>) -> bool {
    matches!(namespace, ResolveResult::Bound(Namespace(value)) if *value == TRANSITIONAL_WORD || *value == STRICT_WORD)
}

fn is_mce_namespace(namespace: &ResolveResult<'_>) -> bool {
    matches!(namespace, ResolveResult::Bound(Namespace(value)) if *value == MCE_NAMESPACE)
}

fn is_relationships_namespace(namespace: &ResolveResult<'_>) -> bool {
    matches!(namespace, ResolveResult::Bound(Namespace(value)) if *value == RELATIONSHIPS_NAMESPACE || *value == STRICT_RELATIONSHIPS_NAMESPACE)
}

fn is_signature_relationship(value: &str) -> bool {
    matches!(
        value,
        rt::DIGITAL_SIGNATURE_ORIGIN
            | "http://schemas.openxmlformats.org/package/2006/relationships/digital-signature/signature"
            | "http://schemas.openxmlformats.org/package/2006/relationships/digital-signature/certificate"
    )
}

fn story_scanner_limits(limits: Limits) -> sanitize::Limits {
    limits
        .xml
        .with_max_document_bytes(limits.story.max_story_bytes)
        .unwrap_or(limits.xml)
}

fn add_diagnostic(
    diagnostics: &mut Vec<Diagnostic>,
    class: UnsupportedClass,
    count: usize,
) -> Result<()> {
    if let Some(existing) = diagnostics
        .iter_mut()
        .find(|diagnostic| diagnostic.class == class)
    {
        existing.count = existing
            .count
            .checked_add(count)
            .ok_or_else(|| invalid("story hyperlink diagnostic count overflows usize"))?;
        return Ok(());
    }
    diagnostics
        .try_reserve(1)
        .map_err(|source| Error::Allocation {
            resource: "story hyperlink diagnostics",
            source,
        })?;
    diagnostics.push(Diagnostic { class, count });
    Ok(())
}

fn coalesce_diagnostics(mut diagnostics: Vec<Diagnostic>) -> Result<Vec<Diagnostic>> {
    diagnostics.sort_unstable_by_key(|diagnostic| diagnostic.class);
    let mut output: Vec<Diagnostic> = Vec::new();
    output
        .try_reserve_exact(diagnostics.len())
        .map_err(|source| Error::Allocation {
            resource: "story hyperlink diagnostic order",
            source,
        })?;
    for diagnostic in diagnostics {
        if let Some(previous) = output.last_mut() {
            if previous.class == diagnostic.class {
                previous.count = previous
                    .count
                    .checked_add(diagnostic.count)
                    .ok_or_else(|| invalid("story hyperlink diagnostic count overflows usize"))?;
                continue;
            }
        }
        output.push(diagnostic);
    }
    Ok(output)
}

fn owned_str(value: &str, resource: &'static str) -> Result<String> {
    let mut owned = String::new();
    owned
        .try_reserve_exact(value.len())
        .map_err(|source| Error::Allocation { resource, source })?;
    owned.push_str(value);
    Ok(owned)
}

fn copy_bytes(bytes: &[u8], resource: &'static str) -> Result<Vec<u8>> {
    let mut copy = Vec::new();
    copy.try_reserve_exact(bytes.len())
        .map_err(|source| Error::Allocation { resource, source })?;
    copy.extend_from_slice(bytes);
    Ok(copy)
}

fn clone_relationship(relationship: &RelationshipState) -> Result<RelationshipState> {
    Ok(RelationshipState::new(
        owned_str(
            relationship.id(),
            "story hyperlink retained relationship ID",
        )?,
        owned_str(
            relationship.relationship_type(),
            "story hyperlink retained relationship type",
        )?,
        owned_str(
            relationship.target(),
            "story hyperlink retained relationship target",
        )?,
        relationship.is_external(),
    ))
}

fn clone_wrapper(wrapper: &Wrapper) -> Result<Wrapper> {
    Ok(Wrapper {
        open: wrapper.open.clone(),
        close: wrapper.close.clone(),
        relationship_id: owned_str(
            &wrapper.relationship_id,
            "story hyperlink wrapper relationship ID",
        )?,
    })
}

fn owned_uri(value: &PackURI, resource: &'static str) -> Result<String> {
    owned_str(value.as_str(), resource)
}

fn clone_uri(value: &PackURI) -> Result<PackURI> {
    PackURI::new(value.as_str()).map_err(|error| Error::InvalidUri(error.to_string()))
}

fn contains_ascii_case_insensitive(haystack: &str, needle: &str) -> bool {
    haystack
        .as_bytes()
        .windows(needle.len())
        .any(|window| window.eq_ignore_ascii_case(needle.as_bytes()))
}

fn starts_with_ascii_case_insensitive(haystack: &str, needle: &str) -> bool {
    haystack
        .get(..needle.len())
        .is_some_and(|prefix| prefix.eq_ignore_ascii_case(needle))
}

fn unsupported(operation: &'static str, diagnostics: &[Diagnostic]) -> Error {
    let reason = if diagnostics
        .iter()
        .any(|diagnostic| diagnostic.class == UnsupportedClass::UnknownOwner)
    {
        "story package has unsupported or ambiguous reference ownership"
    } else {
        "story package contains external-reference classes outside the supported hyperlink closure"
    };
    Error::UnsafeEdit {
        format: "DOCX",
        operation,
        reason,
    }
}

fn invalid(message: impl Into<String>) -> Error {
    Error::InvalidFormat(message.into())
}

fn limit(resource: &'static str, maximum: usize, actual: usize) -> Error {
    Error::ExternalHyperlinkRedactionLimit {
        resource,
        maximum,
        actual,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn story(part_name: &str) -> StoryInfo {
        StoryInfo {
            part_name: part_name.to_owned(),
            kind: StoryKind::Main,
        }
    }

    fn relationship(
        part_name: &str,
        relationship_id: &str,
        target_url: &str,
    ) -> ExternalHyperlinkRelationship {
        ExternalHyperlinkRelationship {
            part_name: part_name.to_owned(),
            kind: StoryKind::Main,
            relationship_id: relationship_id.to_owned(),
            target_url: target_url.to_owned(),
            wrapper_count: 1,
        }
    }

    #[test]
    fn relationship_indexes_preserve_story_ranges_and_target_order() {
        let stories = [story("/word/header1.xml"), story("/word/document.xml")];
        let relationships = [
            relationship("/word/document.xml", "rId1", "https://z.invalid/"),
            relationship("/word/document.xml", "rId2", "https://a.invalid/"),
            relationship("/word/header1.xml", "rId1", "https://a.invalid/"),
        ];

        let (story_ranges, target_order) =
            build_relationship_indexes(&stories, &relationships).unwrap();

        assert_eq!(
            story_ranges.as_slice(),
            &[
                StoryRelationshipRange { start: 2, end: 3 },
                StoryRelationshipRange { start: 0, end: 2 },
            ]
        );
        let ordered_targets = target_order
            .iter()
            .map(|index| relationships[*index].target_url.as_str())
            .collect::<Vec<_>>();
        assert_eq!(
            ordered_targets,
            [
                "https://a.invalid/",
                "https://a.invalid/",
                "https://z.invalid/",
            ]
        );
    }
}
