#![allow(
    clippy::expect_used,
    clippy::unwrap_used,
    reason = "differential assertions intentionally panic on fixture failures"
)]

//! Change 0765: relationship, content-type and owned XML parts that begin
//! with a UTF-8 byte-order mark are edited exactly like the same parts
//! without one.
//!
//! quick-xml drops a leading mark before its first event without counting it
//! in its positions, so the source splices of this crate addressed bytes three
//! bytes early in a marked part. Each test runs one operation on a package and
//! on its twin whose XML members carry a mark, and requires an output that
//! differs only by marks: every member of the marked output is the unmarked
//! output's member, or that member behind one mark, and a mark appears only on
//! a member whose input had one.

use std::collections::{BTreeMap, BTreeSet};
use std::sync::Arc;

use litchi_core::OwnedSource;
use litchi_opc::{
    OpcPackage, OwnedAttributeUpdate, PackURI, PackageWriter, SourceBackedPackage,
    SourceTopologyPlan,
};
use soapberry_zip::office::{ArchiveReader, StreamingArchiveWriter};

const BOM: &[u8] = b"\xEF\xBB\xBF";
const CONTENT_TYPES_NS: &str = "http://schemas.openxmlformats.org/package/2006/content-types";
const RELATIONSHIPS_NS: &str = "http://schemas.openxmlformats.org/package/2006/relationships";
const OFFICE_DOCUMENT_REL: &str =
    "http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument";
const CUSTOM_REL: &str = "http://example.invalid/relationships/custom";

fn pack(uri: &str) -> PackURI {
    PackURI::new(uri).unwrap()
}

fn is_xml_member(name: &str) -> bool {
    name.ends_with(".xml") || name.ends_with(".rels")
}

fn members(archive: &[u8]) -> BTreeMap<String, Vec<u8>> {
    let reader = ArchiveReader::new(archive).unwrap();
    let names: Vec<String> = reader.file_names().map(str::to_owned).collect();
    names
        .into_iter()
        .map(|name| {
            let bytes = reader.read(&name).unwrap();
            (name, bytes)
        })
        .collect()
}

fn archive(entries: &[(&str, Vec<u8>)], mark: impl Fn(&str) -> bool) -> Vec<u8> {
    let mut writer = StreamingArchiveWriter::new();
    for (name, bytes) in entries {
        let bytes = if mark(name) {
            [BOM, bytes.as_slice()].concat()
        } else {
            bytes.clone()
        };
        writer.write_stored(name, &bytes).unwrap();
    }
    writer.finish_to_bytes().unwrap()
}

/// Require the marked output to equal the unmarked output except for marks.
/// Returns the members that kept a mark.
fn assert_equal_but_marks(marked: &[u8], plain: &[u8]) -> BTreeSet<String> {
    let marked = members(marked);
    let plain = members(plain);
    assert_eq!(
        marked.keys().collect::<Vec<_>>(),
        plain.keys().collect::<Vec<_>>()
    );
    let mut kept = BTreeSet::new();
    for (name, bytes) in &marked {
        let unmarked = &plain[name];
        assert!(
            !unmarked.starts_with(BOM),
            "{name}: unmarked output gained a mark"
        );
        if let Some(rest) = bytes.strip_prefix(BOM) {
            assert_eq!(rest, unmarked.as_slice(), "{name}: differs beyond its mark");
            kept.insert(name.clone());
        } else {
            assert_eq!(bytes, unmarked, "{name}: differs");
        }
    }
    kept
}

/// A package with a removable part, a removable root relationship and a
/// non-canonical part relationship document, whose manifests are spliced
/// rather than regenerated by topology publication.
fn topology_entries() -> Vec<(&'static str, Vec<u8>)> {
    let content_types = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="{CONTENT_TYPES_NS}"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/custom/existing.xml" ContentType="application/vnd.example.deleted+xml"/><Override PartName="/custom/_rels/existing.xml.rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/></Types>"#
    );
    let root_relationships = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="{RELATIONSHIPS_NS}"><Relationship Id="rId1" Type="{OFFICE_DOCUMENT_REL}" Target="word/document.xml"/><Relationship Id="rIdDrop" Type="{CUSTOM_REL}" Target="custom/existing.xml"/></Relationships>"#
    );
    let document_relationships = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?> <Relationships xmlns="{RELATIONSHIPS_NS}"><Relationship Id="rId1" Type="{CUSTOM_REL}" Target="../custom/untouched.xml"/></Relationships>"#
    );
    let owned_relationships = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="{RELATIONSHIPS_NS}"><Relationship Id="rIdKeep" Type="{CUSTOM_REL}" Target="untouched.xml"/></Relationships>"#
    );
    vec![
        ("[Content_Types].xml", content_types.into_bytes()),
        ("_rels/.rels", root_relationships.into_bytes()),
        ("word/document.xml", b"<before/>".to_vec()),
        (
            "word/_rels/document.xml.rels",
            document_relationships.into_bytes(),
        ),
        ("custom/existing.xml", b"<deleted/>".to_vec()),
        (
            "custom/_rels/existing.xml.rels",
            owned_relationships.into_bytes(),
        ),
        (
            "custom/untouched.xml",
            b"<items><item id=\"1\"/><item id=\"2\">two</item><item id=\"3\"/></items>".to_vec(),
        ),
    ]
}

fn topology_plan() -> SourceTopologyPlan {
    let mut plan = SourceTopologyPlan::new();
    plan.try_add_part(
        pack("/custom/new.xml"),
        "application/vnd.example.new+xml",
        b"<new/>".to_vec(),
    )
    .unwrap();
    plan.try_add_internal_relationship(
        pack("/word/document.xml"),
        "rId2",
        CUSTOM_REL,
        pack("/custom/new.xml"),
    )
    .unwrap();
    plan.try_remove_part(pack("/custom/existing.xml")).unwrap();
    plan.try_remove_relationship(pack("/"), "rIdDrop").unwrap();
    plan
}

fn publish(bytes: &[u8], plan: SourceTopologyPlan) -> Vec<u8> {
    let package =
        SourceBackedPackage::from_read_at(Arc::new(OwnedSource::new(bytes.to_vec()))).unwrap();
    let mut output = Vec::new();
    package.write_topology_to_stream(&mut output, plan).unwrap();
    output
}

#[test]
fn topology_publication_splices_marked_manifests_like_unmarked_ones() {
    let entries = topology_entries();
    let plain = publish(&archive(&entries, |_| false), topology_plan());
    let marked = publish(&archive(&entries, is_xml_member), topology_plan());
    let kept = assert_equal_but_marks(&marked, &plain);
    // The spliced manifests keep the producer's mark, like every untouched
    // XML member; the removed part and its relationships are gone from both.
    for name in [
        "[Content_Types].xml",
        "_rels/.rels",
        "word/_rels/document.xml.rels",
        "word/document.xml",
        "custom/untouched.xml",
    ] {
        assert!(kept.contains(name), "{name} lost its mark: {kept:?}");
    }
    let manifest =
        String::from_utf8(members(&marked)["[Content_Types].xml"][3..].to_vec()).unwrap();
    assert!(manifest.contains("PartName=\"/custom/new.xml\""));
    assert!(!manifest.contains("PartName=\"/custom/existing.xml\""));
    let appended = members(&marked)["word/_rels/document.xml.rels"].clone();
    assert!(appended.ends_with(b"Target=\"../custom/new.xml\"/></Relationships>"));
    OpcPackage::from_bytes(&marked).unwrap();
}

#[test]
fn owned_xml_part_ranges_are_byte_ranges_of_marked_bytes() {
    let entries = topology_entries();
    let name = pack("/custom/untouched.xml");
    let plain_package = OpcPackage::from_bytes(&archive(&entries, |_| false)).unwrap();
    let marked_package = OpcPackage::from_bytes(&archive(&entries, is_xml_member)).unwrap();
    let plain = plain_package.source_xml_part(&name).unwrap();
    let marked = marked_package.source_xml_part(&name).unwrap();
    assert_eq!(marked.bytes(), [BOM, plain.bytes()].concat().as_slice());
    let tag = |bytes: &[u8], needle: &[u8]| {
        let start = bytes
            .windows(needle.len())
            .position(|window| window == needle)
            .unwrap();
        start..start + needle.len()
    };
    let check = |edit: &dyn Fn(&litchi_opc::OwnedXmlPart, &[u8]) -> litchi_opc::OwnedXmlPart| {
        let plain_out = edit(&plain, plain.bytes());
        let marked_out = edit(&marked, marked.bytes());
        assert_eq!(
            marked_out.bytes(),
            [BOM, plain_out.bytes()].concat().as_slice()
        );
    };
    check(&|part, bytes| {
        part.replace_element(tag(bytes, b"<item id=\"2\">"), b"<item id=\"2\">new</item>")
            .unwrap()
    });
    check(&|part, bytes| {
        part.remove_element(tag(bytes, b"<item id=\"3\"/>"))
            .unwrap()
    });
    check(&|part, bytes| {
        part.append_element(tag(bytes, b"<items>"), b"<item id=\"4\"/>")
            .unwrap()
    });
    check(&|part, bytes| {
        part.update_attributes(
            &[OwnedAttributeUpdate {
                start_tag: tag(bytes, b"<item id=\"1\"/>"),
                name: "id",
                value: Some(b"9"),
            }],
            1 << 20,
        )
        .unwrap()
    });
    // A range at the reader's uncounted positions no longer names the tag.
    let early = tag(marked.bytes(), b"<item id=\"2\">");
    assert!(
        marked
            .remove_element(early.start - 3..early.end - 3)
            .is_err()
    );
}

#[test]
fn eager_round_trip_of_marked_manifests_matches_the_unmarked_round_trip() {
    let entries = topology_entries();
    let plain =
        PackageWriter::to_bytes(&OpcPackage::from_bytes(&archive(&entries, |_| false)).unwrap())
            .unwrap();
    let marked = PackageWriter::to_bytes(
        &OpcPackage::from_bytes(&archive(&entries, is_xml_member)).unwrap(),
    )
    .unwrap();
    let kept = assert_equal_but_marks(&marked, &plain);
    // Parts are preserved with their marks.
    for name in [
        "word/document.xml",
        "custom/untouched.xml",
        "custom/existing.xml",
    ] {
        assert!(kept.contains(name), "{name} lost its mark: {kept:?}");
    }
}

#[test]
fn a_local_replacement_of_a_marked_part_publishes_like_the_unmarked_one() {
    // The replacement differs from its original inside one element, so the
    // publication audit takes change 0747's window proof over the original's
    // audit; with a mark, both sides carry it and every offset is physical.
    let entries = topology_entries();
    let item = b"<items><item id=\"1\"/><item id=\"2\">two</item><item id=\"3\"/></items>";
    let edited = b"<items><item id=\"1\"/><item id=\"2\">TWO!</item><item id=\"3\"/></items>";
    let publish_with = |marked: bool| {
        let archive = archive(&entries, |name| marked && is_xml_member(name));
        let mut plan = SourceTopologyPlan::new();
        let replacement = if marked {
            [BOM, edited.as_slice()].concat()
        } else {
            edited.to_vec()
        };
        plan.try_replace_part(pack("/custom/untouched.xml"), replacement)
            .unwrap();
        publish(&archive, plan)
    };
    let plain = publish_with(false);
    let marked = publish_with(true);
    let kept = assert_equal_but_marks(&marked, &plain);
    assert!(kept.contains("custom/untouched.xml"), "{kept:?}");
    assert_eq!(
        members(&marked)["custom/untouched.xml"],
        [BOM, edited.as_slice()].concat()
    );
    assert_ne!(item.as_slice(), edited.as_slice());
    // A marked replacement with an out-of-window defect is still refused.
    let mut plan = SourceTopologyPlan::new();
    plan.try_replace_part(
        pack("/custom/untouched.xml"),
        [
            BOM,
            b"<items><item id=\"1\"/><item id=\"2\">TWO!</item><item id=\"3\"/></items><x/>",
        ]
        .concat(),
    )
    .unwrap();
    let package = SourceBackedPackage::from_read_at(Arc::new(OwnedSource::new(archive(
        &entries,
        is_xml_member,
    ))))
    .unwrap();
    let mut output = Vec::new();
    assert!(package.write_topology_to_stream(&mut output, plan).is_err());
    assert!(output.is_empty());
}

#[test]
fn a_marked_malformed_replacement_is_refused_at_its_physical_offset() {
    let entries = topology_entries();
    let refusal = |marked: bool| {
        let defect = b"<items><item id=\"1\"/><item id=\"2\">TWO</itm><item id=\"3\"/></items>";
        let replacement = if marked {
            [BOM, defect.as_slice()].concat()
        } else {
            defect.to_vec()
        };
        let mut plan = SourceTopologyPlan::new();
        plan.try_replace_part(pack("/custom/untouched.xml"), replacement)
            .unwrap();
        let package = SourceBackedPackage::from_read_at(Arc::new(OwnedSource::new(archive(
            &entries,
            |name| marked && is_xml_member(name),
        ))))
        .unwrap();
        let mut output = Vec::new();
        let error = package
            .write_topology_to_stream(&mut output, plan)
            .unwrap_err();
        assert!(output.is_empty());
        format!("{error:?}")
    };
    let offset = |message: &str| {
        let start = message.find("offset: ").expect(message) + "offset: ".len();
        message[start..]
            .chars()
            .take_while(char::is_ascii_digit)
            .collect::<String>()
            .parse::<usize>()
            .unwrap()
    };
    let plain = refusal(false);
    let marked = refusal(true);
    assert_eq!(
        offset(&marked),
        offset(&plain) + BOM.len(),
        "{plain} / {marked}"
    );
}
