use std::{
    env,
    error::Error,
    fs,
    path::{Path, PathBuf},
};

fn main() -> Result<(), Box<dyn Error>> {
    const PROTO_DIRECTORY: &str = "src/protos";
    const BUFFA_PROJECTION_DIRECTORY: &str = "src/buffa-projections";
    let proto_directory = Path::new(PROTO_DIRECTORY);
    let buffa_projection_directory = Path::new(BUFFA_PROJECTION_DIRECTORY);

    println!("cargo:rerun-if-changed={PROTO_DIRECTORY}");
    println!("cargo:rerun-if-changed={BUFFA_PROJECTION_DIRECTORY}");

    let mut proto_files = fs::read_dir(proto_directory)?
        .map(|directory_entry| directory_entry.map(|entry| entry.path()))
        .collect::<Result<Vec<PathBuf>, _>>()?;
    proto_files.retain(|path| {
        path.extension()
            .is_some_and(|extension| extension == "proto")
    });
    proto_files.sort_unstable();

    if proto_files.is_empty() {
        return Err(format!("no Protocol Buffer schemas found in {PROTO_DIRECTORY}").into());
    }
    enforce_text_projection_provenance(proto_directory, buffa_projection_directory)?;

    prost_build::Config::new()
        .include_file("iwa_protos.rs")
        .compile_protos(&proto_files, &[proto_directory])?;

    // Keep the archive-header sidecar isolated from format projections. Prost
    // remains the full-corpus compatibility generator during migration.
    let buffa_proto_files = [
        proto_directory.join("TSPMessages.proto"),
        proto_directory.join("TSPArchiveMessages.proto"),
    ];
    let buffa_out_directory = PathBuf::from(env::var("OUT_DIR")?).join("buffa");
    buffa_build::Config::new()
        .files(&buffa_proto_files)
        .includes(&[proto_directory])
        .out_dir(buffa_out_directory)
        .include_file("iwa_buffa_protos.rs")
        .generate_views(true)
        .lazy_views(true)
        .preserve_unknown_fields(true)
        .generate_json(false)
        .generate_text(false)
        .reflect_mode(buffa_build::ReflectMode::Off)
        .idiomatic_field_names(true)
        .compile()?;

    // The text decoder never encodes or preserves from its view: caller-owned
    // source bytes remain authoritative. Generate the tiny derived projection
    // separately with unknown retention disabled so unrelated native fields
    // consume neither generated closure nor unknown-span storage.
    let buffa_text_out_directory = PathBuf::from(env::var("OUT_DIR")?).join("buffa-text-storage");
    buffa_build::Config::new()
        .files(&[buffa_projection_directory.join("TSWPStorageArchive.proto")])
        .includes(&[buffa_projection_directory])
        .out_dir(&buffa_text_out_directory)
        .include_file("iwa_text_storage_buffa_protos.rs")
        .generate_views(true)
        .lazy_views(true)
        .preserve_unknown_fields(false)
        .generate_json(false)
        .generate_text(false)
        .reflect_mode(buffa_build::ReflectMode::Off)
        .idiomatic_field_names(true)
        .compile()?;
    enforce_text_projection_budget(&buffa_text_out_directory)?;

    Ok(())
}

fn enforce_text_projection_provenance(
    proto_directory: &Path,
    projection_directory: &Path,
) -> Result<(), Box<dyn Error>> {
    const TEXT_DECLARATION: &str = "repeated string text = 3;";

    let canonical = fs::read_to_string(proto_directory.join("TSWPArchives.proto"))?;
    let projection = fs::read_to_string(projection_directory.join("TSWPStorageArchive.proto"))?;
    if canonical.matches(TEXT_DECLARATION).count() != 1
        || projection.matches(TEXT_DECLARATION).count() != 1
    {
        return Err(
            "derived TSWP text projection is out of sync with StorageArchive field 3".into(),
        );
    }
    Ok(())
}

fn enforce_text_projection_budget(directory: &Path) -> Result<(), Box<dyn Error>> {
    const EXPECTED_FILES: usize = 5;
    const MAX_GENERATED_BYTES: u64 = 32 * 1024;

    let mut files = 0usize;
    let mut bytes = 0u64;
    for entry_result in fs::read_dir(directory)? {
        let entry = entry_result?;
        if !entry.file_type()?.is_file() {
            continue;
        }
        files = files
            .checked_add(1)
            .ok_or("generated file count overflow")?;
        bytes = bytes
            .checked_add(entry.metadata()?.len())
            .ok_or("generated byte count overflow")?;
    }

    if files != EXPECTED_FILES || bytes > MAX_GENERATED_BYTES {
        return Err(format!(
            "TSWP text projection generated {files} files/{bytes} bytes; expected {EXPECTED_FILES} files and at most {MAX_GENERATED_BYTES} bytes"
        )
        .into());
    }
    Ok(())
}
