[package]
name        = "litchi-iwa-protos"
description = "Generated raw Protocol Buffer schemas for Apple iWork IWA archives."
version.workspace      = true
edition.workspace      = true
authors.workspace      = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true

[dependencies]
buffa = "=0.9.1"
prost = { workspace = true }

[build-dependencies]
buffa-build = "=0.9.1"
prost-build = { workspace = true }

[lints]
workspace = true
