//! Closed graphic-property vocabulary and typed lexical values.

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Kind {
    Dr3dAmbientColor,
    Dr3dBackScale,
    Dr3dBackfaceCulling,
    Dr3dCloseBack,
    Dr3dCloseFront,
    Dr3dDepth,
    Dr3dDiffuseColor,
    Dr3dEdgeRounding,
    Dr3dEdgeRoundingMode,
    Dr3dEmissiveColor,
    Dr3dEndAngle,
    Dr3dHorizontalSegments,
    Dr3dLightingMode,
    Dr3dNormalsDirection,
    Dr3dNormalsKind,
    Dr3dShadow,
    Dr3dShininess,
    Dr3dSpecularColor,
    Dr3dTextureFilter,
    Dr3dTextureGenerationModeX,
    Dr3dTextureGenerationModeY,
    Dr3dTextureKind,
    Dr3dTextureMode,
    Dr3dVerticalSegments,
    DrawAutoGrowHeight,
    DrawAutoGrowWidth,
    DrawBlue,
    DrawCaptionAngle,
    DrawCaptionAngleType,
    DrawCaptionEscape,
    DrawCaptionEscapeDirection,
    DrawCaptionFitLineLength,
    DrawCaptionGap,
    DrawCaptionLineLength,
    DrawCaptionType,
    DrawColorInversion,
    DrawColorMode,
    DrawContrast,
    DrawDecimalPlaces,
    DrawDrawAspect,
    DrawEndGuide,
    DrawEndLineSpacingHorizontal,
    DrawEndLineSpacingVertical,
    DrawFill,
    DrawFillColor,
    DrawFillGradientName,
    DrawFillHatchName,
    DrawFillHatchSolid,
    DrawFillImageHeight,
    DrawFillImageName,
    DrawFillImageRefPoint,
    DrawFillImageRefPointX,
    DrawFillImageRefPointY,
    DrawFillImageWidth,
    DrawFitToContour,
    DrawFitToSize,
    DrawFrameDisplayBorder,
    DrawFrameDisplayScrollbar,
    DrawFrameMarginHorizontal,
    DrawFrameMarginVertical,
    DrawGamma,
    DrawGradientStepCount,
    DrawGreen,
    DrawGuideDistance,
    DrawGuideOverhang,
    DrawImageOpacity,
    DrawLineDistance,
    DrawLuminance,
    DrawMarkerEnd,
    DrawMarkerEndCenter,
    DrawMarkerEndWidth,
    DrawMarkerStart,
    DrawMarkerStartCenter,
    DrawMarkerStartWidth,
    DrawMeasureAlign,
    DrawMeasureVerticalAlign,
    DrawOleDrawAspect,
    DrawOpacity,
    DrawOpacityName,
    DrawParallel,
    DrawPlacing,
    DrawRed,
    DrawSecondaryFillColor,
    DrawShadow,
    DrawShadowColor,
    DrawShadowOffsetX,
    DrawShadowOffsetY,
    DrawShadowOpacity,
    DrawShowUnit,
    DrawStartGuide,
    DrawStartLineSpacingHorizontal,
    DrawStartLineSpacingVertical,
    DrawStroke,
    DrawStrokeDash,
    DrawStrokeDashNames,
    DrawStrokeLinejoin,
    DrawSymbolColor,
    DrawTextareaHorizontalAlign,
    DrawTextareaVerticalAlign,
    DrawTileRepeatOffset,
    DrawUnit,
    DrawVisibleAreaHeight,
    DrawVisibleAreaLeft,
    DrawVisibleAreaTop,
    DrawVisibleAreaWidth,
    DrawWrapInfluenceOnPosition,
    FoBackgroundColor,
    FoBorder,
    FoBorderBottom,
    FoBorderLeft,
    FoBorderRight,
    FoBorderTop,
    FoClip,
    FoMargin,
    FoMarginBottom,
    FoMarginLeft,
    FoMarginRight,
    FoMarginTop,
    FoMaxHeight,
    FoMaxWidth,
    FoMinHeight,
    FoMinWidth,
    FoPadding,
    FoPaddingBottom,
    FoPaddingLeft,
    FoPaddingRight,
    FoPaddingTop,
    FoWrapOption,
    StyleBackgroundTransparency,
    StyleBorderLineWidth,
    StyleBorderLineWidthBottom,
    StyleBorderLineWidthLeft,
    StyleBorderLineWidthRight,
    StyleBorderLineWidthTop,
    StyleEditable,
    StyleFlowWithText,
    StyleHorizontalPos,
    StyleHorizontalRel,
    StyleMirror,
    StyleNumberWrappedParagraphs,
    StyleOverflowBehavior,
    StylePrintContent,
    StyleProtect,
    StyleRelHeight,
    StyleRelWidth,
    StyleRepeat,
    StyleRunThrough,
    StyleShadow,
    StyleShrinkToFit,
    StyleVerticalPos,
    StyleVerticalRel,
    StyleWrap,
    StyleWrapContour,
    StyleWrapContourMode,
    StyleWrapDynamicThreshold,
    StyleWritingMode,
    SvgFillRule,
    SvgHeight,
    SvgStrokeColor,
    SvgStrokeLinecap,
    SvgStrokeOpacity,
    SvgStrokeWidth,
    SvgWidth,
    SvgX,
    SvgY,
    TextAnchorPageNumber,
    TextAnchorType,
    TextAnimation,
    TextAnimationDelay,
    TextAnimationDirection,
    TextAnimationRepeat,
    TextAnimationStartInside,
    TextAnimationSteps,
    TextAnimationStopInside,
}
impl Kind {
    pub const ALL: &'static [Self] = &[
        Self::Dr3dAmbientColor,
        Self::Dr3dBackScale,
        Self::Dr3dBackfaceCulling,
        Self::Dr3dCloseBack,
        Self::Dr3dCloseFront,
        Self::Dr3dDepth,
        Self::Dr3dDiffuseColor,
        Self::Dr3dEdgeRounding,
        Self::Dr3dEdgeRoundingMode,
        Self::Dr3dEmissiveColor,
        Self::Dr3dEndAngle,
        Self::Dr3dHorizontalSegments,
        Self::Dr3dLightingMode,
        Self::Dr3dNormalsDirection,
        Self::Dr3dNormalsKind,
        Self::Dr3dShadow,
        Self::Dr3dShininess,
        Self::Dr3dSpecularColor,
        Self::Dr3dTextureFilter,
        Self::Dr3dTextureGenerationModeX,
        Self::Dr3dTextureGenerationModeY,
        Self::Dr3dTextureKind,
        Self::Dr3dTextureMode,
        Self::Dr3dVerticalSegments,
        Self::DrawAutoGrowHeight,
        Self::DrawAutoGrowWidth,
        Self::DrawBlue,
        Self::DrawCaptionAngle,
        Self::DrawCaptionAngleType,
        Self::DrawCaptionEscape,
        Self::DrawCaptionEscapeDirection,
        Self::DrawCaptionFitLineLength,
        Self::DrawCaptionGap,
        Self::DrawCaptionLineLength,
        Self::DrawCaptionType,
        Self::DrawColorInversion,
        Self::DrawColorMode,
        Self::DrawContrast,
        Self::DrawDecimalPlaces,
        Self::DrawDrawAspect,
        Self::DrawEndGuide,
        Self::DrawEndLineSpacingHorizontal,
        Self::DrawEndLineSpacingVertical,
        Self::DrawFill,
        Self::DrawFillColor,
        Self::DrawFillGradientName,
        Self::DrawFillHatchName,
        Self::DrawFillHatchSolid,
        Self::DrawFillImageHeight,
        Self::DrawFillImageName,
        Self::DrawFillImageRefPoint,
        Self::DrawFillImageRefPointX,
        Self::DrawFillImageRefPointY,
        Self::DrawFillImageWidth,
        Self::DrawFitToContour,
        Self::DrawFitToSize,
        Self::DrawFrameDisplayBorder,
        Self::DrawFrameDisplayScrollbar,
        Self::DrawFrameMarginHorizontal,
        Self::DrawFrameMarginVertical,
        Self::DrawGamma,
        Self::DrawGradientStepCount,
        Self::DrawGreen,
        Self::DrawGuideDistance,
        Self::DrawGuideOverhang,
        Self::DrawImageOpacity,
        Self::DrawLineDistance,
        Self::DrawLuminance,
        Self::DrawMarkerEnd,
        Self::DrawMarkerEndCenter,
        Self::DrawMarkerEndWidth,
        Self::DrawMarkerStart,
        Self::DrawMarkerStartCenter,
        Self::DrawMarkerStartWidth,
        Self::DrawMeasureAlign,
        Self::DrawMeasureVerticalAlign,
        Self::DrawOleDrawAspect,
        Self::DrawOpacity,
        Self::DrawOpacityName,
        Self::DrawParallel,
        Self::DrawPlacing,
        Self::DrawRed,
        Self::DrawSecondaryFillColor,
        Self::DrawShadow,
        Self::DrawShadowColor,
        Self::DrawShadowOffsetX,
        Self::DrawShadowOffsetY,
        Self::DrawShadowOpacity,
        Self::DrawShowUnit,
        Self::DrawStartGuide,
        Self::DrawStartLineSpacingHorizontal,
        Self::DrawStartLineSpacingVertical,
        Self::DrawStroke,
        Self::DrawStrokeDash,
        Self::DrawStrokeDashNames,
        Self::DrawStrokeLinejoin,
        Self::DrawSymbolColor,
        Self::DrawTextareaHorizontalAlign,
        Self::DrawTextareaVerticalAlign,
        Self::DrawTileRepeatOffset,
        Self::DrawUnit,
        Self::DrawVisibleAreaHeight,
        Self::DrawVisibleAreaLeft,
        Self::DrawVisibleAreaTop,
        Self::DrawVisibleAreaWidth,
        Self::DrawWrapInfluenceOnPosition,
        Self::FoBackgroundColor,
        Self::FoBorder,
        Self::FoBorderBottom,
        Self::FoBorderLeft,
        Self::FoBorderRight,
        Self::FoBorderTop,
        Self::FoClip,
        Self::FoMargin,
        Self::FoMarginBottom,
        Self::FoMarginLeft,
        Self::FoMarginRight,
        Self::FoMarginTop,
        Self::FoMaxHeight,
        Self::FoMaxWidth,
        Self::FoMinHeight,
        Self::FoMinWidth,
        Self::FoPadding,
        Self::FoPaddingBottom,
        Self::FoPaddingLeft,
        Self::FoPaddingRight,
        Self::FoPaddingTop,
        Self::FoWrapOption,
        Self::StyleBackgroundTransparency,
        Self::StyleBorderLineWidth,
        Self::StyleBorderLineWidthBottom,
        Self::StyleBorderLineWidthLeft,
        Self::StyleBorderLineWidthRight,
        Self::StyleBorderLineWidthTop,
        Self::StyleEditable,
        Self::StyleFlowWithText,
        Self::StyleHorizontalPos,
        Self::StyleHorizontalRel,
        Self::StyleMirror,
        Self::StyleNumberWrappedParagraphs,
        Self::StyleOverflowBehavior,
        Self::StylePrintContent,
        Self::StyleProtect,
        Self::StyleRelHeight,
        Self::StyleRelWidth,
        Self::StyleRepeat,
        Self::StyleRunThrough,
        Self::StyleShadow,
        Self::StyleShrinkToFit,
        Self::StyleVerticalPos,
        Self::StyleVerticalRel,
        Self::StyleWrap,
        Self::StyleWrapContour,
        Self::StyleWrapContourMode,
        Self::StyleWrapDynamicThreshold,
        Self::StyleWritingMode,
        Self::SvgFillRule,
        Self::SvgHeight,
        Self::SvgStrokeColor,
        Self::SvgStrokeLinecap,
        Self::SvgStrokeOpacity,
        Self::SvgStrokeWidth,
        Self::SvgWidth,
        Self::SvgX,
        Self::SvgY,
        Self::TextAnchorPageNumber,
        Self::TextAnchorType,
        Self::TextAnimation,
        Self::TextAnimationDelay,
        Self::TextAnimationDirection,
        Self::TextAnimationRepeat,
        Self::TextAnimationStartInside,
        Self::TextAnimationSteps,
        Self::TextAnimationStopInside,
    ];
    pub fn example(self) -> &'static str {
        match self {
            Self::Dr3dAmbientColor => "#102030",
            Self::Dr3dBackScale => "-.5%",
            Self::Dr3dBackfaceCulling => "disabled",
            Self::Dr3dCloseBack => "true",
            Self::Dr3dCloseFront => "true",
            Self::Dr3dDepth => "-0.5cm",
            Self::Dr3dDiffuseColor => "#102030",
            Self::Dr3dEdgeRounding => "-.5%",
            Self::Dr3dEdgeRoundingMode => "attractive",
            Self::Dr3dEmissiveColor => "#102030",
            Self::Dr3dEndAngle => "sample",
            Self::Dr3dHorizontalSegments => "000",
            Self::Dr3dLightingMode => "double-sided",
            Self::Dr3dNormalsDirection => "inverse",
            Self::Dr3dNormalsKind => "flat",
            Self::Dr3dShadow => "hidden",
            Self::Dr3dShininess => "-.5%",
            Self::Dr3dSpecularColor => "#102030",
            Self::Dr3dTextureFilter => "disabled",
            Self::Dr3dTextureGenerationModeX => "object",
            Self::Dr3dTextureGenerationModeY => "object",
            Self::Dr3dTextureKind => "color",
            Self::Dr3dTextureMode => "blend",
            Self::Dr3dVerticalSegments => "000",
            Self::DrawAutoGrowHeight => "true",
            Self::DrawAutoGrowWidth => "true",
            Self::DrawBlue => "-100%",
            Self::DrawCaptionAngle => "sample",
            Self::DrawCaptionAngleType => "fixed",
            Self::DrawCaptionEscape => "-0.5cm",
            Self::DrawCaptionEscapeDirection => "auto",
            Self::DrawCaptionFitLineLength => "true",
            Self::DrawCaptionGap => "-0.5cm",
            Self::DrawCaptionLineLength => "-0.5cm",
            Self::DrawCaptionType => "angled-connector-line",
            Self::DrawColorInversion => "true",
            Self::DrawColorMode => "greyscale",
            Self::DrawContrast => "-.5%",
            Self::DrawDecimalPlaces => "000",
            Self::DrawDrawAspect => "content",
            Self::DrawEndGuide => "-0.5cm",
            Self::DrawEndLineSpacingHorizontal => "-0.5cm",
            Self::DrawEndLineSpacingVertical => "-0.5cm",
            Self::DrawFill => "bitmap",
            Self::DrawFillColor => "#102030",
            Self::DrawFillGradientName => "name_1",
            Self::DrawFillHatchName => "name_1",
            Self::DrawFillHatchSolid => "true",
            Self::DrawFillImageHeight => "-0.5cm",
            Self::DrawFillImageName => "name_1",
            Self::DrawFillImageRefPoint => "bottom",
            Self::DrawFillImageRefPointX => "-.5%",
            Self::DrawFillImageRefPointY => "-.5%",
            Self::DrawFillImageWidth => "-0.5cm",
            Self::DrawFitToContour => "true",
            Self::DrawFitToSize => "true",
            Self::DrawFrameDisplayBorder => "true",
            Self::DrawFrameDisplayScrollbar => "true",
            Self::DrawFrameMarginHorizontal => "0px",
            Self::DrawFrameMarginVertical => "0px",
            Self::DrawGamma => "-.5%",
            Self::DrawGradientStepCount => "000",
            Self::DrawGreen => "-100%",
            Self::DrawGuideDistance => "-0.5cm",
            Self::DrawGuideOverhang => "-0.5cm",
            Self::DrawImageOpacity => "100.0%",
            Self::DrawLineDistance => "-0.5cm",
            Self::DrawLuminance => "100.0%",
            Self::DrawMarkerEnd => "name_1",
            Self::DrawMarkerEndCenter => "true",
            Self::DrawMarkerEndWidth => "-0.5cm",
            Self::DrawMarkerStart => "name_1",
            Self::DrawMarkerStartCenter => "true",
            Self::DrawMarkerStartWidth => "-0.5cm",
            Self::DrawMeasureAlign => "automatic",
            Self::DrawMeasureVerticalAlign => "above",
            Self::DrawOleDrawAspect => "000",
            Self::DrawOpacity => "-.5%",
            Self::DrawOpacityName => "name_1",
            Self::DrawParallel => "true",
            Self::DrawPlacing => "above",
            Self::DrawRed => "-100%",
            Self::DrawSecondaryFillColor => "#102030",
            Self::DrawShadow => "hidden",
            Self::DrawShadowColor => "#102030",
            Self::DrawShadowOffsetX => "-0.5cm",
            Self::DrawShadowOffsetY => "-0.5cm",
            Self::DrawShadowOpacity => "100.0%",
            Self::DrawShowUnit => "true",
            Self::DrawStartGuide => "-0.5cm",
            Self::DrawStartLineSpacingHorizontal => "-0.5cm",
            Self::DrawStartLineSpacingVertical => "-0.5cm",
            Self::DrawStroke => "dash",
            Self::DrawStrokeDash => "name_1",
            Self::DrawStrokeDashNames => "one two",
            Self::DrawStrokeLinejoin => "bevel",
            Self::DrawSymbolColor => "#102030",
            Self::DrawTextareaHorizontalAlign => "center",
            Self::DrawTextareaVerticalAlign => "bottom",
            Self::DrawTileRepeatOffset => "50% horizontal",
            Self::DrawUnit => "automatic",
            Self::DrawVisibleAreaHeight => ".1cm",
            Self::DrawVisibleAreaLeft => "0cm",
            Self::DrawVisibleAreaTop => "0cm",
            Self::DrawVisibleAreaWidth => ".1cm",
            Self::DrawWrapInfluenceOnPosition => "iterative",
            Self::FoBackgroundColor => "transparent",
            Self::FoBorder => "sample",
            Self::FoBorderBottom => "sample",
            Self::FoBorderLeft => "sample",
            Self::FoBorderRight => "sample",
            Self::FoBorderTop => "sample",
            Self::FoClip => "auto",
            Self::FoMargin => "0cm",
            Self::FoMarginBottom => "0cm",
            Self::FoMarginLeft => "-0.5cm",
            Self::FoMarginRight => "-0.5cm",
            Self::FoMarginTop => "0cm",
            Self::FoMaxHeight => "-0.5cm",
            Self::FoMaxWidth => "-0.5cm",
            Self::FoMinHeight => "-0.5cm",
            Self::FoMinWidth => "-0.5cm",
            Self::FoPadding => "0cm",
            Self::FoPaddingBottom => "0cm",
            Self::FoPaddingLeft => "0cm",
            Self::FoPaddingRight => "0cm",
            Self::FoPaddingTop => "0cm",
            Self::FoWrapOption => "no-wrap",
            Self::StyleBackgroundTransparency => "100.0%",
            Self::StyleBorderLineWidth => "1pt 2pt 3pt",
            Self::StyleBorderLineWidthBottom => "1pt 2pt 3pt",
            Self::StyleBorderLineWidthLeft => "1pt 2pt 3pt",
            Self::StyleBorderLineWidthRight => "1pt 2pt 3pt",
            Self::StyleBorderLineWidthTop => "1pt 2pt 3pt",
            Self::StyleEditable => "true",
            Self::StyleFlowWithText => "true",
            Self::StyleHorizontalPos => "center",
            Self::StyleHorizontalRel => "char",
            Self::StyleMirror => "none",
            Self::StyleNumberWrappedParagraphs => "no-limit",
            Self::StyleOverflowBehavior => "auto-create-new-frame",
            Self::StylePrintContent => "true",
            Self::StyleProtect => "content",
            Self::StyleRelHeight => "scale",
            Self::StyleRelWidth => "scale",
            Self::StyleRepeat => "no-repeat",
            Self::StyleRunThrough => "background",
            Self::StyleShadow => "sample",
            Self::StyleShrinkToFit => "true",
            Self::StyleVerticalPos => "below",
            Self::StyleVerticalRel => "baseline",
            Self::StyleWrap => "biggest",
            Self::StyleWrapContour => "true",
            Self::StyleWrapContourMode => "full",
            Self::StyleWrapDynamicThreshold => "0cm",
            Self::StyleWritingMode => "lr",
            Self::SvgFillRule => "evenodd",
            Self::SvgHeight => "-0.5cm",
            Self::SvgStrokeColor => "#102030",
            Self::SvgStrokeLinecap => "butt",
            Self::SvgStrokeOpacity => "100.0%",
            Self::SvgStrokeWidth => "-0.5cm",
            Self::SvgWidth => "-0.5cm",
            Self::SvgX => "-0.5cm",
            Self::SvgY => "-0.5cm",
            Self::TextAnchorPageNumber => "01",
            Self::TextAnchorType => "as-char",
            Self::TextAnimation => "alternate",
            Self::TextAnimationDelay => "PT1.5S",
            Self::TextAnimationDirection => "down",
            Self::TextAnimationRepeat => "000",
            Self::TextAnimationStartInside => "true",
            Self::TextAnimationSteps => "-0.5cm",
            Self::TextAnimationStopInside => "true",
        }
    }
}

/// Closed namespaces used by the 174 graphic property names.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Namespace {
    Dr3d,
    Draw,
    Fo,
    Style,
    Svg,
    Text,
}

/// A lexically validated value whose variant identifies its normative datatype.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Value {
    Boolean(bool),
    Color(String),
    Length(String),
    NonNegativeLength(String),
    PositiveLength(String),
    NonNegativePixelLength(String),
    Percent(String),
    ZeroToHundredPercent(String),
    SignedZeroToHundredPercent(String),
    NonNegativeInteger(String),
    PositiveInteger(String),
    Duration(String),
    Clip(String),
    StyleNameRef(String),
    StyleNameRefs(Vec<String>),
    Keyword(String),
    Text(String),
    Compound(String),
}

impl Value {
    pub fn lexical(&self) -> String {
        match self {
            Self::Boolean(value) => value.to_string(),
            Self::Color(value)
            | Self::Length(value)
            | Self::NonNegativeLength(value)
            | Self::PositiveLength(value)
            | Self::NonNegativePixelLength(value)
            | Self::Percent(value)
            | Self::ZeroToHundredPercent(value)
            | Self::SignedZeroToHundredPercent(value)
            | Self::NonNegativeInteger(value)
            | Self::PositiveInteger(value)
            | Self::Duration(value)
            | Self::Clip(value)
            | Self::StyleNameRef(value)
            | Self::Keyword(value)
            | Self::Text(value)
            | Self::Compound(value) => value.clone(),
            Self::StyleNameRefs(values) => values.join(" "),
        }
    }
}
