//! Package-independent change-tracking values.

use litchi_opc::PackURI;

use crate::Result;

/// A cryptographically strong random identifier recorded by a producer.
///
/// The XML schema's complete `xsd:unsignedInt` domain is retained. Generating
/// cryptographic randomness remains the caller's responsibility.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Id(u32);

impl Id {
    /// Wrap an identifier supplied or generated by the caller.
    #[inline]
    #[must_use]
    pub const fn new(value: u32) -> Self {
        Self(value)
    }

    /// Return the unsigned wire value.
    #[inline]
    #[must_use]
    pub const fn value(self) -> u32 {
        self.0
    }
}

impl From<u32> for Id {
    #[inline]
    fn from(value: u32) -> Self {
        Self::new(value)
    }
}

/// One shape's semantic selector data and optional modification identifier.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Shape {
    pub(super) name: Option<String>,
    pub(super) modification_id: Option<Id>,
    pub(super) trackable: bool,
}

impl Shape {
    /// Exact producer-visible shape name, when present.
    #[inline]
    #[must_use]
    pub fn name(&self) -> Option<&str> {
        self.name.as_deref()
    }

    /// Identifier updated by a producer when this shape changes.
    #[inline]
    #[must_use]
    pub const fn modification_id(&self) -> Option<Id> {
        self.modification_id
    }

    /// Whether this shape exposes the standard `p:nvPr` extension owner.
    #[inline]
    #[must_use]
    pub const fn supports_modification_id(&self) -> bool {
        self.trackable
    }

    pub(super) fn new(name: Option<String>, modification_id: Option<Id>, trackable: bool) -> Self {
        Self {
            name,
            modification_id,
            trackable,
        }
    }
}

/// Complete typed change-tracking state for one slide.
///
/// Malformed producer duplicates remain inspectable so callers can repair
/// them by checked position. A commit cannot publish duplicate modification
/// identifiers.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct State {
    creation_id: Option<Id>,
    shapes: Vec<Shape>,
}

impl State {
    /// Identifier generated when the slide was created.
    #[inline]
    #[must_use]
    pub const fn creation_id(&self) -> Option<Id> {
        self.creation_id
    }

    /// Shapes in bounded depth-first presentation order.
    #[inline]
    #[must_use]
    pub fn shapes(&self) -> &[Shape] {
        &self.shapes
    }

    pub(super) fn new(creation_id: Option<Id>, shapes: Vec<Shape>) -> Self {
        Self {
            creation_id,
            shapes,
        }
    }

    pub(super) fn creation_id_mut(&mut self) -> &mut Option<Id> {
        &mut self.creation_id
    }

    pub(super) fn shapes_mut(&mut self) -> &mut [Shape] {
        &mut self.shapes
    }

    pub(super) fn validate(&self) -> Result<()> {
        super::codec::validate_unique_modification_ids(self)
    }
}

/// Immutable source-bound change-tracking snapshot for one slide.
#[derive(Debug, Clone)]
pub struct Snapshot {
    pub(super) owner: PackURI,
    pub(super) source: Vec<u8>,
    pub(super) state: State,
}

impl Snapshot {
    /// Borrow the complete typed state.
    #[inline]
    #[must_use]
    pub const fn state(&self) -> &State {
        &self.state
    }

    /// Start an isolated semantic edit. The snapshot itself is never changed.
    #[inline]
    #[must_use]
    pub fn edit(&self) -> super::Edit {
        super::Edit::new(self.clone())
    }

    pub(super) fn from_source(owner: PackURI, source: Vec<u8>) -> Result<Self> {
        let state = super::codec::read_state(&source)?;
        Ok(Self {
            owner,
            source,
            state,
        })
    }
}
