//! Read-only inventory projection over the current editor snapshot.

use super::super::codec::{corrupted, u32_at};
use super::super::model::{Editor, Entry, Inventory, Metadata, Reference, WriteOptions};
use crate::package::Result;
use litchi_ole_common::object::{Object, Objects};

impl Editor {
    /// Validates every DOC field reference against the owning `ObjectPool`.
    pub(in crate::embedded_object) fn validate_references(&self) -> Result<()> {
        self.objects().map(|_| ())
    }

    /// Returns the current managed-object snapshot with inert OLE metadata.
    ///
    /// The projection only reads the editor's current candidate. It never
    /// opens, follows, renders, instantiates, or executes an embedded object,
    /// and it does not publish any state. Mutations continue to operate on a
    /// cloned candidate and therefore remain atomic if a later validation
    /// step fails.
    ///
    /// # Errors
    ///
    /// Returns an error when a managed field has no owning `ObjectPool`
    /// storage or a metadata projection cannot be read.
    pub fn inventory(&self) -> Result<Inventory> {
        let references = self.objects()?;
        let mut entries = Vec::with_capacity(references.len());
        for reference in references {
            let object =
                object_for_reference(self.package.objects(), &reference).ok_or_else(|| {
                    corrupted(format!(
                        "managed embedded-object storage {:?} is missing",
                        reference.storage_name
                    ))
                })?;
            entries.push(Entry::from_parts(reference, Metadata::of(object)?));
        }
        Ok(Inventory::from_entries(entries))
    }

    /// Captures one managed object's complete inert transfer closure.
    ///
    /// The returned options own the standalone `ObjectPool` CFB and the exact
    /// `PICFAndOfficeArtData` preview block addressed by the field result.
    /// Field CPs, CHPX references, and receiver storage names are intentionally
    /// regenerated by the destination editor instead of being copied as
    /// source-local identifiers.
    pub fn export_for_transfer(
        &self,
        storage_id: u32,
        destination_storage_id: u32,
    ) -> Result<WriteOptions> {
        let reference = self
            .objects()?
            .into_iter()
            .find(|reference| reference.storage_id == storage_id)
            .ok_or_else(|| corrupted("managed embedded-object storage ID was not found"))?;
        let object = object_for_reference(self.package.objects(), &reference)
            .ok_or_else(|| corrupted("managed embedded-object storage is missing"))?;
        let bytes = self.clone().finish()?;
        let revision = crate::tracked_revision::RevisionEditor::open(bytes, self.limits)?;
        let preview_cp = reference
            .separator_cp
            .checked_add(1)
            .ok_or_else(|| corrupted("embedded preview CP overflow"))?;
        let data_offset = revision.picture_location_at_cp(preview_cp)?;
        let offset = usize::try_from(data_offset)
            .map_err(|_| corrupted("embedded preview offset exceeds usize"))?;
        let length = usize::try_from(u32_at(&self.data, offset)?)
            .map_err(|_| corrupted("embedded preview length exceeds usize"))?;
        let end = offset
            .checked_add(length)
            .ok_or_else(|| corrupted("embedded preview range overflow"))?;
        let picture_data = self
            .data
            .get(offset..end)
            .ok_or_else(|| corrupted("embedded preview exceeds the Data stream"))?
            .to_vec();
        Ok(WriteOptions::new(
            destination_storage_id,
            object.compound().to_vec(),
            picture_data,
        ))
    }
}

pub(in crate::embedded_object) fn object_for_reference<'a>(
    objects: &'a Objects,
    reference: &Reference,
) -> Option<&'a Object> {
    objects.get(&reference.storage_name).or_else(|| {
        objects.iter().find(|object| {
            object
                .path()
                .last()
                .and_then(|name| name.strip_prefix('_'))
                .and_then(|value| value.parse::<u32>().ok())
                == Some(reference.storage_id)
        })
    })
}
