//! Create a Keynote presentation, then edit its transition through `litchi-keynote`.

use std::error::Error;
use std::path::{Path, PathBuf};

use litchi_iwa::keynote::KeynoteDocumentBuilder;
use litchi_keynote::{
    Package, SlideSelector,
    transition::{Acceleration, Direction, Effect, MosaicType, TextDelivery},
};
use tempfile::NamedTempFile;

fn main() -> Result<(), Box<dyn Error>> {
    let output = PathBuf::from(
        std::env::args()
            .nth(1)
            .ok_or("usage: create_keynote_transition <output.key>")?,
    );

    let keynote = KeynoteDocumentBuilder::new()
        .title("Transition vocabulary")
        .subtitle("Generated by litchi-iwa")
        .build()?;
    let package = Package::from_bytes(&keynote.to_bytes()?)?;
    let mut settings = package
        .slide_transition(SlideSelector::index(0))?
        .ok_or("generated slide has no modern transition settings")?;
    settings.set_effect(Some(Effect::MagicMove))?;
    settings.set_direction(Some(Direction::from_native(2)));
    let mut custom_parameters = *settings.custom_parameters();
    custom_parameters.set_mosaic_type(Some(MosaicType::from_native(7)));
    custom_parameters.set_acceleration(Some(Acceleration::EaseInOut));
    custom_parameters.set_text_delivery(Some(TextDelivery::ByWord));
    settings.set_custom_parameters(custom_parameters)?;
    let edit = package.edit_slide_transition(SlideSelector::index(0))?;
    settings.set_delay(Some(0.25))?;
    let commit = edit.set(settings.clone())?.commit()?;
    assert_eq!(
        commit.package().slide_transition(SlideSelector::index(0))?,
        Some(settings)
    );
    save_new(&output, commit.package())?;
    Ok(())
}

/// Publishes through a sibling temporary file without overwriting an existing target.
fn save_new(path: &Path, package: &Package) -> Result<(), Box<dyn Error>> {
    let parent = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."));
    let mut temporary = NamedTempFile::new_in(parent)?;
    package.write_to(temporary.as_file_mut())?;
    temporary.as_file().sync_all()?;
    temporary
        .persist_noclobber(path)
        .map_err(|error| Box::new(error.error))?;
    Ok(())
}
