//! Create a Keynote presentation containing typed transition vocabulary.

use litchi_iwa::keynote::{KeynoteDocumentBuilder, KeynoteEditor};
use litchi_keynote::transition::{Acceleration, Direction, Effect, MosaicType, TextDelivery};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let output = std::env::args()
        .nth(1)
        .ok_or("usage: create_keynote_transition <output.key>")?;

    let mut keynote = KeynoteDocumentBuilder::new()
        .title("Transition vocabulary")
        .subtitle("Generated by litchi-iwa")
        .build()?;
    let mut settings = keynote
        .slide_transition(0)?
        .ok_or("generated slide has no modern transition settings")?;
    settings.effect = Some(Effect::MagicMove);
    settings.direction = Some(Direction::from_native(2));
    settings.custom_parameters.mosaic_type = Some(MosaicType::from_native(7));
    settings.custom_parameters.acceleration = Some(Acceleration::EaseInOut);
    settings.custom_parameters.text_delivery = Some(TextDelivery::ByWord);
    keynote.set_slide_transition(0, settings.clone())?;

    let reopened = KeynoteEditor::from_bytes(&keynote.to_bytes()?)?;
    assert_eq!(reopened.slide_transition(0)?, Some(settings));
    reopened.save(output)?;
    Ok(())
}
