// Generated from the ODF 1.2 OS paragraph inline grammar.

use super::super::Ns;

pub(crate) fn is_ruby_base_child(namespace: Ns, local: &[u8]) -> bool {
    matches!(
        (namespace, local),
        (Ns::Dr3d, b"scene")
            | (Ns::Draw | Ns::Text, b"a")
            | (
                Ns::Draw,
                b"caption"
                    | b"circle"
                    | b"connector"
                    | b"control"
                    | b"custom-shape"
                    | b"ellipse"
                    | b"frame"
                    | b"g"
                    | b"line"
                    | b"measure"
                    | b"page-thumbnail"
                    | b"path"
                    | b"polygon"
                    | b"polyline"
                    | b"rect"
                    | b"regular-polygon"
            )
            | (Ns::Office, b"annotation" | b"annotation-end")
            | (Ns::Presentation, b"date-time" | b"footer" | b"header")
            | (
                Ns::Text,
                b"alphabetical-index-mark"
                    | b"alphabetical-index-mark-end"
                    | b"alphabetical-index-mark-start"
                    | b"author-initials"
                    | b"author-name"
                    | b"bibliography-mark"
                    | b"bookmark"
                    | b"bookmark-end"
                    | b"bookmark-ref"
                    | b"bookmark-start"
                    | b"change"
                    | b"change-end"
                    | b"change-start"
                    | b"chapter"
                    | b"character-count"
                    | b"conditional-text"
                    | b"creation-date"
                    | b"creation-time"
                    | b"creator"
                    | b"database-display"
                    | b"database-name"
                    | b"database-next"
                    | b"database-row-number"
                    | b"database-row-select"
                    | b"date"
                    | b"dde-connection"
                    | b"description"
                    | b"editing-cycles"
                    | b"editing-duration"
                    | b"execute-macro"
                    | b"expression"
                    | b"file-name"
                    | b"hidden-paragraph"
                    | b"hidden-text"
                    | b"image-count"
                    | b"initial-creator"
                    | b"keywords"
                    | b"line-break"
                    | b"measure"
                    | b"meta"
                    | b"meta-field"
                    | b"modification-date"
                    | b"modification-time"
                    | b"note"
                    | b"note-ref"
                    | b"object-count"
                    | b"page-continuation"
                    | b"page-count"
                    | b"page-number"
                    | b"page-variable-get"
                    | b"page-variable-set"
                    | b"paragraph-count"
                    | b"placeholder"
                    | b"print-date"
                    | b"print-time"
                    | b"printed-by"
                    | b"reference-mark"
                    | b"reference-mark-end"
                    | b"reference-mark-start"
                    | b"reference-ref"
                    | b"ruby"
                    | b"s"
                    | b"script"
                    | b"sender-city"
                    | b"sender-company"
                    | b"sender-country"
                    | b"sender-email"
                    | b"sender-fax"
                    | b"sender-firstname"
                    | b"sender-initials"
                    | b"sender-lastname"
                    | b"sender-phone-private"
                    | b"sender-phone-work"
                    | b"sender-position"
                    | b"sender-postal-code"
                    | b"sender-state-or-province"
                    | b"sender-street"
                    | b"sender-title"
                    | b"sequence"
                    | b"sequence-ref"
                    | b"sheet-name"
                    | b"soft-page-break"
                    | b"span"
                    | b"subject"
                    | b"tab"
                    | b"table-count"
                    | b"table-formula"
                    | b"template-name"
                    | b"text-input"
                    | b"time"
                    | b"title"
                    | b"toc-mark"
                    | b"toc-mark-end"
                    | b"toc-mark-start"
                    | b"user-defined"
                    | b"user-field-get"
                    | b"user-field-input"
                    | b"user-index-mark"
                    | b"user-index-mark-end"
                    | b"user-index-mark-start"
                    | b"variable-get"
                    | b"variable-input"
                    | b"variable-set"
                    | b"word-count"
            )
    )
}

pub(crate) fn is_hyperlink_child(namespace: Ns, local: &[u8]) -> bool {
    matches!(
        (namespace, local),
        (Ns::Dr3d, b"scene")
            | (
                Ns::Draw,
                b"a" | b"caption"
                    | b"circle"
                    | b"connector"
                    | b"control"
                    | b"custom-shape"
                    | b"ellipse"
                    | b"frame"
                    | b"g"
                    | b"line"
                    | b"measure"
                    | b"page-thumbnail"
                    | b"path"
                    | b"polygon"
                    | b"polyline"
                    | b"rect"
                    | b"regular-polygon"
            )
            | (Ns::Office, b"annotation" | b"annotation-end")
            | (Ns::Presentation, b"date-time" | b"footer" | b"header")
            | (
                Ns::Text,
                b"alphabetical-index-mark"
                    | b"alphabetical-index-mark-end"
                    | b"alphabetical-index-mark-start"
                    | b"author-initials"
                    | b"author-name"
                    | b"bibliography-mark"
                    | b"bookmark"
                    | b"bookmark-end"
                    | b"bookmark-ref"
                    | b"bookmark-start"
                    | b"change"
                    | b"change-end"
                    | b"change-start"
                    | b"chapter"
                    | b"character-count"
                    | b"conditional-text"
                    | b"creation-date"
                    | b"creation-time"
                    | b"creator"
                    | b"database-display"
                    | b"database-name"
                    | b"database-next"
                    | b"database-row-number"
                    | b"database-row-select"
                    | b"date"
                    | b"dde-connection"
                    | b"description"
                    | b"editing-cycles"
                    | b"editing-duration"
                    | b"execute-macro"
                    | b"expression"
                    | b"file-name"
                    | b"hidden-paragraph"
                    | b"hidden-text"
                    | b"image-count"
                    | b"initial-creator"
                    | b"keywords"
                    | b"line-break"
                    | b"measure"
                    | b"meta"
                    | b"meta-field"
                    | b"modification-date"
                    | b"modification-time"
                    | b"note"
                    | b"note-ref"
                    | b"object-count"
                    | b"page-continuation"
                    | b"page-count"
                    | b"page-number"
                    | b"page-variable-get"
                    | b"page-variable-set"
                    | b"paragraph-count"
                    | b"placeholder"
                    | b"print-date"
                    | b"print-time"
                    | b"printed-by"
                    | b"reference-mark"
                    | b"reference-mark-end"
                    | b"reference-mark-start"
                    | b"reference-ref"
                    | b"ruby"
                    | b"s"
                    | b"script"
                    | b"sender-city"
                    | b"sender-company"
                    | b"sender-country"
                    | b"sender-email"
                    | b"sender-fax"
                    | b"sender-firstname"
                    | b"sender-initials"
                    | b"sender-lastname"
                    | b"sender-phone-private"
                    | b"sender-phone-work"
                    | b"sender-position"
                    | b"sender-postal-code"
                    | b"sender-state-or-province"
                    | b"sender-street"
                    | b"sender-title"
                    | b"sequence"
                    | b"sequence-ref"
                    | b"sheet-name"
                    | b"soft-page-break"
                    | b"span"
                    | b"subject"
                    | b"tab"
                    | b"table-count"
                    | b"table-formula"
                    | b"template-name"
                    | b"text-input"
                    | b"time"
                    | b"title"
                    | b"toc-mark"
                    | b"toc-mark-end"
                    | b"toc-mark-start"
                    | b"user-defined"
                    | b"user-field-get"
                    | b"user-field-input"
                    | b"user-index-mark"
                    | b"user-index-mark-end"
                    | b"user-index-mark-start"
                    | b"variable-get"
                    | b"variable-input"
                    | b"variable-set"
                    | b"word-count"
            )
    )
}
