// Generated from the ODF 1.2 OS Relax NG style:text-properties closure.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum TextPropertyKind {
    FoFontVariant,
    FoTextTransform,
    FoColor,
    StyleUseWindowFontColor,
    StyleTextOutline,
    StyleTextLineThroughType,
    StyleTextLineThroughStyle,
    StyleTextLineThroughWidth,
    StyleTextLineThroughColor,
    StyleTextLineThroughText,
    StyleTextLineThroughTextStyle,
    StyleTextPosition,
    StyleFontName,
    StyleFontNameAsian,
    StyleFontNameComplex,
    FoFontFamily,
    StyleFontFamilyAsian,
    StyleFontFamilyComplex,
    StyleFontFamilyGeneric,
    StyleFontFamilyGenericAsian,
    StyleFontFamilyGenericComplex,
    StyleFontStyleName,
    StyleFontStyleNameAsian,
    StyleFontStyleNameComplex,
    StyleFontPitch,
    StyleFontPitchAsian,
    StyleFontPitchComplex,
    StyleFontCharset,
    StyleFontCharsetAsian,
    StyleFontCharsetComplex,
    FoFontSize,
    StyleFontSizeAsian,
    StyleFontSizeComplex,
    StyleFontSizeRel,
    StyleFontSizeRelAsian,
    StyleFontSizeRelComplex,
    StyleScriptType,
    FoLetterSpacing,
    FoLanguage,
    StyleLanguageAsian,
    StyleLanguageComplex,
    FoCountry,
    StyleCountryAsian,
    StyleCountryComplex,
    FoScript,
    StyleScriptAsian,
    StyleScriptComplex,
    StyleRfcLanguageTag,
    StyleRfcLanguageTagAsian,
    StyleRfcLanguageTagComplex,
    FoFontStyle,
    StyleFontStyleAsian,
    StyleFontStyleComplex,
    StyleFontRelief,
    FoTextShadow,
    StyleTextUnderlineType,
    StyleTextUnderlineStyle,
    StyleTextUnderlineWidth,
    StyleTextUnderlineColor,
    StyleTextOverlineType,
    StyleTextOverlineStyle,
    StyleTextOverlineWidth,
    StyleTextOverlineColor,
    StyleTextOverlineMode,
    FoFontWeight,
    StyleFontWeightAsian,
    StyleFontWeightComplex,
    StyleTextUnderlineMode,
    StyleTextLineThroughMode,
    StyleLetterKerning,
    StyleTextBlinking,
    StyleTextCombine,
    StyleTextCombineStartChar,
    StyleTextCombineEndChar,
    StyleTextEmphasize,
    StyleTextScale,
    StyleTextRotationAngle,
    StyleTextRotationScale,
    FoHyphenate,
    FoHyphenationRemainCharCount,
    FoHyphenationPushCharCount,
    TextDisplay,
    TextCondition,
    FoBackgroundColor,
}

impl TextPropertyKind {
    pub const ALL: &'static [Self] = &[
        Self::FoFontVariant,
        Self::FoTextTransform,
        Self::FoColor,
        Self::StyleUseWindowFontColor,
        Self::StyleTextOutline,
        Self::StyleTextLineThroughType,
        Self::StyleTextLineThroughStyle,
        Self::StyleTextLineThroughWidth,
        Self::StyleTextLineThroughColor,
        Self::StyleTextLineThroughText,
        Self::StyleTextLineThroughTextStyle,
        Self::StyleTextPosition,
        Self::StyleFontName,
        Self::StyleFontNameAsian,
        Self::StyleFontNameComplex,
        Self::FoFontFamily,
        Self::StyleFontFamilyAsian,
        Self::StyleFontFamilyComplex,
        Self::StyleFontFamilyGeneric,
        Self::StyleFontFamilyGenericAsian,
        Self::StyleFontFamilyGenericComplex,
        Self::StyleFontStyleName,
        Self::StyleFontStyleNameAsian,
        Self::StyleFontStyleNameComplex,
        Self::StyleFontPitch,
        Self::StyleFontPitchAsian,
        Self::StyleFontPitchComplex,
        Self::StyleFontCharset,
        Self::StyleFontCharsetAsian,
        Self::StyleFontCharsetComplex,
        Self::FoFontSize,
        Self::StyleFontSizeAsian,
        Self::StyleFontSizeComplex,
        Self::StyleFontSizeRel,
        Self::StyleFontSizeRelAsian,
        Self::StyleFontSizeRelComplex,
        Self::StyleScriptType,
        Self::FoLetterSpacing,
        Self::FoLanguage,
        Self::StyleLanguageAsian,
        Self::StyleLanguageComplex,
        Self::FoCountry,
        Self::StyleCountryAsian,
        Self::StyleCountryComplex,
        Self::FoScript,
        Self::StyleScriptAsian,
        Self::StyleScriptComplex,
        Self::StyleRfcLanguageTag,
        Self::StyleRfcLanguageTagAsian,
        Self::StyleRfcLanguageTagComplex,
        Self::FoFontStyle,
        Self::StyleFontStyleAsian,
        Self::StyleFontStyleComplex,
        Self::StyleFontRelief,
        Self::FoTextShadow,
        Self::StyleTextUnderlineType,
        Self::StyleTextUnderlineStyle,
        Self::StyleTextUnderlineWidth,
        Self::StyleTextUnderlineColor,
        Self::StyleTextOverlineType,
        Self::StyleTextOverlineStyle,
        Self::StyleTextOverlineWidth,
        Self::StyleTextOverlineColor,
        Self::StyleTextOverlineMode,
        Self::FoFontWeight,
        Self::StyleFontWeightAsian,
        Self::StyleFontWeightComplex,
        Self::StyleTextUnderlineMode,
        Self::StyleTextLineThroughMode,
        Self::StyleLetterKerning,
        Self::StyleTextBlinking,
        Self::StyleTextCombine,
        Self::StyleTextCombineStartChar,
        Self::StyleTextCombineEndChar,
        Self::StyleTextEmphasize,
        Self::StyleTextScale,
        Self::StyleTextRotationAngle,
        Self::StyleTextRotationScale,
        Self::FoHyphenate,
        Self::FoHyphenationRemainCharCount,
        Self::FoHyphenationPushCharCount,
        Self::TextDisplay,
        Self::TextCondition,
        Self::FoBackgroundColor,
    ];

    pub fn namespace(self) -> TextPropertyNamespace {
        match self {
            Self::FoFontVariant => TextPropertyNamespace::Fo,
            Self::FoTextTransform => TextPropertyNamespace::Fo,
            Self::FoColor => TextPropertyNamespace::Fo,
            Self::StyleUseWindowFontColor => TextPropertyNamespace::Style,
            Self::StyleTextOutline => TextPropertyNamespace::Style,
            Self::StyleTextLineThroughType => TextPropertyNamespace::Style,
            Self::StyleTextLineThroughStyle => TextPropertyNamespace::Style,
            Self::StyleTextLineThroughWidth => TextPropertyNamespace::Style,
            Self::StyleTextLineThroughColor => TextPropertyNamespace::Style,
            Self::StyleTextLineThroughText => TextPropertyNamespace::Style,
            Self::StyleTextLineThroughTextStyle => TextPropertyNamespace::Style,
            Self::StyleTextPosition => TextPropertyNamespace::Style,
            Self::StyleFontName => TextPropertyNamespace::Style,
            Self::StyleFontNameAsian => TextPropertyNamespace::Style,
            Self::StyleFontNameComplex => TextPropertyNamespace::Style,
            Self::FoFontFamily => TextPropertyNamespace::Fo,
            Self::StyleFontFamilyAsian => TextPropertyNamespace::Style,
            Self::StyleFontFamilyComplex => TextPropertyNamespace::Style,
            Self::StyleFontFamilyGeneric => TextPropertyNamespace::Style,
            Self::StyleFontFamilyGenericAsian => TextPropertyNamespace::Style,
            Self::StyleFontFamilyGenericComplex => TextPropertyNamespace::Style,
            Self::StyleFontStyleName => TextPropertyNamespace::Style,
            Self::StyleFontStyleNameAsian => TextPropertyNamespace::Style,
            Self::StyleFontStyleNameComplex => TextPropertyNamespace::Style,
            Self::StyleFontPitch => TextPropertyNamespace::Style,
            Self::StyleFontPitchAsian => TextPropertyNamespace::Style,
            Self::StyleFontPitchComplex => TextPropertyNamespace::Style,
            Self::StyleFontCharset => TextPropertyNamespace::Style,
            Self::StyleFontCharsetAsian => TextPropertyNamespace::Style,
            Self::StyleFontCharsetComplex => TextPropertyNamespace::Style,
            Self::FoFontSize => TextPropertyNamespace::Fo,
            Self::StyleFontSizeAsian => TextPropertyNamespace::Style,
            Self::StyleFontSizeComplex => TextPropertyNamespace::Style,
            Self::StyleFontSizeRel => TextPropertyNamespace::Style,
            Self::StyleFontSizeRelAsian => TextPropertyNamespace::Style,
            Self::StyleFontSizeRelComplex => TextPropertyNamespace::Style,
            Self::StyleScriptType => TextPropertyNamespace::Style,
            Self::FoLetterSpacing => TextPropertyNamespace::Fo,
            Self::FoLanguage => TextPropertyNamespace::Fo,
            Self::StyleLanguageAsian => TextPropertyNamespace::Style,
            Self::StyleLanguageComplex => TextPropertyNamespace::Style,
            Self::FoCountry => TextPropertyNamespace::Fo,
            Self::StyleCountryAsian => TextPropertyNamespace::Style,
            Self::StyleCountryComplex => TextPropertyNamespace::Style,
            Self::FoScript => TextPropertyNamespace::Fo,
            Self::StyleScriptAsian => TextPropertyNamespace::Style,
            Self::StyleScriptComplex => TextPropertyNamespace::Style,
            Self::StyleRfcLanguageTag => TextPropertyNamespace::Style,
            Self::StyleRfcLanguageTagAsian => TextPropertyNamespace::Style,
            Self::StyleRfcLanguageTagComplex => TextPropertyNamespace::Style,
            Self::FoFontStyle => TextPropertyNamespace::Fo,
            Self::StyleFontStyleAsian => TextPropertyNamespace::Style,
            Self::StyleFontStyleComplex => TextPropertyNamespace::Style,
            Self::StyleFontRelief => TextPropertyNamespace::Style,
            Self::FoTextShadow => TextPropertyNamespace::Fo,
            Self::StyleTextUnderlineType => TextPropertyNamespace::Style,
            Self::StyleTextUnderlineStyle => TextPropertyNamespace::Style,
            Self::StyleTextUnderlineWidth => TextPropertyNamespace::Style,
            Self::StyleTextUnderlineColor => TextPropertyNamespace::Style,
            Self::StyleTextOverlineType => TextPropertyNamespace::Style,
            Self::StyleTextOverlineStyle => TextPropertyNamespace::Style,
            Self::StyleTextOverlineWidth => TextPropertyNamespace::Style,
            Self::StyleTextOverlineColor => TextPropertyNamespace::Style,
            Self::StyleTextOverlineMode => TextPropertyNamespace::Style,
            Self::FoFontWeight => TextPropertyNamespace::Fo,
            Self::StyleFontWeightAsian => TextPropertyNamespace::Style,
            Self::StyleFontWeightComplex => TextPropertyNamespace::Style,
            Self::StyleTextUnderlineMode => TextPropertyNamespace::Style,
            Self::StyleTextLineThroughMode => TextPropertyNamespace::Style,
            Self::StyleLetterKerning => TextPropertyNamespace::Style,
            Self::StyleTextBlinking => TextPropertyNamespace::Style,
            Self::StyleTextCombine => TextPropertyNamespace::Style,
            Self::StyleTextCombineStartChar => TextPropertyNamespace::Style,
            Self::StyleTextCombineEndChar => TextPropertyNamespace::Style,
            Self::StyleTextEmphasize => TextPropertyNamespace::Style,
            Self::StyleTextScale => TextPropertyNamespace::Style,
            Self::StyleTextRotationAngle => TextPropertyNamespace::Style,
            Self::StyleTextRotationScale => TextPropertyNamespace::Style,
            Self::FoHyphenate => TextPropertyNamespace::Fo,
            Self::FoHyphenationRemainCharCount => TextPropertyNamespace::Fo,
            Self::FoHyphenationPushCharCount => TextPropertyNamespace::Fo,
            Self::TextDisplay => TextPropertyNamespace::Text,
            Self::TextCondition => TextPropertyNamespace::Text,
            Self::FoBackgroundColor => TextPropertyNamespace::Fo,
        }
    }

    pub fn local_name(self) -> &'static str {
        match self {
            Self::FoFontVariant => "font-variant",
            Self::FoTextTransform => "text-transform",
            Self::FoColor => "color",
            Self::StyleUseWindowFontColor => "use-window-font-color",
            Self::StyleTextOutline => "text-outline",
            Self::StyleTextLineThroughType => "text-line-through-type",
            Self::StyleTextLineThroughStyle => "text-line-through-style",
            Self::StyleTextLineThroughWidth => "text-line-through-width",
            Self::StyleTextLineThroughColor => "text-line-through-color",
            Self::StyleTextLineThroughText => "text-line-through-text",
            Self::StyleTextLineThroughTextStyle => "text-line-through-text-style",
            Self::StyleTextPosition => "text-position",
            Self::StyleFontName => "font-name",
            Self::StyleFontNameAsian => "font-name-asian",
            Self::StyleFontNameComplex => "font-name-complex",
            Self::FoFontFamily => "font-family",
            Self::StyleFontFamilyAsian => "font-family-asian",
            Self::StyleFontFamilyComplex => "font-family-complex",
            Self::StyleFontFamilyGeneric => "font-family-generic",
            Self::StyleFontFamilyGenericAsian => "font-family-generic-asian",
            Self::StyleFontFamilyGenericComplex => "font-family-generic-complex",
            Self::StyleFontStyleName => "font-style-name",
            Self::StyleFontStyleNameAsian => "font-style-name-asian",
            Self::StyleFontStyleNameComplex => "font-style-name-complex",
            Self::StyleFontPitch => "font-pitch",
            Self::StyleFontPitchAsian => "font-pitch-asian",
            Self::StyleFontPitchComplex => "font-pitch-complex",
            Self::StyleFontCharset => "font-charset",
            Self::StyleFontCharsetAsian => "font-charset-asian",
            Self::StyleFontCharsetComplex => "font-charset-complex",
            Self::FoFontSize => "font-size",
            Self::StyleFontSizeAsian => "font-size-asian",
            Self::StyleFontSizeComplex => "font-size-complex",
            Self::StyleFontSizeRel => "font-size-rel",
            Self::StyleFontSizeRelAsian => "font-size-rel-asian",
            Self::StyleFontSizeRelComplex => "font-size-rel-complex",
            Self::StyleScriptType => "script-type",
            Self::FoLetterSpacing => "letter-spacing",
            Self::FoLanguage => "language",
            Self::StyleLanguageAsian => "language-asian",
            Self::StyleLanguageComplex => "language-complex",
            Self::FoCountry => "country",
            Self::StyleCountryAsian => "country-asian",
            Self::StyleCountryComplex => "country-complex",
            Self::FoScript => "script",
            Self::StyleScriptAsian => "script-asian",
            Self::StyleScriptComplex => "script-complex",
            Self::StyleRfcLanguageTag => "rfc-language-tag",
            Self::StyleRfcLanguageTagAsian => "rfc-language-tag-asian",
            Self::StyleRfcLanguageTagComplex => "rfc-language-tag-complex",
            Self::FoFontStyle => "font-style",
            Self::StyleFontStyleAsian => "font-style-asian",
            Self::StyleFontStyleComplex => "font-style-complex",
            Self::StyleFontRelief => "font-relief",
            Self::FoTextShadow => "text-shadow",
            Self::StyleTextUnderlineType => "text-underline-type",
            Self::StyleTextUnderlineStyle => "text-underline-style",
            Self::StyleTextUnderlineWidth => "text-underline-width",
            Self::StyleTextUnderlineColor => "text-underline-color",
            Self::StyleTextOverlineType => "text-overline-type",
            Self::StyleTextOverlineStyle => "text-overline-style",
            Self::StyleTextOverlineWidth => "text-overline-width",
            Self::StyleTextOverlineColor => "text-overline-color",
            Self::StyleTextOverlineMode => "text-overline-mode",
            Self::FoFontWeight => "font-weight",
            Self::StyleFontWeightAsian => "font-weight-asian",
            Self::StyleFontWeightComplex => "font-weight-complex",
            Self::StyleTextUnderlineMode => "text-underline-mode",
            Self::StyleTextLineThroughMode => "text-line-through-mode",
            Self::StyleLetterKerning => "letter-kerning",
            Self::StyleTextBlinking => "text-blinking",
            Self::StyleTextCombine => "text-combine",
            Self::StyleTextCombineStartChar => "text-combine-start-char",
            Self::StyleTextCombineEndChar => "text-combine-end-char",
            Self::StyleTextEmphasize => "text-emphasize",
            Self::StyleTextScale => "text-scale",
            Self::StyleTextRotationAngle => "text-rotation-angle",
            Self::StyleTextRotationScale => "text-rotation-scale",
            Self::FoHyphenate => "hyphenate",
            Self::FoHyphenationRemainCharCount => "hyphenation-remain-char-count",
            Self::FoHyphenationPushCharCount => "hyphenation-push-char-count",
            Self::TextDisplay => "display",
            Self::TextCondition => "condition",
            Self::FoBackgroundColor => "background-color",
        }
    }

    pub(crate) fn from_expanded(namespace: TextPropertyNamespace, local: &str) -> Option<Self> {
        match (namespace, local) {
            (TextPropertyNamespace::Fo, "font-variant") => Some(Self::FoFontVariant),
            (TextPropertyNamespace::Fo, "text-transform") => Some(Self::FoTextTransform),
            (TextPropertyNamespace::Fo, "color") => Some(Self::FoColor),
            (TextPropertyNamespace::Style, "use-window-font-color") => Some(Self::StyleUseWindowFontColor),
            (TextPropertyNamespace::Style, "text-outline") => Some(Self::StyleTextOutline),
            (TextPropertyNamespace::Style, "text-line-through-type") => Some(Self::StyleTextLineThroughType),
            (TextPropertyNamespace::Style, "text-line-through-style") => Some(Self::StyleTextLineThroughStyle),
            (TextPropertyNamespace::Style, "text-line-through-width") => Some(Self::StyleTextLineThroughWidth),
            (TextPropertyNamespace::Style, "text-line-through-color") => Some(Self::StyleTextLineThroughColor),
            (TextPropertyNamespace::Style, "text-line-through-text") => Some(Self::StyleTextLineThroughText),
            (TextPropertyNamespace::Style, "text-line-through-text-style") => Some(Self::StyleTextLineThroughTextStyle),
            (TextPropertyNamespace::Style, "text-position") => Some(Self::StyleTextPosition),
            (TextPropertyNamespace::Style, "font-name") => Some(Self::StyleFontName),
            (TextPropertyNamespace::Style, "font-name-asian") => Some(Self::StyleFontNameAsian),
            (TextPropertyNamespace::Style, "font-name-complex") => Some(Self::StyleFontNameComplex),
            (TextPropertyNamespace::Fo, "font-family") => Some(Self::FoFontFamily),
            (TextPropertyNamespace::Style, "font-family-asian") => Some(Self::StyleFontFamilyAsian),
            (TextPropertyNamespace::Style, "font-family-complex") => Some(Self::StyleFontFamilyComplex),
            (TextPropertyNamespace::Style, "font-family-generic") => Some(Self::StyleFontFamilyGeneric),
            (TextPropertyNamespace::Style, "font-family-generic-asian") => Some(Self::StyleFontFamilyGenericAsian),
            (TextPropertyNamespace::Style, "font-family-generic-complex") => Some(Self::StyleFontFamilyGenericComplex),
            (TextPropertyNamespace::Style, "font-style-name") => Some(Self::StyleFontStyleName),
            (TextPropertyNamespace::Style, "font-style-name-asian") => Some(Self::StyleFontStyleNameAsian),
            (TextPropertyNamespace::Style, "font-style-name-complex") => Some(Self::StyleFontStyleNameComplex),
            (TextPropertyNamespace::Style, "font-pitch") => Some(Self::StyleFontPitch),
            (TextPropertyNamespace::Style, "font-pitch-asian") => Some(Self::StyleFontPitchAsian),
            (TextPropertyNamespace::Style, "font-pitch-complex") => Some(Self::StyleFontPitchComplex),
            (TextPropertyNamespace::Style, "font-charset") => Some(Self::StyleFontCharset),
            (TextPropertyNamespace::Style, "font-charset-asian") => Some(Self::StyleFontCharsetAsian),
            (TextPropertyNamespace::Style, "font-charset-complex") => Some(Self::StyleFontCharsetComplex),
            (TextPropertyNamespace::Fo, "font-size") => Some(Self::FoFontSize),
            (TextPropertyNamespace::Style, "font-size-asian") => Some(Self::StyleFontSizeAsian),
            (TextPropertyNamespace::Style, "font-size-complex") => Some(Self::StyleFontSizeComplex),
            (TextPropertyNamespace::Style, "font-size-rel") => Some(Self::StyleFontSizeRel),
            (TextPropertyNamespace::Style, "font-size-rel-asian") => Some(Self::StyleFontSizeRelAsian),
            (TextPropertyNamespace::Style, "font-size-rel-complex") => Some(Self::StyleFontSizeRelComplex),
            (TextPropertyNamespace::Style, "script-type") => Some(Self::StyleScriptType),
            (TextPropertyNamespace::Fo, "letter-spacing") => Some(Self::FoLetterSpacing),
            (TextPropertyNamespace::Fo, "language") => Some(Self::FoLanguage),
            (TextPropertyNamespace::Style, "language-asian") => Some(Self::StyleLanguageAsian),
            (TextPropertyNamespace::Style, "language-complex") => Some(Self::StyleLanguageComplex),
            (TextPropertyNamespace::Fo, "country") => Some(Self::FoCountry),
            (TextPropertyNamespace::Style, "country-asian") => Some(Self::StyleCountryAsian),
            (TextPropertyNamespace::Style, "country-complex") => Some(Self::StyleCountryComplex),
            (TextPropertyNamespace::Fo, "script") => Some(Self::FoScript),
            (TextPropertyNamespace::Style, "script-asian") => Some(Self::StyleScriptAsian),
            (TextPropertyNamespace::Style, "script-complex") => Some(Self::StyleScriptComplex),
            (TextPropertyNamespace::Style, "rfc-language-tag") => Some(Self::StyleRfcLanguageTag),
            (TextPropertyNamespace::Style, "rfc-language-tag-asian") => Some(Self::StyleRfcLanguageTagAsian),
            (TextPropertyNamespace::Style, "rfc-language-tag-complex") => Some(Self::StyleRfcLanguageTagComplex),
            (TextPropertyNamespace::Fo, "font-style") => Some(Self::FoFontStyle),
            (TextPropertyNamespace::Style, "font-style-asian") => Some(Self::StyleFontStyleAsian),
            (TextPropertyNamespace::Style, "font-style-complex") => Some(Self::StyleFontStyleComplex),
            (TextPropertyNamespace::Style, "font-relief") => Some(Self::StyleFontRelief),
            (TextPropertyNamespace::Fo, "text-shadow") => Some(Self::FoTextShadow),
            (TextPropertyNamespace::Style, "text-underline-type") => Some(Self::StyleTextUnderlineType),
            (TextPropertyNamespace::Style, "text-underline-style") => Some(Self::StyleTextUnderlineStyle),
            (TextPropertyNamespace::Style, "text-underline-width") => Some(Self::StyleTextUnderlineWidth),
            (TextPropertyNamespace::Style, "text-underline-color") => Some(Self::StyleTextUnderlineColor),
            (TextPropertyNamespace::Style, "text-overline-type") => Some(Self::StyleTextOverlineType),
            (TextPropertyNamespace::Style, "text-overline-style") => Some(Self::StyleTextOverlineStyle),
            (TextPropertyNamespace::Style, "text-overline-width") => Some(Self::StyleTextOverlineWidth),
            (TextPropertyNamespace::Style, "text-overline-color") => Some(Self::StyleTextOverlineColor),
            (TextPropertyNamespace::Style, "text-overline-mode") => Some(Self::StyleTextOverlineMode),
            (TextPropertyNamespace::Fo, "font-weight") => Some(Self::FoFontWeight),
            (TextPropertyNamespace::Style, "font-weight-asian") => Some(Self::StyleFontWeightAsian),
            (TextPropertyNamespace::Style, "font-weight-complex") => Some(Self::StyleFontWeightComplex),
            (TextPropertyNamespace::Style, "text-underline-mode") => Some(Self::StyleTextUnderlineMode),
            (TextPropertyNamespace::Style, "text-line-through-mode") => Some(Self::StyleTextLineThroughMode),
            (TextPropertyNamespace::Style, "letter-kerning") => Some(Self::StyleLetterKerning),
            (TextPropertyNamespace::Style, "text-blinking") => Some(Self::StyleTextBlinking),
            (TextPropertyNamespace::Style, "text-combine") => Some(Self::StyleTextCombine),
            (TextPropertyNamespace::Style, "text-combine-start-char") => Some(Self::StyleTextCombineStartChar),
            (TextPropertyNamespace::Style, "text-combine-end-char") => Some(Self::StyleTextCombineEndChar),
            (TextPropertyNamespace::Style, "text-emphasize") => Some(Self::StyleTextEmphasize),
            (TextPropertyNamespace::Style, "text-scale") => Some(Self::StyleTextScale),
            (TextPropertyNamespace::Style, "text-rotation-angle") => Some(Self::StyleTextRotationAngle),
            (TextPropertyNamespace::Style, "text-rotation-scale") => Some(Self::StyleTextRotationScale),
            (TextPropertyNamespace::Fo, "hyphenate") => Some(Self::FoHyphenate),
            (TextPropertyNamespace::Fo, "hyphenation-remain-char-count") => Some(Self::FoHyphenationRemainCharCount),
            (TextPropertyNamespace::Fo, "hyphenation-push-char-count") => Some(Self::FoHyphenationPushCharCount),
            (TextPropertyNamespace::Text, "display") => Some(Self::TextDisplay),
            (TextPropertyNamespace::Text, "condition") => Some(Self::TextCondition),
            (TextPropertyNamespace::Fo, "background-color") => Some(Self::FoBackgroundColor),
            _ => None,
        }
    }

    pub(crate) fn parse_value(self, value: &str) -> Result<TextPropertyValue> {
        match self {
            Self::FoFontVariant => validate_spec(value, &[], &["fontVariant"], false, self),
            Self::FoTextTransform => validate_spec(value, &["none", "lowercase", "uppercase", "capitalize"], &[], false, self),
            Self::FoColor => validate_spec(value, &[], &["color"], false, self),
            Self::StyleUseWindowFontColor => validate_spec(value, &[], &["boolean"], false, self),
            Self::StyleTextOutline => validate_spec(value, &[], &["boolean"], false, self),
            Self::StyleTextLineThroughType => validate_spec(value, &[], &["lineType"], false, self),
            Self::StyleTextLineThroughStyle => validate_spec(value, &[], &["lineStyle"], false, self),
            Self::StyleTextLineThroughWidth => validate_spec(value, &[], &["lineWidth"], false, self),
            Self::StyleTextLineThroughColor => validate_spec(value, &["font-color"], &["color"], false, self),
            Self::StyleTextLineThroughText => validate_spec(value, &[], &["string"], false, self),
            Self::StyleTextLineThroughTextStyle => validate_spec(value, &[], &["styleNameRef"], false, self),
            Self::StyleTextPosition => validate_spec(value, &["super", "sub"], &["percent", "percent"], true, self),
            Self::StyleFontName => validate_spec(value, &[], &["string"], false, self),
            Self::StyleFontNameAsian => validate_spec(value, &[], &["string"], false, self),
            Self::StyleFontNameComplex => validate_spec(value, &[], &["string"], false, self),
            Self::FoFontFamily => validate_spec(value, &[], &["string"], false, self),
            Self::StyleFontFamilyAsian => validate_spec(value, &[], &["string"], false, self),
            Self::StyleFontFamilyComplex => validate_spec(value, &[], &["string"], false, self),
            Self::StyleFontFamilyGeneric => validate_spec(value, &[], &["fontFamilyGeneric"], false, self),
            Self::StyleFontFamilyGenericAsian => validate_spec(value, &[], &["fontFamilyGeneric"], false, self),
            Self::StyleFontFamilyGenericComplex => validate_spec(value, &[], &["fontFamilyGeneric"], false, self),
            Self::StyleFontStyleName => validate_spec(value, &[], &["string"], false, self),
            Self::StyleFontStyleNameAsian => validate_spec(value, &[], &["string"], false, self),
            Self::StyleFontStyleNameComplex => validate_spec(value, &[], &["string"], false, self),
            Self::StyleFontPitch => validate_spec(value, &[], &["fontPitch"], false, self),
            Self::StyleFontPitchAsian => validate_spec(value, &[], &["fontPitch"], false, self),
            Self::StyleFontPitchComplex => validate_spec(value, &[], &["fontPitch"], false, self),
            Self::StyleFontCharset => validate_spec(value, &[], &["textEncoding"], false, self),
            Self::StyleFontCharsetAsian => validate_spec(value, &[], &["textEncoding"], false, self),
            Self::StyleFontCharsetComplex => validate_spec(value, &[], &["textEncoding"], false, self),
            Self::FoFontSize => validate_spec(value, &[], &["positiveLength", "percent"], false, self),
            Self::StyleFontSizeAsian => validate_spec(value, &[], &["positiveLength", "percent"], false, self),
            Self::StyleFontSizeComplex => validate_spec(value, &[], &["positiveLength", "percent"], false, self),
            Self::StyleFontSizeRel => validate_spec(value, &[], &["length"], false, self),
            Self::StyleFontSizeRelAsian => validate_spec(value, &[], &["length"], false, self),
            Self::StyleFontSizeRelComplex => validate_spec(value, &[], &["length"], false, self),
            Self::StyleScriptType => validate_spec(value, &["latin", "asian", "complex", "ignore"], &[], false, self),
            Self::FoLetterSpacing => validate_spec(value, &["normal"], &["length"], false, self),
            Self::FoLanguage => validate_spec(value, &[], &["languageCode"], false, self),
            Self::StyleLanguageAsian => validate_spec(value, &[], &["languageCode"], false, self),
            Self::StyleLanguageComplex => validate_spec(value, &[], &["languageCode"], false, self),
            Self::FoCountry => validate_spec(value, &[], &["countryCode"], false, self),
            Self::StyleCountryAsian => validate_spec(value, &[], &["countryCode"], false, self),
            Self::StyleCountryComplex => validate_spec(value, &[], &["countryCode"], false, self),
            Self::FoScript => validate_spec(value, &[], &["scriptCode"], false, self),
            Self::StyleScriptAsian => validate_spec(value, &[], &["scriptCode"], false, self),
            Self::StyleScriptComplex => validate_spec(value, &[], &["scriptCode"], false, self),
            Self::StyleRfcLanguageTag => validate_spec(value, &[], &["language"], false, self),
            Self::StyleRfcLanguageTagAsian => validate_spec(value, &[], &["language"], false, self),
            Self::StyleRfcLanguageTagComplex => validate_spec(value, &[], &["language"], false, self),
            Self::FoFontStyle => validate_spec(value, &[], &["fontStyle"], false, self),
            Self::StyleFontStyleAsian => validate_spec(value, &[], &["fontStyle"], false, self),
            Self::StyleFontStyleComplex => validate_spec(value, &[], &["fontStyle"], false, self),
            Self::StyleFontRelief => validate_spec(value, &["none", "embossed", "engraved"], &[], false, self),
            Self::FoTextShadow => validate_spec(value, &[], &["shadowType"], false, self),
            Self::StyleTextUnderlineType => validate_spec(value, &[], &["lineType"], false, self),
            Self::StyleTextUnderlineStyle => validate_spec(value, &[], &["lineStyle"], false, self),
            Self::StyleTextUnderlineWidth => validate_spec(value, &[], &["lineWidth"], false, self),
            Self::StyleTextUnderlineColor => validate_spec(value, &["font-color"], &["color"], false, self),
            Self::StyleTextOverlineType => validate_spec(value, &[], &["lineType"], false, self),
            Self::StyleTextOverlineStyle => validate_spec(value, &[], &["lineStyle"], false, self),
            Self::StyleTextOverlineWidth => validate_spec(value, &[], &["lineWidth"], false, self),
            Self::StyleTextOverlineColor => validate_spec(value, &["font-color"], &["color"], false, self),
            Self::StyleTextOverlineMode => validate_spec(value, &[], &["lineMode"], false, self),
            Self::FoFontWeight => validate_spec(value, &[], &["fontWeight"], false, self),
            Self::StyleFontWeightAsian => validate_spec(value, &[], &["fontWeight"], false, self),
            Self::StyleFontWeightComplex => validate_spec(value, &[], &["fontWeight"], false, self),
            Self::StyleTextUnderlineMode => validate_spec(value, &[], &["lineMode"], false, self),
            Self::StyleTextLineThroughMode => validate_spec(value, &[], &["lineMode"], false, self),
            Self::StyleLetterKerning => validate_spec(value, &[], &["boolean"], false, self),
            Self::StyleTextBlinking => validate_spec(value, &[], &["boolean"], false, self),
            Self::StyleTextCombine => validate_spec(value, &["none", "letters", "lines"], &[], false, self),
            Self::StyleTextCombineStartChar => validate_spec(value, &[], &["character"], false, self),
            Self::StyleTextCombineEndChar => validate_spec(value, &[], &["character"], false, self),
            Self::StyleTextEmphasize => validate_spec(value, &["none", "none", "accent", "dot", "circle", "disc", "above", "below"], &[], true, self),
            Self::StyleTextScale => validate_spec(value, &[], &["percent"], false, self),
            Self::StyleTextRotationAngle => validate_spec(value, &[], &["angle"], false, self),
            Self::StyleTextRotationScale => validate_spec(value, &["fixed", "line-height"], &[], false, self),
            Self::FoHyphenate => validate_spec(value, &[], &["boolean"], false, self),
            Self::FoHyphenationRemainCharCount => validate_spec(value, &[], &["positiveInteger"], false, self),
            Self::FoHyphenationPushCharCount => validate_spec(value, &[], &["positiveInteger"], false, self),
            Self::TextDisplay => validate_spec(value, &["true"], &[], false, self),
            Self::TextCondition => validate_spec(value, &["none"], &[], false, self),
            Self::FoBackgroundColor => validate_spec(value, &["transparent"], &["color"], false, self),
        }
    }

    pub fn example(self) -> &'static str {
        match self {
            Self::FoFontVariant => "normal",
            Self::FoTextTransform => "none",
            Self::FoColor => "#102030",
            Self::StyleUseWindowFontColor => "true",
            Self::StyleTextOutline => "true",
            Self::StyleTextLineThroughType => "none",
            Self::StyleTextLineThroughStyle => "none",
            Self::StyleTextLineThroughWidth => "auto",
            Self::StyleTextLineThroughColor => "font-color",
            Self::StyleTextLineThroughText => "sample",
            Self::StyleTextLineThroughTextStyle => "name_1",
            Self::StyleTextPosition => "super",
            Self::StyleFontName => "sample",
            Self::StyleFontNameAsian => "sample",
            Self::StyleFontNameComplex => "sample",
            Self::FoFontFamily => "sample",
            Self::StyleFontFamilyAsian => "sample",
            Self::StyleFontFamilyComplex => "sample",
            Self::StyleFontFamilyGeneric => "roman",
            Self::StyleFontFamilyGenericAsian => "roman",
            Self::StyleFontFamilyGenericComplex => "roman",
            Self::StyleFontStyleName => "sample",
            Self::StyleFontStyleNameAsian => "sample",
            Self::StyleFontStyleNameComplex => "sample",
            Self::StyleFontPitch => "fixed",
            Self::StyleFontPitchAsian => "fixed",
            Self::StyleFontPitchComplex => "fixed",
            Self::StyleFontCharset => "UTF-8",
            Self::StyleFontCharsetAsian => "UTF-8",
            Self::StyleFontCharsetComplex => "UTF-8",
            Self::FoFontSize => ".1pt",
            Self::StyleFontSizeAsian => ".1pt",
            Self::StyleFontSizeComplex => ".1pt",
            Self::StyleFontSizeRel => "-0.5pt",
            Self::StyleFontSizeRelAsian => "-0.5pt",
            Self::StyleFontSizeRelComplex => "-0.5pt",
            Self::StyleScriptType => "latin",
            Self::FoLetterSpacing => "normal",
            Self::FoLanguage => "en",
            Self::StyleLanguageAsian => "en",
            Self::StyleLanguageComplex => "en",
            Self::FoCountry => "US",
            Self::StyleCountryAsian => "US",
            Self::StyleCountryComplex => "US",
            Self::FoScript => "Latn",
            Self::StyleScriptAsian => "Latn",
            Self::StyleScriptComplex => "Latn",
            Self::StyleRfcLanguageTag => "en-US",
            Self::StyleRfcLanguageTagAsian => "en-US",
            Self::StyleRfcLanguageTagComplex => "en-US",
            Self::FoFontStyle => "normal",
            Self::StyleFontStyleAsian => "normal",
            Self::StyleFontStyleComplex => "normal",
            Self::StyleFontRelief => "none",
            Self::FoTextShadow => "none",
            Self::StyleTextUnderlineType => "none",
            Self::StyleTextUnderlineStyle => "none",
            Self::StyleTextUnderlineWidth => "auto",
            Self::StyleTextUnderlineColor => "font-color",
            Self::StyleTextOverlineType => "none",
            Self::StyleTextOverlineStyle => "none",
            Self::StyleTextOverlineWidth => "auto",
            Self::StyleTextOverlineColor => "font-color",
            Self::StyleTextOverlineMode => "continuous",
            Self::FoFontWeight => "normal",
            Self::StyleFontWeightAsian => "normal",
            Self::StyleFontWeightComplex => "normal",
            Self::StyleTextUnderlineMode => "continuous",
            Self::StyleTextLineThroughMode => "continuous",
            Self::StyleLetterKerning => "true",
            Self::StyleTextBlinking => "true",
            Self::StyleTextCombine => "none",
            Self::StyleTextCombineStartChar => "x",
            Self::StyleTextCombineEndChar => "x",
            Self::StyleTextEmphasize => "none",
            Self::StyleTextScale => "-.5%",
            Self::StyleTextRotationAngle => "90",
            Self::StyleTextRotationScale => "fixed",
            Self::FoHyphenate => "true",
            Self::FoHyphenationRemainCharCount => "01",
            Self::FoHyphenationPushCharCount => "01",
            Self::TextDisplay => "true",
            Self::TextCondition => "none",
            Self::FoBackgroundColor => "transparent",
        }
    }
}

fn leaf_keywords(reference: &str) -> &'static [&'static str] {
    match reference {
        "boolean" => &["true", "false"],
        "fontFamilyGeneric" => &["roman", "swiss", "modern", "decorative", "script", "system"],
        "fontPitch" => &["fixed", "variable"],
        "fontStyle" => &["normal", "italic", "oblique"],
        "fontVariant" => &["normal", "small-caps"],
        "fontWeight" => &["normal", "bold", "100", "200", "300", "400", "500", "600", "700", "800", "900"],
        "lineMode" => &["continuous", "skip-white-space"],
        "lineStyle" => &["none", "solid", "dotted", "dash", "long-dash", "dot-dash", "dot-dot-dash", "wave"],
        "lineType" => &["none", "single", "double"],
        "lineWidth" => &["auto", "normal", "bold", "thin", "medium", "thick"],
        "shadowType" => &["none"],
        _ => &[],
    }
}

fn leaf_refs(reference: &str) -> &'static [&'static str] {
    match reference {
        "lineWidth" => &["positiveInteger", "percent", "positiveLength"],
        "shadowType" => &["string"],
        _ => &[],
    }
}

fn leaf_is_list(reference: &str) -> bool {
    match reference {
        _ => false,
    }
}
