[package]
name        = "litchi-pages"
description = "Pages semantic value models and document capabilities."
version.workspace      = true
edition.workspace      = true
authors.workspace      = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true

[dependencies]
litchi-iwa-core  = { workspace = true }
litchi-iwa-protos = { workspace = true }
litchi-iwa-text = { workspace = true }
prost           = { workspace = true }
thiserror       = { workspace = true }

[lints]
workspace = true
