//! Shared ownership for source-backed OPC payloads.

use std::mem::size_of;
use std::sync::Arc;

use litchi_core::Reservation;
use litchi_opc::{OpcError, PartData, SourceBackedPackage};

use crate::error::{Error, Result, allocation};

/// Storage occupied by one allocation's strong/weak Arc counters.
pub(crate) const ARC_HEADER_BYTES: usize = 2 * size_of::<usize>();

/// Fixed storage for an Arc-owned `Vec<u8>` payload (excluding its byte
/// buffer). The vector header lives in the Arc allocation.
pub(crate) const SOURCE_PAYLOAD_ARC_STORAGE_BYTES: usize = ARC_HEADER_BYTES + size_of::<Vec<u8>>();

/// Clone-shared outstanding memory/object reservations for generated source
/// payloads. Keeping this owner beside `SourcePayload` ensures opaque ranges
/// and other generic source aliases retain the same lease.
#[derive(Debug)]
pub(crate) struct RetainedBudgetHold {
    _memory: Option<Reservation>,
    _objects: Option<Reservation>,
}

/// Fixed storage charged alongside one clone-shared generated-state lease.
pub(crate) const RETAINED_BUDGET_HOLD_STORAGE_BYTES: usize =
    size_of::<RetainedBudgetHold>() + ARC_HEADER_BYTES;

pub(crate) fn retained_budget_hold(
    memory: Option<Reservation>,
    objects: Option<Reservation>,
) -> Arc<RetainedBudgetHold> {
    Arc::new(RetainedBudgetHold {
        _memory: memory,
        _objects: objects,
    })
}

/// Exact Part bytes without detaching a managed OPC reservation.
#[derive(Clone, Debug)]
pub(crate) enum SourcePayload {
    Managed(PartData),
    Owned(Arc<Vec<u8>>),
    /// Generated bytes whose memory/object reservation must follow every
    /// clone of this payload, including opaque XML ranges.
    OwnedBudgeted {
        bytes: Arc<Vec<u8>>,
        budget: Arc<RetainedBudgetHold>,
    },
}

impl SourcePayload {
    pub(crate) fn from_part_data(package: &SourceBackedPackage, data: PartData) -> Result<Self> {
        if package.cache_diagnostics().budget_managed {
            return Ok(Self::Managed(data));
        }
        Ok(Self::Owned(data.into_arc().map_err(Error::Package)?))
    }

    pub(crate) fn as_bytes(&self) -> &[u8] {
        match self {
            Self::Managed(data) => data.as_bytes(),
            Self::Owned(bytes) => bytes.as_slice(),
            Self::OwnedBudgeted { bytes, budget } => {
                let _keep_alive = budget;
                bytes.as_slice()
            },
        }
    }

    pub(crate) fn len(&self) -> usize {
        self.as_bytes().len()
    }

    /// Return an existing detached allocation without silently escaping a
    /// managed reservation.
    pub(crate) fn detached_arc(&self) -> Result<Arc<Vec<u8>>> {
        match self {
            Self::Managed(_) => Err(Error::Package(OpcError::ManagedPartDataArcEscape)),
            Self::Owned(bytes) => Ok(Arc::clone(bytes)),
            Self::OwnedBudgeted { .. } => Err(Error::Package(OpcError::ManagedPartDataArcEscape)),
        }
    }

    /// Explicitly copy a managed payload under a caller-supplied aggregate
    /// bound. Compatibility payloads keep sharing their allocation.
    pub(crate) fn materialized_arc(
        &self,
        maximum: usize,
        resource: &'static str,
    ) -> Result<Arc<Vec<u8>>> {
        if self.len() > maximum {
            return Err(Error::Invalid(format!(
                "{resource} exceeds the explicit materialization bound {maximum} bytes"
            )));
        }
        match self {
            Self::Managed(data) => copy_bytes(data.as_bytes(), resource),
            Self::Owned(bytes) => Ok(Arc::clone(bytes)),
            Self::OwnedBudgeted { bytes, .. } => copy_bytes(bytes, resource),
        }
    }

    /// Build an owned source handle, retaining the supplied generated-state
    /// lease with all aliases of the source bytes.
    pub(crate) fn owned_budgeted(
        bytes: Arc<Vec<u8>>,
        budget: Option<Arc<RetainedBudgetHold>>,
    ) -> Self {
        match budget {
            Some(budget) => Self::OwnedBudgeted { bytes, budget },
            None => Self::Owned(bytes),
        }
    }

    /// Retained model charge for this source handle's own Arc allocation.
    pub(crate) fn retained_storage_bytes(&self) -> usize {
        self.len()
            + match self {
                Self::Owned(_) | Self::OwnedBudgeted { .. } => SOURCE_PAYLOAD_ARC_STORAGE_BYTES,
                Self::Managed(_) => 0,
            }
    }
}

impl PartialEq for SourcePayload {
    fn eq(&self, other: &Self) -> bool {
        self.as_bytes() == other.as_bytes()
    }
}

impl Eq for SourcePayload {}

fn copy_bytes(bytes: &[u8], resource: &'static str) -> Result<Arc<Vec<u8>>> {
    let mut copy = Vec::new();
    copy.try_reserve_exact(bytes.len())
        .map_err(|source| allocation(resource, source))?;
    copy.extend_from_slice(bytes);
    Ok(Arc::new(copy))
}
