//! Layered XLSX package ownership for rich-value family parts.

mod load;
mod model;

pub use load::load;
pub use model::{
    Document, FEATURE_PROPERTY_BAG_CONTENT_TYPE, FEATURE_PROPERTY_BAG_RELATIONSHIP, Kind, Package,
    Part, RICH_STYLE_CONTENT_TYPE, RICH_STYLE_RELATIONSHIP, RICH_VALUE_ARRAY_CONTENT_TYPE,
    RICH_VALUE_ARRAY_RELATIONSHIP, RICH_VALUE_DATA_CONTENT_TYPE, RICH_VALUE_DATA_RELATIONSHIP,
    RICH_VALUE_RELATIONSHIPS_CONTENT_TYPE, RICH_VALUE_RELATIONSHIPS_RELATIONSHIP,
    RICH_VALUE_STRUCTURE_CONTENT_TYPE, RICH_VALUE_STRUCTURE_RELATIONSHIP,
    RICH_VALUE_TYPES_CONTENT_TYPE, RICH_VALUE_TYPES_RELATIONSHIP,
    SUPPORTING_PROPERTY_BAG_CONTENT_TYPE, SUPPORTING_PROPERTY_BAG_RELATIONSHIP,
    SUPPORTING_PROPERTY_BAG_STRUCTURE_CONTENT_TYPE, SUPPORTING_PROPERTY_BAG_STRUCTURE_RELATIONSHIP,
    WEB_IMAGE_CONTENT_TYPE, WEB_IMAGE_RELATIONSHIP,
};
