//! Exact-source standalone Numbers chart-data transactions.
//!
//! A chart grid is editable only when its drawable owns the inline data.  A
//! non-zero native mediator is admitted only when its resolved typed TN object
//! is the bounded empty dependency shell emitted for standalone charts;
//! table/formula graphs whose caches may be regenerated by Numbers after the
//! package is reopened are refused rather than receiving a misleading
//! grid-only mutation.  The selected chart payload is rewritten with the
//! shared lazy chart-data codec and published through the chart-arrangement
//! archive seam.

#![allow(
    clippy::cast_possible_truncation,
    clippy::cast_sign_loss,
    clippy::map_err_ignore,
    clippy::needless_pass_by_value,
    reason = "The package boundary converts bounded native arithmetic and redacts graph failures."
)]

use std::fmt;
use std::mem::size_of;
use std::sync::Arc;

use litchi_core::Position;
use litchi_iwa_archive::package::{OwnedExactArtifacts, SharedBytes};
use litchi_iwa_common::chart::data::ChartData;
use litchi_iwa_common::decode_varint_from_bytes;
use litchi_iwa_common::varint::encoded_len;
use litchi_iwa_protos::chart_data_codec as codec;

use super::Package;
use super::chart_arrangement::{
    self, ChartArrangementError, ChartBudget, ChartSelection, parse_wire_view_with_budget,
    physical_catalog, retain_payload_pair, rewrite_selected_chart_payload_with_previews,
    same_selection, select_chart_with_budget, selected_chart_payload, verify_locality,
};
use super::chart_data::{
    ChartDataError, map_arrangement_error, map_codec_limit, read_selected_chart_data,
};
use crate::{ChartSelector, SheetSelector};

const CHART_EXTENSION_FIELD: u32 = 10_000;
const CHART_MEDIATOR_FIELD: u32 = 8;
const REFERENCE_IDENTIFIER_FIELD: u32 = 1;
const CHART_MEDIATOR_MESSAGE_TYPE: u32 = 12_006;
const MEDIATOR_SUPER_FIELD: u32 = 1;
const MEDIATOR_ENTITY_ID_FIELD: u32 = 2;
const MEDIATOR_FORMULAS_FIELD: u32 = 3;
const MEDIATOR_COLUMNS_ARE_SERIES_FIELD: u32 = 4;
const MEDIATOR_REGISTERED_FIELD: u32 = 5;
const MEDIATOR_INFO_FIELD: u32 = 1;
const MEDIATOR_LOCAL_SERIES_FIELD: u32 = 2;
const MEDIATOR_REMOTE_SERIES_FIELD: u32 = 3;
const FORMULA_DATA_FIELD: u32 = 1;
const FORMULA_ROW_LABEL_FIELD: u32 = 3;
const FORMULA_COLUMN_LABEL_FIELD: u32 = 4;
const FORMULA_DIRECTION_FIELD: u32 = 5;
const FORMULA_ERROR_POS_FIELD: u32 = 6;
const FORMULA_ERROR_NEG_FIELD: u32 = 7;
const FORMULA_SCATTER_POS_FIELD: u32 = 8;
const FORMULA_SCATTER_NEG_FIELD: u32 = 9;
const FORMULA_SCHEME_FIELD: u32 = 10;

/// A staged standalone Numbers chart-data edit.
pub struct SheetChartDataEdit<'a> {
    source: &'a Package,
    selection: ChartSelection,
    before: Arc<ChartData>,
    after: Option<ChartData>,
}

impl fmt::Debug for SheetChartDataEdit<'_> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("SheetChartDataEdit")
            .field("sheet_position", &self.selection.sheet_position)
            .field("chart_position", &self.selection.chart_position)
            .field("before", &self.before)
            .field("after", &self.after())
            .finish_non_exhaustive()
    }
}

impl<'a> SheetChartDataEdit<'a> {
    fn new(
        source: &'a Package,
        selection: ChartSelection,
        before: ChartData,
        budget: &mut ChartBudget,
    ) -> Result<Self, ChartDataError> {
        let before = retain_chart_data_header(before, budget)?;
        Ok(Self {
            source,
            selection,
            after: None,
            before,
        })
    }

    /// Return the selected sheet source position.
    #[must_use]
    pub const fn sheet_position(&self) -> Position {
        self.selection.sheet_position
    }

    /// Return the selected chart source position within the sheet.
    #[must_use]
    pub const fn chart_position(&self) -> Position {
        self.selection.chart_position
    }

    /// Return the chart data observed when this edit began.
    #[must_use]
    pub fn before(&self) -> &ChartData {
        &self.before
    }

    /// Return the chart data staged for publication.
    #[must_use]
    pub fn after(&self) -> &ChartData {
        self.after.as_ref().unwrap_or(&self.before)
    }

    /// Stage a complete replacement of the finite numeric values.
    ///
    /// Row and column labels are retained from the source.  A replacement
    /// whose labels or dimensions differ is rejected by `commit` with a
    /// typed [`ChartDataError::ShapeMismatch`].
    #[must_use]
    pub fn set(mut self, data: ChartData) -> Self {
        self.after = Some(data);
        self
    }

    /// Validate and atomically publish the staged immutable candidate.
    pub fn commit(self) -> Result<SheetChartDataCommit, ChartDataError> {
        commit_edit(
            self.source,
            &self.selection,
            Arc::clone(&self.before),
            self.after,
        )
    }
}

/// Exact-source checked reversible standalone chart-data patch.
#[derive(Clone, PartialEq)]
pub struct SheetChartDataPatch {
    artifacts: OwnedExactArtifacts,
    selection: ChartSelection,
    before: Arc<ChartData>,
    after: Arc<ChartData>,
    source_payload: Option<Arc<[u8]>>,
    target_payload: Option<Arc<[u8]>>,
}

impl fmt::Debug for SheetChartDataPatch {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("SheetChartDataPatch")
            .field("sheet_position", &self.selection.sheet_position)
            .field("chart_position", &self.selection.chart_position)
            .field("before", &self.before)
            .field("after", &self.after)
            .finish_non_exhaustive()
    }
}

impl SheetChartDataPatch {
    /// Return the selected sheet source position.
    #[must_use]
    pub const fn sheet_position(&self) -> Position {
        self.selection.sheet_position
    }

    /// Return the selected chart source position within the sheet.
    #[must_use]
    pub const fn chart_position(&self) -> Position {
        self.selection.chart_position
    }

    /// Return the chart data required from the source package.
    #[must_use]
    pub fn before(&self) -> &ChartData {
        &self.before
    }

    /// Return the chart data produced by the target package.
    #[must_use]
    pub fn after(&self) -> &ChartData {
        &self.after
    }

    /// Return the source artifact's compact diagnostic fingerprint.
    #[must_use]
    pub const fn source_fingerprint(&self) -> u64 {
        self.artifacts.source_fingerprint()
    }

    /// Return the target artifact's compact diagnostic fingerprint.
    #[must_use]
    pub const fn target_fingerprint(&self) -> u64 {
        self.artifacts.target_fingerprint()
    }

    /// Return whether the patch preserves the exact source artifact.
    #[must_use]
    pub fn is_noop(&self) -> bool {
        self.before.bitwise_eq(&self.after) && self.artifacts.is_byte_noop()
    }

    /// Return the exact reversible patch from target back to source.
    #[must_use]
    pub fn inverse(&self) -> Self {
        Self {
            artifacts: self.artifacts.inverse(),
            selection: self.selection.clone(),
            before: Arc::clone(&self.after),
            after: Arc::clone(&self.before),
            source_payload: self.target_payload.clone(),
            target_payload: self.source_payload.clone(),
        }
    }
}

/// Compact evidence describing one chart-data publication.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct SheetChartDataDiagnostics {
    changed: bool,
    touched_components: usize,
    full_reparse_performed: bool,
    deleted_previews: usize,
}

impl SheetChartDataDiagnostics {
    const fn unchanged() -> Self {
        Self {
            changed: false,
            touched_components: 0,
            full_reparse_performed: false,
            deleted_previews: 0,
        }
    }

    const fn published(deleted_previews: usize) -> Self {
        Self {
            changed: true,
            touched_components: 1,
            full_reparse_performed: true,
            deleted_previews,
        }
    }

    /// Return whether the package bytes and semantic state changed.
    #[must_use]
    pub const fn changed(self) -> bool {
        self.changed
    }

    /// Return the number of rewritten IWA components.
    #[must_use]
    pub const fn touched_components(self) -> usize {
        self.touched_components
    }

    /// Return whether the candidate was reopened before publication.
    #[must_use]
    pub const fn full_reparse_performed(self) -> bool {
        self.full_reparse_performed
    }

    /// Return the number of canonical root previews invalidated by this
    /// publication.
    #[must_use]
    pub const fn deleted_previews(self) -> usize {
        self.deleted_previews
    }
}

/// Fully verified result of one immutable chart-data transaction.
#[must_use = "a Numbers chart-data commit contains the validated package snapshot"]
#[derive(Debug)]
pub struct SheetChartDataCommit {
    package: Package,
    patch: SheetChartDataPatch,
    diagnostics: SheetChartDataDiagnostics,
}

impl SheetChartDataCommit {
    /// Borrow the fully reopened package snapshot.
    #[must_use]
    pub const fn package(&self) -> &Package {
        &self.package
    }

    /// Consume this publication and return its package snapshot.
    #[must_use]
    pub fn into_package(self) -> Package {
        self.package
    }

    /// Borrow the reversible exact-source patch.
    #[must_use]
    pub const fn patch(&self) -> &SheetChartDataPatch {
        &self.patch
    }

    /// Borrow compact publication diagnostics.
    #[must_use]
    pub const fn diagnostics(&self) -> &SheetChartDataDiagnostics {
        &self.diagnostics
    }
}

/// Ergonomic aliases matching the other focused chart owners.
pub type ChartDataEdit<'a> = SheetChartDataEdit<'a>;
/// Ergonomic alias for [`SheetChartDataPatch`].
pub type ChartDataPatch = SheetChartDataPatch;
/// Ergonomic alias for [`SheetChartDataCommit`].
pub type ChartDataCommit = SheetChartDataCommit;
/// Ergonomic alias for [`SheetChartDataDiagnostics`].
pub type ChartDataDiagnostics = SheetChartDataDiagnostics;

impl Package {
    /// Begin an exact immutable edit of one standalone sheet chart's numeric
    /// grid through semantic selectors.
    pub fn edit_sheet_chart_data<'sheet>(
        &self,
        sheet_selector: impl Into<SheetSelector<'sheet>>,
        chart_selector: impl Into<ChartSelector>,
    ) -> Result<SheetChartDataEdit<'_>, ChartDataError> {
        let mut budget = ChartBudget::for_package(self).map_err(map_arrangement_error)?;
        let selection = select_chart_with_budget(
            self,
            sheet_selector.into(),
            chart_selector.into(),
            true,
            &mut budget,
        )
        .map_err(map_arrangement_error)?;
        ensure_standalone_chart(self, &selection, &mut budget).map_err(map_arrangement_error)?;
        let before = read_selected_chart_data(self, &selection, &mut budget)?;
        SheetChartDataEdit::new(self, selection, before, &mut budget)
    }

    /// Apply an exact-source checked standalone chart-data patch.
    pub fn apply_sheet_chart_data(
        &self,
        patch: &SheetChartDataPatch,
    ) -> Result<SheetChartDataCommit, ChartDataError> {
        let catalog = physical_catalog(self).map_err(map_arrangement_error)?;
        let source_owner = catalog.__source_owner();
        if !patch.artifacts.authorizes_owner(&source_owner) {
            return Err(ChartDataError::PatchConflict);
        }
        apply_patch_exact(self, patch, catalog)
    }
}

fn commit_edit(
    source: &Package,
    selection: &ChartSelection,
    before: Arc<ChartData>,
    after: Option<ChartData>,
) -> Result<SheetChartDataCommit, ChartDataError> {
    let catalog = physical_catalog(source).map_err(map_arrangement_error)?;
    let source_owner = catalog.__source_owner();
    commit_patch_parts(source, selection, before, None, after, source_owner)
}

fn apply_patch_exact(
    source: &Package,
    patch: &SheetChartDataPatch,
    catalog: &litchi_iwa_archive::SourceCatalog,
) -> Result<SheetChartDataCommit, ChartDataError> {
    let mut budget = ChartBudget::for_package(source).map_err(map_arrangement_error)?;
    budget
        .source(source.source_bytes().len())
        .map_err(map_arrangement_error)?;
    let current = select_chart_with_budget(
        source,
        SheetSelector::position(patch.selection.sheet_position),
        ChartSelector::position(patch.selection.chart_position),
        true,
        &mut budget,
    )
    .map_err(map_arrangement_error)?;
    if !same_selection(&current, &patch.selection) {
        return Err(ChartDataError::PatchConflict);
    }
    ensure_standalone_chart(source, &current, &mut budget).map_err(map_arrangement_error)?;
    let current_data = read_selected_chart_data(source, &current, &mut budget)?;
    let current_compare_work = chart_data_compare_work(&current_data, patch.before.as_ref())?;
    budget
        .preflight_work(current_compare_work)
        .map_err(map_arrangement_error)?;
    budget
        .work(current_compare_work)
        .map_err(map_arrangement_error)?;
    if !current_data.bitwise_eq(patch.before.as_ref()) {
        return Err(ChartDataError::PatchConflict);
    }
    if patch.is_noop() {
        return Ok(SheetChartDataCommit {
            package: source.snapshot(),
            patch: patch.clone(),
            diagnostics: SheetChartDataDiagnostics::unchanged(),
        });
    }
    if !catalog.source_is_exact() {
        return Err(ChartDataError::PatchConflict);
    }
    let target_owner = patch.artifacts.target_owner();
    budget
        .candidate_reopen(target_owner.len())
        .map_err(map_arrangement_error)?;
    let candidate = Package::from_source_owner_with_options(target_owner, source.state.options)
        .map_err(|_| ChartDataError::Verification)?;
    let candidate_catalog = physical_catalog(&candidate).map_err(map_arrangement_error)?;
    let selected = select_chart_with_budget(
        &candidate,
        SheetSelector::position(patch.selection.sheet_position),
        ChartSelector::position(patch.selection.chart_position),
        true,
        &mut budget,
    )
    .map_err(map_arrangement_error)?;
    if !same_selection(&selected, &patch.selection) {
        return Err(ChartDataError::Verification);
    }
    ensure_standalone_chart(&candidate, &selected, &mut budget).map_err(map_arrangement_error)?;
    let candidate_data = read_selected_chart_data(&candidate, &selected, &mut budget)?;
    let candidate_compare_work = chart_data_compare_work(&candidate_data, patch.after.as_ref())?;
    budget
        .preflight_work(candidate_compare_work)
        .map_err(map_arrangement_error)?;
    budget
        .work(candidate_compare_work)
        .map_err(map_arrangement_error)?;
    if !candidate_data.bitwise_eq(patch.after.as_ref()) {
        return Err(ChartDataError::Verification);
    }
    let target_payload = patch
        .target_payload
        .as_deref()
        .ok_or(ChartDataError::Verification)?;
    verify_locality(
        source,
        &candidate,
        &patch.selection,
        Some(target_payload),
        &mut budget,
    )
    .map_err(map_arrangement_error)?;
    let source_preview_count = chart_arrangement::root_preview_count(catalog, &mut budget)
        .map_err(map_arrangement_error)?;
    let target_preview_count =
        chart_arrangement::root_preview_count(candidate_catalog, &mut budget)
            .map_err(map_arrangement_error)?;
    let deleted_previews = source_preview_count.saturating_sub(target_preview_count);
    Ok(SheetChartDataCommit {
        package: candidate,
        patch: patch.clone(),
        diagnostics: SheetChartDataDiagnostics::published(deleted_previews),
    })
}

fn commit_patch_parts(
    source: &Package,
    selection: &ChartSelection,
    before: Arc<ChartData>,
    after: Option<Arc<ChartData>>,
    owned_after: Option<ChartData>,
    source_owner: SharedBytes,
) -> Result<SheetChartDataCommit, ChartDataError> {
    let mut budget = ChartBudget::for_package(source).map_err(map_arrangement_error)?;
    let after = match (after, owned_after) {
        (Some(after), None) => after,
        (None, Some(after)) => retain_chart_data(after, &mut budget)?,
        (None, None) => Arc::clone(&before),
        (Some(_), Some(_)) => return Err(ChartDataError::InvalidSource),
    };
    let axes_work = chart_data_compare_work(before.as_ref(), after.as_ref())?;
    budget
        .preflight_work(axes_work)
        .map_err(map_arrangement_error)?;
    budget.work(axes_work).map_err(map_arrangement_error)?;
    ensure_axes(before.as_ref(), after.as_ref())?;
    budget
        .source(source.source_bytes().len())
        .map_err(map_arrangement_error)?;
    let current = select_chart_with_budget(
        source,
        SheetSelector::position(selection.sheet_position),
        ChartSelector::position(selection.chart_position),
        true,
        &mut budget,
    )
    .map_err(map_arrangement_error)?;
    if !same_selection(&current, selection) {
        return Err(ChartDataError::PatchConflict);
    }
    ensure_standalone_chart(source, &current, &mut budget).map_err(map_arrangement_error)?;
    let current_data = read_selected_chart_data(source, &current, &mut budget)?;
    let current_compare_work = chart_data_compare_work(&current_data, before.as_ref())?;
    budget
        .preflight_work(current_compare_work)
        .map_err(map_arrangement_error)?;
    budget
        .work(current_compare_work)
        .map_err(map_arrangement_error)?;
    if !current_data.bitwise_eq(before.as_ref()) {
        return Err(ChartDataError::PatchConflict);
    }

    let requested_equal = before.bitwise_eq(after.as_ref());
    if requested_equal {
        charge_artifact_fingerprints(&mut budget, &source_owner, &source_owner)?;
        return Ok(SheetChartDataCommit {
            package: source.snapshot(),
            patch: SheetChartDataPatch {
                artifacts: OwnedExactArtifacts::new(source_owner.clone(), source_owner),
                selection: selection.clone(),
                before,
                after,
                source_payload: None,
                target_payload: None,
            },
            diagnostics: SheetChartDataDiagnostics::unchanged(),
        });
    }
    let source_catalog = physical_catalog(source).map_err(map_arrangement_error)?;
    if !source_catalog.source_is_exact() {
        return Err(ChartDataError::UnsupportedSource);
    }
    let candidate = rewrite_sheet_chart_data(source, selection, after.as_ref(), &mut budget)?;
    let target_catalog = physical_catalog(&candidate).map_err(map_arrangement_error)?;
    let target_owner = target_catalog.__source_owner();
    let selected = select_chart_with_budget(
        &candidate,
        SheetSelector::position(selection.sheet_position),
        ChartSelector::position(selection.chart_position),
        true,
        &mut budget,
    )
    .map_err(map_arrangement_error)?;
    if !same_selection(&selected, selection) {
        return Err(ChartDataError::Verification);
    }
    ensure_standalone_chart(&candidate, &selected, &mut budget).map_err(map_arrangement_error)?;
    let candidate_data = read_selected_chart_data(&candidate, &selected, &mut budget)?;
    let candidate_compare_work = chart_data_compare_work(&candidate_data, after.as_ref())?;
    budget
        .preflight_work(candidate_compare_work)
        .map_err(map_arrangement_error)?;
    budget
        .work(candidate_compare_work)
        .map_err(map_arrangement_error)?;
    if !candidate_data.bitwise_eq(after.as_ref()) {
        return Err(ChartDataError::Verification);
    }
    let source_payload =
        selected_chart_payload(source, selection).map_err(map_arrangement_error)?;
    let target_payload =
        selected_chart_payload(&candidate, &selected).map_err(map_arrangement_error)?;
    verify_locality(
        source,
        &candidate,
        selection,
        Some(target_payload),
        &mut budget,
    )
    .map_err(map_arrangement_error)?;
    let (source_payload, target_payload) =
        retain_payload_pair(source_payload, target_payload, &mut budget)
            .map_err(map_arrangement_error)?;
    let deleted_previews = chart_arrangement::root_preview_count(source_catalog, &mut budget)
        .and_then(|source_count| {
            chart_arrangement::root_preview_count(target_catalog, &mut budget)
                .map(|target_count| source_count.saturating_sub(target_count))
        })
        .map_err(map_arrangement_error)?;
    charge_artifact_fingerprints(&mut budget, &source_owner, &target_owner)?;
    Ok(SheetChartDataCommit {
        package: candidate,
        patch: SheetChartDataPatch {
            artifacts: OwnedExactArtifacts::new(source_owner, target_owner),
            selection: selection.clone(),
            before,
            after,
            source_payload: Some(source_payload),
            target_payload: Some(target_payload),
        },
        diagnostics: SheetChartDataDiagnostics::published(deleted_previews),
    })
}

fn charge_artifact_fingerprints(
    budget: &mut ChartBudget,
    source: &SharedBytes,
    target: &SharedBytes,
) -> Result<(), ChartDataError> {
    let target_work = if SharedBytes::ptr_eq(source, target) {
        0
    } else {
        target.len()
    };
    let fingerprint_work = source
        .len()
        .checked_add(target_work)
        .ok_or(ChartDataError::InvalidSource)?;
    budget
        .preflight_work(fingerprint_work)
        .map_err(map_arrangement_error)?;
    budget
        .work(fingerprint_work)
        .map_err(map_arrangement_error)?;
    Ok(())
}

fn rewrite_sheet_chart_data(
    source: &Package,
    selection: &ChartSelection,
    after: &ChartData,
    budget: &mut ChartBudget,
) -> Result<Package, ChartDataError> {
    let original = selected_chart_payload(source, selection).map_err(map_arrangement_error)?;
    let options = budget.data_codec_options().map_err(map_arrangement_error)?;
    let prepared = codec::prepare_chart_data_rewrite(original, after.values(), options)
        .map_err(map_rewrite_error)?;
    budget
        .data_codec_report(prepared.prepare_report())
        .map_err(map_arrangement_error)?;
    let requirements = prepared.execution_requirements();
    budget
        .data_codec_requirements(requirements)
        .map_err(map_arrangement_error)?;
    let rewritten = prepared
        .execute(requirements.exact_limits())
        .map_err(map_rewrite_error)?
        .into_output();
    rewrite_selected_chart_payload_with_previews(source, selection, rewritten, true, budget)
        .map_err(map_arrangement_error)
}

fn map_rewrite_error(error: codec::RewriteError) -> ChartDataError {
    match error {
        codec::RewriteError::Decode(error) => {
            map_codec_limit(&error).unwrap_or(ChartDataError::InvalidSource)
        },
        codec::RewriteError::Limit(limit) => {
            let (kind, observed, maximum) = match limit {
                codec::RewriteLimit::Bytes { observed, maximum }
                | codec::RewriteLimit::Output { observed, maximum } => (
                    super::chart_data::ChartDataLimitKind::WireBytes,
                    observed,
                    maximum,
                ),
                codec::RewriteLimit::Fields { observed, maximum } => (
                    super::chart_data::ChartDataLimitKind::WireFields,
                    observed,
                    maximum,
                ),
                codec::RewriteLimit::Work { observed, maximum }
                | codec::RewriteLimit::Scratch { observed, maximum } => (
                    super::chart_data::ChartDataLimitKind::WireWork,
                    observed,
                    maximum,
                ),
                codec::RewriteLimit::Nesting { observed, maximum } => (
                    super::chart_data::ChartDataLimitKind::WireNesting,
                    observed as usize,
                    maximum as usize,
                ),
                codec::RewriteLimit::Allocations { observed, maximum } => (
                    super::chart_data::ChartDataLimitKind::Allocations,
                    observed,
                    maximum,
                ),
                codec::RewriteLimit::Retained { observed, maximum } => (
                    super::chart_data::ChartDataLimitKind::RetainedBytes,
                    observed,
                    maximum,
                ),
                _ => return ChartDataError::InvalidSource,
            };
            ChartDataError::LimitExceeded {
                kind,
                observed: observed as u64,
                maximum: maximum as u64,
            }
        },
        codec::RewriteError::Shape { .. } => ChartDataError::ShapeMismatch,
        codec::RewriteError::NonFiniteNumeric { .. } => ChartDataError::InvalidSource,
        codec::RewriteError::Allocation { amount } => ChartDataError::Allocation { amount },
        codec::RewriteError::Projection => ChartDataError::InvalidSource,
    }
}

fn ensure_axes(before: &ChartData, after: &ChartData) -> Result<(), ChartDataError> {
    if before.row_names() != after.row_names() || before.column_names() != after.column_names() {
        return Err(ChartDataError::ShapeMismatch);
    }
    Ok(())
}

fn retain_chart_data_header(
    data: ChartData,
    budget: &mut ChartBudget,
) -> Result<Arc<ChartData>, ChartDataError> {
    budget
        .preflight_allocations(1)
        .map_err(map_arrangement_error)?;
    budget
        .preflight_retained(size_of::<ChartData>())
        .map_err(map_arrangement_error)?;
    let retained = Arc::new(data);
    budget.allocations(1).map_err(map_arrangement_error)?;
    budget
        .retained(size_of::<ChartData>())
        .map_err(map_arrangement_error)?;
    Ok(retained)
}

fn retain_chart_data(
    data: ChartData,
    budget: &mut ChartBudget,
) -> Result<Arc<ChartData>, ChartDataError> {
    let (retained, allocations, memory_work) = chart_data_memory(&data)?;
    budget
        .preflight_work(memory_work)
        .map_err(map_arrangement_error)?;
    budget.work(memory_work).map_err(map_arrangement_error)?;
    budget
        .preflight_allocations(allocations)
        .map_err(map_arrangement_error)?;
    budget
        .preflight_retained(retained)
        .map_err(map_arrangement_error)?;
    let owned = Arc::new(data);
    budget
        .allocations(allocations)
        .map_err(map_arrangement_error)?;
    budget.retained(retained).map_err(map_arrangement_error)?;
    Ok(owned)
}

fn chart_data_memory(data: &ChartData) -> Result<(usize, usize, usize), ChartDataError> {
    let row_labels = data.row_names().len();
    let column_labels = data.column_names().len();
    let label_count = row_labels
        .checked_add(column_labels)
        .ok_or(ChartDataError::InvalidSource)?;
    let label_text = data
        .row_names()
        .iter()
        .chain(data.column_names())
        .try_fold(0usize, |total, label| total.checked_add(label.len()))
        .ok_or(ChartDataError::InvalidSource)?;
    let row_count = data.values().len();
    let cell_count = row_count
        .checked_mul(data.column_names().len())
        .ok_or(ChartDataError::InvalidSource)?;
    let label_slots = label_count
        .checked_mul(size_of::<String>())
        .ok_or(ChartDataError::InvalidSource)?;
    let row_slots = row_count
        .checked_mul(size_of::<Vec<Option<f64>>>())
        .ok_or(ChartDataError::InvalidSource)?;
    let cell_slots = cell_count
        .checked_mul(size_of::<Option<f64>>())
        .ok_or(ChartDataError::InvalidSource)?;
    let retained = size_of::<ChartData>()
        .checked_add(label_slots)
        .and_then(|amount| amount.checked_add(label_text))
        .and_then(|amount| amount.checked_add(row_slots))
        .and_then(|amount| amount.checked_add(cell_slots))
        .ok_or(ChartDataError::InvalidSource)?;
    let string_allocations = data
        .row_names()
        .iter()
        .chain(data.column_names())
        .filter(|label| !label.is_empty())
        .count();
    let allocations = usize::from(row_labels != 0)
        .checked_add(usize::from(column_labels != 0))
        .and_then(|amount| amount.checked_add(string_allocations))
        .and_then(|amount| amount.checked_add(usize::from(row_count != 0)))
        .and_then(|amount| amount.checked_add(row_count))
        .and_then(|amount| amount.checked_add(1))
        .ok_or(ChartDataError::InvalidSource)?;
    let memory_work = row_labels
        .checked_add(column_labels)
        .and_then(|amount| amount.checked_add(row_count))
        .and_then(|amount| amount.checked_add(label_text))
        .ok_or(ChartDataError::InvalidSource)?;
    Ok((retained, allocations, memory_work))
}

fn chart_data_compare_work(left: &ChartData, right: &ChartData) -> Result<usize, ChartDataError> {
    let left_text = left
        .row_names()
        .iter()
        .chain(left.column_names())
        .try_fold(0usize, |total, label| total.checked_add(label.len()))
        .ok_or(ChartDataError::InvalidSource)?;
    let right_text = right
        .row_names()
        .iter()
        .chain(right.column_names())
        .try_fold(0usize, |total, label| total.checked_add(label.len()))
        .ok_or(ChartDataError::InvalidSource)?;
    let left_cells = left
        .values()
        .len()
        .checked_mul(left.column_names().len())
        .ok_or(ChartDataError::InvalidSource)?;
    let right_cells = right
        .values()
        .len()
        .checked_mul(right.column_names().len())
        .ok_or(ChartDataError::InvalidSource)?;
    left_text
        .checked_add(right_text)
        .and_then(|amount| amount.checked_add(left_cells))
        .and_then(|amount| amount.checked_add(right_cells))
        .and_then(|amount| amount.checked_add(left.values().len()))
        .and_then(|amount| amount.checked_add(right.values().len()))
        .ok_or(ChartDataError::InvalidSource)
}

fn ensure_standalone_chart(
    package: &Package,
    selection: &ChartSelection,
    budget: &mut ChartBudget,
) -> Result<(), ChartArrangementError> {
    let payload = selected_chart_payload(package, selection)?;
    let root = parse_wire_view_with_budget(payload, 1, budget)?;
    let mut chart_payload = None;
    for field in root.fields() {
        if field.number() != CHART_EXTENSION_FIELD {
            continue;
        }
        if chart_payload.is_some() || field.wire_type() != 2 {
            return Err(ChartArrangementError::InvalidSource);
        }
        field
            .validate_canonical_framing()
            .map_err(|_| ChartArrangementError::InvalidSource)?;
        chart_payload = Some(field.payload());
    }
    let chart_payload = chart_payload.ok_or(ChartArrangementError::InvalidSource)?;
    let chart = parse_wire_view_with_budget(chart_payload, 2, budget)?;
    let mut mediator = None;
    for field in chart.fields() {
        if field.number() != CHART_MEDIATOR_FIELD {
            continue;
        }
        if mediator.is_some() || field.wire_type() != 2 {
            return Err(ChartArrangementError::InvalidSource);
        }
        field
            .validate_canonical_framing()
            .map_err(|_| ChartArrangementError::InvalidSource)?;
        mediator = Some(field.payload());
    }
    let Some(mediator) = mediator else {
        return Ok(());
    };
    let reference = parse_wire_view_with_budget(mediator, 3, budget)?;
    let mut identifier = None;
    for field in reference.fields() {
        if field.number() != REFERENCE_IDENTIFIER_FIELD {
            continue;
        }
        if identifier.is_some() || field.wire_type() != 0 {
            return Err(ChartArrangementError::InvalidSource);
        }
        field
            .validate_canonical_key()
            .map_err(|_| ChartArrangementError::InvalidSource)?;
        let (value, consumed) = decode_varint_from_bytes(field.payload())
            .map_err(|_| ChartArrangementError::InvalidSource)?;
        if consumed != field.payload().len() || encoded_len(value) != consumed {
            return Err(ChartArrangementError::InvalidSource);
        }
        identifier = Some(value);
    }
    let Some(identifier) = identifier else {
        return Err(ChartArrangementError::InvalidSource);
    };
    if identifier == 0 {
        return Ok(());
    }
    budget.references(1)?;
    budget.work(package.state.index.lookup_work())?;
    let resolved = package
        .state
        .index
        .resolve_ref_id(&package.state.components, identifier)
        .map_err(chart_arrangement::map_package_error)?
        .ok_or(ChartArrangementError::UnsupportedDependency)?;
    let mediator_object = chart_arrangement::object_from_resolved(package, resolved)?;
    chart_arrangement::validate_message_metadata(mediator_object)?;
    let Some((message_index, message)) =
        chart_arrangement::unique_typed_message(mediator_object, CHART_MEDIATOR_MESSAGE_TYPE)?
    else {
        return Err(ChartArrangementError::UnsupportedDependency);
    };
    if message_index >= resolved.messages.len() {
        return Err(ChartArrangementError::InvalidSource);
    }
    validate_mediator_metadata(mediator_object, message_index, budget)?;
    validate_standalone_mediator(message.data.as_slice(), budget)?;
    Ok(())
}

fn validate_mediator_metadata(
    object: &litchi_iwa_core::ArchiveObject,
    message_index: usize,
    budget: &mut ChartBudget,
) -> Result<(), ChartArrangementError> {
    object
        .archive_info
        .message_infos
        .get(message_index)
        .ok_or(ChartArrangementError::InvalidSource)?;
    let mut metadata_work = 0usize;
    let mut references = 0usize;
    for info in &object.archive_info.message_infos {
        metadata_work = metadata_work
            .checked_add(info.field_infos.len())
            .and_then(|amount| amount.checked_add(info.object_references.len()))
            .and_then(|amount| amount.checked_add(info.data_references.len()))
            .ok_or(ChartArrangementError::InvalidSource)?;
        references = references
            .checked_add(info.object_references.len())
            .and_then(|amount| amount.checked_add(info.data_references.len()))
            .ok_or(ChartArrangementError::InvalidSource)?;
        for field in &info.field_infos {
            metadata_work = metadata_work
                .checked_add(field.object_references.len())
                .and_then(|amount| amount.checked_add(field.data_references.len()))
                .ok_or(ChartArrangementError::InvalidSource)?;
            references = references
                .checked_add(field.object_references.len())
                .and_then(|amount| amount.checked_add(field.data_references.len()))
                .ok_or(ChartArrangementError::InvalidSource)?;
        }
    }
    budget.preflight_work(metadata_work)?;
    budget.work(metadata_work)?;
    budget.references(references)?;
    if references != 0 {
        return Err(ChartArrangementError::UnsupportedDependency);
    }
    Ok(())
}

fn validate_standalone_mediator(
    payload: &[u8],
    budget: &mut ChartBudget,
) -> Result<(), ChartArrangementError> {
    let mediator = parse_wire_view_with_budget(payload, 1, budget)?;
    let mut super_payload = None;
    let mut entity_id = None;
    let mut formulas = None;
    let mut columns_are_series = false;
    let mut registered = false;
    for field in mediator.fields() {
        match field.number() {
            MEDIATOR_SUPER_FIELD => {
                if super_payload.is_some() || field.wire_type() != 2 {
                    return Err(ChartArrangementError::InvalidSource);
                }
                field
                    .validate_canonical_framing()
                    .map_err(|_| ChartArrangementError::InvalidSource)?;
                super_payload = Some(field.payload());
            },
            MEDIATOR_ENTITY_ID_FIELD => {
                if entity_id.is_some() || field.wire_type() != 2 {
                    return Err(ChartArrangementError::InvalidSource);
                }
                field
                    .validate_canonical_framing()
                    .map_err(|_| ChartArrangementError::InvalidSource)?;
                if field.payload().is_empty() || std::str::from_utf8(field.payload()).is_err() {
                    return Err(ChartArrangementError::InvalidSource);
                }
                entity_id = Some(field.payload());
            },
            MEDIATOR_FORMULAS_FIELD => {
                if formulas.is_some() || field.wire_type() != 2 {
                    return Err(ChartArrangementError::InvalidSource);
                }
                field
                    .validate_canonical_framing()
                    .map_err(|_| ChartArrangementError::InvalidSource)?;
                formulas = Some(field.payload());
            },
            MEDIATOR_COLUMNS_ARE_SERIES_FIELD | MEDIATOR_REGISTERED_FIELD => {
                if field.wire_type() != 0 {
                    return Err(ChartArrangementError::InvalidSource);
                }
                let seen = if field.number() == MEDIATOR_COLUMNS_ARE_SERIES_FIELD {
                    &mut columns_are_series
                } else {
                    &mut registered
                };
                if *seen {
                    return Err(ChartArrangementError::InvalidSource);
                }
                let value = scalar_varint(field)?;
                if value != 0 {
                    return Err(ChartArrangementError::UnsupportedDependency);
                }
                *seen = true;
            },
            _ => return Err(ChartArrangementError::UnsupportedDependency),
        }
    }
    let super_payload = super_payload.ok_or(ChartArrangementError::InvalidSource)?;
    if entity_id.is_none() {
        return Err(ChartArrangementError::InvalidSource);
    }
    validate_standalone_mediator_super(super_payload, budget)?;
    if let Some(formulas) = formulas {
        validate_standalone_formula_storage(formulas, budget)?;
    }
    Ok(())
}

fn validate_standalone_mediator_super(
    payload: &[u8],
    budget: &mut ChartBudget,
) -> Result<(), ChartArrangementError> {
    let super_view = parse_wire_view_with_budget(payload, 2, budget)?;
    let mut info = None;
    for field in super_view.fields() {
        match field.number() {
            MEDIATOR_INFO_FIELD => {
                if info.is_some() || field.wire_type() != 2 {
                    return Err(ChartArrangementError::InvalidSource);
                }
                field
                    .validate_canonical_framing()
                    .map_err(|_| ChartArrangementError::InvalidSource)?;
                info = Some(field.payload());
            },
            MEDIATOR_LOCAL_SERIES_FIELD | MEDIATOR_REMOTE_SERIES_FIELD => {
                if field.wire_type() != 0 {
                    return Err(ChartArrangementError::InvalidSource);
                }
                let _ = scalar_varint(field)?;
            },
            _ => return Err(ChartArrangementError::UnsupportedDependency),
        }
    }
    let Some(info) = info else {
        return Ok(());
    };
    let info_view = parse_wire_view_with_budget(info, 3, budget)?;
    let mut identifier = None;
    for field in info_view.fields() {
        if field.number() != REFERENCE_IDENTIFIER_FIELD || field.wire_type() != 0 {
            return Err(ChartArrangementError::InvalidSource);
        }
        if identifier.is_some() {
            return Err(ChartArrangementError::InvalidSource);
        }
        let value = scalar_varint(field)?;
        if value != 0 {
            return Err(ChartArrangementError::UnsupportedDependency);
        }
        identifier = Some(value);
    }
    if identifier != Some(0) {
        return Err(ChartArrangementError::InvalidSource);
    }
    Ok(())
}

fn validate_standalone_formula_storage(
    payload: &[u8],
    budget: &mut ChartBudget,
) -> Result<(), ChartArrangementError> {
    let formulas = parse_wire_view_with_budget(payload, 2, budget)?;
    let mut direction = false;
    let mut scheme = false;
    for field in formulas.fields() {
        match field.number() {
            FORMULA_DIRECTION_FIELD => {
                if direction || field.wire_type() != 0 {
                    return Err(ChartArrangementError::InvalidSource);
                }
                let _ = scalar_varint(field)?;
                direction = true;
            },
            FORMULA_SCHEME_FIELD => {
                if scheme || field.wire_type() != 0 {
                    return Err(ChartArrangementError::InvalidSource);
                }
                let _ = scalar_varint(field)?;
                scheme = true;
            },
            FORMULA_DATA_FIELD
            | FORMULA_ROW_LABEL_FIELD
            | FORMULA_COLUMN_LABEL_FIELD
            | FORMULA_ERROR_POS_FIELD
            | FORMULA_ERROR_NEG_FIELD
            | FORMULA_SCATTER_POS_FIELD
            | FORMULA_SCATTER_NEG_FIELD => {
                return Err(ChartArrangementError::UnsupportedDependency);
            },
            _ => return Err(ChartArrangementError::UnsupportedDependency),
        }
    }
    Ok(())
}

fn scalar_varint(
    field: litchi_iwa_common::wire::WireFieldView<'_>,
) -> Result<u64, ChartArrangementError> {
    field
        .validate_canonical_key()
        .map_err(|_| ChartArrangementError::InvalidSource)?;
    let (value, consumed) = decode_varint_from_bytes(field.payload())
        .map_err(|_| ChartArrangementError::InvalidSource)?;
    if consumed != field.payload().len() || encoded_len(value) != consumed {
        return Err(ChartArrangementError::InvalidSource);
    }
    Ok(value)
}
