use litchi_rtf::{RtfDocument,RtfWriter,TablePreferredWidthUnit,TextDirection};

fn write(document:&RtfDocument<'_>)->String{let mut output=Vec::new();RtfWriter::new(&mut output).write_document(document).unwrap();String::from_utf8(output).unwrap()}

#[test]
fn parses_logical_leading_trailing_widths_bidi_and_canonical_order(){let source=r#"{\rtf1\trowd\ltrrow\trftsWidth2\trwWidth5000\trftsWidthB3\trwWidthB240\trftsWidthA2\trwWidthA1250\cellx900\cellx2100\intbl A\cell B\cell\row\trowd\rtlrow\trftsWidthB2\trwWidthB750\trftsWidthA3\trwWidthA360\cellx1000\cellx2200\intbl C\cell D\cell\row}"#;let document=RtfDocument::parse(source).unwrap();let rows=document.tables()[0].rows();assert_eq!(rows[0].direction(),Some(TextDirection::LeftToRight));assert_eq!(rows[1].direction(),Some(TextDirection::RightToLeft));assert_eq!(rows[0].geometry().leading_invisible_width().unwrap().unit(),TablePreferredWidthUnit::Twips);assert_eq!(rows[0].geometry().leading_invisible_width().unwrap().value(),Some(240));assert_eq!(rows[0].geometry().trailing_invisible_width().unwrap().unit(),TablePreferredWidthUnit::Percent);assert_eq!(rows[1].geometry().leading_invisible_width().unwrap().unit(),TablePreferredWidthUnit::Percent);assert_eq!(rows[1].geometry().trailing_invisible_width().unwrap().value(),Some(360));assert_eq!(rows[0].cells().iter().map(|cell|cell.right_boundary()).collect::<Vec<_>>(),vec![Some(900),Some(2100)]);assert_eq!(rows[1].cells().iter().map(|cell|cell.right_boundary()).collect::<Vec<_>>(),vec![Some(1000),Some(2200)]);let first=write(&document);assert!(first.contains("\\trftsWidth2\\trwWidth5000\\trftsWidthB3\\trwWidthB240\\trftsWidthA2\\trwWidthA1250"));let second=write(&RtfDocument::parse(&first).unwrap());assert_eq!(first,second);}

#[test]
fn restores_groups_resets_trowd_and_normalizes_unit_only_defaults(){let source=r#"{\rtf1\trowd{\trftsWidthB3\trwWidthB100\trftsWidthA2\trwWidthA500}\cellx1000\intbl A\cell\row\trowd\trftsWidthB3\trftsWidthA2\cellx1100\intbl B\cell\row\trowd\cellx1200\intbl C\cell\row}"#;let document=RtfDocument::parse(source).unwrap();let rows=document.tables()[0].rows();assert_eq!(rows[0].geometry().leading_invisible_width(),None);assert_eq!(rows[0].geometry().trailing_invisible_width(),None);assert_eq!(rows[1].geometry().leading_invisible_width().unwrap().value(),Some(0));assert_eq!(rows[1].geometry().trailing_invisible_width().unwrap().value(),Some(0));assert_eq!(rows[2].geometry().leading_invisible_width(),None);assert_eq!(rows[2].geometry().trailing_invisible_width(),None);let written=write(&document);assert!(written.contains("\\trftsWidthB3\\trftsWidthA2\\cellx1100"));assert!(!written.contains("trwWidthB0"));assert!(!written.contains("trwWidthA0"));}

#[test]
fn applies_end_defined_nested_widths_and_owned_conversion(){let source=r#"{\rtf1\trowd\cellx5000\intbl\itap2 Inner\nestcell{\*\nesttableprops\itap2\trowd\rtlrow\trftsWidthB3\trwWidthB144\trftsWidthA2\trwWidthA625\cellx700\nestrow}\intbl\itap1\cell\row}"#;let document=RtfDocument::parse(source).unwrap();let nested=&document.tables()[0].rows()[0].cells()[0].nested_tables()[0].table.rows()[0];assert_eq!(nested.direction(),Some(TextDirection::RightToLeft));assert_eq!(nested.geometry().leading_invisible_width().unwrap().value(),Some(144));assert_eq!(nested.geometry().trailing_invisible_width().unwrap().value(),Some(625));assert_eq!(nested.cells()[0].right_boundary(),Some(700));let reparsed=RtfDocument::parse(&write(&document)).unwrap();let nested=&reparsed.tables()[0].rows()[0].cells()[0].nested_tables()[0].table.rows()[0];assert_eq!(nested.geometry().leading_invisible_width().unwrap().value(),Some(144));assert_eq!(nested.cells()[0].right_boundary(),Some(700));}

#[test]
fn rejects_malformed_duplicate_unpaired_and_out_of_range_controls(){for controls in ["trftsWidthB","trwWidthB","trftsWidthA","trwWidthA","trftsWidthB-1","trftsWidthA4","trwWidthB1","trwWidthA1","trftsWidthB3\\trwWidthB-1","trftsWidthA3\\trwWidthA31681","trftsWidthB2\\trwWidthB5001","trftsWidthA2\\trwWidthA-1","trftsWidthB0\\trwWidthB1","trftsWidthA1\\trwWidthA1","trftsWidthB3\\trftsWidthB3","trftsWidthA2\\trftsWidthA2","trftsWidthB3\\trwWidthB1\\trwWidthB2","trftsWidthA3\\trwWidthA1\\trwWidthA2"]{let source=format!("{{\\rtf1\\trowd\\{controls}\\cellx1000\\intbl X\\cell\\row}}");assert!(RtfDocument::parse(&source).is_err(),"accepted {controls}");}assert!(RtfDocument::parse(r#"{\rtf1\trowd\trftsWidthB2\trwWidthB5000\trftsWidthA3\trwWidthA31680\cellx31680\intbl X\cell\row}"#).is_ok());}

#[test]
fn parses_real_libreoffice_unit_only_invisible_widths(){let path=std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../3rdparty/libreoffice-core/sw/qa/extras/rtfexport/data/tdf108505_fieldCharFormat2.rtf");let fixture=std::fs::read_to_string(path).unwrap();let pair="\\trftsWidthB3\\trftsWidthA3";let marker=fixture.find(pair).unwrap();let start=fixture[..marker].rfind("\\trowd").unwrap();let end=marker+pair.len();let document=RtfDocument::parse(&format!("{{\\rtf1{}\\cellx1000\\intbl X\\cell\\row}}",&fixture[start..end])).unwrap();let row=&document.tables()[0].rows()[0];assert!(row.geometry().leading_invisible_width().is_some_and(|width|width.unit()==TablePreferredWidthUnit::Twips&&width.value()==Some(0)));assert!(row.geometry().trailing_invisible_width().is_some_and(|width|width.unit()==TablePreferredWidthUnit::Twips&&width.value()==Some(0)));let reparsed=RtfDocument::parse(&write(&document)).unwrap();assert!(reparsed.tables()[0].rows()[0].geometry().leading_invisible_width().is_some());}
