#![allow(
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::unwrap_used,
    reason = "The streaming ZIP64 fixtures use fixed, bounded test buffers."
)]

//! Public streaming ZIP64 Deflate coverage.
//!
//! The ordinary cases below retain only small archives.  The ignored case is
//! the one deliberately multi-gigabyte traversal: its input is generated by a
//! fixed-size zero reader and its output is checked through a counting sink,
//! so neither side allocates a buffer proportional to the logical member.

use crc32fast::Hasher;
use soapberry_zip::extra_fields::ExtraFieldId;
use soapberry_zip::office::{
    ArchiveLimits, ArchiveReader, StreamingArchiveLimits, StreamingArchiveWriter,
    StreamingLimitResource,
};
use soapberry_zip::{
    CompressionMethod, ErrorKind, RECOMMENDED_BUFFER_SIZE, ReaderAt, ZipArchive,
    ZipArchiveEntryWayfinder, ZipArchiveWriter, ZipLocator, ZipOperationAccounting,
};
use std::io::{self, Cursor, Read, Write};
use std::sync::Arc;

const ZIP32_MAX: u64 = u32::MAX as u64;
const HUGE_ZERO_RUN: u64 = ZIP32_MAX + 1;
const STREAM_BUFFER_SIZE: usize = 16 * 1024;

#[derive(Debug)]
struct ZeroReader {
    remaining: u64,
    max_request: usize,
}

impl ZeroReader {
    fn new(length: u64) -> Self {
        Self {
            remaining: length,
            max_request: 0,
        }
    }
}

impl Read for ZeroReader {
    fn read(&mut self, output: &mut [u8]) -> io::Result<usize> {
        if output.is_empty() || self.remaining == 0 {
            return Ok(0);
        }
        let amount = self.remaining.min(output.len() as u64) as usize;
        output[..amount].fill(0);
        self.remaining -= amount as u64;
        self.max_request = self.max_request.max(output.len());
        Ok(amount)
    }
}

#[derive(Debug)]
struct MixedReader {
    position: u64,
    length: u64,
}

impl MixedReader {
    fn new(length: u64) -> Self {
        Self {
            position: 0,
            length,
        }
    }
}

fn mixed_byte(position: u64) -> u8 {
    let block = (position / 4096) % 4;
    if block < 2 {
        0x5a
    } else {
        let mut value = position.wrapping_add(0x9e37_79b9_7f4a_7c15);
        value ^= value >> 30;
        value = value.wrapping_mul(0xbf58_476d_1ce4_e5b9);
        value ^= value >> 27;
        value = value.wrapping_mul(0x94d0_49bb_1331_11eb);
        value ^= value >> 31;
        value as u8
    }
}

impl Read for MixedReader {
    fn read(&mut self, output: &mut [u8]) -> io::Result<usize> {
        if output.is_empty() || self.position >= self.length {
            return Ok(0);
        }
        // A non-buffer-sized source makes the test exercise repeated reader
        // calls as well as repeated compressor writes.
        let amount = output
            .len()
            .min(7919)
            .min((self.length - self.position) as usize);
        for (index, byte) in output[..amount].iter_mut().enumerate() {
            *byte = mixed_byte(self.position + index as u64);
        }
        self.position += amount as u64;
        Ok(amount)
    }
}

#[derive(Debug)]
struct DigestSink {
    count: u64,
    crc: Hasher,
    max_write: usize,
}

impl DigestSink {
    fn new() -> Self {
        Self {
            count: 0,
            crc: Hasher::new(),
            max_write: 0,
        }
    }

    fn finish(self) -> (u64, u32, usize) {
        (self.count, self.crc.finalize(), self.max_write)
    }
}

impl Write for DigestSink {
    fn write(&mut self, input: &[u8]) -> io::Result<usize> {
        self.count = self
            .count
            .checked_add(input.len() as u64)
            .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData, "digest count overflow"))?;
        self.crc.update(input);
        self.max_write = self.max_write.max(input.len());
        Ok(input.len())
    }

    fn flush(&mut self) -> io::Result<()> {
        Ok(())
    }
}

#[derive(Debug)]
struct ShortSink {
    bytes: Vec<u8>,
    maximum: usize,
}

impl ShortSink {
    fn new(maximum: usize) -> Self {
        assert!(maximum > 0);
        Self {
            bytes: Vec::new(),
            maximum,
        }
    }
}

impl Write for ShortSink {
    fn write(&mut self, input: &[u8]) -> io::Result<usize> {
        let amount = input.len().min(self.maximum);
        self.bytes.extend_from_slice(&input[..amount]);
        Ok(amount)
    }

    fn flush(&mut self) -> io::Result<()> {
        Ok(())
    }
}

#[derive(Debug)]
struct FailingSink {
    bytes: Vec<u8>,
    fail_after: usize,
}

impl FailingSink {
    fn new(fail_after: usize) -> Self {
        Self {
            bytes: Vec::new(),
            fail_after,
        }
    }
}

impl Write for FailingSink {
    fn write(&mut self, input: &[u8]) -> io::Result<usize> {
        if self.bytes.len() >= self.fail_after {
            return Err(io::Error::new(io::ErrorKind::BrokenPipe, "sink failed"));
        }
        let amount = input.len().min(self.fail_after - self.bytes.len());
        self.bytes.extend_from_slice(&input[..amount]);
        Ok(amount)
    }

    fn flush(&mut self) -> io::Result<()> {
        Ok(())
    }
}

#[derive(Debug)]
struct BoundedVecSink {
    bytes: Vec<u8>,
    maximum: usize,
}

impl BoundedVecSink {
    fn new(maximum: usize) -> Self {
        Self {
            bytes: Vec::new(),
            maximum,
        }
    }
}

impl Write for BoundedVecSink {
    fn write(&mut self, input: &[u8]) -> io::Result<usize> {
        let next = self.bytes.len().checked_add(input.len()).ok_or_else(|| {
            io::Error::new(io::ErrorKind::InvalidInput, "bounded sink length overflow")
        })?;
        if next > self.maximum {
            return Err(io::Error::new(
                io::ErrorKind::Other,
                "bounded sink output ceiling reached",
            ));
        }
        self.bytes.extend_from_slice(input);
        Ok(input.len())
    }

    fn flush(&mut self) -> io::Result<()> {
        Ok(())
    }
}

/// A sink whose physical storage starts at a large logical offset.  The
/// prefix is represented by the sparse reader below rather than allocated.
#[derive(Debug)]
struct SparseSink {
    logical_length: u64,
    bytes: Vec<u8>,
}

impl SparseSink {
    fn new(prefix_length: u64) -> Self {
        Self {
            logical_length: prefix_length,
            bytes: Vec::new(),
        }
    }

    fn into_reader(self) -> SparseReader {
        SparseReader {
            prefix_length: self.logical_length - self.bytes.len() as u64,
            bytes: Arc::new(self.bytes),
        }
    }
}

impl Write for SparseSink {
    fn write(&mut self, input: &[u8]) -> io::Result<usize> {
        self.logical_length = self
            .logical_length
            .checked_add(input.len() as u64)
            .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidInput, "sparse length overflow"))?;
        self.bytes.extend_from_slice(input);
        Ok(input.len())
    }

    fn flush(&mut self) -> io::Result<()> {
        Ok(())
    }
}

#[derive(Debug, Clone)]
struct SparseReader {
    prefix_length: u64,
    bytes: Arc<Vec<u8>>,
}

impl SparseReader {
    fn length(&self) -> u64 {
        self.prefix_length + self.bytes.len() as u64
    }
}

impl ReaderAt for SparseReader {
    fn read_at(&self, output: &mut [u8], offset: u64) -> io::Result<usize> {
        if output.is_empty() || offset >= self.length() {
            return Ok(0);
        }
        let available = (self.length() - offset).min(output.len() as u64) as usize;
        let end = offset + available as u64;
        let mut cursor = offset;
        while cursor < end {
            let output_offset = (cursor - offset) as usize;
            if cursor < self.prefix_length {
                let amount = (self.prefix_length.min(end) - cursor) as usize;
                output[output_offset..output_offset + amount].fill(0);
                cursor += amount as u64;
                continue;
            }

            let source_offset = usize::try_from(cursor - self.prefix_length).map_err(|_| {
                io::Error::new(io::ErrorKind::InvalidData, "sparse source offset overflow")
            })?;
            if source_offset >= self.bytes.len() {
                return Err(io::Error::new(
                    io::ErrorKind::UnexpectedEof,
                    "sparse output framing is incomplete",
                ));
            }
            let amount = (self.bytes.len() - source_offset).min((end - cursor) as usize);
            output[output_offset..output_offset + amount]
                .copy_from_slice(&self.bytes[source_offset..source_offset + amount]);
            cursor += amount as u64;
        }
        Ok(available)
    }
}

fn crc32_zeroes(length: u64) -> u32 {
    if length == 0 {
        return Hasher::new().finalize();
    }

    let mut powers = Vec::new();
    let mut one = Hasher::new();
    one.update(&[0]);
    powers.push(one);
    let mut block_length = 1_u64;
    while block_length < length {
        let previous = powers.last().unwrap();
        let mut doubled = previous.clone();
        doubled.combine(previous);
        powers.push(doubled);
        block_length = block_length.saturating_mul(2);
    }

    let mut remaining = length;
    let mut bit = 0_usize;
    let mut combined = Hasher::new();
    while remaining != 0 {
        if remaining & 1 == 1 {
            combined.combine(&powers[bit]);
        }
        remaining >>= 1;
        bit += 1;
    }
    combined.finalize()
}

fn mixed_payload(length: usize) -> Vec<u8> {
    (0..length)
        .map(|position| mixed_byte(position as u64))
        .collect()
}

fn first_record<R: ReaderAt>(
    archive: &ZipArchive<R>,
) -> (
    ZipArchiveEntryWayfinder,
    bool,
    u64,
    u64,
    u32,
    CompressionMethod,
    Option<std::ops::Range<u64>>,
) {
    let mut buffer = vec![0_u8; RECOMMENDED_BUFFER_SIZE];
    let mut entries = archive.entries(&mut buffer);
    let record = entries.next_entry().unwrap().unwrap();
    let result = (
        record.wayfinder(),
        record.is_zip64(),
        record.local_header_offset(),
        record.uncompressed_size_hint(),
        record.crc32(),
        record.compression_method(),
        record.zip64_local_header_offset_range(),
    );
    assert!(entries.next_entry().unwrap().is_none());
    result
}

fn open_sparse(reader: SparseReader) -> ZipArchive<SparseReader> {
    let length = reader.length();
    let mut buffer = vec![0_u8; RECOMMENDED_BUFFER_SIZE];
    ZipLocator::new()
        .locate_in_reader(reader, &mut buffer, length)
        .map_err(|(_, error)| error)
        .unwrap()
}

fn verified_entry_bytes<R: ReaderAt>(
    archive: &ZipArchive<R>,
    wayfinder: ZipArchiveEntryWayfinder,
) -> Vec<u8> {
    let entry = archive.get_entry(wayfinder).unwrap();
    let reader = entry.reader();
    let decoder = flate2::read::DeflateDecoder::new(reader);
    let mut verifier = entry.verifying_reader(decoder);
    let mut output = Vec::new();
    verifier.read_to_end(&mut output).unwrap();
    output
}

#[test]
fn zero_crc_composition_matches_small_direct_hashes() {
    for length in [0_u64, 1, 2, 7, 32, 4096] {
        let direct = vec![0_u8; length as usize];
        assert_eq!(crc32_zeroes(length), soapberry_zip::crc32(&direct));
    }
}

#[test]
fn default_office_streaming_bytes_are_readable_and_accounted() {
    let payload = mixed_payload(128 * 1024 + 17);
    let mut writer = StreamingArchiveWriter::new();
    let mut accounting = ZipOperationAccounting::default();
    writer
        .write_deflated_stream_with_accounting(
            "content.xml",
            MixedReader::new(payload.len() as u64),
            &mut accounting,
        )
        .unwrap();
    let bytes = writer.finish_to_bytes().unwrap();

    assert!(!bytes.is_empty());
    assert!(accounting.generated_deflate_payload_bytes_emitted() > 0);
    assert_eq!(accounting.stored_payload_bytes_emitted(), 0);
    assert!(!ZipArchive::from_slice(&bytes).unwrap().is_zip64());

    let reader = ArchiveReader::new(&bytes).unwrap();
    assert_eq!(reader.file_names().collect::<Vec<_>>(), ["content.xml"]);
    assert_eq!(
        reader.metadata("content.xml").unwrap().uncompressed_size(),
        payload.len() as u64
    );
    assert_eq!(
        reader.metadata("content.xml").unwrap().compressed_size(),
        accounting.generated_deflate_payload_bytes_emitted()
    );
    let mut decoded = Vec::new();
    let mut read_accounting = ZipOperationAccounting::default();
    assert_eq!(
        reader
            .read_to_with_accounting("content.xml", &mut decoded, &mut read_accounting)
            .unwrap(),
        payload.len() as u64
    );
    assert_eq!(decoded, payload);
    assert_eq!(
        read_accounting.deflate_bytes_produced(),
        payload.len() as u64
    );
    assert_eq!(
        read_accounting.deflate_bytes_accepted(),
        payload.len() as u64
    );

    let raised_limits =
        StreamingArchiveLimits::new(4, 64, 4096).with_byte_limits(ZIP32_MAX, ZIP32_MAX, 1 << 20);
    let mut raised = StreamingArchiveWriter::with_limits(raised_limits);
    raised
        .write_deflated_stream("zip64.bin", Cursor::new(payload.as_slice()))
        .unwrap();
    let raised_bytes = raised.finish_to_bytes().unwrap();
    let raised_archive = ZipArchive::from_slice(&raised_bytes)
        .unwrap()
        .into_zip_archive();
    assert!(raised_archive.is_zip64());
    let (_, raised_record_zip64, _, _, _, _, _) = first_record(&raised_archive);
    assert!(raised_record_zip64);
}

#[test]
fn office_owned_entry_round_trips_through_short_borrowed_sink() {
    let payload = mixed_payload(96 * 1024 + 3);
    let mut sink = ShortSink::new(3);
    {
        let writer = StreamingArchiveWriter::with_writer(&mut sink);
        let mut entry = writer
            .start_entry("owned.bin", CompressionMethod::Deflate)
            .unwrap();
        for chunk in payload.chunks(137) {
            entry.write_all(chunk).unwrap();
        }
        let writer = entry.finish().unwrap();
        writer.finish().unwrap();
    }

    let reader = ArchiveReader::new(&sink.bytes).unwrap();
    let mut decoded = Vec::new();
    reader.read_to("owned.bin", &mut decoded).unwrap();
    assert_eq!(decoded, payload);
}

#[test]
fn explicit_zip64_borrowed_stream_has_64_bit_descriptor_and_reopens() {
    let payload = b"small explicit ZIP64 Deflate payload";
    let mut output = Cursor::new(Vec::new());
    let mut archive = ZipArchiveWriter::new(&mut output);
    let (mut entry, config) = archive
        .new_file("explicit.bin")
        .compression_method(CompressionMethod::Deflate)
        .zip64(true)
        .start()
        .unwrap();
    let encoder = flate2::write::DeflateEncoder::new(&mut entry, flate2::Compression::default());
    let mut data_writer = config.wrap(encoder);
    data_writer.write_all(payload).unwrap();
    let (encoder, descriptor) = data_writer.finish().unwrap();
    encoder.finish().unwrap();
    entry.finish(descriptor).unwrap();
    archive.finish().unwrap();

    let raw = output.into_inner();
    let archive = ZipArchive::from_slice(raw.as_slice()).unwrap();
    assert!(archive.is_zip64());
    let (wayfinder, compressed_size, central_directory_offset) = {
        let mut entries = archive.entries();
        let record = entries.next_entry().unwrap().unwrap();
        assert!(record.is_zip64());
        assert!(record.has_data_descriptor());
        assert_eq!(record.compression_method(), CompressionMethod::Deflate);
        assert_eq!(record.uncompressed_size_hint(), payload.len() as u64);
        assert_eq!(record.crc32(), soapberry_zip::crc32(payload));
        let zip64_extra = record
            .extra_fields()
            .find(|(id, _)| *id == ExtraFieldId::ZIP64)
            .map(|(_, data)| data.to_vec())
            .unwrap();
        assert_eq!(zip64_extra.len(), 16);
        assert_eq!(
            u64::from_le_bytes(zip64_extra[..8].try_into().unwrap()),
            payload.len() as u64
        );
        let result = (
            record.wayfinder(),
            record.compressed_size_hint(),
            record.central_directory_offset(),
        );
        assert!(entries.next_entry().unwrap().is_none());
        result
    };

    let descriptor_start = 30 + "explicit.bin".len() + 20 + compressed_size as usize;
    assert_eq!(
        &raw[descriptor_start..descriptor_start + 4],
        &0x0807_4b50_u32.to_le_bytes()
    );
    assert_eq!(central_directory_offset as usize - descriptor_start, 24);
    let archive = archive.into_zip_archive();
    assert_eq!(verified_entry_bytes(&archive, wayfinder), payload);
}

#[test]
fn generated_offset_promotes_at_below_at_and_above_zip32_boundary() {
    let payload = b"offset boundary";
    for offset in [ZIP32_MAX - 1, ZIP32_MAX, ZIP32_MAX + 1] {
        let sink = SparseSink::new(offset);
        let archive = ZipArchiveWriter::builder().with_offset(offset).build(sink);
        let mut entry = archive
            .start_file_owned("boundary.bin", CompressionMethod::Deflate)
            .unwrap();
        entry.write_all(payload).unwrap();
        let archive = entry.finish().unwrap();
        let sink = archive.finish().unwrap();
        assert!(sink.bytes.len() < 1024 * 1024);
        let reader = sink.into_reader();
        let archive = open_sparse(reader.clone());
        assert!(archive.is_zip64());

        let (wayfinder, record_zip64, local_offset, size, crc, method, offset_range) =
            first_record(&archive);
        assert_eq!(local_offset, offset);
        assert_eq!(size, payload.len() as u64);
        assert_eq!(crc, soapberry_zip::crc32(payload));
        assert_eq!(method, CompressionMethod::Deflate);
        if offset < ZIP32_MAX {
            assert!(!record_zip64);
            assert!(offset_range.is_none());
        } else {
            assert!(record_zip64);
            let range = offset_range.unwrap();
            assert_eq!(range.end - range.start, 8);
            let mut encoded = [0_u8; 8];
            reader.read_exact_at(&mut encoded, range.start).unwrap();
            assert_eq!(encoded, offset.to_le_bytes());
        }
        assert_eq!(verified_entry_bytes(&archive, wayfinder), payload);
    }
}

#[test]
fn owned_stream_reports_sink_failure_with_progress() {
    let name = "failure.bin";
    let mut sink = FailingSink::new(30 + name.len());
    let mut entry = StreamingArchiveWriter::with_writer(&mut sink)
        .start_entry(name, CompressionMethod::Store)
        .unwrap();
    let immediate = entry.write(b"payload").unwrap_err();
    assert_eq!(immediate.kind(), io::ErrorKind::BrokenPipe);
    assert!(entry.is_poisoned());

    let failure = match entry.finish_with_progress() {
        Ok(_) => panic!("poisoned entry unexpectedly finished"),
        Err(failure) => failure,
    };
    assert!(matches!(
        failure.error().kind(),
        ErrorKind::IO(_) | ErrorKind::Io(_)
    ));
    assert!(failure.progress().is_poisoned());
    assert!(failure.progress().output_bytes() <= sink.fail_after as u64);
}

#[test]
fn output_limit_boundary_is_reported_after_entry_publication() {
    let payload = b"output limit payload";
    let mut probe = StreamingArchiveWriter::new();
    probe
        .write_deflated_stream("payload.bin", Cursor::new(payload))
        .unwrap();
    let expected = probe.finish_to_bytes().unwrap();

    let exact_limits =
        StreamingArchiveLimits::new(4, 64, 64).with_byte_limits(1024, 1024, expected.len() as u64);
    let mut exact = StreamingArchiveWriter::with_limits(exact_limits);
    exact
        .write_deflated_stream("payload.bin", Cursor::new(payload))
        .unwrap();
    assert_eq!(exact.finish_to_bytes().unwrap(), expected);

    let short_limits = exact_limits.with_byte_limits(1024, 1024, expected.len() as u64 - 1);
    let mut short = StreamingArchiveWriter::with_limits(short_limits);
    short
        .write_deflated_stream("payload.bin", Cursor::new(payload))
        .unwrap();
    let failure = short.finish_with_progress().unwrap_err();
    assert_eq!(
        failure.limit().map(|limit| limit.resource()),
        Some(StreamingLimitResource::OutputBytes)
    );
    assert!(failure.progress().is_poisoned());
}

/// This is the single full ZIP64 traversal.  It is intentionally ignored in
/// normal test runs because it processes a four-GiB logical member, but it
/// retains only fixed-size input/output state and validates the complete
/// Deflate CRC.
#[test]
#[ignore = "bounded multi-gigabyte ZIP64 traversal; run explicitly"]
fn one_bounded_zero_reader_crosses_zip64_size_boundary() {
    let mut source = ZeroReader::new(HUGE_ZERO_RUN);
    let limits = StreamingArchiveLimits::new(4, 64, 4096).with_byte_limits(
        HUGE_ZERO_RUN,
        HUGE_ZERO_RUN,
        64 * 1024 * 1024,
    );
    let mut accounting = ZipOperationAccounting::default();
    let writer = StreamingArchiveWriter::with_writer_and_limits(
        BoundedVecSink::new(64 * 1024 * 1024),
        limits,
    );
    let mut writer = writer;
    writer
        .write_deflated_stream_with_accounting("zeros.bin", &mut source, &mut accounting)
        .unwrap();
    let (sink, progress) = writer.finish_with_progress().unwrap();
    assert_eq!(progress.output_bytes(), sink.bytes.len() as u64);
    assert_eq!(source.remaining, 0);
    assert!(source.max_request <= STREAM_BUFFER_SIZE);
    assert!(sink.bytes.len() < 64 * 1024 * 1024);

    let archive = ZipArchive::from_slice(&sink.bytes)
        .unwrap()
        .into_zip_archive();
    assert!(archive.is_zip64());
    let (wayfinder, record_zip64, local_offset, size, crc, method, _) = first_record(&archive);
    assert!(record_zip64);
    assert_eq!(local_offset, 0);
    assert_eq!(size, HUGE_ZERO_RUN);
    assert_eq!(crc, crc32_zeroes(HUGE_ZERO_RUN));
    assert_eq!(method, CompressionMethod::Deflate);
    assert_eq!(
        accounting.generated_deflate_payload_bytes_emitted(),
        wayfinder.compressed_size_hint()
    );

    let read_limits = ArchiveLimits {
        max_entry_size: HUGE_ZERO_RUN,
        max_total_size: HUGE_ZERO_RUN,
        ..ArchiveLimits::default()
    };
    let office = ArchiveReader::new_with_limits(&sink.bytes, read_limits).unwrap();
    assert_eq!(
        office.metadata("zeros.bin").unwrap().uncompressed_size(),
        HUGE_ZERO_RUN
    );
    let mut digest = DigestSink::new();
    let mut accounting = ZipOperationAccounting::default();
    assert_eq!(
        office
            .read_to_with_accounting("zeros.bin", &mut digest, &mut accounting)
            .unwrap(),
        HUGE_ZERO_RUN
    );
    let (count, crc_after_read, max_write) = digest.finish();
    assert_eq!(count, HUGE_ZERO_RUN);
    assert_eq!(crc_after_read, crc32_zeroes(HUGE_ZERO_RUN));
    assert!(max_write <= STREAM_BUFFER_SIZE);
    assert_eq!(accounting.deflate_bytes_produced(), HUGE_ZERO_RUN);
    assert_eq!(accounting.deflate_bytes_accepted(), HUGE_ZERO_RUN);
}
