use super::model::{Change, Flags, MAX_SNAPSHOT_BYTES, Metadata, Name};
use super::validation::{decode, encode_name, name_bytes};
use crate::prop::{Id, Prop, Props, Value};
use crate::{Error, Record, Result};

const IS_COMPLEX: u16 = 0x8000;
const PROPERTY_ID_MASK: u16 = 0x3FFF;
const MAX_PROPERTIES: usize = 0x0FFF;

/// Parses one Opt-family record as an immutable picture metadata snapshot.
pub fn parse<'data>(record: &Record<'data>) -> Result<Snapshot<'data>> {
    Snapshot::parse(record)
}

/// An immutable picture metadata snapshot backed by the caller's record bytes.
#[derive(Debug)]
pub struct Snapshot<'data> {
    record: Record<'data>,
    properties: Props<'data>,
}

impl<'data> Snapshot<'data> {
    /// Parses and validates picture-name metadata without copying source bytes.
    pub fn parse(record: &Record<'data>) -> Result<Self> {
        if record.data().len() > MAX_SNAPSHOT_BYTES {
            return Err(Error::MalformedProperties {
                reason: "picture snapshot exceeds the safe property-record bound",
            });
        }
        let properties = Props::parse(record)?;
        decode(&properties)?;
        Ok(Self {
            record: record.clone(),
            properties,
        })
    }

    /// Returns the exact parsed record view.
    #[must_use]
    pub const fn record(&self) -> &Record<'data> {
        &self.record
    }

    /// Returns the lossless property descriptors in source order.
    #[must_use]
    pub const fn properties(&self) -> &Props<'data> {
        &self.properties
    }

    /// Returns the typed picture-name projection, if this table contains one.
    pub fn metadata(&self) -> Result<Option<Metadata<'data>>> {
        decode(&self.properties)
    }

    /// Returns the exact source record bytes reconstructed from its checked
    /// header fields and borrowed body.
    pub fn encode(&self) -> Result<Vec<u8>> {
        encode_record(&self.record, entries(&self.properties)?)
    }

    /// Starts a non-mutating transaction over this snapshot.
    #[must_use]
    pub fn edit(&self) -> Edit<'_, 'data> {
        Edit {
            source: self,
            name: None,
            flags: None,
        }
    }
}

/// An owned committed picture snapshot.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Owned {
    bytes: Vec<u8>,
}

impl Owned {
    fn new(bytes: Vec<u8>) -> Result<Self> {
        if bytes.len() > MAX_SNAPSHOT_BYTES + 8 {
            return Err(Error::MalformedProperties {
                reason: "picture snapshot exceeds the safe property-record bound",
            });
        }
        let (record, consumed) = Record::parse(&bytes, 0)?;
        if consumed != bytes.len() {
            return Err(Error::TrailingData { offset: consumed });
        }
        Props::parse(&record)?;
        Ok(Self { bytes })
    }

    /// Returns the complete owned `OfficeArt` record, including its header.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8] {
        &self.bytes
    }

    /// Borrows the committed bytes as a fresh immutable semantic snapshot.
    pub fn snapshot(&self) -> Result<Snapshot<'_>> {
        let (record, consumed) = Record::parse(&self.bytes, 0)?;
        if consumed != self.bytes.len() {
            return Err(Error::TrailingData { offset: consumed });
        }
        Snapshot::parse(&record)
    }
}

/// The reversible semantic changes produced by one picture edit.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Patch {
    name: Option<Change<Vec<u8>>>,
    flags: Option<Change<u32>>,
}

impl Patch {
    /// Returns whether the edit changed neither modeled property.
    #[must_use]
    pub const fn is_empty(&self) -> bool {
        self.name.is_none() && self.flags.is_none()
    }

    /// Returns the exact before/after UTF-16 payload change, if any.
    #[must_use]
    pub fn name(&self) -> Option<&Change<Vec<u8>>> {
        self.name.as_ref()
    }

    /// Returns the before/after raw flags change, if any.
    #[must_use]
    pub fn flags(&self) -> Option<&Change<u32>> {
        self.flags.as_ref()
    }
}

/// A committed new snapshot paired with its reversible semantic patch.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Commit {
    snapshot: Owned,
    patch: Patch,
}

impl Commit {
    /// Returns the owned post-edit snapshot.
    #[must_use]
    pub const fn snapshot(&self) -> &Owned {
        &self.snapshot
    }

    /// Returns the reversible patch generated by the edit.
    #[must_use]
    pub const fn patch(&self) -> &Patch {
        &self.patch
    }

    /// Consumes the commit and returns its owned post-edit snapshot.
    #[must_use]
    pub fn into_snapshot(self) -> Owned {
        self.snapshot
    }
}

/// A transaction that edits only the typed picture-name family.
pub struct Edit<'snapshot, 'data> {
    source: &'snapshot Snapshot<'data>,
    name: Option<NameChange>,
    flags: Option<Flags>,
}

impl Edit<'_, '_> {
    /// Replaces the picture comment, file name, or URL with checked text.
    pub fn set_name(&mut self, text: &str) -> Result<&mut Self> {
        self.name = Some(NameChange::Set(encode_name(text)?));
        Ok(self)
    }

    /// Clears the picture name while preserving the property's source slot.
    pub fn clear_name(&mut self) -> &mut Self {
        self.name = Some(NameChange::Clear);
        self
    }

    /// Replaces the checked BLIP-name flags.
    pub fn set_flags(&mut self, flags: Flags) -> &mut Self {
        self.flags = Some(flags);
        self
    }

    /// Validates and commits the edit without mutating its source snapshot.
    pub fn commit(self) -> Result<Commit> {
        let before_name = self
            .source
            .properties
            .prop(Id::PictureFileName)
            .map(name_bytes)
            .transpose()?
            .flatten()
            .map(ToOwned::to_owned);
        let before_flags = self
            .source
            .properties
            .prop(Id::BlipFlags)
            .map(raw_flags)
            .transpose()?;
        let mut changed = entries(&self.source.properties)?;

        if let Some(change) = &self.name {
            apply_name(&mut changed, change)?;
        }
        if let Some(flags) = self.flags {
            apply_flags(&mut changed, flags);
        }

        let bytes = encode_record(&self.source.record, changed)?;
        let snapshot = Owned::new(bytes)?;
        let after = snapshot.snapshot()?.metadata()?;
        let after_name = after
            .and_then(Metadata::name)
            .map(Name::raw_bytes)
            .map(ToOwned::to_owned);
        let after_flags = after.map(|metadata| metadata.flags().raw());
        let patch = Patch {
            name: (before_name != after_name).then(|| Change::new(before_name, after_name)),
            flags: (before_flags != after_flags).then(|| Change::new(before_flags, after_flags)),
        };
        Ok(Commit { snapshot, patch })
    }
}

#[derive(Debug)]
enum NameChange {
    Set(Vec<u8>),
    Clear,
}

#[derive(Debug)]
struct Entry {
    opid: u16,
    value: i32,
    complex: Option<Vec<u8>>,
}

fn entries(properties: &Props<'_>) -> Result<Vec<Entry>> {
    properties
        .iter()
        .map(|property| {
            let complex = match property.value() {
                Value::Simple(_) => None,
                Value::Complex(bytes) => Some(bytes.to_vec()),
                Value::Array(array) => Some(array.raw_data().to_vec()),
            };
            Ok(Entry {
                opid: property.raw_opid(),
                value: property.raw_value(),
                complex,
            })
        })
        .collect()
}

fn apply_name(entries: &mut Vec<Entry>, change: &NameChange) -> Result<()> {
    let index = entries
        .iter()
        .position(|entry| entry.opid & PROPERTY_ID_MASK == Id::PictureFileName.raw());
    match (index, change) {
        (Some(index), NameChange::Set(bytes)) => {
            let entry = &mut entries[index];
            entry.opid |= IS_COMPLEX;
            entry.value =
                i32::try_from(bytes.len()).map_err(|_err| Error::MalformedProperties {
                    reason: "picture name exceeds the signed property length",
                })?;
            entry.complex = Some(bytes.clone());
        },
        (Some(index), NameChange::Clear) => {
            let entry = &mut entries[index];
            entry.opid &= !IS_COMPLEX;
            entry.value = 0;
            entry.complex = None;
        },
        (None, NameChange::Set(bytes)) => {
            let value = i32::try_from(bytes.len()).map_err(|_err| Error::MalformedProperties {
                reason: "picture name exceeds the signed property length",
            })?;
            entries.push(Entry {
                opid: IS_COMPLEX | Id::PictureFileName.raw(),
                value,
                complex: Some(bytes.clone()),
            });
        },
        (None, NameChange::Clear) => {},
    }
    Ok(())
}

fn apply_flags(entries: &mut Vec<Entry>, flags: Flags) {
    let index = entries
        .iter()
        .position(|entry| entry.opid & PROPERTY_ID_MASK == Id::BlipFlags.raw());
    if let Some(index) = index {
        let entry = &mut entries[index];
        entry.opid &= !IS_COMPLEX;
        entry.value = flags.raw() as i32;
        entry.complex = None;
    } else {
        entries.push(Entry {
            opid: Id::BlipFlags.raw(),
            value: flags.raw() as i32,
            complex: None,
        });
    }
}

fn raw_flags(property: &Prop<'_>) -> Result<u32> {
    if property.is_complex() {
        return Err(Error::MalformedProperties {
            reason: "picture flags must be a simple property",
        });
    }
    Ok(property.raw_value() as u32)
}

fn encode_record(record: &Record<'_>, entries: Vec<Entry>) -> Result<Vec<u8>> {
    if entries.len() > MAX_PROPERTIES {
        return Err(Error::MalformedProperties {
            reason: "picture property count exceeds the OfficeArt header bound",
        });
    }
    let header_len = entries
        .len()
        .checked_mul(6)
        .ok_or(Error::ArithmeticOverflow {
            context: "picture property header length",
        })?;
    let complex_len = entries.iter().try_fold(0_usize, |total, entry| {
        total.checked_add(entry.complex.as_ref().map_or(0, Vec::len))
    });
    let body_len = header_len
        .checked_add(complex_len.ok_or(Error::ArithmeticOverflow {
            context: "picture complex property length",
        })?)
        .ok_or(Error::ArithmeticOverflow {
            context: "picture property body length",
        })?;
    if body_len > MAX_SNAPSHOT_BYTES {
        return Err(Error::MalformedProperties {
            reason: "picture snapshot exceeds the safe property-record bound",
        });
    }
    let body_len_u32 = u32::try_from(body_len).map_err(|_err| Error::ArithmeticOverflow {
        context: "picture record body length",
    })?;
    let mut bytes = Vec::with_capacity(body_len + 8);
    let entry_count = u16::try_from(entries.len()).map_err(|_err| Error::MalformedProperties {
        reason: "picture property count exceeds the OfficeArt header bound",
    })?;
    let version_instance = (entry_count << 4) | u16::from(record.version());
    bytes.extend_from_slice(&version_instance.to_le_bytes());
    bytes.extend_from_slice(&record.raw_kind().to_le_bytes());
    bytes.extend_from_slice(&body_len_u32.to_le_bytes());
    for entry in &entries {
        bytes.extend_from_slice(&entry.opid.to_le_bytes());
        bytes.extend_from_slice(&entry.value.to_le_bytes());
    }
    for entry in entries {
        if let Some(complex) = entry.complex {
            bytes.extend_from_slice(&complex);
        }
    }
    Ok(bytes)
}
