#![no_main]

//! Strict, source-preserving fuzzing for the native Numbers Fraction
//! `FormatStructArchive` projection.
//!
//! Fraction is a deliberately narrow member of the shared format envelope:
//! native type 262 and one of the nine signed/positive denominator strategies
//! in `fraction_accuracy`.  A legacy field 20
//! (`requires_fraction_replacement`) is accepted only when it carries the
//! canonical false value; that exact source span is retained by rewrites and
//! never synthesized by a canonical writer.  This target keeps that family
//! boundary explicit while exercising source-preserving rewrites,
//! unknown-span retention, and finite resource contracts.

use std::{hint::black_box, sync::OnceLock};

use libfuzzer_sys::fuzz_target;
use litchi_iwa_protos::numbers_table_cell_fraction_format_codec as codec;

const MAX_INPUT_BYTES: usize = 64 * 1024;
const MAX_OUTPUT_BYTES: usize = 128 * 1024;
const MAX_FIELDS: usize = 16 * 1024;
const MAX_WORK_BYTES: usize = 512 * 1024;
const MAX_RECURSION: u32 = 64;

const ALL_ACCURACIES: &[u32] = &[
    codec::NATIVE_FRACTION_UP_TO_ONE_DIGIT,
    codec::NATIVE_FRACTION_UP_TO_TWO_DIGITS,
    codec::NATIVE_FRACTION_UP_TO_THREE_DIGITS,
    codec::NATIVE_FRACTION_HALVES,
    codec::NATIVE_FRACTION_QUARTERS,
    codec::NATIVE_FRACTION_EIGHTHS,
    codec::NATIVE_FRACTION_SIXTEENTHS,
    codec::NATIVE_FRACTION_TENTHS,
    codec::NATIVE_FRACTION_HUNDREDTHS,
];

const CANONICAL_UP_TO_ONE_DIGIT: &[u8] = &[0x08, 0x86, 0x02, 0x58, 0xff, 0xff, 0xff, 0xff, 0x0f];
const CANONICAL_UP_TO_TWO_DIGITS: &[u8] = &[0x08, 0x86, 0x02, 0x58, 0xfe, 0xff, 0xff, 0xff, 0x0f];
const CANONICAL_UP_TO_THREE_DIGITS: &[u8] = &[0x08, 0x86, 0x02, 0x58, 0xfd, 0xff, 0xff, 0xff, 0x0f];
const CANONICAL_HALVES: &[u8] = &[0x08, 0x86, 0x02, 0x58, 0x02];
const CANONICAL_QUARTERS: &[u8] = &[0x08, 0x86, 0x02, 0x58, 0x04];
const CANONICAL_EIGHTHS: &[u8] = &[0x08, 0x86, 0x02, 0x58, 0x08];
const CANONICAL_SIXTEENTHS: &[u8] = &[0x08, 0x86, 0x02, 0x58, 0x10];
const CANONICAL_TENTHS: &[u8] = &[0x08, 0x86, 0x02, 0x58, 0x0a];
const CANONICAL_HUNDREDTHS: &[u8] = &[0x08, 0x86, 0x02, 0x58, 0x64];

const CANONICAL_SOURCES: &[&[u8]] = &[
    CANONICAL_UP_TO_ONE_DIGIT,
    CANONICAL_UP_TO_TWO_DIGITS,
    CANONICAL_UP_TO_THREE_DIGITS,
    CANONICAL_HALVES,
    CANONICAL_QUARTERS,
    CANONICAL_EIGHTHS,
    CANONICAL_SIXTEENTHS,
    CANONICAL_TENTHS,
    CANONICAL_HUNDREDTHS,
];

const FIXED_CASES: &[&[u8]] = &[
    // Every valid native denominator strategy is a checked-in fixture as
    // well as being generated by exercise_all_accuracies below.
    CANONICAL_UP_TO_ONE_DIGIT,
    CANONICAL_UP_TO_TWO_DIGITS,
    CANONICAL_UP_TO_THREE_DIGITS,
    CANONICAL_HALVES,
    CANONICAL_QUARTERS,
    CANONICAL_EIGHTHS,
    CANONICAL_SIXTEENTHS,
    CANONICAL_TENTHS,
    CANONICAL_HUNDREDTHS,
    // Unknown scalar (with an intentionally overlong value), fixed64,
    // length-delimited, fixed32, and balanced group spans are interleaved
    // with selected Fraction fields.  All unknown bytes are source-owned.
    &[
        0x08, 0x86, 0x02, 0xa0, 0x06, 0x81, 0x00, 0xa1, 0x06, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06,
        0x07, 0x08, 0x58, 0x08, 0xa2, 0x06, 0x04, 0xde, 0xad, 0xbe, 0xef, 0xa5, 0x06, 0xca, 0xfe,
        0xba, 0xbe, 0xa3, 0x06, 0xa8, 0x06, 0x01, 0xa4, 0x06, 0x58, 0x10,
    ],
    // Repeated unknown spans and a length-delimited extension after the
    // selected fields exercise exact order and multiplicity preservation.
    &[
        0x08, 0x86, 0x02, 0xa0, 0x06, 0x81, 0x00, 0x58, 0x64, 0xaa, 0x06, 0x03, 0x01, 0x7f, 0x00,
        0xa0, 0x06, 0x81, 0x00,
    ],
    // Missing selected fields.
    &[0x58, 0x08],
    &[0x08, 0x86, 0x02],
    // Duplicate selected fields.
    &[0x08, 0x86, 0x02, 0x08, 0x86, 0x02, 0x58, 0x08],
    &[0x08, 0x86, 0x02, 0x58, 0x08, 0x58, 0x10],
    // Wrong wire types for both selected fields.
    &[0x0a, 0x01, 0x00, 0x58, 0x08],
    &[0x08, 0x86, 0x02, 0x5a, 0x01, 0x08],
    // Known selected keys and values encoded noncanonically.
    &[0x88, 0x00, 0x86, 0x02, 0x58, 0x08],
    &[0x08, 0x86, 0x82, 0x00, 0x58, 0x08],
    &[0x08, 0x86, 0x02, 0xd8, 0x00, 0x08],
    &[0x08, 0x86, 0x02, 0x58, 0x88, 0x00],
    // Invalid denominator values, including the old automatic sentinel.
    &[0x08, 0x86, 0x02, 0x58, 0x00],
    &[0x08, 0x86, 0x02, 0x58, 0x01],
    &[0x08, 0x86, 0x02, 0x58, 0x03],
    &[0x08, 0x86, 0x02, 0x58, 0x05],
    &[0x08, 0x86, 0x02, 0x58, 0x09],
    &[0x08, 0x86, 0x02, 0x58, 0x11],
    &[0x08, 0x86, 0x02, 0x58, 0xfd, 0x01],
    &[0x08, 0x86, 0x02, 0x58, 0xff, 0xff, 0xff, 0xff, 0x0e],
    // Field 20 is a legacy marker rather than a writer-owned Fraction value.
    // Canonical false is accepted and retained byte-for-byte; true, duplicate
    // presence, and the wrong wire type stay hot as refusals.
    &[0x08, 0x86, 0x02, 0x58, 0x08, 0xa0, 0x01, 0x00],
    &[0x08, 0x86, 0x02, 0x58, 0x08, 0xa0, 0x01, 0x01],
    &[
        0x08, 0x86, 0x02, 0x58, 0x08, 0xa0, 0x01, 0x00, 0xa0, 0x01, 0x00,
    ],
    &[0x08, 0x86, 0x02, 0x58, 0x08, 0xa2, 0x01, 0x01, 0x00],
    &[0x08, 0x86, 0x02, 0x58, 0x08, 0xa0, 0x01, 0x80, 0x00],
    &[0x08, 0x86, 0x02, 0x58, 0x08, 0xa0, 0x81, 0x00, 0x00],
    // Other known FormatStructArchive fields cannot be hidden behind the
    // Fraction route.
    &[0x08, 0x86, 0x02, 0x10, 0x02, 0x58, 0x08],
    &[0x08, 0x86, 0x02, 0x20, 0x00, 0x58, 0x08],
    &[0x08, 0x86, 0x02, 0x1a, 0x03, b'U', b'S', b'D', 0x58, 0x08],
    &[0x08, 0x86, 0x02, 0x40, 0x0a, 0x58, 0x08],
    // Number, Percentage, and Currency discriminators are wrong-family
    // payloads even when the Fraction field is otherwise well formed.
    &[0x08, 0x80, 0x02, 0x58, 0x08],
    &[0x08, 0x82, 0x02, 0x58, 0x08],
    &[0x08, 0x81, 0x02, 0x58, 0x08],
    // Unterminated, mismatched, and truncated groups remain malformed.
    &[0x08, 0x86, 0x02, 0x58, 0x08, 0xa3, 0x06, 0x08, 0x01],
    &[0x08, 0x86, 0x02, 0x58, 0x08, 0xa4, 0x06],
    &[0x08, 0x86, 0x02, 0x58, 0x08, 0xa3, 0x06, 0xac, 0x06],
];

fuzz_target!(|data: &[u8]| {
    let Some(source) = normalize_input(data) else {
        return;
    };
    exercise_source(&source, data);

    // Keep every denominator strategy and resource-boundary assertion
    // reachable even when a campaign starts with only malformed bytes.
    static FIXTURES: OnceLock<()> = OnceLock::new();
    FIXTURES.get_or_init(|| {
        for fixed in FIXED_CASES {
            exercise_source(fixed, b"fixed-fraction-format");
        }
        exercise_all_accuracies();
        exercise_canonical_writes();
        exercise_limit_guards();
    });
});

fn normalize_input(data: &[u8]) -> Option<Vec<u8>> {
    if let Some(encoded) = data.strip_prefix(b"hex:") {
        return decode_hex(encoded);
    }
    (data.len() <= MAX_INPUT_BYTES).then(|| data.to_vec())
}

fn decode_hex(encoded: &[u8]) -> Option<Vec<u8>> {
    if encoded.len() > MAX_INPUT_BYTES.saturating_mul(2).saturating_add(16) {
        return None;
    }
    let mut output = Vec::with_capacity(encoded.len() / 2);
    let mut high = None;
    for byte in encoded.iter().copied() {
        if byte.is_ascii_whitespace() {
            continue;
        }
        let nibble = hex_nibble(byte)?;
        if let Some(high_nibble) = high.take() {
            output.push((high_nibble << 4) | nibble);
            if output.len() > MAX_INPUT_BYTES {
                return None;
            }
        } else {
            high = Some(nibble);
        }
    }
    high.is_none().then_some(output)
}

fn hex_nibble(byte: u8) -> Option<u8> {
    match byte {
        b'0'..=b'9' => Some(byte - b'0'),
        b'a'..=b'f' => Some(byte - b'a' + 10),
        b'A'..=b'F' => Some(byte - b'A' + 10),
        _ => None,
    }
}

fn options(source: &[u8]) -> codec::DecodeOptions {
    codec::DecodeOptions::new(
        MAX_INPUT_BYTES.max(source.len()),
        MAX_OUTPUT_BYTES.max(source.len()),
        MAX_FIELDS,
        MAX_WORK_BYTES,
        MAX_RECURSION,
        0,
        0,
        0,
    )
}

fn exercise_source(source: &[u8], data: &[u8]) {
    let before = source.to_vec();
    let decode_options = options(source);
    let scalar = codec::decode_fraction_format(source, decode_options);
    assert_eq!(
        source,
        before.as_slice(),
        "scalar decode modified its source"
    );
    let reported = codec::decode_fraction_format_with_report(source, decode_options);
    assert_eq!(
        source,
        before.as_slice(),
        "reported decode modified its source"
    );

    match (scalar, reported) {
        (Ok(snapshot), Ok((reported_snapshot, report))) => {
            assert_eq!(snapshot, reported_snapshot);
            assert_snapshot(snapshot);
            assert_eq!(snapshot.raw(), source);
            assert_borrowed(source, snapshot.raw());
            assert_report(report, source.len());
            black_box((snapshot, report));
            exercise_rewrites(source, snapshot, data, &before);
            exercise_limit_profiles(source, report);
        },
        (Err(scalar_error), Err(reported_error)) => {
            assert_eq!(
                scalar_error.resource_limit(),
                reported_error.resource_limit(),
                "Fraction-format scalar/report error classifications disagree"
            );
            observe_error(scalar_error);
            observe_error(reported_error);
        },
        (scalar_result, reported_result) => panic!(
            "Fraction-format scalar/report disagreement: scalar={:?}, report={:?}",
            scalar_result.map(|snapshot| snapshot.fraction_accuracy()),
            reported_result.map(|(snapshot, _)| snapshot.fraction_accuracy())
        ),
    }

    assert_eq!(
        source,
        before.as_slice(),
        "Fraction-format probes modified source"
    );
}

fn assert_snapshot(snapshot: codec::FractionFormatSnapshot<'_>) {
    assert_eq!(snapshot.format_type(), codec::NATIVE_FRACTION_FORMAT_TYPE);
    assert!(ALL_ACCURACIES.contains(&snapshot.fraction_accuracy()));
    assert!(matches!(
        snapshot.requires_fraction_replacement(),
        None | Some(false)
    ));
}

fn assert_borrowed(source: &[u8], borrowed: &[u8]) {
    if borrowed.is_empty() {
        return;
    }
    let source_start = source.as_ptr() as usize;
    let source_end = source_start
        .checked_add(source.len())
        .expect("bounded source pointer range");
    let borrowed_start = borrowed.as_ptr() as usize;
    let borrowed_end = borrowed_start
        .checked_add(borrowed.len())
        .expect("bounded borrowed pointer range");
    assert!(
        borrowed_start >= source_start && borrowed_end <= source_end,
        "Fraction-format snapshot did not borrow from its source"
    );
}

fn assert_report(report: codec::DecodeReport, source_len: usize) {
    assert_eq!(report.input_bytes(), source_len);
    assert_eq!(report.output_bytes(), 0);
    assert!(report.input_bytes() <= MAX_INPUT_BYTES.max(source_len));
    assert!(report.output_bytes() <= MAX_OUTPUT_BYTES.max(source_len));
    assert!(report.fields() <= MAX_FIELDS);
    assert!(report.work_bytes() <= MAX_WORK_BYTES);
    assert!(report.max_depth() <= MAX_RECURSION);
    assert_eq!(report.references(), 0);
    assert_eq!(report.items(), 0);
    assert_eq!(report.text_bytes(), 0);
    assert_eq!(report.allocations(), 0);
}

fn exercise_rewrites(
    source: &[u8],
    snapshot: codec::FractionFormatSnapshot<'_>,
    data: &[u8],
    before: &[u8],
) {
    let preserved = codec::FractionFormatWrite::from_snapshot(snapshot);
    let requested = requested_write(data, snapshot);
    for write in [preserved, requested] {
        let prepared = match codec::prepare_fraction_format_rewrite(source, write, options(source))
        {
            Ok(prepared) => prepared,
            Err(error) => {
                observe_error(error);
                continue;
            },
        };
        let requirements = prepared.execution_requirements();
        let preparation = prepared.prepare_report();
        assert_eq!(preparation.output_bytes(), requirements.output_bytes());
        assert_eq!(preparation.fields(), requirements.fields());
        assert_eq!(preparation.work_bytes(), requirements.work_bytes());
        assert_eq!(preparation.max_depth(), requirements.max_depth());
        assert_eq!(preparation.allocations(), requirements.allocations());
        assert_eq!(preparation.retained_bytes(), requirements.retained_bytes());
        assert_eq!(preparation.scratch_bytes(), requirements.scratch_bytes());
        assert_eq!(source, before, "prepare modified its source");

        let output = prepared
            .execute(codec::RewriteExecutionLimits::exact(requirements))
            .unwrap_or_else(|error| panic!("exact Fraction-format replay failed: {error}"));
        assert_eq!(source, before, "execute modified its source");
        assert_eq!(output.bytes().len(), requirements.output_bytes());
        assert_eq!(output.report().output_bytes(), requirements.output_bytes());
        assert_eq!(output.report().fields(), requirements.fields());
        assert_eq!(output.report().work_bytes(), requirements.work_bytes());
        assert_eq!(output.report().max_depth(), requirements.max_depth());
        assert_eq!(output.report().allocations(), requirements.allocations());
        assert_eq!(
            output.report().retained_bytes(),
            requirements.retained_bytes()
        );
        assert_eq!(
            output.report().scratch_bytes(),
            requirements.scratch_bytes()
        );

        let readback = codec::decode_fraction_format(output.bytes(), options(output.bytes()))
            .unwrap_or_else(|error| panic!("Fraction-format candidate readback failed: {error}"));
        assert_eq!(codec::FractionFormatWrite::from_snapshot(readback), write);
        if source.windows(3).any(|window| window == [0xa0, 0x01, 0x00]) {
            assert_eq!(
                readback.requires_fraction_replacement(),
                Some(false),
                "canonical field-20=false was not observed"
            );
            assert!(
                output
                    .bytes()
                    .windows(3)
                    .any(|window| window == [0xa0, 0x01, 0x00]),
                "explicit field-20=false was not retained by rewrite"
            );
        } else {
            assert_eq!(
                readback.requires_fraction_replacement(),
                None,
                "canonical Fraction writer synthesized field-20=false"
            );
            assert!(
                !output
                    .bytes()
                    .windows(3)
                    .any(|window| window == [0xa0, 0x01, 0x00]),
                "Fraction rewrite synthesized field-20=false"
            );
        }
        if write == preserved {
            assert_eq!(output.bytes(), source, "preserving rewrite was not a no-op");
        }
        assert_known_unknown_spans_preserved(source, output.bytes());

        let one_shot = codec::rewrite_fraction_format(source, write, options(source))
            .unwrap_or_else(|error| panic!("one-shot Fraction-format rewrite failed: {error}"));
        assert_eq!(one_shot.bytes(), output.bytes());
        assert_eq!(one_shot.report(), output.report());
        exercise_limit_failures(source, write, prepared, requirements);
        black_box(output);
    }
}

fn requested_write(
    data: &[u8],
    snapshot: codec::FractionFormatSnapshot<'_>,
) -> codec::FractionFormatWrite {
    let accuracy = match data.first().copied().unwrap_or_default() % 4 {
        0 => snapshot.fraction_accuracy(),
        1 => codec::NATIVE_FRACTION_UP_TO_ONE_DIGIT,
        2 => codec::NATIVE_FRACTION_HUNDREDTHS,
        _ => {
            let index =
                usize::from(data.get(1).copied().unwrap_or_default()) % ALL_ACCURACIES.len();
            ALL_ACCURACIES
                .get(index)
                .copied()
                .unwrap_or(codec::NATIVE_FRACTION_EIGHTHS)
        },
    };
    write_for_accuracy(accuracy)
}

fn write_for_accuracy(accuracy: u32) -> codec::FractionFormatWrite {
    let source = canonical_source(accuracy);
    let snapshot = codec::decode_fraction_format(source, options(source))
        .unwrap_or_else(|error| panic!("valid Fraction accuracy fixture rejected: {error}"));
    codec::FractionFormatWrite::from_snapshot(snapshot)
}

fn canonical_source(accuracy: u32) -> &'static [u8] {
    let index = ALL_ACCURACIES
        .iter()
        .position(|candidate| *candidate == accuracy)
        .unwrap_or_else(|| panic!("requested invalid Fraction accuracy {accuracy}"));
    CANONICAL_SOURCES[index]
}

fn assert_known_unknown_spans_preserved(source: &[u8], candidate: &[u8]) {
    let source_shape = parse_root_shape(source)
        .expect("successful Fraction-format source must have valid root wire records");
    let candidate_shape = parse_root_shape(candidate)
        .expect("rewritten Fraction-format candidate must have valid root wire records");

    // Compare parsed records, not arbitrary byte windows.  Selected values may
    // change, but every unknown root span must retain its exact bytes,
    // relative order, and multiplicity.
    assert_eq!(
        source_shape, candidate_shape,
        "Fraction-format rewrite changed unknown-span order or multiplicity"
    );
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum RootField<'source> {
    Selected(u32),
    Unknown(&'source [u8]),
}

fn parse_root_shape(source: &[u8]) -> Option<Vec<RootField<'_>>> {
    let mut fields = Vec::new();
    let mut offset = 0usize;
    while offset < source.len() {
        let start = offset;
        let (number, wire, key_len) = read_wire_key(source, offset)?;
        offset = offset.checked_add(key_len)?;
        offset = skip_wire_value(source, offset, wire, number, 0)?;
        let raw = source.get(start..offset)?;
        let field = match number {
            1 | 11 => RootField::Selected(number),
            _ => RootField::Unknown(raw),
        };
        fields.push(field);
    }
    Some(fields)
}

fn read_wire_key(source: &[u8], offset: usize) -> Option<(u32, u8, usize)> {
    let (key, consumed, canonical) = read_wire_varint(source, offset)?;
    if !canonical {
        return None;
    }
    let number = u32::try_from(key >> 3).ok()?;
    let wire = u8::try_from(key & 7).ok()?;
    (number != 0 && number <= 0x1fff_ffff).then_some((number, wire, consumed))
}

fn skip_wire_value(
    source: &[u8],
    offset: usize,
    wire: u8,
    field_number: u32,
    depth: usize,
) -> Option<usize> {
    match wire {
        // Unknown scalar values intentionally allow relaxed varints, matching
        // the production source-preservation path.
        0 => {
            let (_, consumed, _) = read_wire_varint(source, offset)?;
            offset.checked_add(consumed)
        },
        1 => offset.checked_add(8).filter(|end| *end <= source.len()),
        2 => {
            let (length, consumed, canonical) = read_wire_varint(source, offset)?;
            if !canonical {
                return None;
            }
            let payload_start = offset.checked_add(consumed)?;
            let payload_len = usize::try_from(length).ok()?;
            payload_start
                .checked_add(payload_len)
                .filter(|end| *end <= source.len())
        },
        3 => skip_wire_group(source, offset, field_number, depth),
        // End-group records are consumed by skip_wire_group and are invalid at
        // the root or as a value of another non-group field.
        4 => None,
        5 => offset.checked_add(4).filter(|end| *end <= source.len()),
        _ => None,
    }
}

fn skip_wire_group(
    source: &[u8],
    mut offset: usize,
    root_number: u32,
    depth: usize,
) -> Option<usize> {
    if depth >= MAX_RECURSION as usize {
        return None;
    }
    let mut stack = vec![root_number];
    while offset < source.len() {
        let (number, wire, key_len) = read_wire_key(source, offset)?;
        offset = offset.checked_add(key_len)?;
        match wire {
            3 => {
                if stack.len() >= MAX_RECURSION as usize {
                    return None;
                }
                stack.push(number);
            },
            4 => {
                if stack.pop()? != number {
                    return None;
                }
                if stack.is_empty() {
                    return Some(offset);
                }
            },
            _ => {
                offset = skip_wire_value(source, offset, wire, number, depth + stack.len())?;
            },
        }
    }
    None
}

fn read_wire_varint(source: &[u8], offset: usize) -> Option<(u64, usize, bool)> {
    let mut value = 0u64;
    let mut shift = 0u32;
    let mut cursor = offset;
    while cursor < source.len() && cursor.checked_sub(offset)? < 10 {
        let byte = source[cursor];
        let part = u64::from(byte & 0x7f);
        if shift == 63 && part > 1 {
            return None;
        }
        value |= part.checked_shl(shift)?;
        cursor += 1;
        if byte & 0x80 == 0 {
            let consumed = cursor.checked_sub(offset)?;
            return Some((value, consumed, encoded_wire_varint_len(value) == consumed));
        }
        shift += 7;
    }
    None
}

const fn encoded_wire_varint_len(value: u64) -> usize {
    if value == 0 {
        1
    } else {
        (64usize - value.leading_zeros() as usize).div_ceil(7)
    }
}

fn exercise_limit_failures(
    source: &[u8],
    write: codec::FractionFormatWrite,
    prepared: codec::PreparedFractionFormatRewrite<'_>,
    requirements: codec::RewriteExecutionRequirements,
) {
    let exact = codec::RewriteExecutionLimits::exact(requirements);
    let probes = [
        (requirements.output_bytes() > 0)
            .then(|| exact.with_output_bytes(requirements.output_bytes().saturating_sub(1))),
        (requirements.fields() > 0)
            .then(|| exact.with_fields(requirements.fields().saturating_sub(1))),
        (requirements.work_bytes() > 0)
            .then(|| exact.with_work_bytes(requirements.work_bytes().saturating_sub(1))),
        (requirements.max_depth() > 0)
            .then(|| exact.with_max_depth(requirements.max_depth().saturating_sub(1))),
        (requirements.allocations() > 0)
            .then(|| exact.with_allocations(requirements.allocations().saturating_sub(1))),
        (requirements.retained_bytes() > 0)
            .then(|| exact.with_retained_bytes(requirements.retained_bytes().saturating_sub(1))),
    ];
    for limits in probes.into_iter().flatten() {
        let result = prepared.execute(limits);
        assert!(
            result.is_err(),
            "Fraction-format rewrite accepted a strict limit"
        );
        if let Err(error) = result {
            black_box(error.resource_limit());
            observe_error(error);
        }
    }

    // Re-preparation is intentionally part of this probe: the source and
    // request remain reusable after every failed execution.
    let replay = codec::rewrite_fraction_format(source, write, options(source));
    if let Err(error) = replay {
        observe_error(error);
    }
}

fn exercise_limit_profiles(source: &[u8], report: codec::DecodeReport) {
    if source.is_empty() {
        return;
    }
    let input_limited = codec::DecodeOptions::new(
        source.len() - 1,
        MAX_OUTPUT_BYTES,
        MAX_FIELDS,
        MAX_WORK_BYTES,
        MAX_RECURSION,
        0,
        0,
        0,
    );
    assert_resource_limit(
        codec::decode_fraction_format(source, input_limited),
        |limit| matches!(limit, codec::DecodeLimit::InputBytes { .. }),
    );

    if report.fields() > 0 {
        let options = codec::DecodeOptions::new(
            MAX_INPUT_BYTES.max(source.len()),
            MAX_OUTPUT_BYTES.max(source.len()),
            report.fields() - 1,
            MAX_WORK_BYTES,
            MAX_RECURSION,
            0,
            0,
            0,
        );
        assert_resource_limit(codec::decode_fraction_format(source, options), |limit| {
            matches!(limit, codec::DecodeLimit::Fields { .. })
        });
    }

    if report.work_bytes() > 0 {
        let options = codec::DecodeOptions::new(
            MAX_INPUT_BYTES.max(source.len()),
            MAX_OUTPUT_BYTES.max(source.len()),
            MAX_FIELDS,
            report.work_bytes() - 1,
            MAX_RECURSION,
            0,
            0,
            0,
        );
        assert_resource_limit(codec::decode_fraction_format(source, options), |limit| {
            matches!(limit, codec::DecodeLimit::Work { .. })
        });
    }
}

fn exercise_all_accuracies() {
    for (&accuracy, &source) in ALL_ACCURACIES.iter().zip(CANONICAL_SOURCES.iter()) {
        let snapshot = codec::decode_fraction_format(source, options(source))
            .unwrap_or_else(|error| panic!("Fraction accuracy {accuracy} decode failed: {error}"));
        assert_eq!(snapshot.fraction_accuracy(), accuracy);
        let write = codec::FractionFormatWrite::from_snapshot(snapshot);
        let output =
            codec::canonical_fraction_format(write, options(&[])).unwrap_or_else(|error| {
                panic!("Fraction accuracy {accuracy} canonical write failed: {error}")
            });
        assert_eq!(output.bytes(), source);
        let readback = codec::decode_fraction_format(output.bytes(), options(output.bytes()))
            .unwrap_or_else(|error| {
                panic!("Fraction accuracy {accuracy} readback failed: {error}")
            });
        assert_eq!(readback.fraction_accuracy(), accuracy);
        assert_eq!(codec::FractionFormatWrite::from_snapshot(readback), write);
        black_box(output);
    }

    // Exercise the typed façade as well as the raw field-11 values.  This
    // keeps every public precision spelling reachable from the fuzz binary.
    for accuracy in [
        codec::FractionAccuracy::UpToOneDigit,
        codec::FractionAccuracy::UpToTwoDigits,
        codec::FractionAccuracy::UpToThreeDigits,
        codec::FractionAccuracy::Halves,
        codec::FractionAccuracy::Quarters,
        codec::FractionAccuracy::Eighths,
        codec::FractionAccuracy::Sixteenths,
        codec::FractionAccuracy::Tenths,
        codec::FractionAccuracy::Hundredths,
    ] {
        let write = codec::FractionFormatWrite::from_accuracy(accuracy);
        assert_eq!(write.accuracy(), Some(accuracy));
        let output = codec::canonical_fraction_format(write, options(&[]))
            .unwrap_or_else(|error| panic!("typed Fraction accuracy write failed: {error}"));
        let readback = codec::decode_fraction_format(output.bytes(), options(output.bytes()))
            .unwrap_or_else(|error| panic!("typed Fraction accuracy readback failed: {error}"));
        assert_eq!(readback.accuracy(), Some(accuracy));
        black_box(output);
    }
}

fn assert_resource_limit<T>(
    result: Result<T, codec::DecodeError>,
    predicate: impl FnOnce(codec::DecodeLimit) -> bool,
) {
    let error = match result {
        Ok(_) => panic!("resource-limited Fraction-format operation unexpectedly succeeded"),
        Err(error) => error,
    };
    let limit = error
        .resource_limit()
        .expect("resource failure did not expose a typed limit");
    assert!(
        predicate(limit),
        "unexpected Fraction-format resource limit"
    );
    observe_error(error);
}

fn exercise_canonical_writes() {
    for &accuracy in ALL_ACCURACIES {
        let write = write_for_accuracy(accuracy);
        let prepared = codec::prepare_fraction_format_write(write, options(&[]))
            .unwrap_or_else(|error| panic!("canonical Fraction-format prepare failed: {error}"));
        let requirements = prepared.execution_requirements();
        let preparation = prepared.prepare_report();
        assert_eq!(preparation.output_bytes(), requirements.output_bytes());
        assert_eq!(preparation.fields(), requirements.fields());
        assert_eq!(preparation.work_bytes(), requirements.work_bytes());
        assert_eq!(preparation.max_depth(), requirements.max_depth());
        assert_eq!(preparation.allocations(), requirements.allocations());
        let output = prepared
            .execute(codec::RewriteExecutionLimits::exact(requirements))
            .unwrap_or_else(|error| panic!("canonical Fraction-format execute failed: {error}"));
        assert_eq!(output.bytes().len(), requirements.output_bytes());
        assert_eq!(output.report(), preparation);
        let readback = codec::decode_fraction_format(output.bytes(), options(output.bytes()))
            .unwrap_or_else(|error| panic!("canonical Fraction-format readback failed: {error}"));
        assert_eq!(codec::FractionFormatWrite::from_snapshot(readback), write);
        assert_eq!(
            readback.requires_fraction_replacement(),
            None,
            "canonical Fraction writer synthesized field-20=false"
        );
        assert_eq!(
            codec::canonical_fraction_format(write, options(&[]))
                .expect("canonical one-shot")
                .bytes(),
            output.bytes()
        );
        black_box(output);
    }
}

fn exercise_limit_guards() {
    let source = CANONICAL_EIGHTHS;
    let write = write_for_accuracy(codec::NATIVE_FRACTION_HUNDREDTHS);
    let mut output_limited = options(source);
    output_limited = output_limited.with_max_output_bytes(0);
    assert_resource_limit(
        codec::prepare_fraction_format_rewrite(source, write, output_limited),
        |limit| matches!(limit, codec::DecodeLimit::OutputBytes { .. }),
    );

    let prepared = codec::prepare_fraction_format_rewrite(source, write, options(source))
        .expect("limit guard prepare");
    let requirements = prepared.execution_requirements();
    assert_resource_limit(
        prepared.execute(codec::RewriteExecutionLimits::exact(requirements).with_allocations(0)),
        |limit| matches!(limit, codec::DecodeLimit::Allocation { .. }),
    );

    // A group chain beyond the finite scanner depth must fail with a typed
    // nesting limit rather than recurse or allocate without bound.
    let deep = deep_group_source((MAX_RECURSION + 1) as usize);
    let error = codec::decode_fraction_format(&deep, options(&deep))
        .expect_err("deep Fraction group unexpectedly decoded");
    assert!(matches!(
        error.resource_limit(),
        Some(codec::DecodeLimit::Nesting { .. })
    ));
    observe_error(error);
}

fn deep_group_source(depth: usize) -> Vec<u8> {
    let mut source = CANONICAL_EIGHTHS.to_vec();
    for _ in 0..depth {
        source.extend_from_slice(&[0xa3, 0x06]);
    }
    for _ in 0..depth {
        source.extend_from_slice(&[0xa4, 0x06]);
    }
    source
}

fn observe_error(error: codec::DecodeError) {
    black_box(error.to_string());
    black_box(format_args!("{error:?}"));
}
