[package]
name        = "litchi-core"
description = "Common types, traits, and utilities for the Litchi office-formats library."
version.workspace      = true
edition.workspace      = true
authors.workspace      = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true

[dependencies]
aho-corasick    = { workspace = true }
chrono          = { workspace = true }
fast-float2     = { workspace = true }
once_cell       = { workspace = true }
rand            = { workspace = true }
serde           = { workspace = true }
smallvec        = { workspace = true }
thiserror       = { workspace = true }
zerocopy        = { workspace = true }
