//! Render a simple in-memory "document" to Markdown using `ToMarkdown`.
//!
//! `litchi-markdown` is format-agnostic: it ships the [`ToMarkdown`] trait and
//! configuration types, but no concrete `impl ToMarkdown for ...` blocks (those
//! live alongside the format crates). This example therefore defines its own
//! tiny `MyDoc` struct, implements `ToMarkdown` for it, and exercises the
//! default [`MarkdownOptions`].
//!
//! # Run
//!
//! ```bash
//! cargo run -p litchi-markdown --example simple_doc
//! ```
use std::fmt::Write as _;

use litchi_core::Result;
use litchi_markdown::{MarkdownOptions, ToMarkdown};

/// A toy document with a title, free-form paragraphs, and a single 2D table.
struct MyDoc {
    title: String,
    paragraphs: Vec<String>,
    /// Row-major table. The first row is rendered as the table header.
    table: Vec<Vec<String>>,
}

impl ToMarkdown for MyDoc {
    fn to_markdown_with_options(&self, _options: &MarkdownOptions) -> Result<String> {
        // Pre-allocate a reasonable upper bound to avoid reallocations.
        let mut out = String::with_capacity(256);

        // H1 title.
        writeln!(out, "# {}", self.title).unwrap();
        writeln!(out).unwrap();

        // Paragraphs separated by blank lines.
        for para in &self.paragraphs {
            writeln!(out, "{para}").unwrap();
            writeln!(out).unwrap();
        }

        // Markdown table (assumes first row is the header).
        if let Some((header, body)) = self.table.split_first() {
            // Header row.
            out.push('|');
            for cell in header {
                write!(out, " {cell} |").unwrap();
            }
            out.push('\n');

            // Separator row.
            out.push('|');
            for _ in header {
                out.push_str("---|");
            }
            out.push('\n');

            // Body rows.
            for row in body {
                out.push('|');
                for cell in row {
                    write!(out, " {cell} |").unwrap();
                }
                out.push('\n');
            }
        }

        Ok(out)
    }
}

fn main() -> Result<()> {
    let doc = MyDoc {
        title: "Litchi Markdown Demo".to_owned(),
        paragraphs: vec![
            "This document was generated by a tiny `ToMarkdown` impl living \
             entirely inside the example."
                .to_owned(),
            "Real format crates (litchi-docx, litchi-odf, ...) provide their \
             own implementations on top of the same trait."
                .to_owned(),
        ],
        table: vec![
            vec!["Format".to_owned(), "Crate".to_owned()],
            vec!["DOCX".to_owned(), "litchi-docx".to_owned()],
            vec!["ODT".to_owned(), "litchi-odf".to_owned()],
            vec!["RTF".to_owned(), "litchi-rtf".to_owned()],
        ],
    };

    // `to_markdown` uses `MarkdownOptions::default()` under the hood.
    let rendered = doc.to_markdown()?;

    println!("--- Rendered Markdown ---");
    println!("{rendered}");

    Ok(())
}
