#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Kind {
    Dr3dAmbientColor,
    Dr3dBackScale,
    Dr3dBackfaceCulling,
    Dr3dCloseBack,
    Dr3dCloseFront,
    Dr3dDepth,
    Dr3dDiffuseColor,
    Dr3dEdgeRounding,
    Dr3dEdgeRoundingMode,
    Dr3dEmissiveColor,
    Dr3dEndAngle,
    Dr3dHorizontalSegments,
    Dr3dLightingMode,
    Dr3dNormalsDirection,
    Dr3dNormalsKind,
    Dr3dShadow,
    Dr3dShininess,
    Dr3dSpecularColor,
    Dr3dTextureFilter,
    Dr3dTextureGenerationModeX,
    Dr3dTextureGenerationModeY,
    Dr3dTextureKind,
    Dr3dTextureMode,
    Dr3dVerticalSegments,
    DrawAutoGrowHeight,
    DrawAutoGrowWidth,
    DrawBlue,
    DrawCaptionAngle,
    DrawCaptionAngleType,
    DrawCaptionEscape,
    DrawCaptionEscapeDirection,
    DrawCaptionFitLineLength,
    DrawCaptionGap,
    DrawCaptionLineLength,
    DrawCaptionType,
    DrawColorInversion,
    DrawColorMode,
    DrawContrast,
    DrawDecimalPlaces,
    DrawDrawAspect,
    DrawEndGuide,
    DrawEndLineSpacingHorizontal,
    DrawEndLineSpacingVertical,
    DrawFill,
    DrawFillColor,
    DrawFillGradientName,
    DrawFillHatchName,
    DrawFillHatchSolid,
    DrawFillImageHeight,
    DrawFillImageName,
    DrawFillImageRefPoint,
    DrawFillImageRefPointX,
    DrawFillImageRefPointY,
    DrawFillImageWidth,
    DrawFitToContour,
    DrawFitToSize,
    DrawFrameDisplayBorder,
    DrawFrameDisplayScrollbar,
    DrawFrameMarginHorizontal,
    DrawFrameMarginVertical,
    DrawGamma,
    DrawGradientStepCount,
    DrawGreen,
    DrawGuideDistance,
    DrawGuideOverhang,
    DrawImageOpacity,
    DrawLineDistance,
    DrawLuminance,
    DrawMarkerEnd,
    DrawMarkerEndCenter,
    DrawMarkerEndWidth,
    DrawMarkerStart,
    DrawMarkerStartCenter,
    DrawMarkerStartWidth,
    DrawMeasureAlign,
    DrawMeasureVerticalAlign,
    DrawOleDrawAspect,
    DrawOpacity,
    DrawOpacityName,
    DrawParallel,
    DrawPlacing,
    DrawRed,
    DrawSecondaryFillColor,
    DrawShadow,
    DrawShadowColor,
    DrawShadowOffsetX,
    DrawShadowOffsetY,
    DrawShadowOpacity,
    DrawShowUnit,
    DrawStartGuide,
    DrawStartLineSpacingHorizontal,
    DrawStartLineSpacingVertical,
    DrawStroke,
    DrawStrokeDash,
    DrawStrokeDashNames,
    DrawStrokeLinejoin,
    DrawSymbolColor,
    DrawTextareaHorizontalAlign,
    DrawTextareaVerticalAlign,
    DrawTileRepeatOffset,
    DrawUnit,
    DrawVisibleAreaHeight,
    DrawVisibleAreaLeft,
    DrawVisibleAreaTop,
    DrawVisibleAreaWidth,
    DrawWrapInfluenceOnPosition,
    FoBackgroundColor,
    FoBorder,
    FoBorderBottom,
    FoBorderLeft,
    FoBorderRight,
    FoBorderTop,
    FoClip,
    FoMargin,
    FoMarginBottom,
    FoMarginLeft,
    FoMarginRight,
    FoMarginTop,
    FoMaxHeight,
    FoMaxWidth,
    FoMinHeight,
    FoMinWidth,
    FoPadding,
    FoPaddingBottom,
    FoPaddingLeft,
    FoPaddingRight,
    FoPaddingTop,
    FoWrapOption,
    StyleBackgroundTransparency,
    StyleBorderLineWidth,
    StyleBorderLineWidthBottom,
    StyleBorderLineWidthLeft,
    StyleBorderLineWidthRight,
    StyleBorderLineWidthTop,
    StyleEditable,
    StyleFlowWithText,
    StyleHorizontalPos,
    StyleHorizontalRel,
    StyleMirror,
    StyleNumberWrappedParagraphs,
    StyleOverflowBehavior,
    StylePrintContent,
    StyleProtect,
    StyleRelHeight,
    StyleRelWidth,
    StyleRepeat,
    StyleRunThrough,
    StyleShadow,
    StyleShrinkToFit,
    StyleVerticalPos,
    StyleVerticalRel,
    StyleWrap,
    StyleWrapContour,
    StyleWrapContourMode,
    StyleWrapDynamicThreshold,
    StyleWritingMode,
    SvgFillRule,
    SvgHeight,
    SvgStrokeColor,
    SvgStrokeLinecap,
    SvgStrokeOpacity,
    SvgStrokeWidth,
    SvgWidth,
    SvgX,
    SvgY,
    TextAnchorPageNumber,
    TextAnchorType,
    TextAnimation,
    TextAnimationDelay,
    TextAnimationDirection,
    TextAnimationRepeat,
    TextAnimationStartInside,
    TextAnimationSteps,
    TextAnimationStopInside,
}
impl Kind {
    pub const ALL: &'static [Self] = &[
        Self::Dr3dAmbientColor,
        Self::Dr3dBackScale,
        Self::Dr3dBackfaceCulling,
        Self::Dr3dCloseBack,
        Self::Dr3dCloseFront,
        Self::Dr3dDepth,
        Self::Dr3dDiffuseColor,
        Self::Dr3dEdgeRounding,
        Self::Dr3dEdgeRoundingMode,
        Self::Dr3dEmissiveColor,
        Self::Dr3dEndAngle,
        Self::Dr3dHorizontalSegments,
        Self::Dr3dLightingMode,
        Self::Dr3dNormalsDirection,
        Self::Dr3dNormalsKind,
        Self::Dr3dShadow,
        Self::Dr3dShininess,
        Self::Dr3dSpecularColor,
        Self::Dr3dTextureFilter,
        Self::Dr3dTextureGenerationModeX,
        Self::Dr3dTextureGenerationModeY,
        Self::Dr3dTextureKind,
        Self::Dr3dTextureMode,
        Self::Dr3dVerticalSegments,
        Self::DrawAutoGrowHeight,
        Self::DrawAutoGrowWidth,
        Self::DrawBlue,
        Self::DrawCaptionAngle,
        Self::DrawCaptionAngleType,
        Self::DrawCaptionEscape,
        Self::DrawCaptionEscapeDirection,
        Self::DrawCaptionFitLineLength,
        Self::DrawCaptionGap,
        Self::DrawCaptionLineLength,
        Self::DrawCaptionType,
        Self::DrawColorInversion,
        Self::DrawColorMode,
        Self::DrawContrast,
        Self::DrawDecimalPlaces,
        Self::DrawDrawAspect,
        Self::DrawEndGuide,
        Self::DrawEndLineSpacingHorizontal,
        Self::DrawEndLineSpacingVertical,
        Self::DrawFill,
        Self::DrawFillColor,
        Self::DrawFillGradientName,
        Self::DrawFillHatchName,
        Self::DrawFillHatchSolid,
        Self::DrawFillImageHeight,
        Self::DrawFillImageName,
        Self::DrawFillImageRefPoint,
        Self::DrawFillImageRefPointX,
        Self::DrawFillImageRefPointY,
        Self::DrawFillImageWidth,
        Self::DrawFitToContour,
        Self::DrawFitToSize,
        Self::DrawFrameDisplayBorder,
        Self::DrawFrameDisplayScrollbar,
        Self::DrawFrameMarginHorizontal,
        Self::DrawFrameMarginVertical,
        Self::DrawGamma,
        Self::DrawGradientStepCount,
        Self::DrawGreen,
        Self::DrawGuideDistance,
        Self::DrawGuideOverhang,
        Self::DrawImageOpacity,
        Self::DrawLineDistance,
        Self::DrawLuminance,
        Self::DrawMarkerEnd,
        Self::DrawMarkerEndCenter,
        Self::DrawMarkerEndWidth,
        Self::DrawMarkerStart,
        Self::DrawMarkerStartCenter,
        Self::DrawMarkerStartWidth,
        Self::DrawMeasureAlign,
        Self::DrawMeasureVerticalAlign,
        Self::DrawOleDrawAspect,
        Self::DrawOpacity,
        Self::DrawOpacityName,
        Self::DrawParallel,
        Self::DrawPlacing,
        Self::DrawRed,
        Self::DrawSecondaryFillColor,
        Self::DrawShadow,
        Self::DrawShadowColor,
        Self::DrawShadowOffsetX,
        Self::DrawShadowOffsetY,
        Self::DrawShadowOpacity,
        Self::DrawShowUnit,
        Self::DrawStartGuide,
        Self::DrawStartLineSpacingHorizontal,
        Self::DrawStartLineSpacingVertical,
        Self::DrawStroke,
        Self::DrawStrokeDash,
        Self::DrawStrokeDashNames,
        Self::DrawStrokeLinejoin,
        Self::DrawSymbolColor,
        Self::DrawTextareaHorizontalAlign,
        Self::DrawTextareaVerticalAlign,
        Self::DrawTileRepeatOffset,
        Self::DrawUnit,
        Self::DrawVisibleAreaHeight,
        Self::DrawVisibleAreaLeft,
        Self::DrawVisibleAreaTop,
        Self::DrawVisibleAreaWidth,
        Self::DrawWrapInfluenceOnPosition,
        Self::FoBackgroundColor,
        Self::FoBorder,
        Self::FoBorderBottom,
        Self::FoBorderLeft,
        Self::FoBorderRight,
        Self::FoBorderTop,
        Self::FoClip,
        Self::FoMargin,
        Self::FoMarginBottom,
        Self::FoMarginLeft,
        Self::FoMarginRight,
        Self::FoMarginTop,
        Self::FoMaxHeight,
        Self::FoMaxWidth,
        Self::FoMinHeight,
        Self::FoMinWidth,
        Self::FoPadding,
        Self::FoPaddingBottom,
        Self::FoPaddingLeft,
        Self::FoPaddingRight,
        Self::FoPaddingTop,
        Self::FoWrapOption,
        Self::StyleBackgroundTransparency,
        Self::StyleBorderLineWidth,
        Self::StyleBorderLineWidthBottom,
        Self::StyleBorderLineWidthLeft,
        Self::StyleBorderLineWidthRight,
        Self::StyleBorderLineWidthTop,
        Self::StyleEditable,
        Self::StyleFlowWithText,
        Self::StyleHorizontalPos,
        Self::StyleHorizontalRel,
        Self::StyleMirror,
        Self::StyleNumberWrappedParagraphs,
        Self::StyleOverflowBehavior,
        Self::StylePrintContent,
        Self::StyleProtect,
        Self::StyleRelHeight,
        Self::StyleRelWidth,
        Self::StyleRepeat,
        Self::StyleRunThrough,
        Self::StyleShadow,
        Self::StyleShrinkToFit,
        Self::StyleVerticalPos,
        Self::StyleVerticalRel,
        Self::StyleWrap,
        Self::StyleWrapContour,
        Self::StyleWrapContourMode,
        Self::StyleWrapDynamicThreshold,
        Self::StyleWritingMode,
        Self::SvgFillRule,
        Self::SvgHeight,
        Self::SvgStrokeColor,
        Self::SvgStrokeLinecap,
        Self::SvgStrokeOpacity,
        Self::SvgStrokeWidth,
        Self::SvgWidth,
        Self::SvgX,
        Self::SvgY,
        Self::TextAnchorPageNumber,
        Self::TextAnchorType,
        Self::TextAnimation,
        Self::TextAnimationDelay,
        Self::TextAnimationDirection,
        Self::TextAnimationRepeat,
        Self::TextAnimationStartInside,
        Self::TextAnimationSteps,
        Self::TextAnimationStopInside,
    ];
    pub fn namespace(self) -> Namespace {
        match self {
            Self::Dr3dAmbientColor => Namespace::Dr3d,
            Self::Dr3dBackScale => Namespace::Dr3d,
            Self::Dr3dBackfaceCulling => Namespace::Dr3d,
            Self::Dr3dCloseBack => Namespace::Dr3d,
            Self::Dr3dCloseFront => Namespace::Dr3d,
            Self::Dr3dDepth => Namespace::Dr3d,
            Self::Dr3dDiffuseColor => Namespace::Dr3d,
            Self::Dr3dEdgeRounding => Namespace::Dr3d,
            Self::Dr3dEdgeRoundingMode => Namespace::Dr3d,
            Self::Dr3dEmissiveColor => Namespace::Dr3d,
            Self::Dr3dEndAngle => Namespace::Dr3d,
            Self::Dr3dHorizontalSegments => Namespace::Dr3d,
            Self::Dr3dLightingMode => Namespace::Dr3d,
            Self::Dr3dNormalsDirection => Namespace::Dr3d,
            Self::Dr3dNormalsKind => Namespace::Dr3d,
            Self::Dr3dShadow => Namespace::Dr3d,
            Self::Dr3dShininess => Namespace::Dr3d,
            Self::Dr3dSpecularColor => Namespace::Dr3d,
            Self::Dr3dTextureFilter => Namespace::Dr3d,
            Self::Dr3dTextureGenerationModeX => Namespace::Dr3d,
            Self::Dr3dTextureGenerationModeY => Namespace::Dr3d,
            Self::Dr3dTextureKind => Namespace::Dr3d,
            Self::Dr3dTextureMode => Namespace::Dr3d,
            Self::Dr3dVerticalSegments => Namespace::Dr3d,
            Self::DrawAutoGrowHeight => Namespace::Draw,
            Self::DrawAutoGrowWidth => Namespace::Draw,
            Self::DrawBlue => Namespace::Draw,
            Self::DrawCaptionAngle => Namespace::Draw,
            Self::DrawCaptionAngleType => Namespace::Draw,
            Self::DrawCaptionEscape => Namespace::Draw,
            Self::DrawCaptionEscapeDirection => Namespace::Draw,
            Self::DrawCaptionFitLineLength => Namespace::Draw,
            Self::DrawCaptionGap => Namespace::Draw,
            Self::DrawCaptionLineLength => Namespace::Draw,
            Self::DrawCaptionType => Namespace::Draw,
            Self::DrawColorInversion => Namespace::Draw,
            Self::DrawColorMode => Namespace::Draw,
            Self::DrawContrast => Namespace::Draw,
            Self::DrawDecimalPlaces => Namespace::Draw,
            Self::DrawDrawAspect => Namespace::Draw,
            Self::DrawEndGuide => Namespace::Draw,
            Self::DrawEndLineSpacingHorizontal => Namespace::Draw,
            Self::DrawEndLineSpacingVertical => Namespace::Draw,
            Self::DrawFill => Namespace::Draw,
            Self::DrawFillColor => Namespace::Draw,
            Self::DrawFillGradientName => Namespace::Draw,
            Self::DrawFillHatchName => Namespace::Draw,
            Self::DrawFillHatchSolid => Namespace::Draw,
            Self::DrawFillImageHeight => Namespace::Draw,
            Self::DrawFillImageName => Namespace::Draw,
            Self::DrawFillImageRefPoint => Namespace::Draw,
            Self::DrawFillImageRefPointX => Namespace::Draw,
            Self::DrawFillImageRefPointY => Namespace::Draw,
            Self::DrawFillImageWidth => Namespace::Draw,
            Self::DrawFitToContour => Namespace::Draw,
            Self::DrawFitToSize => Namespace::Draw,
            Self::DrawFrameDisplayBorder => Namespace::Draw,
            Self::DrawFrameDisplayScrollbar => Namespace::Draw,
            Self::DrawFrameMarginHorizontal => Namespace::Draw,
            Self::DrawFrameMarginVertical => Namespace::Draw,
            Self::DrawGamma => Namespace::Draw,
            Self::DrawGradientStepCount => Namespace::Draw,
            Self::DrawGreen => Namespace::Draw,
            Self::DrawGuideDistance => Namespace::Draw,
            Self::DrawGuideOverhang => Namespace::Draw,
            Self::DrawImageOpacity => Namespace::Draw,
            Self::DrawLineDistance => Namespace::Draw,
            Self::DrawLuminance => Namespace::Draw,
            Self::DrawMarkerEnd => Namespace::Draw,
            Self::DrawMarkerEndCenter => Namespace::Draw,
            Self::DrawMarkerEndWidth => Namespace::Draw,
            Self::DrawMarkerStart => Namespace::Draw,
            Self::DrawMarkerStartCenter => Namespace::Draw,
            Self::DrawMarkerStartWidth => Namespace::Draw,
            Self::DrawMeasureAlign => Namespace::Draw,
            Self::DrawMeasureVerticalAlign => Namespace::Draw,
            Self::DrawOleDrawAspect => Namespace::Draw,
            Self::DrawOpacity => Namespace::Draw,
            Self::DrawOpacityName => Namespace::Draw,
            Self::DrawParallel => Namespace::Draw,
            Self::DrawPlacing => Namespace::Draw,
            Self::DrawRed => Namespace::Draw,
            Self::DrawSecondaryFillColor => Namespace::Draw,
            Self::DrawShadow => Namespace::Draw,
            Self::DrawShadowColor => Namespace::Draw,
            Self::DrawShadowOffsetX => Namespace::Draw,
            Self::DrawShadowOffsetY => Namespace::Draw,
            Self::DrawShadowOpacity => Namespace::Draw,
            Self::DrawShowUnit => Namespace::Draw,
            Self::DrawStartGuide => Namespace::Draw,
            Self::DrawStartLineSpacingHorizontal => Namespace::Draw,
            Self::DrawStartLineSpacingVertical => Namespace::Draw,
            Self::DrawStroke => Namespace::Draw,
            Self::DrawStrokeDash => Namespace::Draw,
            Self::DrawStrokeDashNames => Namespace::Draw,
            Self::DrawStrokeLinejoin => Namespace::Draw,
            Self::DrawSymbolColor => Namespace::Draw,
            Self::DrawTextareaHorizontalAlign => Namespace::Draw,
            Self::DrawTextareaVerticalAlign => Namespace::Draw,
            Self::DrawTileRepeatOffset => Namespace::Draw,
            Self::DrawUnit => Namespace::Draw,
            Self::DrawVisibleAreaHeight => Namespace::Draw,
            Self::DrawVisibleAreaLeft => Namespace::Draw,
            Self::DrawVisibleAreaTop => Namespace::Draw,
            Self::DrawVisibleAreaWidth => Namespace::Draw,
            Self::DrawWrapInfluenceOnPosition => Namespace::Draw,
            Self::FoBackgroundColor => Namespace::Fo,
            Self::FoBorder => Namespace::Fo,
            Self::FoBorderBottom => Namespace::Fo,
            Self::FoBorderLeft => Namespace::Fo,
            Self::FoBorderRight => Namespace::Fo,
            Self::FoBorderTop => Namespace::Fo,
            Self::FoClip => Namespace::Fo,
            Self::FoMargin => Namespace::Fo,
            Self::FoMarginBottom => Namespace::Fo,
            Self::FoMarginLeft => Namespace::Fo,
            Self::FoMarginRight => Namespace::Fo,
            Self::FoMarginTop => Namespace::Fo,
            Self::FoMaxHeight => Namespace::Fo,
            Self::FoMaxWidth => Namespace::Fo,
            Self::FoMinHeight => Namespace::Fo,
            Self::FoMinWidth => Namespace::Fo,
            Self::FoPadding => Namespace::Fo,
            Self::FoPaddingBottom => Namespace::Fo,
            Self::FoPaddingLeft => Namespace::Fo,
            Self::FoPaddingRight => Namespace::Fo,
            Self::FoPaddingTop => Namespace::Fo,
            Self::FoWrapOption => Namespace::Fo,
            Self::StyleBackgroundTransparency => Namespace::Style,
            Self::StyleBorderLineWidth => Namespace::Style,
            Self::StyleBorderLineWidthBottom => Namespace::Style,
            Self::StyleBorderLineWidthLeft => Namespace::Style,
            Self::StyleBorderLineWidthRight => Namespace::Style,
            Self::StyleBorderLineWidthTop => Namespace::Style,
            Self::StyleEditable => Namespace::Style,
            Self::StyleFlowWithText => Namespace::Style,
            Self::StyleHorizontalPos => Namespace::Style,
            Self::StyleHorizontalRel => Namespace::Style,
            Self::StyleMirror => Namespace::Style,
            Self::StyleNumberWrappedParagraphs => Namespace::Style,
            Self::StyleOverflowBehavior => Namespace::Style,
            Self::StylePrintContent => Namespace::Style,
            Self::StyleProtect => Namespace::Style,
            Self::StyleRelHeight => Namespace::Style,
            Self::StyleRelWidth => Namespace::Style,
            Self::StyleRepeat => Namespace::Style,
            Self::StyleRunThrough => Namespace::Style,
            Self::StyleShadow => Namespace::Style,
            Self::StyleShrinkToFit => Namespace::Style,
            Self::StyleVerticalPos => Namespace::Style,
            Self::StyleVerticalRel => Namespace::Style,
            Self::StyleWrap => Namespace::Style,
            Self::StyleWrapContour => Namespace::Style,
            Self::StyleWrapContourMode => Namespace::Style,
            Self::StyleWrapDynamicThreshold => Namespace::Style,
            Self::StyleWritingMode => Namespace::Style,
            Self::SvgFillRule => Namespace::Svg,
            Self::SvgHeight => Namespace::Svg,
            Self::SvgStrokeColor => Namespace::Svg,
            Self::SvgStrokeLinecap => Namespace::Svg,
            Self::SvgStrokeOpacity => Namespace::Svg,
            Self::SvgStrokeWidth => Namespace::Svg,
            Self::SvgWidth => Namespace::Svg,
            Self::SvgX => Namespace::Svg,
            Self::SvgY => Namespace::Svg,
            Self::TextAnchorPageNumber => Namespace::Text,
            Self::TextAnchorType => Namespace::Text,
            Self::TextAnimation => Namespace::Text,
            Self::TextAnimationDelay => Namespace::Text,
            Self::TextAnimationDirection => Namespace::Text,
            Self::TextAnimationRepeat => Namespace::Text,
            Self::TextAnimationStartInside => Namespace::Text,
            Self::TextAnimationSteps => Namespace::Text,
            Self::TextAnimationStopInside => Namespace::Text,
        }
    }
    pub fn local_name(self) -> &'static str {
        match self {
            Self::Dr3dAmbientColor => "ambient-color",
            Self::Dr3dBackScale => "back-scale",
            Self::Dr3dBackfaceCulling => "backface-culling",
            Self::Dr3dCloseBack => "close-back",
            Self::Dr3dCloseFront => "close-front",
            Self::Dr3dDepth => "depth",
            Self::Dr3dDiffuseColor => "diffuse-color",
            Self::Dr3dEdgeRounding => "edge-rounding",
            Self::Dr3dEdgeRoundingMode => "edge-rounding-mode",
            Self::Dr3dEmissiveColor => "emissive-color",
            Self::Dr3dEndAngle => "end-angle",
            Self::Dr3dHorizontalSegments => "horizontal-segments",
            Self::Dr3dLightingMode => "lighting-mode",
            Self::Dr3dNormalsDirection => "normals-direction",
            Self::Dr3dNormalsKind => "normals-kind",
            Self::Dr3dShadow => "shadow",
            Self::Dr3dShininess => "shininess",
            Self::Dr3dSpecularColor => "specular-color",
            Self::Dr3dTextureFilter => "texture-filter",
            Self::Dr3dTextureGenerationModeX => "texture-generation-mode-x",
            Self::Dr3dTextureGenerationModeY => "texture-generation-mode-y",
            Self::Dr3dTextureKind => "texture-kind",
            Self::Dr3dTextureMode => "texture-mode",
            Self::Dr3dVerticalSegments => "vertical-segments",
            Self::DrawAutoGrowHeight => "auto-grow-height",
            Self::DrawAutoGrowWidth => "auto-grow-width",
            Self::DrawBlue => "blue",
            Self::DrawCaptionAngle => "caption-angle",
            Self::DrawCaptionAngleType => "caption-angle-type",
            Self::DrawCaptionEscape => "caption-escape",
            Self::DrawCaptionEscapeDirection => "caption-escape-direction",
            Self::DrawCaptionFitLineLength => "caption-fit-line-length",
            Self::DrawCaptionGap => "caption-gap",
            Self::DrawCaptionLineLength => "caption-line-length",
            Self::DrawCaptionType => "caption-type",
            Self::DrawColorInversion => "color-inversion",
            Self::DrawColorMode => "color-mode",
            Self::DrawContrast => "contrast",
            Self::DrawDecimalPlaces => "decimal-places",
            Self::DrawDrawAspect => "draw-aspect",
            Self::DrawEndGuide => "end-guide",
            Self::DrawEndLineSpacingHorizontal => "end-line-spacing-horizontal",
            Self::DrawEndLineSpacingVertical => "end-line-spacing-vertical",
            Self::DrawFill => "fill",
            Self::DrawFillColor => "fill-color",
            Self::DrawFillGradientName => "fill-gradient-name",
            Self::DrawFillHatchName => "fill-hatch-name",
            Self::DrawFillHatchSolid => "fill-hatch-solid",
            Self::DrawFillImageHeight => "fill-image-height",
            Self::DrawFillImageName => "fill-image-name",
            Self::DrawFillImageRefPoint => "fill-image-ref-point",
            Self::DrawFillImageRefPointX => "fill-image-ref-point-x",
            Self::DrawFillImageRefPointY => "fill-image-ref-point-y",
            Self::DrawFillImageWidth => "fill-image-width",
            Self::DrawFitToContour => "fit-to-contour",
            Self::DrawFitToSize => "fit-to-size",
            Self::DrawFrameDisplayBorder => "frame-display-border",
            Self::DrawFrameDisplayScrollbar => "frame-display-scrollbar",
            Self::DrawFrameMarginHorizontal => "frame-margin-horizontal",
            Self::DrawFrameMarginVertical => "frame-margin-vertical",
            Self::DrawGamma => "gamma",
            Self::DrawGradientStepCount => "gradient-step-count",
            Self::DrawGreen => "green",
            Self::DrawGuideDistance => "guide-distance",
            Self::DrawGuideOverhang => "guide-overhang",
            Self::DrawImageOpacity => "image-opacity",
            Self::DrawLineDistance => "line-distance",
            Self::DrawLuminance => "luminance",
            Self::DrawMarkerEnd => "marker-end",
            Self::DrawMarkerEndCenter => "marker-end-center",
            Self::DrawMarkerEndWidth => "marker-end-width",
            Self::DrawMarkerStart => "marker-start",
            Self::DrawMarkerStartCenter => "marker-start-center",
            Self::DrawMarkerStartWidth => "marker-start-width",
            Self::DrawMeasureAlign => "measure-align",
            Self::DrawMeasureVerticalAlign => "measure-vertical-align",
            Self::DrawOleDrawAspect => "ole-draw-aspect",
            Self::DrawOpacity => "opacity",
            Self::DrawOpacityName => "opacity-name",
            Self::DrawParallel => "parallel",
            Self::DrawPlacing => "placing",
            Self::DrawRed => "red",
            Self::DrawSecondaryFillColor => "secondary-fill-color",
            Self::DrawShadow => "shadow",
            Self::DrawShadowColor => "shadow-color",
            Self::DrawShadowOffsetX => "shadow-offset-x",
            Self::DrawShadowOffsetY => "shadow-offset-y",
            Self::DrawShadowOpacity => "shadow-opacity",
            Self::DrawShowUnit => "show-unit",
            Self::DrawStartGuide => "start-guide",
            Self::DrawStartLineSpacingHorizontal => "start-line-spacing-horizontal",
            Self::DrawStartLineSpacingVertical => "start-line-spacing-vertical",
            Self::DrawStroke => "stroke",
            Self::DrawStrokeDash => "stroke-dash",
            Self::DrawStrokeDashNames => "stroke-dash-names",
            Self::DrawStrokeLinejoin => "stroke-linejoin",
            Self::DrawSymbolColor => "symbol-color",
            Self::DrawTextareaHorizontalAlign => "textarea-horizontal-align",
            Self::DrawTextareaVerticalAlign => "textarea-vertical-align",
            Self::DrawTileRepeatOffset => "tile-repeat-offset",
            Self::DrawUnit => "unit",
            Self::DrawVisibleAreaHeight => "visible-area-height",
            Self::DrawVisibleAreaLeft => "visible-area-left",
            Self::DrawVisibleAreaTop => "visible-area-top",
            Self::DrawVisibleAreaWidth => "visible-area-width",
            Self::DrawWrapInfluenceOnPosition => "wrap-influence-on-position",
            Self::FoBackgroundColor => "background-color",
            Self::FoBorder => "border",
            Self::FoBorderBottom => "border-bottom",
            Self::FoBorderLeft => "border-left",
            Self::FoBorderRight => "border-right",
            Self::FoBorderTop => "border-top",
            Self::FoClip => "clip",
            Self::FoMargin => "margin",
            Self::FoMarginBottom => "margin-bottom",
            Self::FoMarginLeft => "margin-left",
            Self::FoMarginRight => "margin-right",
            Self::FoMarginTop => "margin-top",
            Self::FoMaxHeight => "max-height",
            Self::FoMaxWidth => "max-width",
            Self::FoMinHeight => "min-height",
            Self::FoMinWidth => "min-width",
            Self::FoPadding => "padding",
            Self::FoPaddingBottom => "padding-bottom",
            Self::FoPaddingLeft => "padding-left",
            Self::FoPaddingRight => "padding-right",
            Self::FoPaddingTop => "padding-top",
            Self::FoWrapOption => "wrap-option",
            Self::StyleBackgroundTransparency => "background-transparency",
            Self::StyleBorderLineWidth => "border-line-width",
            Self::StyleBorderLineWidthBottom => "border-line-width-bottom",
            Self::StyleBorderLineWidthLeft => "border-line-width-left",
            Self::StyleBorderLineWidthRight => "border-line-width-right",
            Self::StyleBorderLineWidthTop => "border-line-width-top",
            Self::StyleEditable => "editable",
            Self::StyleFlowWithText => "flow-with-text",
            Self::StyleHorizontalPos => "horizontal-pos",
            Self::StyleHorizontalRel => "horizontal-rel",
            Self::StyleMirror => "mirror",
            Self::StyleNumberWrappedParagraphs => "number-wrapped-paragraphs",
            Self::StyleOverflowBehavior => "overflow-behavior",
            Self::StylePrintContent => "print-content",
            Self::StyleProtect => "protect",
            Self::StyleRelHeight => "rel-height",
            Self::StyleRelWidth => "rel-width",
            Self::StyleRepeat => "repeat",
            Self::StyleRunThrough => "run-through",
            Self::StyleShadow => "shadow",
            Self::StyleShrinkToFit => "shrink-to-fit",
            Self::StyleVerticalPos => "vertical-pos",
            Self::StyleVerticalRel => "vertical-rel",
            Self::StyleWrap => "wrap",
            Self::StyleWrapContour => "wrap-contour",
            Self::StyleWrapContourMode => "wrap-contour-mode",
            Self::StyleWrapDynamicThreshold => "wrap-dynamic-threshold",
            Self::StyleWritingMode => "writing-mode",
            Self::SvgFillRule => "fill-rule",
            Self::SvgHeight => "height",
            Self::SvgStrokeColor => "stroke-color",
            Self::SvgStrokeLinecap => "stroke-linecap",
            Self::SvgStrokeOpacity => "stroke-opacity",
            Self::SvgStrokeWidth => "stroke-width",
            Self::SvgWidth => "width",
            Self::SvgX => "x",
            Self::SvgY => "y",
            Self::TextAnchorPageNumber => "anchor-page-number",
            Self::TextAnchorType => "anchor-type",
            Self::TextAnimation => "animation",
            Self::TextAnimationDelay => "animation-delay",
            Self::TextAnimationDirection => "animation-direction",
            Self::TextAnimationRepeat => "animation-repeat",
            Self::TextAnimationStartInside => "animation-start-inside",
            Self::TextAnimationSteps => "animation-steps",
            Self::TextAnimationStopInside => "animation-stop-inside",
        }
    }
    pub(crate) fn from_expanded(namespace: Namespace, local: &[u8]) -> Option<Self> {
        match (namespace, local) {
            (Namespace::Dr3d, b"ambient-color") => Some(Self::Dr3dAmbientColor),
            (Namespace::Dr3d, b"back-scale") => Some(Self::Dr3dBackScale),
            (Namespace::Dr3d, b"backface-culling") => Some(Self::Dr3dBackfaceCulling),
            (Namespace::Dr3d, b"close-back") => Some(Self::Dr3dCloseBack),
            (Namespace::Dr3d, b"close-front") => Some(Self::Dr3dCloseFront),
            (Namespace::Dr3d, b"depth") => Some(Self::Dr3dDepth),
            (Namespace::Dr3d, b"diffuse-color") => Some(Self::Dr3dDiffuseColor),
            (Namespace::Dr3d, b"edge-rounding") => Some(Self::Dr3dEdgeRounding),
            (Namespace::Dr3d, b"edge-rounding-mode") => Some(Self::Dr3dEdgeRoundingMode),
            (Namespace::Dr3d, b"emissive-color") => Some(Self::Dr3dEmissiveColor),
            (Namespace::Dr3d, b"end-angle") => Some(Self::Dr3dEndAngle),
            (Namespace::Dr3d, b"horizontal-segments") => Some(Self::Dr3dHorizontalSegments),
            (Namespace::Dr3d, b"lighting-mode") => Some(Self::Dr3dLightingMode),
            (Namespace::Dr3d, b"normals-direction") => Some(Self::Dr3dNormalsDirection),
            (Namespace::Dr3d, b"normals-kind") => Some(Self::Dr3dNormalsKind),
            (Namespace::Dr3d, b"shadow") => Some(Self::Dr3dShadow),
            (Namespace::Dr3d, b"shininess") => Some(Self::Dr3dShininess),
            (Namespace::Dr3d, b"specular-color") => Some(Self::Dr3dSpecularColor),
            (Namespace::Dr3d, b"texture-filter") => Some(Self::Dr3dTextureFilter),
            (Namespace::Dr3d, b"texture-generation-mode-x") => {
                Some(Self::Dr3dTextureGenerationModeX)
            },
            (Namespace::Dr3d, b"texture-generation-mode-y") => {
                Some(Self::Dr3dTextureGenerationModeY)
            },
            (Namespace::Dr3d, b"texture-kind") => Some(Self::Dr3dTextureKind),
            (Namespace::Dr3d, b"texture-mode") => Some(Self::Dr3dTextureMode),
            (Namespace::Dr3d, b"vertical-segments") => Some(Self::Dr3dVerticalSegments),
            (Namespace::Draw, b"auto-grow-height") => Some(Self::DrawAutoGrowHeight),
            (Namespace::Draw, b"auto-grow-width") => Some(Self::DrawAutoGrowWidth),
            (Namespace::Draw, b"blue") => Some(Self::DrawBlue),
            (Namespace::Draw, b"caption-angle") => Some(Self::DrawCaptionAngle),
            (Namespace::Draw, b"caption-angle-type") => Some(Self::DrawCaptionAngleType),
            (Namespace::Draw, b"caption-escape") => Some(Self::DrawCaptionEscape),
            (Namespace::Draw, b"caption-escape-direction") => {
                Some(Self::DrawCaptionEscapeDirection)
            },
            (Namespace::Draw, b"caption-fit-line-length") => Some(Self::DrawCaptionFitLineLength),
            (Namespace::Draw, b"caption-gap") => Some(Self::DrawCaptionGap),
            (Namespace::Draw, b"caption-line-length") => Some(Self::DrawCaptionLineLength),
            (Namespace::Draw, b"caption-type") => Some(Self::DrawCaptionType),
            (Namespace::Draw, b"color-inversion") => Some(Self::DrawColorInversion),
            (Namespace::Draw, b"color-mode") => Some(Self::DrawColorMode),
            (Namespace::Draw, b"contrast") => Some(Self::DrawContrast),
            (Namespace::Draw, b"decimal-places") => Some(Self::DrawDecimalPlaces),
            (Namespace::Draw, b"draw-aspect") => Some(Self::DrawDrawAspect),
            (Namespace::Draw, b"end-guide") => Some(Self::DrawEndGuide),
            (Namespace::Draw, b"end-line-spacing-horizontal") => {
                Some(Self::DrawEndLineSpacingHorizontal)
            },
            (Namespace::Draw, b"end-line-spacing-vertical") => {
                Some(Self::DrawEndLineSpacingVertical)
            },
            (Namespace::Draw, b"fill") => Some(Self::DrawFill),
            (Namespace::Draw, b"fill-color") => Some(Self::DrawFillColor),
            (Namespace::Draw, b"fill-gradient-name") => Some(Self::DrawFillGradientName),
            (Namespace::Draw, b"fill-hatch-name") => Some(Self::DrawFillHatchName),
            (Namespace::Draw, b"fill-hatch-solid") => Some(Self::DrawFillHatchSolid),
            (Namespace::Draw, b"fill-image-height") => Some(Self::DrawFillImageHeight),
            (Namespace::Draw, b"fill-image-name") => Some(Self::DrawFillImageName),
            (Namespace::Draw, b"fill-image-ref-point") => Some(Self::DrawFillImageRefPoint),
            (Namespace::Draw, b"fill-image-ref-point-x") => Some(Self::DrawFillImageRefPointX),
            (Namespace::Draw, b"fill-image-ref-point-y") => Some(Self::DrawFillImageRefPointY),
            (Namespace::Draw, b"fill-image-width") => Some(Self::DrawFillImageWidth),
            (Namespace::Draw, b"fit-to-contour") => Some(Self::DrawFitToContour),
            (Namespace::Draw, b"fit-to-size") => Some(Self::DrawFitToSize),
            (Namespace::Draw, b"frame-display-border") => Some(Self::DrawFrameDisplayBorder),
            (Namespace::Draw, b"frame-display-scrollbar") => Some(Self::DrawFrameDisplayScrollbar),
            (Namespace::Draw, b"frame-margin-horizontal") => Some(Self::DrawFrameMarginHorizontal),
            (Namespace::Draw, b"frame-margin-vertical") => Some(Self::DrawFrameMarginVertical),
            (Namespace::Draw, b"gamma") => Some(Self::DrawGamma),
            (Namespace::Draw, b"gradient-step-count") => Some(Self::DrawGradientStepCount),
            (Namespace::Draw, b"green") => Some(Self::DrawGreen),
            (Namespace::Draw, b"guide-distance") => Some(Self::DrawGuideDistance),
            (Namespace::Draw, b"guide-overhang") => Some(Self::DrawGuideOverhang),
            (Namespace::Draw, b"image-opacity") => Some(Self::DrawImageOpacity),
            (Namespace::Draw, b"line-distance") => Some(Self::DrawLineDistance),
            (Namespace::Draw, b"luminance") => Some(Self::DrawLuminance),
            (Namespace::Draw, b"marker-end") => Some(Self::DrawMarkerEnd),
            (Namespace::Draw, b"marker-end-center") => Some(Self::DrawMarkerEndCenter),
            (Namespace::Draw, b"marker-end-width") => Some(Self::DrawMarkerEndWidth),
            (Namespace::Draw, b"marker-start") => Some(Self::DrawMarkerStart),
            (Namespace::Draw, b"marker-start-center") => Some(Self::DrawMarkerStartCenter),
            (Namespace::Draw, b"marker-start-width") => Some(Self::DrawMarkerStartWidth),
            (Namespace::Draw, b"measure-align") => Some(Self::DrawMeasureAlign),
            (Namespace::Draw, b"measure-vertical-align") => Some(Self::DrawMeasureVerticalAlign),
            (Namespace::Draw, b"ole-draw-aspect") => Some(Self::DrawOleDrawAspect),
            (Namespace::Draw, b"opacity") => Some(Self::DrawOpacity),
            (Namespace::Draw, b"opacity-name") => Some(Self::DrawOpacityName),
            (Namespace::Draw, b"parallel") => Some(Self::DrawParallel),
            (Namespace::Draw, b"placing") => Some(Self::DrawPlacing),
            (Namespace::Draw, b"red") => Some(Self::DrawRed),
            (Namespace::Draw, b"secondary-fill-color") => Some(Self::DrawSecondaryFillColor),
            (Namespace::Draw, b"shadow") => Some(Self::DrawShadow),
            (Namespace::Draw, b"shadow-color") => Some(Self::DrawShadowColor),
            (Namespace::Draw, b"shadow-offset-x") => Some(Self::DrawShadowOffsetX),
            (Namespace::Draw, b"shadow-offset-y") => Some(Self::DrawShadowOffsetY),
            (Namespace::Draw, b"shadow-opacity") => Some(Self::DrawShadowOpacity),
            (Namespace::Draw, b"show-unit") => Some(Self::DrawShowUnit),
            (Namespace::Draw, b"start-guide") => Some(Self::DrawStartGuide),
            (Namespace::Draw, b"start-line-spacing-horizontal") => {
                Some(Self::DrawStartLineSpacingHorizontal)
            },
            (Namespace::Draw, b"start-line-spacing-vertical") => {
                Some(Self::DrawStartLineSpacingVertical)
            },
            (Namespace::Draw, b"stroke") => Some(Self::DrawStroke),
            (Namespace::Draw, b"stroke-dash") => Some(Self::DrawStrokeDash),
            (Namespace::Draw, b"stroke-dash-names") => Some(Self::DrawStrokeDashNames),
            (Namespace::Draw, b"stroke-linejoin") => Some(Self::DrawStrokeLinejoin),
            (Namespace::Draw, b"symbol-color") => Some(Self::DrawSymbolColor),
            (Namespace::Draw, b"textarea-horizontal-align") => {
                Some(Self::DrawTextareaHorizontalAlign)
            },
            (Namespace::Draw, b"textarea-vertical-align") => Some(Self::DrawTextareaVerticalAlign),
            (Namespace::Draw, b"tile-repeat-offset") => Some(Self::DrawTileRepeatOffset),
            (Namespace::Draw, b"unit") => Some(Self::DrawUnit),
            (Namespace::Draw, b"visible-area-height") => Some(Self::DrawVisibleAreaHeight),
            (Namespace::Draw, b"visible-area-left") => Some(Self::DrawVisibleAreaLeft),
            (Namespace::Draw, b"visible-area-top") => Some(Self::DrawVisibleAreaTop),
            (Namespace::Draw, b"visible-area-width") => Some(Self::DrawVisibleAreaWidth),
            (Namespace::Draw, b"wrap-influence-on-position") => {
                Some(Self::DrawWrapInfluenceOnPosition)
            },
            (Namespace::Fo, b"background-color") => Some(Self::FoBackgroundColor),
            (Namespace::Fo, b"border") => Some(Self::FoBorder),
            (Namespace::Fo, b"border-bottom") => Some(Self::FoBorderBottom),
            (Namespace::Fo, b"border-left") => Some(Self::FoBorderLeft),
            (Namespace::Fo, b"border-right") => Some(Self::FoBorderRight),
            (Namespace::Fo, b"border-top") => Some(Self::FoBorderTop),
            (Namespace::Fo, b"clip") => Some(Self::FoClip),
            (Namespace::Fo, b"margin") => Some(Self::FoMargin),
            (Namespace::Fo, b"margin-bottom") => Some(Self::FoMarginBottom),
            (Namespace::Fo, b"margin-left") => Some(Self::FoMarginLeft),
            (Namespace::Fo, b"margin-right") => Some(Self::FoMarginRight),
            (Namespace::Fo, b"margin-top") => Some(Self::FoMarginTop),
            (Namespace::Fo, b"max-height") => Some(Self::FoMaxHeight),
            (Namespace::Fo, b"max-width") => Some(Self::FoMaxWidth),
            (Namespace::Fo, b"min-height") => Some(Self::FoMinHeight),
            (Namespace::Fo, b"min-width") => Some(Self::FoMinWidth),
            (Namespace::Fo, b"padding") => Some(Self::FoPadding),
            (Namespace::Fo, b"padding-bottom") => Some(Self::FoPaddingBottom),
            (Namespace::Fo, b"padding-left") => Some(Self::FoPaddingLeft),
            (Namespace::Fo, b"padding-right") => Some(Self::FoPaddingRight),
            (Namespace::Fo, b"padding-top") => Some(Self::FoPaddingTop),
            (Namespace::Fo, b"wrap-option") => Some(Self::FoWrapOption),
            (Namespace::Style, b"background-transparency") => {
                Some(Self::StyleBackgroundTransparency)
            },
            (Namespace::Style, b"border-line-width") => Some(Self::StyleBorderLineWidth),
            (Namespace::Style, b"border-line-width-bottom") => {
                Some(Self::StyleBorderLineWidthBottom)
            },
            (Namespace::Style, b"border-line-width-left") => Some(Self::StyleBorderLineWidthLeft),
            (Namespace::Style, b"border-line-width-right") => Some(Self::StyleBorderLineWidthRight),
            (Namespace::Style, b"border-line-width-top") => Some(Self::StyleBorderLineWidthTop),
            (Namespace::Style, b"editable") => Some(Self::StyleEditable),
            (Namespace::Style, b"flow-with-text") => Some(Self::StyleFlowWithText),
            (Namespace::Style, b"horizontal-pos") => Some(Self::StyleHorizontalPos),
            (Namespace::Style, b"horizontal-rel") => Some(Self::StyleHorizontalRel),
            (Namespace::Style, b"mirror") => Some(Self::StyleMirror),
            (Namespace::Style, b"number-wrapped-paragraphs") => {
                Some(Self::StyleNumberWrappedParagraphs)
            },
            (Namespace::Style, b"overflow-behavior") => Some(Self::StyleOverflowBehavior),
            (Namespace::Style, b"print-content") => Some(Self::StylePrintContent),
            (Namespace::Style, b"protect") => Some(Self::StyleProtect),
            (Namespace::Style, b"rel-height") => Some(Self::StyleRelHeight),
            (Namespace::Style, b"rel-width") => Some(Self::StyleRelWidth),
            (Namespace::Style, b"repeat") => Some(Self::StyleRepeat),
            (Namespace::Style, b"run-through") => Some(Self::StyleRunThrough),
            (Namespace::Style, b"shadow") => Some(Self::StyleShadow),
            (Namespace::Style, b"shrink-to-fit") => Some(Self::StyleShrinkToFit),
            (Namespace::Style, b"vertical-pos") => Some(Self::StyleVerticalPos),
            (Namespace::Style, b"vertical-rel") => Some(Self::StyleVerticalRel),
            (Namespace::Style, b"wrap") => Some(Self::StyleWrap),
            (Namespace::Style, b"wrap-contour") => Some(Self::StyleWrapContour),
            (Namespace::Style, b"wrap-contour-mode") => Some(Self::StyleWrapContourMode),
            (Namespace::Style, b"wrap-dynamic-threshold") => Some(Self::StyleWrapDynamicThreshold),
            (Namespace::Style, b"writing-mode") => Some(Self::StyleWritingMode),
            (Namespace::Svg, b"fill-rule") => Some(Self::SvgFillRule),
            (Namespace::Svg, b"height") => Some(Self::SvgHeight),
            (Namespace::Svg, b"stroke-color") => Some(Self::SvgStrokeColor),
            (Namespace::Svg, b"stroke-linecap") => Some(Self::SvgStrokeLinecap),
            (Namespace::Svg, b"stroke-opacity") => Some(Self::SvgStrokeOpacity),
            (Namespace::Svg, b"stroke-width") => Some(Self::SvgStrokeWidth),
            (Namespace::Svg, b"width") => Some(Self::SvgWidth),
            (Namespace::Svg, b"x") => Some(Self::SvgX),
            (Namespace::Svg, b"y") => Some(Self::SvgY),
            (Namespace::Text, b"anchor-page-number") => Some(Self::TextAnchorPageNumber),
            (Namespace::Text, b"anchor-type") => Some(Self::TextAnchorType),
            (Namespace::Text, b"animation") => Some(Self::TextAnimation),
            (Namespace::Text, b"animation-delay") => Some(Self::TextAnimationDelay),
            (Namespace::Text, b"animation-direction") => Some(Self::TextAnimationDirection),
            (Namespace::Text, b"animation-repeat") => Some(Self::TextAnimationRepeat),
            (Namespace::Text, b"animation-start-inside") => Some(Self::TextAnimationStartInside),
            (Namespace::Text, b"animation-steps") => Some(Self::TextAnimationSteps),
            (Namespace::Text, b"animation-stop-inside") => Some(Self::TextAnimationStopInside),
            _ => None,
        }
    }
    pub(crate) fn parse_value(self, value: &str) -> Result<Value> {
        match self {
            Self::Dr3dAmbientColor => validate_spec(value, &[], &["color"], false, self),
            Self::Dr3dBackScale => validate_spec(value, &[], &["percent"], false, self),
            Self::Dr3dBackfaceCulling => {
                validate_spec(value, &["disabled", "enabled"], &[], false, self)
            },
            Self::Dr3dCloseBack => validate_spec(value, &[], &["boolean"], false, self),
            Self::Dr3dCloseFront => validate_spec(value, &[], &["boolean"], false, self),
            Self::Dr3dDepth => validate_spec(value, &[], &["length"], false, self),
            Self::Dr3dDiffuseColor => validate_spec(value, &[], &["color"], false, self),
            Self::Dr3dEdgeRounding => validate_spec(value, &[], &["percent"], false, self),
            Self::Dr3dEdgeRoundingMode => {
                validate_spec(value, &["attractive", "correct"], &[], false, self)
            },
            Self::Dr3dEmissiveColor => validate_spec(value, &[], &["color"], false, self),
            Self::Dr3dEndAngle => validate_spec(value, &[], &["angle"], false, self),
            Self::Dr3dHorizontalSegments => {
                validate_spec(value, &[], &["nonNegativeInteger"], false, self)
            },
            Self::Dr3dLightingMode => {
                validate_spec(value, &["double-sided", "standard"], &[], false, self)
            },
            Self::Dr3dNormalsDirection => {
                validate_spec(value, &["inverse", "normal"], &[], false, self)
            },
            Self::Dr3dNormalsKind => {
                validate_spec(value, &["flat", "object", "sphere"], &[], false, self)
            },
            Self::Dr3dShadow => validate_spec(value, &["hidden", "visible"], &[], false, self),
            Self::Dr3dShininess => validate_spec(value, &[], &["percent"], false, self),
            Self::Dr3dSpecularColor => validate_spec(value, &[], &["color"], false, self),
            Self::Dr3dTextureFilter => {
                validate_spec(value, &["disabled", "enabled"], &[], false, self)
            },
            Self::Dr3dTextureGenerationModeX => {
                validate_spec(value, &["object", "parallel", "sphere"], &[], false, self)
            },
            Self::Dr3dTextureGenerationModeY => {
                validate_spec(value, &["object", "parallel", "sphere"], &[], false, self)
            },
            Self::Dr3dTextureKind => validate_spec(
                value,
                &["color", "intensity", "luminance"],
                &[],
                false,
                self,
            ),
            Self::Dr3dTextureMode => {
                validate_spec(value, &["blend", "modulate", "replace"], &[], false, self)
            },
            Self::Dr3dVerticalSegments => {
                validate_spec(value, &[], &["nonNegativeInteger"], false, self)
            },
            Self::DrawAutoGrowHeight => validate_spec(value, &[], &["boolean"], false, self),
            Self::DrawAutoGrowWidth => validate_spec(value, &[], &["boolean"], false, self),
            Self::DrawBlue => {
                validate_spec(value, &[], &["signedZeroToHundredPercent"], false, self)
            },
            Self::DrawCaptionAngle => validate_spec(value, &[], &["angle"], false, self),
            Self::DrawCaptionAngleType => {
                validate_spec(value, &["fixed", "free"], &[], false, self)
            },
            Self::DrawCaptionEscape => {
                validate_spec(value, &[], &["length", "percent"], false, self)
            },
            Self::DrawCaptionEscapeDirection => {
                validate_spec(value, &["auto", "horizontal", "vertical"], &[], false, self)
            },
            Self::DrawCaptionFitLineLength => validate_spec(value, &[], &["boolean"], false, self),
            Self::DrawCaptionGap => validate_spec(value, &[], &["distance"], false, self),
            Self::DrawCaptionLineLength => validate_spec(value, &[], &["length"], false, self),
            Self::DrawCaptionType => validate_spec(
                value,
                &["angled-connector-line", "angled-line", "straight-line"],
                &[],
                false,
                self,
            ),
            Self::DrawColorInversion => validate_spec(value, &[], &["boolean"], false, self),
            Self::DrawColorMode => validate_spec(
                value,
                &["greyscale", "mono", "standard", "watermark"],
                &[],
                false,
                self,
            ),
            Self::DrawContrast => validate_spec(value, &[], &["percent"], false, self),
            Self::DrawDecimalPlaces => {
                validate_spec(value, &[], &["nonNegativeInteger"], false, self)
            },
            Self::DrawDrawAspect => validate_spec(
                value,
                &["content", "icon", "print-view", "thumbnail"],
                &[],
                false,
                self,
            ),
            Self::DrawEndGuide => validate_spec(value, &[], &["length"], false, self),
            Self::DrawEndLineSpacingHorizontal => {
                validate_spec(value, &[], &["distance"], false, self)
            },
            Self::DrawEndLineSpacingVertical => {
                validate_spec(value, &[], &["distance"], false, self)
            },
            Self::DrawFill => validate_spec(
                value,
                &["bitmap", "gradient", "hatch", "none", "solid"],
                &[],
                false,
                self,
            ),
            Self::DrawFillColor => validate_spec(value, &[], &["color"], false, self),
            Self::DrawFillGradientName => validate_spec(value, &[], &["styleNameRef"], false, self),
            Self::DrawFillHatchName => validate_spec(value, &[], &["styleNameRef"], false, self),
            Self::DrawFillHatchSolid => validate_spec(value, &[], &["boolean"], false, self),
            Self::DrawFillImageHeight => {
                validate_spec(value, &[], &["length", "percent"], false, self)
            },
            Self::DrawFillImageName => validate_spec(value, &[], &["styleNameRef"], false, self),
            Self::DrawFillImageRefPoint => validate_spec(
                value,
                &[
                    "bottom",
                    "bottom-left",
                    "bottom-right",
                    "center",
                    "left",
                    "right",
                    "top",
                    "top-left",
                    "top-right",
                ],
                &[],
                false,
                self,
            ),
            Self::DrawFillImageRefPointX => validate_spec(value, &[], &["percent"], false, self),
            Self::DrawFillImageRefPointY => validate_spec(value, &[], &["percent"], false, self),
            Self::DrawFillImageWidth => {
                validate_spec(value, &[], &["length", "percent"], false, self)
            },
            Self::DrawFitToContour => validate_spec(value, &[], &["boolean"], false, self),
            Self::DrawFitToSize => validate_spec(value, &[], &["boolean"], false, self),
            Self::DrawFrameDisplayBorder => validate_spec(value, &[], &["boolean"], false, self),
            Self::DrawFrameDisplayScrollbar => validate_spec(value, &[], &["boolean"], false, self),
            Self::DrawFrameMarginHorizontal => {
                validate_spec(value, &[], &["nonNegativePixelLength"], false, self)
            },
            Self::DrawFrameMarginVertical => {
                validate_spec(value, &[], &["nonNegativePixelLength"], false, self)
            },
            Self::DrawGamma => validate_spec(value, &[], &["percent"], false, self),
            Self::DrawGradientStepCount => {
                validate_spec(value, &[], &["nonNegativeInteger"], false, self)
            },
            Self::DrawGreen => {
                validate_spec(value, &[], &["signedZeroToHundredPercent"], false, self)
            },
            Self::DrawGuideDistance => validate_spec(value, &[], &["distance"], false, self),
            Self::DrawGuideOverhang => validate_spec(value, &[], &["length"], false, self),
            Self::DrawImageOpacity => {
                validate_spec(value, &[], &["zeroToHundredPercent"], false, self)
            },
            Self::DrawLineDistance => validate_spec(value, &[], &["distance"], false, self),
            Self::DrawLuminance => {
                validate_spec(value, &[], &["zeroToHundredPercent"], false, self)
            },
            Self::DrawMarkerEnd => validate_spec(value, &[], &["styleNameRef"], false, self),
            Self::DrawMarkerEndCenter => validate_spec(value, &[], &["boolean"], false, self),
            Self::DrawMarkerEndWidth => validate_spec(value, &[], &["length"], false, self),
            Self::DrawMarkerStart => validate_spec(value, &[], &["styleNameRef"], false, self),
            Self::DrawMarkerStartCenter => validate_spec(value, &[], &["boolean"], false, self),
            Self::DrawMarkerStartWidth => validate_spec(value, &[], &["length"], false, self),
            Self::DrawMeasureAlign => validate_spec(
                value,
                &["automatic", "inside", "left-outside", "right-outside"],
                &[],
                false,
                self,
            ),
            Self::DrawMeasureVerticalAlign => validate_spec(
                value,
                &["above", "automatic", "below", "center"],
                &[],
                false,
                self,
            ),
            Self::DrawOleDrawAspect => {
                validate_spec(value, &[], &["nonNegativeInteger"], false, self)
            },
            Self::DrawOpacity => validate_spec(value, &[], &["percent"], false, self),
            Self::DrawOpacityName => validate_spec(value, &[], &["styleNameRef"], false, self),
            Self::DrawParallel => validate_spec(value, &[], &["boolean"], false, self),
            Self::DrawPlacing => validate_spec(value, &["above", "below"], &[], false, self),
            Self::DrawRed => {
                validate_spec(value, &[], &["signedZeroToHundredPercent"], false, self)
            },
            Self::DrawSecondaryFillColor => validate_spec(value, &[], &["color"], false, self),
            Self::DrawShadow => validate_spec(value, &["hidden", "visible"], &[], false, self),
            Self::DrawShadowColor => validate_spec(value, &[], &["color"], false, self),
            Self::DrawShadowOffsetX => validate_spec(value, &[], &["length"], false, self),
            Self::DrawShadowOffsetY => validate_spec(value, &[], &["length"], false, self),
            Self::DrawShadowOpacity => {
                validate_spec(value, &[], &["zeroToHundredPercent"], false, self)
            },
            Self::DrawShowUnit => validate_spec(value, &[], &["boolean"], false, self),
            Self::DrawStartGuide => validate_spec(value, &[], &["length"], false, self),
            Self::DrawStartLineSpacingHorizontal => {
                validate_spec(value, &[], &["distance"], false, self)
            },
            Self::DrawStartLineSpacingVertical => {
                validate_spec(value, &[], &["distance"], false, self)
            },
            Self::DrawStroke => validate_spec(value, &["dash", "none", "solid"], &[], false, self),
            Self::DrawStrokeDash => validate_spec(value, &[], &["styleNameRef"], false, self),
            Self::DrawStrokeDashNames => validate_spec(value, &[], &["styleNameRefs"], false, self),
            Self::DrawStrokeLinejoin => validate_spec(
                value,
                &["bevel", "middle", "miter", "none", "round"],
                &[],
                false,
                self,
            ),
            Self::DrawSymbolColor => validate_spec(value, &[], &["color"], false, self),
            Self::DrawTextareaHorizontalAlign => validate_spec(
                value,
                &["center", "justify", "left", "right"],
                &[],
                false,
                self,
            ),
            Self::DrawTextareaVerticalAlign => validate_spec(
                value,
                &["bottom", "justify", "middle", "top"],
                &[],
                false,
                self,
            ),
            Self::DrawTileRepeatOffset => validate_spec(
                value,
                &["horizontal", "vertical"],
                &["zeroToHundredPercent"],
                true,
                self,
            ),
            Self::DrawUnit => validate_spec(
                value,
                &[
                    "automatic",
                    "cm",
                    "ft",
                    "inch",
                    "km",
                    "m",
                    "mi",
                    "mm",
                    "pc",
                    "pt",
                ],
                &[],
                false,
                self,
            ),
            Self::DrawVisibleAreaHeight => {
                validate_spec(value, &[], &["positiveLength"], false, self)
            },
            Self::DrawVisibleAreaLeft => {
                validate_spec(value, &[], &["nonNegativeLength"], false, self)
            },
            Self::DrawVisibleAreaTop => {
                validate_spec(value, &[], &["nonNegativeLength"], false, self)
            },
            Self::DrawVisibleAreaWidth => {
                validate_spec(value, &[], &["positiveLength"], false, self)
            },
            Self::DrawWrapInfluenceOnPosition => validate_spec(
                value,
                &["iterative", "once-concurrent", "once-successive"],
                &[],
                false,
                self,
            ),
            Self::FoBackgroundColor => {
                validate_spec(value, &["transparent"], &["color"], false, self)
            },
            Self::FoBorder => validate_spec(value, &[], &["string"], false, self),
            Self::FoBorderBottom => validate_spec(value, &[], &["string"], false, self),
            Self::FoBorderLeft => validate_spec(value, &[], &["string"], false, self),
            Self::FoBorderRight => validate_spec(value, &[], &["string"], false, self),
            Self::FoBorderTop => validate_spec(value, &[], &["string"], false, self),
            Self::FoClip => validate_spec(value, &["auto"], &["clipShape"], false, self),
            Self::FoMargin => {
                validate_spec(value, &[], &["nonNegativeLength", "percent"], false, self)
            },
            Self::FoMarginBottom => {
                validate_spec(value, &[], &["nonNegativeLength", "percent"], false, self)
            },
            Self::FoMarginLeft => validate_spec(value, &[], &["length", "percent"], false, self),
            Self::FoMarginRight => validate_spec(value, &[], &["length", "percent"], false, self),
            Self::FoMarginTop => {
                validate_spec(value, &[], &["nonNegativeLength", "percent"], false, self)
            },
            Self::FoMaxHeight => validate_spec(value, &[], &["length", "percent"], false, self),
            Self::FoMaxWidth => validate_spec(value, &[], &["length", "percent"], false, self),
            Self::FoMinHeight => validate_spec(value, &[], &["length", "percent"], false, self),
            Self::FoMinWidth => validate_spec(value, &[], &["length", "percent"], false, self),
            Self::FoPadding => validate_spec(value, &[], &["nonNegativeLength"], false, self),
            Self::FoPaddingBottom => validate_spec(value, &[], &["nonNegativeLength"], false, self),
            Self::FoPaddingLeft => validate_spec(value, &[], &["nonNegativeLength"], false, self),
            Self::FoPaddingRight => validate_spec(value, &[], &["nonNegativeLength"], false, self),
            Self::FoPaddingTop => validate_spec(value, &[], &["nonNegativeLength"], false, self),
            Self::FoWrapOption => validate_spec(value, &["no-wrap", "wrap"], &[], false, self),
            Self::StyleBackgroundTransparency => {
                validate_spec(value, &[], &["zeroToHundredPercent"], false, self)
            },
            Self::StyleBorderLineWidth => validate_spec(value, &[], &["borderWidths"], false, self),
            Self::StyleBorderLineWidthBottom => {
                validate_spec(value, &[], &["borderWidths"], false, self)
            },
            Self::StyleBorderLineWidthLeft => {
                validate_spec(value, &[], &["borderWidths"], false, self)
            },
            Self::StyleBorderLineWidthRight => {
                validate_spec(value, &[], &["borderWidths"], false, self)
            },
            Self::StyleBorderLineWidthTop => {
                validate_spec(value, &[], &["borderWidths"], false, self)
            },
            Self::StyleEditable => validate_spec(value, &[], &["boolean"], false, self),
            Self::StyleFlowWithText => validate_spec(value, &[], &["boolean"], false, self),
            Self::StyleHorizontalPos => validate_spec(
                value,
                &[
                    "center",
                    "from-inside",
                    "from-left",
                    "inside",
                    "left",
                    "outside",
                    "right",
                ],
                &[],
                false,
                self,
            ),
            Self::StyleHorizontalRel => validate_spec(
                value,
                &[
                    "char",
                    "frame",
                    "frame-content",
                    "frame-end-margin",
                    "frame-start-margin",
                    "page",
                    "page-content",
                    "page-end-margin",
                    "page-start-margin",
                    "paragraph",
                    "paragraph-content",
                    "paragraph-end-margin",
                    "paragraph-start-margin",
                ],
                &[],
                false,
                self,
            ),
            Self::StyleMirror => validate_spec(
                value,
                &["none", "vertical"],
                &["horizontal-mirror"],
                true,
                self,
            ),
            Self::StyleNumberWrappedParagraphs => {
                validate_spec(value, &["no-limit"], &["positiveInteger"], false, self)
            },
            Self::StyleOverflowBehavior => {
                validate_spec(value, &["auto-create-new-frame", "clip"], &[], false, self)
            },
            Self::StylePrintContent => validate_spec(value, &[], &["boolean"], false, self),
            Self::StyleProtect => validate_spec(
                value,
                &["content", "none", "position", "size"],
                &[],
                true,
                self,
            ),
            Self::StyleRelHeight => {
                validate_spec(value, &["scale", "scale-min"], &["percent"], false, self)
            },
            Self::StyleRelWidth => {
                validate_spec(value, &["scale", "scale-min"], &["percent"], false, self)
            },
            Self::StyleRepeat => {
                validate_spec(value, &["no-repeat", "repeat", "stretch"], &[], false, self)
            },
            Self::StyleRunThrough => {
                validate_spec(value, &["background", "foreground"], &[], false, self)
            },
            Self::StyleShadow => validate_spec(value, &[], &["shadowType"], false, self),
            Self::StyleShrinkToFit => validate_spec(value, &[], &["boolean"], false, self),
            Self::StyleVerticalPos => validate_spec(
                value,
                &["below", "bottom", "from-top", "middle", "top"],
                &[],
                false,
                self,
            ),
            Self::StyleVerticalRel => validate_spec(
                value,
                &[
                    "baseline",
                    "char",
                    "frame",
                    "frame-content",
                    "line",
                    "page",
                    "page-content",
                    "paragraph",
                    "paragraph-content",
                    "text",
                ],
                &[],
                false,
                self,
            ),
            Self::StyleWrap => validate_spec(
                value,
                &[
                    "biggest",
                    "dynamic",
                    "left",
                    "none",
                    "parallel",
                    "right",
                    "run-through",
                ],
                &[],
                false,
                self,
            ),
            Self::StyleWrapContour => validate_spec(value, &[], &["boolean"], false, self),
            Self::StyleWrapContourMode => {
                validate_spec(value, &["full", "outside"], &[], false, self)
            },
            Self::StyleWrapDynamicThreshold => {
                validate_spec(value, &[], &["nonNegativeLength"], false, self)
            },
            Self::StyleWritingMode => validate_spec(
                value,
                &["lr", "lr-tb", "page", "rl", "rl-tb", "tb", "tb-lr", "tb-rl"],
                &[],
                false,
                self,
            ),
            Self::SvgFillRule => validate_spec(value, &["evenodd", "nonzero"], &[], false, self),
            Self::SvgHeight => validate_spec(value, &[], &["length"], false, self),
            Self::SvgStrokeColor => validate_spec(value, &[], &["color"], false, self),
            Self::SvgStrokeLinecap => {
                validate_spec(value, &["butt", "round", "square"], &[], false, self)
            },
            Self::SvgStrokeOpacity => {
                validate_spec(value, &[], &["zeroToHundredPercent"], false, self)
            },
            Self::SvgStrokeWidth => validate_spec(value, &[], &["length"], false, self),
            Self::SvgWidth => validate_spec(value, &[], &["length"], false, self),
            Self::SvgX => validate_spec(value, &[], &["coordinate"], false, self),
            Self::SvgY => validate_spec(value, &[], &["coordinate"], false, self),
            Self::TextAnchorPageNumber => {
                validate_spec(value, &[], &["positiveInteger"], false, self)
            },
            Self::TextAnchorType => validate_spec(
                value,
                &["as-char", "char", "frame", "page", "paragraph"],
                &[],
                false,
                self,
            ),
            Self::TextAnimation => validate_spec(
                value,
                &["alternate", "none", "scroll", "slide"],
                &[],
                false,
                self,
            ),
            Self::TextAnimationDelay => validate_spec(value, &[], &["duration"], false, self),
            Self::TextAnimationDirection => {
                validate_spec(value, &["down", "left", "right", "up"], &[], false, self)
            },
            Self::TextAnimationRepeat => {
                validate_spec(value, &[], &["nonNegativeInteger"], false, self)
            },
            Self::TextAnimationStartInside => validate_spec(value, &[], &["boolean"], false, self),
            Self::TextAnimationSteps => validate_spec(value, &[], &["length"], false, self),
            Self::TextAnimationStopInside => validate_spec(value, &[], &["boolean"], false, self),
        }
    }
    pub fn example(self) -> &'static str {
        match self {
            Self::Dr3dAmbientColor => "#102030",
            Self::Dr3dBackScale => "-.5%",
            Self::Dr3dBackfaceCulling => "disabled",
            Self::Dr3dCloseBack => "true",
            Self::Dr3dCloseFront => "true",
            Self::Dr3dDepth => "-0.5cm",
            Self::Dr3dDiffuseColor => "#102030",
            Self::Dr3dEdgeRounding => "-.5%",
            Self::Dr3dEdgeRoundingMode => "attractive",
            Self::Dr3dEmissiveColor => "#102030",
            Self::Dr3dEndAngle => "sample",
            Self::Dr3dHorizontalSegments => "000",
            Self::Dr3dLightingMode => "double-sided",
            Self::Dr3dNormalsDirection => "inverse",
            Self::Dr3dNormalsKind => "flat",
            Self::Dr3dShadow => "hidden",
            Self::Dr3dShininess => "-.5%",
            Self::Dr3dSpecularColor => "#102030",
            Self::Dr3dTextureFilter => "disabled",
            Self::Dr3dTextureGenerationModeX => "object",
            Self::Dr3dTextureGenerationModeY => "object",
            Self::Dr3dTextureKind => "color",
            Self::Dr3dTextureMode => "blend",
            Self::Dr3dVerticalSegments => "000",
            Self::DrawAutoGrowHeight => "true",
            Self::DrawAutoGrowWidth => "true",
            Self::DrawBlue => "-100%",
            Self::DrawCaptionAngle => "sample",
            Self::DrawCaptionAngleType => "fixed",
            Self::DrawCaptionEscape => "-0.5cm",
            Self::DrawCaptionEscapeDirection => "auto",
            Self::DrawCaptionFitLineLength => "true",
            Self::DrawCaptionGap => "-0.5cm",
            Self::DrawCaptionLineLength => "-0.5cm",
            Self::DrawCaptionType => "angled-connector-line",
            Self::DrawColorInversion => "true",
            Self::DrawColorMode => "greyscale",
            Self::DrawContrast => "-.5%",
            Self::DrawDecimalPlaces => "000",
            Self::DrawDrawAspect => "content",
            Self::DrawEndGuide => "-0.5cm",
            Self::DrawEndLineSpacingHorizontal => "-0.5cm",
            Self::DrawEndLineSpacingVertical => "-0.5cm",
            Self::DrawFill => "bitmap",
            Self::DrawFillColor => "#102030",
            Self::DrawFillGradientName => "name_1",
            Self::DrawFillHatchName => "name_1",
            Self::DrawFillHatchSolid => "true",
            Self::DrawFillImageHeight => "-0.5cm",
            Self::DrawFillImageName => "name_1",
            Self::DrawFillImageRefPoint => "bottom",
            Self::DrawFillImageRefPointX => "-.5%",
            Self::DrawFillImageRefPointY => "-.5%",
            Self::DrawFillImageWidth => "-0.5cm",
            Self::DrawFitToContour => "true",
            Self::DrawFitToSize => "true",
            Self::DrawFrameDisplayBorder => "true",
            Self::DrawFrameDisplayScrollbar => "true",
            Self::DrawFrameMarginHorizontal => "0px",
            Self::DrawFrameMarginVertical => "0px",
            Self::DrawGamma => "-.5%",
            Self::DrawGradientStepCount => "000",
            Self::DrawGreen => "-100%",
            Self::DrawGuideDistance => "-0.5cm",
            Self::DrawGuideOverhang => "-0.5cm",
            Self::DrawImageOpacity => "100.0%",
            Self::DrawLineDistance => "-0.5cm",
            Self::DrawLuminance => "100.0%",
            Self::DrawMarkerEnd => "name_1",
            Self::DrawMarkerEndCenter => "true",
            Self::DrawMarkerEndWidth => "-0.5cm",
            Self::DrawMarkerStart => "name_1",
            Self::DrawMarkerStartCenter => "true",
            Self::DrawMarkerStartWidth => "-0.5cm",
            Self::DrawMeasureAlign => "automatic",
            Self::DrawMeasureVerticalAlign => "above",
            Self::DrawOleDrawAspect => "000",
            Self::DrawOpacity => "-.5%",
            Self::DrawOpacityName => "name_1",
            Self::DrawParallel => "true",
            Self::DrawPlacing => "above",
            Self::DrawRed => "-100%",
            Self::DrawSecondaryFillColor => "#102030",
            Self::DrawShadow => "hidden",
            Self::DrawShadowColor => "#102030",
            Self::DrawShadowOffsetX => "-0.5cm",
            Self::DrawShadowOffsetY => "-0.5cm",
            Self::DrawShadowOpacity => "100.0%",
            Self::DrawShowUnit => "true",
            Self::DrawStartGuide => "-0.5cm",
            Self::DrawStartLineSpacingHorizontal => "-0.5cm",
            Self::DrawStartLineSpacingVertical => "-0.5cm",
            Self::DrawStroke => "dash",
            Self::DrawStrokeDash => "name_1",
            Self::DrawStrokeDashNames => "one two",
            Self::DrawStrokeLinejoin => "bevel",
            Self::DrawSymbolColor => "#102030",
            Self::DrawTextareaHorizontalAlign => "center",
            Self::DrawTextareaVerticalAlign => "bottom",
            Self::DrawTileRepeatOffset => "50% horizontal",
            Self::DrawUnit => "automatic",
            Self::DrawVisibleAreaHeight => ".1cm",
            Self::DrawVisibleAreaLeft => "0cm",
            Self::DrawVisibleAreaTop => "0cm",
            Self::DrawVisibleAreaWidth => ".1cm",
            Self::DrawWrapInfluenceOnPosition => "iterative",
            Self::FoBackgroundColor => "transparent",
            Self::FoBorder => "sample",
            Self::FoBorderBottom => "sample",
            Self::FoBorderLeft => "sample",
            Self::FoBorderRight => "sample",
            Self::FoBorderTop => "sample",
            Self::FoClip => "auto",
            Self::FoMargin => "0cm",
            Self::FoMarginBottom => "0cm",
            Self::FoMarginLeft => "-0.5cm",
            Self::FoMarginRight => "-0.5cm",
            Self::FoMarginTop => "0cm",
            Self::FoMaxHeight => "-0.5cm",
            Self::FoMaxWidth => "-0.5cm",
            Self::FoMinHeight => "-0.5cm",
            Self::FoMinWidth => "-0.5cm",
            Self::FoPadding => "0cm",
            Self::FoPaddingBottom => "0cm",
            Self::FoPaddingLeft => "0cm",
            Self::FoPaddingRight => "0cm",
            Self::FoPaddingTop => "0cm",
            Self::FoWrapOption => "no-wrap",
            Self::StyleBackgroundTransparency => "100.0%",
            Self::StyleBorderLineWidth => "1pt 2pt 3pt",
            Self::StyleBorderLineWidthBottom => "1pt 2pt 3pt",
            Self::StyleBorderLineWidthLeft => "1pt 2pt 3pt",
            Self::StyleBorderLineWidthRight => "1pt 2pt 3pt",
            Self::StyleBorderLineWidthTop => "1pt 2pt 3pt",
            Self::StyleEditable => "true",
            Self::StyleFlowWithText => "true",
            Self::StyleHorizontalPos => "center",
            Self::StyleHorizontalRel => "char",
            Self::StyleMirror => "none",
            Self::StyleNumberWrappedParagraphs => "no-limit",
            Self::StyleOverflowBehavior => "auto-create-new-frame",
            Self::StylePrintContent => "true",
            Self::StyleProtect => "content",
            Self::StyleRelHeight => "scale",
            Self::StyleRelWidth => "scale",
            Self::StyleRepeat => "no-repeat",
            Self::StyleRunThrough => "background",
            Self::StyleShadow => "sample",
            Self::StyleShrinkToFit => "true",
            Self::StyleVerticalPos => "below",
            Self::StyleVerticalRel => "baseline",
            Self::StyleWrap => "biggest",
            Self::StyleWrapContour => "true",
            Self::StyleWrapContourMode => "full",
            Self::StyleWrapDynamicThreshold => "0cm",
            Self::StyleWritingMode => "lr",
            Self::SvgFillRule => "evenodd",
            Self::SvgHeight => "-0.5cm",
            Self::SvgStrokeColor => "#102030",
            Self::SvgStrokeLinecap => "butt",
            Self::SvgStrokeOpacity => "100.0%",
            Self::SvgStrokeWidth => "-0.5cm",
            Self::SvgWidth => "-0.5cm",
            Self::SvgX => "-0.5cm",
            Self::SvgY => "-0.5cm",
            Self::TextAnchorPageNumber => "01",
            Self::TextAnchorType => "as-char",
            Self::TextAnimation => "alternate",
            Self::TextAnimationDelay => "PT1.5S",
            Self::TextAnimationDirection => "down",
            Self::TextAnimationRepeat => "000",
            Self::TextAnimationStartInside => "true",
            Self::TextAnimationSteps => "-0.5cm",
            Self::TextAnimationStopInside => "true",
        }
    }
}
use super::codec::validate_spec;
use litchi_core::Result;

/// Closed namespaces used by the 174 graphic property names.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Namespace {
    Dr3d,
    Draw,
    Fo,
    Style,
    Svg,
    Text,
}

impl Namespace {
    pub(crate) fn prefix(self) -> &'static str {
        match self {
            Self::Dr3d => "dr3d",
            Self::Draw => "draw",
            Self::Fo => "fo",
            Self::Style => "style",
            Self::Svg => "svg",
            Self::Text => "text",
        }
    }
}

/// A lexically validated value whose variant identifies its normative datatype.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Value {
    Boolean(bool),
    Color(String),
    Length(String),
    NonNegativeLength(String),
    PositiveLength(String),
    NonNegativePixelLength(String),
    Percent(String),
    ZeroToHundredPercent(String),
    SignedZeroToHundredPercent(String),
    NonNegativeInteger(String),
    PositiveInteger(String),
    Duration(String),
    Clip(String),
    StyleNameRef(String),
    StyleNameRefs(Vec<String>),
    Keyword(String),
    Text(String),
    Compound(String),
}

impl Value {
    pub fn lexical(&self) -> String {
        match self {
            Self::Boolean(value) => value.to_string(),
            Self::Color(value)
            | Self::Length(value)
            | Self::NonNegativeLength(value)
            | Self::PositiveLength(value)
            | Self::NonNegativePixelLength(value)
            | Self::Percent(value)
            | Self::ZeroToHundredPercent(value)
            | Self::SignedZeroToHundredPercent(value)
            | Self::NonNegativeInteger(value)
            | Self::PositiveInteger(value)
            | Self::Duration(value)
            | Self::Clip(value)
            | Self::StyleNameRef(value)
            | Self::Keyword(value)
            | Self::Text(value)
            | Self::Compound(value) => value.clone(),
            Self::StyleNameRefs(values) => values.join(" "),
        }
    }
}
