[package]
name = "ppt0634"
version = "0.0.0"
edition = "2024"

[workspace]

[[bin]]
name = "ppt0634"
path = "src/main.rs"

[[bin]]
name = "ppt0634_alloc"
path = "src/alloc.rs"

[dependencies]
litchi-core = { path = "@ROOT@/crates/litchi-core" }
litchi-cfb = { path = "@ROOT@/crates/litchi-cfb" }
litchi-ppt = { path = "@ROOT@/crates/litchi-ppt" }

[profile.release]
debug = false
strip = false
