//! Bounded, source-backed inspection of ODS content-validation ownership.
//!
//! This module is deliberately read-only. It inventories the document-level
//! validation catalog and the physical cell runs that bind catalog names. The
//! complete source XML remains borrowed by [`Snapshot`], so foreign markup,
//! comments, processing instructions, prefix choices, and lexical forms are
//! never regenerated by this API.

use core::fmt;
use quick_xml::{
    XmlVersion,
    events::{BytesStart, Event},
    name::{Namespace, ResolveResult},
    reader::NsReader,
};
use std::collections::{HashMap, HashSet};

struct AttributeNamespaceIds {
    namespace_ids: HashMap<Vec<u8>, usize>,
    prefix_ids: HashMap<Vec<u8>, usize>,
    #[cfg(test)]
    namespace_content_lookups: usize,
}

impl AttributeNamespaceIds {
    fn with_capacity(estimate: usize) -> Result<Self> {
        let capacity = estimate.min(64);
        let mut namespace_ids = HashMap::new();
        namespace_ids
            .try_reserve(capacity)
            .map_err(|_error| Error::AllocationFailed("expanded attribute namespaces"))?;
        let mut prefix_ids = HashMap::new();
        prefix_ids
            .try_reserve(capacity)
            .map_err(|_error| Error::AllocationFailed("attribute prefix index"))?;
        Ok(Self {
            namespace_ids,
            prefix_ids,
            #[cfg(test)]
            namespace_content_lookups: 0,
        })
    }

    fn id(&mut self, prefix: &[u8], namespace: &[u8]) -> Result<usize> {
        if let Some(id) = self.prefix_ids.get(prefix) {
            return Ok(*id);
        }
        #[cfg(test)]
        {
            self.namespace_content_lookups += 1;
        }
        let id = if let Some(id) = self.namespace_ids.get(namespace) {
            *id
        } else {
            self.namespace_ids
                .try_reserve(1)
                .map_err(|_error| Error::AllocationFailed("attribute namespace index"))?;
            let id = self.namespace_ids.len();
            self.namespace_ids
                .insert(copy_bytes(namespace, "attribute namespace")?, id);
            id
        };
        self.prefix_ids
            .try_reserve(1)
            .map_err(|_error| Error::AllocationFailed("attribute prefix index"))?;
        self.prefix_ids
            .insert(copy_bytes(prefix, "attribute prefix")?, id);
        Ok(id)
    }

    #[cfg(test)]
    fn namespace_content_lookups(&self) -> usize {
        self.namespace_content_lookups
    }
}

const OFFICE: &[u8] = b"urn:oasis:names:tc:opendocument:xmlns:office:1.0";
const TABLE: &[u8] = b"urn:oasis:names:tc:opendocument:xmlns:table:1.0";
const TEXT: &[u8] = b"urn:oasis:names:tc:opendocument:xmlns:text:1.0";
const SCRIPT: &[u8] = b"urn:oasis:names:tc:opendocument:xmlns:script:1.0";
const PRESENTATION: &[u8] = b"urn:oasis:names:tc:opendocument:xmlns:presentation:1.0";
const MCE: &[u8] = b"http://schemas.openxmlformats.org/markup-compatibility/2006";

const MAX_INPUT_BYTES: usize = 256 * 1024 * 1024;
const MAX_EVENTS: usize = 4_000_000;
const MAX_ATTRIBUTES: usize = 4_000_000;
const MAX_DEPTH: usize = 1_024;
const MAX_DEFINITIONS: usize = 65_536;
const MAX_SHEETS: usize = 65_536;
const MAX_BINDINGS: usize = 1_000_000;
const MAX_TEXT_BYTES: usize = 64 * 1024 * 1024;
const MAX_LOGICAL_ROWS: usize = 16_777_216;
const MAX_LOGICAL_COLUMNS: usize = 1_048_576;

/// A content-validation inspection result.
pub type Result<T> = std::result::Result<T, Error>;

/// The resource whose configured or observed value exceeded a limit.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub enum LimitKind {
    InputBytes,
    Events,
    Attributes,
    Depth,
    Definitions,
    Sheets,
    Bindings,
    TextBytes,
    LogicalRows,
    LogicalColumns,
}

/// Errors produced by source-backed content-validation inspection.
#[derive(Clone, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub enum Error {
    /// A configured or hard resource limit was exceeded.
    LimitExceeded {
        kind: LimitKind,
        observed: usize,
        maximum: usize,
    },
    /// An owned allocation could not be reserved.
    AllocationFailed(&'static str),
    /// The XML byte stream is malformed.
    InvalidXml(String),
    /// Validation ownership or placement is malformed or ambiguous.
    InvalidStructure(String),
    /// Markup Compatibility requires branch selection this reader does not perform.
    UnsupportedMarkupCompatibility,
}

impl fmt::Display for Error {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::LimitExceeded {
                kind,
                observed,
                maximum,
            } => write!(
                formatter,
                "ODS content-validation {kind:?} limit exceeded: observed {observed}, maximum {maximum}"
            ),
            Self::AllocationFailed(owner) => {
                write!(
                    formatter,
                    "could not allocate ODS content-validation {owner}"
                )
            },
            Self::InvalidXml(message) | Self::InvalidStructure(message) => {
                formatter.write_str(message)
            },
            Self::UnsupportedMarkupCompatibility => formatter.write_str(
                "ODS content-validation inspection does not select Markup Compatibility branches",
            ),
        }
    }
}

impl std::error::Error for Error {}

/// Caller-selected resource limits, each capped by a fixed implementation ceiling.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Limits {
    input_bytes: usize,
    events: usize,
    attributes: usize,
    depth: usize,
    definitions: usize,
    sheets: usize,
    bindings: usize,
    text_bytes: usize,
    logical_rows: usize,
    logical_columns: usize,
}

impl Default for Limits {
    fn default() -> Self {
        Self {
            input_bytes: MAX_INPUT_BYTES,
            events: MAX_EVENTS,
            attributes: MAX_ATTRIBUTES,
            depth: MAX_DEPTH,
            definitions: MAX_DEFINITIONS,
            sheets: MAX_SHEETS,
            bindings: MAX_BINDINGS,
            text_bytes: MAX_TEXT_BYTES,
            logical_rows: MAX_LOGICAL_ROWS,
            logical_columns: MAX_LOGICAL_COLUMNS,
        }
    }
}

macro_rules! limit_setter {
    ($name:ident, $field:ident) => {
        #[must_use]
        pub const fn $name(mut self, value: usize) -> Self {
            self.$field = value;
            self
        }
    };
}

impl Limits {
    limit_setter!(with_input_bytes, input_bytes);
    limit_setter!(with_events, events);
    limit_setter!(with_attributes, attributes);
    limit_setter!(with_depth, depth);
    limit_setter!(with_definitions, definitions);
    limit_setter!(with_sheets, sheets);
    limit_setter!(with_bindings, bindings);
    limit_setter!(with_text_bytes, text_bytes);
    limit_setter!(with_logical_rows, logical_rows);
    limit_setter!(with_logical_columns, logical_columns);

    fn validate(self) -> Result<Self> {
        for (kind, observed, maximum) in [
            (LimitKind::InputBytes, self.input_bytes, MAX_INPUT_BYTES),
            (LimitKind::Events, self.events, MAX_EVENTS),
            (LimitKind::Attributes, self.attributes, MAX_ATTRIBUTES),
            (LimitKind::Depth, self.depth, MAX_DEPTH),
            (LimitKind::Definitions, self.definitions, MAX_DEFINITIONS),
            (LimitKind::Sheets, self.sheets, MAX_SHEETS),
            (LimitKind::Bindings, self.bindings, MAX_BINDINGS),
            (LimitKind::TextBytes, self.text_bytes, MAX_TEXT_BYTES),
            (LimitKind::LogicalRows, self.logical_rows, MAX_LOGICAL_ROWS),
            (
                LimitKind::LogicalColumns,
                self.logical_columns,
                MAX_LOGICAL_COLUMNS,
            ),
        ] {
            if observed > maximum {
                return Err(Error::LimitExceeded {
                    kind,
                    observed,
                    maximum,
                });
            }
        }
        Ok(self)
    }
}

/// How a validation list is presented by the producer.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub enum DisplayList {
    None,
    Unsorted,
    SortAscending,
}

/// One document-level `table:content-validation` declaration.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Definition {
    name: String,
    condition: Option<String>,
    base_cell_address: Option<String>,
    allow_empty_cell: Option<bool>,
    display_list: Option<DisplayList>,
    opaque_content: bool,
}

impl Definition {
    #[must_use]
    pub fn name(&self) -> &str {
        &self.name
    }

    #[must_use]
    pub fn condition(&self) -> Option<&str> {
        self.condition.as_deref()
    }

    #[must_use]
    pub fn base_cell_address(&self) -> Option<&str> {
        self.base_cell_address.as_deref()
    }

    #[must_use]
    pub const fn allow_empty_cell(&self) -> Option<bool> {
        self.allow_empty_cell
    }

    #[must_use]
    pub const fn display_list(&self) -> Option<DisplayList> {
        self.display_list
    }

    /// Whether foreign markup, comments, or processing instructions occur in this owner.
    #[must_use]
    pub const fn has_opaque_content(&self) -> bool {
        self.opaque_content
    }
}

/// A compact rectangular binding created by one physical cell run.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Binding {
    row: usize,
    column: usize,
    row_count: usize,
    column_count: usize,
    validation_name: String,
    definition_index: Option<usize>,
    covered: bool,
}

impl Binding {
    #[must_use]
    pub const fn row(&self) -> usize {
        self.row
    }

    #[must_use]
    pub const fn column(&self) -> usize {
        self.column
    }

    #[must_use]
    pub const fn row_count(&self) -> usize {
        self.row_count
    }

    #[must_use]
    pub const fn column_count(&self) -> usize {
        self.column_count
    }

    #[must_use]
    pub fn validation_name(&self) -> &str {
        &self.validation_name
    }

    /// The matching definition position, or `None` for a dangling reference.
    #[must_use]
    pub const fn definition_index(&self) -> Option<usize> {
        self.definition_index
    }

    #[must_use]
    pub const fn is_dangling(&self) -> bool {
        self.definition_index.is_none()
    }

    #[must_use]
    pub const fn is_covered_cell(&self) -> bool {
        self.covered
    }
}

/// Validation bindings belonging to one table, in physical source order.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Sheet {
    name: String,
    logical_rows: usize,
    bindings: Vec<Binding>,
}

impl Sheet {
    #[must_use]
    pub fn name(&self) -> &str {
        &self.name
    }

    #[must_use]
    pub const fn logical_row_count(&self) -> usize {
        self.logical_rows
    }

    #[must_use]
    pub fn bindings(&self) -> &[Binding] {
        &self.bindings
    }
}

/// Immutable, read-only validation ownership projected from one exact XML source.
#[derive(Debug, PartialEq, Eq)]
pub struct Snapshot<'xml> {
    source_xml: &'xml str,
    definitions: Vec<Definition>,
    sheets: Vec<Sheet>,
    definition_index: Vec<usize>,
    sheet_index: Vec<usize>,
    catalog_opaque_content: bool,
    binding_opaque_content: bool,
    dangling_bindings: usize,
}

impl<'xml> Snapshot<'xml> {
    /// Parse a canonical ODS `content.xml` owner with default limits.
    pub fn parse(source_xml: &'xml str) -> Result<Self> {
        Self::parse_with_limits(source_xml, Limits::default())
    }

    /// Parse a canonical ODS `content.xml` owner with caller-selected limits.
    pub fn parse_with_limits(source_xml: &'xml str, limits: Limits) -> Result<Self> {
        Parser::new(source_xml, limits.validate()?).parse()
    }

    /// The complete, unchanged XML source backing this inventory.
    #[must_use]
    pub const fn source_xml(&self) -> &'xml str {
        self.source_xml
    }

    #[must_use]
    pub fn definitions(&self) -> &[Definition] {
        &self.definitions
    }

    #[must_use]
    pub fn sheets(&self) -> &[Sheet] {
        &self.sheets
    }

    #[must_use]
    pub fn definition(&self, name: &str) -> Option<&Definition> {
        self.definition_index
            .binary_search_by(|index| self.definitions[*index].name.as_str().cmp(name))
            .ok()
            .map(|position| &self.definitions[self.definition_index[position]])
    }

    #[must_use]
    pub fn sheet(&self, name: &str) -> Option<&Sheet> {
        self.sheet_index
            .binary_search_by(|index| self.sheets[*index].name.as_str().cmp(name))
            .ok()
            .map(|position| &self.sheets[self.sheet_index[position]])
    }

    /// Foreign catalog children, comments, or processing instructions were retained.
    #[must_use]
    pub const fn has_opaque_catalog_content(&self) -> bool {
        self.catalog_opaque_content
    }

    #[must_use]
    pub const fn dangling_binding_count(&self) -> usize {
        self.dangling_bindings
    }

    /// Whether opaque content occurs inside a physical bound-cell owner.
    #[must_use]
    pub const fn has_opaque_binding_content(&self) -> bool {
        self.binding_opaque_content
    }

    /// Whether catalog ownership and every binding reference are fully understood.
    ///
    /// This is an inspection result, not permission to edit or publish the owner.
    #[must_use]
    pub fn has_complete_reference_closure(&self) -> bool {
        self.dangling_bindings == 0
            && !self.catalog_opaque_content
            && !self.binding_opaque_content
            && self
                .definitions
                .iter()
                .all(|definition| !definition.opaque_content)
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum NamespaceKind {
    Office,
    Table,
    Text,
    Script,
    Presentation,
    Other,
}

#[derive(Debug)]
enum Element {
    Root,
    Body,
    Spreadsheet,
    Catalog(usize),
    Definition,
    Sheet(usize),
    RowContainer(usize),
    Row {
        sheet: usize,
        start: usize,
        count: usize,
        next_column: usize,
    },
    Cell(bool),
    Other,
}

struct Parser<'xml> {
    source_xml: &'xml str,
    limits: Limits,
    definitions: Vec<Definition>,
    sheets: Vec<Sheet>,
    stack: Vec<Element>,
    events: usize,
    attributes: usize,
    text_bytes: usize,
    binding_count: usize,
    seen_root: bool,
    seen_body: bool,
    seen_spreadsheet: bool,
    closed_root: bool,
    seen_catalog: bool,
    seen_table: bool,
    spreadsheet_prelude_complete: bool,
    catalog_active: bool,
    active_definition: Option<usize>,
    definition_state: Option<DefinitionState>,
    catalog_opaque_content: bool,
    binding_opaque_content: bool,
}

#[derive(Default)]
struct DefinitionState {
    seen_help: bool,
    seen_error_message: bool,
    seen_error_macro: bool,
}

impl<'xml> Parser<'xml> {
    fn new(source_xml: &'xml str, limits: Limits) -> Self {
        Self {
            source_xml,
            limits,
            definitions: Vec::new(),
            sheets: Vec::new(),
            stack: Vec::new(),
            events: 0,
            attributes: 0,
            text_bytes: 0,
            binding_count: 0,
            seen_root: false,
            seen_body: false,
            seen_spreadsheet: false,
            closed_root: false,
            seen_catalog: false,
            seen_table: false,
            spreadsheet_prelude_complete: false,
            catalog_active: false,
            active_definition: None,
            definition_state: None,
            catalog_opaque_content: false,
            binding_opaque_content: false,
        }
    }

    fn parse(mut self) -> Result<Snapshot<'xml>> {
        check_limit(
            LimitKind::InputBytes,
            self.source_xml.len(),
            self.limits.input_bytes,
        )?;
        self.stack
            .try_reserve(self.limits.depth.min(256))
            .map_err(|_error| Error::AllocationFailed("element stack"))?;
        self.definitions
            .try_reserve(self.limits.definitions.min(256))
            .map_err(|_error| Error::AllocationFailed("definition catalog"))?;
        self.sheets
            .try_reserve(self.limits.sheets.min(64))
            .map_err(|_error| Error::AllocationFailed("sheet inventory"))?;

        let mut reader = NsReader::from_str(self.source_xml);
        reader.config_mut().check_end_names = true;
        reader.config_mut().trim_text(false);
        loop {
            let (resolved, event) = reader.read_resolved_event().map_err(|error| {
                Error::InvalidXml(format!("invalid ODS content-validation XML: {error}"))
            })?;
            self.events = checked_add(self.events, 1, "XML event counter")?;
            check_limit(LimitKind::Events, self.events, self.limits.events)?;
            let namespace = namespace_kind(&resolved)?;
            match event {
                Event::Start(start) => self.start(namespace, &start, &reader, false)?,
                Event::Empty(start) => self.start(namespace, &start, &reader, true)?,
                Event::End(_) => self.end()?,
                Event::Text(text) => {
                    let decoded = text
                        .xml_content(XmlVersion::Explicit1_0)
                        .map_err(|error| Error::InvalidXml(format!("invalid XML text: {error}")))?;
                    if self.stack.is_empty() {
                        if !decoded.trim().is_empty() {
                            return Err(Error::InvalidStructure(
                                "ODS content-validation XML has text outside its root".to_string(),
                            ));
                        }
                    } else if !decoded.trim().is_empty() {
                        self.mark_opaque();
                    }
                },
                Event::Comment(_) | Event::PI(_) => self.mark_opaque(),
                Event::DocType(_) | Event::GeneralRef(_) => {
                    return Err(Error::InvalidStructure(
                        "ODS content-validation inspection rejects DTDs and entity references"
                            .to_string(),
                    ));
                },
                Event::CData(_) => self.mark_opaque(),
                Event::Decl(_) => {},
                Event::Eof => break,
            }
        }
        if !self.seen_root
            || !self.seen_body
            || !self.seen_spreadsheet
            || !self.closed_root
            || !self.stack.is_empty()
        {
            return Err(Error::InvalidStructure(
                "ODS content-validation XML lacks a complete document-content envelope".to_string(),
            ));
        }
        self.finish()
    }

    fn start(
        &mut self,
        namespace: NamespaceKind,
        start: &BytesStart<'_>,
        reader: &NsReader<&[u8]>,
        empty: bool,
    ) -> Result<()> {
        check_limit(
            LimitKind::Depth,
            self.stack.len().saturating_add(1),
            self.limits.depth,
        )?;
        self.validate_attributes(start, reader)?;
        let local = start.local_name();
        let local = local.as_ref();
        if self.has_attribute(start, reader, TABLE, b"content-validation-name")?
            && !(namespace == NamespaceKind::Table
                && matches!(local, b"table-cell" | b"covered-table-cell"))
        {
            return invalid("table:content-validation-name is only valid on a table cell owner");
        }
        let element = self.classify(namespace, local, start, reader)?;
        if empty {
            self.finish_element(element)?;
        } else {
            self.stack
                .try_reserve(1)
                .map_err(|_error| Error::AllocationFailed("element stack"))?;
            self.stack.push(element);
        }
        Ok(())
    }

    fn classify(
        &mut self,
        namespace: NamespaceKind,
        local: &[u8],
        start: &BytesStart<'_>,
        reader: &NsReader<&[u8]>,
    ) -> Result<Element> {
        if namespace == NamespaceKind::Office && local == b"document-content" {
            if self.seen_root || self.closed_root || !self.stack.is_empty() {
                return invalid("multiple or nested office:document-content roots");
            }
            self.seen_root = true;
            return Ok(Element::Root);
        }
        if namespace == NamespaceKind::Office && local == b"body" {
            if self.seen_body {
                return invalid("duplicate office:body owner");
            }
            self.seen_body = true;
            return direct(
                &self.stack,
                |parent| matches!(parent, Element::Root),
                Element::Body,
                "office:body must be the direct child of office:document-content",
            );
        }
        if namespace == NamespaceKind::Office && local == b"spreadsheet" {
            if self.seen_spreadsheet {
                return invalid("duplicate office:spreadsheet owner");
            }
            self.seen_spreadsheet = true;
            return direct(
                &self.stack,
                |parent| matches!(parent, Element::Body),
                Element::Spreadsheet,
                "office:spreadsheet must be the direct child of office:body",
            );
        }
        if self.stack.is_empty() || self.closed_root {
            return invalid("content occurs outside the canonical document root");
        }
        if namespace == NamespaceKind::Table && local == b"content-validations" {
            if !matches!(self.stack.last(), Some(Element::Spreadsheet))
                || self.seen_catalog
                || self.seen_table
                || self.spreadsheet_prelude_complete
            {
                return invalid(
                    "table:content-validations must be the unique catalog before worksheet tables",
                );
            }
            self.seen_catalog = true;
            self.catalog_active = true;
            if has_non_namespace_attributes(start) {
                self.catalog_opaque_content = true;
            }
            return Ok(Element::Catalog(self.definitions.len()));
        }
        if matches!(self.stack.last(), Some(Element::Spreadsheet))
            && namespace == NamespaceKind::Table
            && local != b"content-validations"
            && !matches!(local, b"tracked-changes" | b"calculation-settings")
        {
            self.spreadsheet_prelude_complete = true;
        }
        if namespace == NamespaceKind::Table && local == b"content-validation" {
            if !matches!(self.stack.last(), Some(Element::Catalog(_))) {
                return invalid(
                    "table:content-validation must be a direct child of table:content-validations",
                );
            }
            check_limit(
                LimitKind::Definitions,
                self.definitions.len().saturating_add(1),
                self.limits.definitions,
            )?;
            let definition = self.parse_definition(start, reader)?;
            self.definitions
                .try_reserve(1)
                .map_err(|_error| Error::AllocationFailed("definition catalog"))?;
            self.definitions.push(definition);
            let index = self.definitions.len() - 1;
            self.active_definition = Some(index);
            self.definition_state = Some(DefinitionState::default());
            return Ok(Element::Definition);
        }
        if let Some(index) = self.active_definition {
            if matches!(
                (namespace, local),
                (
                    NamespaceKind::Table,
                    b"help-message" | b"error-message" | b"error-macro"
                )
            ) {
                if !matches!(self.stack.last(), Some(Element::Definition)) {
                    return invalid("validation action must be a direct definition child");
                }
                let state = self.definition_state.as_mut().ok_or_else(|| {
                    Error::InvalidStructure("validation action state is missing".to_string())
                })?;
                match local {
                    b"help-message"
                        if !state.seen_help
                            && !state.seen_error_message
                            && !state.seen_error_macro =>
                    {
                        state.seen_help = true;
                    },
                    b"error-message" if !state.seen_error_message && !state.seen_error_macro => {
                        state.seen_error_message = true;
                    },
                    b"error-macro" if !state.seen_error_macro && !state.seen_error_message => {
                        state.seen_error_macro = true;
                    },
                    _ => return invalid("duplicate or out-of-order validation action"),
                }
            }
            // This prerequisite does not semantically own rich messages, events,
            // or foreign descendants; the exact source retains them instead.
            self.definitions[index].opaque_content = true;
        }
        if namespace == NamespaceKind::Table && local == b"table" {
            if !matches!(self.stack.last(), Some(Element::Spreadsheet)) {
                return Ok(Element::Other);
            }
            self.seen_table = true;
            check_limit(
                LimitKind::Sheets,
                self.sheets.len().saturating_add(1),
                self.limits.sheets,
            )?;
            let name = self.required_attribute(start, reader, TABLE, b"name", "table:name")?;
            let mut bindings = Vec::new();
            bindings
                .try_reserve(self.limits.bindings.min(16))
                .map_err(|_error| Error::AllocationFailed("cell bindings"))?;
            self.sheets
                .try_reserve(1)
                .map_err(|_error| Error::AllocationFailed("sheet inventory"))?;
            self.sheets.push(Sheet {
                name,
                logical_rows: 0,
                bindings,
            });
            return Ok(Element::Sheet(self.sheets.len() - 1));
        }
        if namespace == NamespaceKind::Table
            && matches!(
                local,
                b"table-header-rows" | b"table-row-group" | b"table-rows"
            )
        {
            let sheet = match self.stack.last() {
                Some(Element::Sheet(sheet) | Element::RowContainer(sheet)) => *sheet,
                _ => return Ok(Element::Other),
            };
            return Ok(Element::RowContainer(sheet));
        }
        if namespace == NamespaceKind::Table && local == b"table-row" {
            let sheet = match self.stack.last() {
                Some(Element::Sheet(sheet) | Element::RowContainer(sheet)) => *sheet,
                _ => return Ok(Element::Other),
            };
            let count = self
                .positive_attribute(
                    start,
                    reader,
                    TABLE,
                    b"number-rows-repeated",
                    "table:number-rows-repeated",
                )?
                .unwrap_or(1);
            let row = self.sheets[sheet].logical_rows;
            let end = checked_add(row, count, "repeated row extent")?;
            check_limit(LimitKind::LogicalRows, end, self.limits.logical_rows)?;
            return Ok(Element::Row {
                sheet,
                start: row,
                count,
                next_column: 0,
            });
        }
        if namespace == NamespaceKind::Table
            && matches!(local, b"table-cell" | b"covered-table-cell")
        {
            let (sheet, row, row_count, column) = match self.stack.last() {
                Some(Element::Row {
                    sheet,
                    start,
                    count,
                    next_column,
                }) => (*sheet, *start, *count, *next_column),
                _ => return Ok(Element::Other),
            };
            let column_count = self
                .positive_attribute(
                    start,
                    reader,
                    TABLE,
                    b"number-columns-repeated",
                    "table:number-columns-repeated",
                )?
                .unwrap_or(1);
            let end = checked_add(column, column_count, "repeated column extent")?;
            check_limit(LimitKind::LogicalColumns, end, self.limits.logical_columns)?;
            let validation_name =
                self.optional_attribute(start, reader, TABLE, b"content-validation-name")?;
            let Some(Element::Row { next_column, .. }) = self.stack.last_mut() else {
                return invalid("table cell lost its table-row owner");
            };
            *next_column = end;
            let bound = validation_name.is_some();
            if let Some(validation_name) = validation_name {
                if validation_name.is_empty() {
                    return invalid("table:content-validation-name must not be empty");
                }
                self.binding_count = checked_add(self.binding_count, 1, "binding counter")?;
                check_limit(
                    LimitKind::Bindings,
                    self.binding_count,
                    self.limits.bindings,
                )?;
                self.sheets[sheet]
                    .bindings
                    .try_reserve(1)
                    .map_err(|_error| Error::AllocationFailed("cell binding"))?;
                self.sheets[sheet].bindings.push(Binding {
                    row,
                    column,
                    row_count,
                    column_count,
                    validation_name,
                    definition_index: None,
                    covered: local == b"covered-table-cell",
                });
            }
            return Ok(Element::Cell(bound));
        }

        if self.active_definition.is_some() {
            if !known_definition_element(namespace, local) {
                self.mark_opaque();
            } else if let Some(index) = self.active_definition
                && has_unknown_definition_attributes(namespace, local, start, reader)?
            {
                self.definitions[index].opaque_content = true;
            }
        } else if matches!(self.stack.last(), Some(Element::Catalog(_))) {
            self.catalog_opaque_content = true;
        } else if self
            .stack
            .iter()
            .any(|element| matches!(element, Element::Cell(true)))
        {
            self.binding_opaque_content = true;
        }
        Ok(Element::Other)
    }

    fn end(&mut self) -> Result<()> {
        let element = self.stack.pop().ok_or_else(|| {
            Error::InvalidStructure("ODS content-validation element stack underflow".to_string())
        })?;
        self.finish_element(element)
    }

    fn finish_element(&mut self, element: Element) -> Result<()> {
        match element {
            Element::Root => self.closed_root = true,
            Element::Catalog(start) => {
                self.catalog_active = false;
                if self.definitions.len() == start {
                    return invalid("table:content-validations must contain a definition");
                }
            },
            Element::Definition => {
                self.active_definition = None;
                self.definition_state = None;
            },
            Element::Row {
                sheet,
                start,
                count,
                ..
            } => {
                self.sheets[sheet].logical_rows = checked_add(start, count, "row extent")?;
            },
            Element::Body
            | Element::Spreadsheet
            | Element::Sheet(_)
            | Element::RowContainer(_)
            | Element::Cell(_)
            | Element::Other => {},
        }
        Ok(())
    }

    fn finish(mut self) -> Result<Snapshot<'xml>> {
        let mut definitions = HashMap::new();
        definitions
            .try_reserve(self.definitions.len())
            .map_err(|_error| Error::AllocationFailed("definition name index"))?;
        for (index, definition) in self.definitions.iter().enumerate() {
            if definitions
                .insert(definition.name.as_str(), index)
                .is_some()
            {
                return invalid(format!(
                    "duplicate content-validation definition '{}'",
                    definition.name
                ));
            }
        }
        let mut sheet_names = HashSet::new();
        sheet_names
            .try_reserve(self.sheets.len())
            .map_err(|_error| Error::AllocationFailed("sheet name index"))?;
        let mut dangling_bindings = 0usize;
        for sheet in &mut self.sheets {
            if !sheet_names.insert(sheet.name.as_str()) {
                return invalid(format!("duplicate table name '{}'", sheet.name));
            }
            for binding in &mut sheet.bindings {
                binding.definition_index =
                    definitions.get(binding.validation_name.as_str()).copied();
                if binding.definition_index.is_none() {
                    dangling_bindings =
                        checked_add(dangling_bindings, 1, "dangling validation binding counter")?;
                }
            }
        }
        let mut definition_index = Vec::new();
        definition_index
            .try_reserve_exact(self.definitions.len())
            .map_err(|_error| Error::AllocationFailed("definition lookup index"))?;
        definition_index.extend(0..self.definitions.len());
        definition_index.sort_unstable_by(|left, right| {
            self.definitions[*left]
                .name
                .cmp(&self.definitions[*right].name)
        });
        let mut sheet_index = Vec::new();
        sheet_index
            .try_reserve_exact(self.sheets.len())
            .map_err(|_error| Error::AllocationFailed("sheet lookup index"))?;
        sheet_index.extend(0..self.sheets.len());
        sheet_index
            .sort_unstable_by(|left, right| self.sheets[*left].name.cmp(&self.sheets[*right].name));
        Ok(Snapshot {
            source_xml: self.source_xml,
            definitions: self.definitions,
            sheets: self.sheets,
            definition_index,
            sheet_index,
            catalog_opaque_content: self.catalog_opaque_content,
            binding_opaque_content: self.binding_opaque_content,
            dangling_bindings,
        })
    }

    fn parse_definition(
        &mut self,
        start: &BytesStart<'_>,
        reader: &NsReader<&[u8]>,
    ) -> Result<Definition> {
        let name = self.required_attribute(start, reader, TABLE, b"name", "table:name")?;
        if name.is_empty() {
            return invalid("content-validation name must not be empty");
        }
        let condition = self.optional_attribute(start, reader, TABLE, b"condition")?;
        let base_cell_address =
            self.optional_attribute(start, reader, TABLE, b"base-cell-address")?;
        let allow_empty_cell = self
            .optional_attribute(start, reader, TABLE, b"allow-empty-cell")?
            .map(|value| parse_bool(&value, "table:allow-empty-cell"))
            .transpose()?;
        let display_list = self
            .optional_attribute(start, reader, TABLE, b"display-list")?
            .map(|value| match value.as_str() {
                "none" => Ok(DisplayList::None),
                "unsorted" => Ok(DisplayList::Unsorted),
                "sort-ascending" => Ok(DisplayList::SortAscending),
                _ => invalid(format!("invalid table:display-list value '{value}'")),
            })
            .transpose()?;
        Ok(Definition {
            name,
            condition,
            base_cell_address,
            allow_empty_cell,
            display_list,
            opaque_content: has_unknown_definition_attributes(
                NamespaceKind::Table,
                b"content-validation",
                start,
                reader,
            )?,
        })
    }

    fn validate_attributes(
        &mut self,
        start: &BytesStart<'_>,
        reader: &NsReader<&[u8]>,
    ) -> Result<()> {
        let estimate = start.attributes().count();
        let observed = checked_add(self.attributes, estimate, "attribute counter")?;
        check_limit(LimitKind::Attributes, observed, self.limits.attributes)?;
        self.attributes = observed;
        let mut namespace_ids = AttributeNamespaceIds::with_capacity(estimate)?;
        let mut expanded = HashSet::<(usize, Vec<u8>)>::new();
        expanded
            .try_reserve(estimate)
            .map_err(|_error| Error::AllocationFailed("expanded attribute names"))?;
        for attribute in start.attributes().with_checks(true) {
            let attribute = attribute.map_err(|error| {
                Error::InvalidXml(format!("invalid ODS XML attribute: {error}"))
            })?;
            if is_namespace_declaration(attribute.key.as_ref()) {
                continue;
            }
            let (namespace, local) = reader.resolver().resolve_attribute(attribute.key);
            let namespace = namespace_bytes(&namespace)?;
            if namespace == MCE {
                return Err(Error::UnsupportedMarkupCompatibility);
            }
            let namespace_id = match attribute.key.prefix() {
                Some(prefix) => namespace_ids.id(prefix.as_ref(), namespace)?,
                None => namespace_ids.id(&[], namespace)?,
            };
            let key = (
                namespace_id,
                copy_bytes(local.as_ref(), "attribute local name")?,
            );
            if !expanded.insert(key) {
                return invalid("duplicate expanded XML attribute name");
            }
        }
        Ok(())
    }

    fn required_attribute(
        &mut self,
        start: &BytesStart<'_>,
        reader: &NsReader<&[u8]>,
        namespace: &[u8],
        local: &[u8],
        label: &str,
    ) -> Result<String> {
        self.optional_attribute(start, reader, namespace, local)?
            .ok_or_else(|| Error::InvalidStructure(format!("missing required {label}")))
    }

    fn optional_attribute(
        &mut self,
        start: &BytesStart<'_>,
        reader: &NsReader<&[u8]>,
        namespace: &[u8],
        local: &[u8],
    ) -> Result<Option<String>> {
        for attribute in start.attributes().with_checks(true) {
            let attribute = attribute.map_err(|error| {
                Error::InvalidXml(format!("invalid ODS XML attribute: {error}"))
            })?;
            let (resolved, candidate) = reader.resolver().resolve_attribute(attribute.key);
            if namespace_bytes(&resolved)? == namespace && candidate.as_ref() == local {
                let value = attribute
                    .decoded_and_normalized_value(XmlVersion::Explicit1_0, reader.decoder())
                    .map_err(|error| {
                        Error::InvalidXml(format!("invalid ODS XML attribute value: {error}"))
                    })?;
                return self.copy_text(&value).map(Some);
            }
        }
        Ok(None)
    }

    fn has_attribute(
        &self,
        start: &BytesStart<'_>,
        reader: &NsReader<&[u8]>,
        namespace: &[u8],
        local: &[u8],
    ) -> Result<bool> {
        for attribute in start.attributes().with_checks(true) {
            let attribute = attribute.map_err(|error| {
                Error::InvalidXml(format!("invalid ODS XML attribute: {error}"))
            })?;
            let (resolved, candidate) = reader.resolver().resolve_attribute(attribute.key);
            if namespace_bytes(&resolved)? == namespace && candidate.as_ref() == local {
                return Ok(true);
            }
        }
        Ok(false)
    }

    fn positive_attribute(
        &mut self,
        start: &BytesStart<'_>,
        reader: &NsReader<&[u8]>,
        namespace: &[u8],
        local: &[u8],
        label: &str,
    ) -> Result<Option<usize>> {
        self.optional_attribute(start, reader, namespace, local)?
            .map(|value| {
                value
                    .parse::<usize>()
                    .ok()
                    .filter(|value| *value > 0)
                    .ok_or_else(|| {
                        Error::InvalidStructure(format!("invalid positive {label} value '{value}'"))
                    })
            })
            .transpose()
    }

    fn copy_text(&mut self, value: &str) -> Result<String> {
        self.text_bytes = checked_add(self.text_bytes, value.len(), "retained text bytes")?;
        check_limit(
            LimitKind::TextBytes,
            self.text_bytes,
            self.limits.text_bytes,
        )?;
        let mut result = String::new();
        result
            .try_reserve_exact(value.len())
            .map_err(|_error| Error::AllocationFailed("retained text"))?;
        result.push_str(value);
        Ok(result)
    }

    fn inside_definition(&self) -> Option<usize> {
        self.active_definition
    }

    fn mark_opaque(&mut self) {
        if let Some(index) = self.inside_definition() {
            self.definitions[index].opaque_content = true;
        } else if self.catalog_active {
            self.catalog_opaque_content = true;
        } else if self
            .stack
            .iter()
            .any(|element| matches!(element, Element::Cell(true)))
        {
            self.binding_opaque_content = true;
        }
    }
}

fn namespace_kind(resolved: &ResolveResult<'_>) -> Result<NamespaceKind> {
    let value = namespace_bytes(resolved)?;
    if value == MCE {
        return Err(Error::UnsupportedMarkupCompatibility);
    }
    Ok(match value {
        OFFICE => NamespaceKind::Office,
        TABLE => NamespaceKind::Table,
        TEXT => NamespaceKind::Text,
        SCRIPT => NamespaceKind::Script,
        PRESENTATION => NamespaceKind::Presentation,
        _ => NamespaceKind::Other,
    })
}

fn namespace_bytes<'a>(resolved: &'a ResolveResult<'a>) -> Result<&'a [u8]> {
    match resolved {
        ResolveResult::Bound(Namespace(value)) => Ok(value),
        ResolveResult::Unbound => Ok(&[]),
        ResolveResult::Unknown(prefix) => Err(Error::InvalidStructure(format!(
            "unbound XML namespace prefix '{}'",
            String::from_utf8_lossy(prefix)
        ))),
    }
}

fn known_definition_element(namespace: NamespaceKind, local: &[u8]) -> bool {
    matches!(
        (namespace, local),
        (
            NamespaceKind::Table,
            b"help-message" | b"error-message" | b"error-macro"
        ) | (NamespaceKind::Office, b"event-listeners")
            | (
                NamespaceKind::Text,
                b"p" | b"span" | b"s" | b"tab" | b"line-break"
            )
            | (NamespaceKind::Script, b"event-listener")
            | (NamespaceKind::Presentation, b"event-listener" | b"sound")
    )
}

fn has_unknown_definition_attributes(
    namespace: NamespaceKind,
    local: &[u8],
    start: &BytesStart<'_>,
    reader: &NsReader<&[u8]>,
) -> Result<bool> {
    for attribute in start.attributes().with_checks(true) {
        let attribute = attribute
            .map_err(|error| Error::InvalidXml(format!("invalid ODS XML attribute: {error}")))?;
        if is_namespace_declaration(attribute.key.as_ref()) {
            continue;
        }
        let (resolved, attribute_local) = reader.resolver().resolve_attribute(attribute.key);
        let attribute_namespace = namespace_bytes(&resolved)?;
        let known = match (namespace, local) {
            (NamespaceKind::Table, b"content-validation") => {
                attribute_namespace == TABLE
                    && matches!(
                        attribute_local.as_ref(),
                        b"name"
                            | b"condition"
                            | b"base-cell-address"
                            | b"allow-empty-cell"
                            | b"display-list"
                    )
            },
            (NamespaceKind::Table, b"help-message" | b"error-message") => {
                attribute_namespace == TABLE
                    && matches!(
                        attribute_local.as_ref(),
                        b"title" | b"display" | b"message-type"
                    )
            },
            (NamespaceKind::Table, b"error-macro") => {
                attribute_namespace == TABLE && attribute_local.as_ref() == b"execute"
            },
            (NamespaceKind::Text, b"s") => {
                attribute_namespace == TEXT && attribute_local.as_ref() == b"c"
            },
            _ => false,
        };
        if !known {
            return Ok(true);
        }
    }
    Ok(false)
}

fn has_non_namespace_attributes(start: &BytesStart<'_>) -> bool {
    start
        .attributes()
        .filter_map(std::result::Result::ok)
        .any(|attribute| !is_namespace_declaration(attribute.key.as_ref()))
}

fn is_namespace_declaration(name: &[u8]) -> bool {
    name == b"xmlns" || name.starts_with(b"xmlns:")
}

fn parse_bool(value: &str, label: &str) -> Result<bool> {
    match value {
        "true" | "1" => Ok(true),
        "false" | "0" => Ok(false),
        _ => invalid(format!("invalid Boolean {label} value '{value}'")),
    }
}

fn direct(
    stack: &[Element],
    predicate: impl FnOnce(&Element) -> bool,
    value: Element,
    message: &str,
) -> Result<Element> {
    if stack.last().is_some_and(predicate) {
        Ok(value)
    } else {
        invalid(message)
    }
}

fn checked_add(left: usize, right: usize, label: &str) -> Result<usize> {
    left.checked_add(right)
        .ok_or_else(|| Error::InvalidStructure(format!("{label} overflow")))
}

fn check_limit(kind: LimitKind, observed: usize, maximum: usize) -> Result<()> {
    if observed > maximum {
        Err(Error::LimitExceeded {
            kind,
            observed,
            maximum,
        })
    } else {
        Ok(())
    }
}

fn copy_bytes(value: &[u8], owner: &'static str) -> Result<Vec<u8>> {
    let mut result = Vec::new();
    result
        .try_reserve_exact(value.len())
        .map_err(|_error| Error::AllocationFailed(owner))?;
    result.extend_from_slice(value);
    Ok(result)
}

fn invalid<T>(message: impl Into<String>) -> Result<T> {
    Err(Error::InvalidStructure(message.into()))
}

#[cfg(test)]
mod tests {
    use super::AttributeNamespaceIds;

    #[test]
    fn repeated_prefix_avoids_rehashing_namespace_uri() {
        let namespace = [b'n'; 128 * 1024];
        let mut ids = AttributeNamespaceIds::with_capacity(2_000).unwrap();
        let first = ids.id(b"vendor", &namespace).unwrap();
        for _ in 1..2_000 {
            assert_eq!(ids.id(b"vendor", &namespace).unwrap(), first);
        }
        assert_eq!(ids.namespace_content_lookups(), 1);

        assert_eq!(ids.id(b"alias", &namespace).unwrap(), first);
        assert_eq!(ids.namespace_content_lookups(), 2);
    }
}
