[package]
name = "litchi-docx"
description = "Strict, safe, and move-first WordprocessingML (.docx) APIs for Litchi."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
bitflags = { workspace = true }
caseless = { workspace = true }
litchi-ooxml-common = { workspace = true }
litchi-opc = { workspace = true }
quick-xml = { workspace = true }
thiserror = { workspace = true }
unicode-normalization = { workspace = true }
