[package]
name        = "litchi-opc"
description = "Open Packaging Conventions (OPC) implementation for the Litchi office-formats library."
version.workspace      = true
edition.workspace      = true
authors.workspace      = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true

[features]
default = []
sign = ["dep:litchi-sign"]

[dependencies]
atoi_simd     = { workspace = true }
itoa          = { workspace = true }
litchi-core   = { workspace = true }
litchi-sign   = { workspace = true, optional = true }
memchr        = { workspace = true }
quick-xml     = { workspace = true }
smallvec      = { workspace = true }
soapberry-zip = { workspace = true }
tempfile      = { workspace = true }
thiserror     = { workspace = true }

[dev-dependencies]
p256 = { workspace = true }

[lints]
workspace = true
