// Generated from the ODF 1.2 OS paragraph inline grammar.
fn is_ruby_base_child(namespace: Ns, local: &[u8]) -> bool {
    matches!((namespace, local),
        (Ns::Dr3d, b"scene") |
        (Ns::Draw, b"a") |
        (Ns::Draw, b"caption") |
        (Ns::Draw, b"circle") |
        (Ns::Draw, b"connector") |
        (Ns::Draw, b"control") |
        (Ns::Draw, b"custom-shape") |
        (Ns::Draw, b"ellipse") |
        (Ns::Draw, b"frame") |
        (Ns::Draw, b"g") |
        (Ns::Draw, b"line") |
        (Ns::Draw, b"measure") |
        (Ns::Draw, b"page-thumbnail") |
        (Ns::Draw, b"path") |
        (Ns::Draw, b"polygon") |
        (Ns::Draw, b"polyline") |
        (Ns::Draw, b"rect") |
        (Ns::Draw, b"regular-polygon") |
        (Ns::Office, b"annotation") |
        (Ns::Office, b"annotation-end") |
        (Ns::Presentation, b"date-time") |
        (Ns::Presentation, b"footer") |
        (Ns::Presentation, b"header") |
        (Ns::Text, b"a") |
        (Ns::Text, b"alphabetical-index-mark") |
        (Ns::Text, b"alphabetical-index-mark-end") |
        (Ns::Text, b"alphabetical-index-mark-start") |
        (Ns::Text, b"author-initials") |
        (Ns::Text, b"author-name") |
        (Ns::Text, b"bibliography-mark") |
        (Ns::Text, b"bookmark") |
        (Ns::Text, b"bookmark-end") |
        (Ns::Text, b"bookmark-ref") |
        (Ns::Text, b"bookmark-start") |
        (Ns::Text, b"change") |
        (Ns::Text, b"change-end") |
        (Ns::Text, b"change-start") |
        (Ns::Text, b"chapter") |
        (Ns::Text, b"character-count") |
        (Ns::Text, b"conditional-text") |
        (Ns::Text, b"creation-date") |
        (Ns::Text, b"creation-time") |
        (Ns::Text, b"creator") |
        (Ns::Text, b"database-display") |
        (Ns::Text, b"database-name") |
        (Ns::Text, b"database-next") |
        (Ns::Text, b"database-row-number") |
        (Ns::Text, b"database-row-select") |
        (Ns::Text, b"date") |
        (Ns::Text, b"dde-connection") |
        (Ns::Text, b"description") |
        (Ns::Text, b"editing-cycles") |
        (Ns::Text, b"editing-duration") |
        (Ns::Text, b"execute-macro") |
        (Ns::Text, b"expression") |
        (Ns::Text, b"file-name") |
        (Ns::Text, b"hidden-paragraph") |
        (Ns::Text, b"hidden-text") |
        (Ns::Text, b"image-count") |
        (Ns::Text, b"initial-creator") |
        (Ns::Text, b"keywords") |
        (Ns::Text, b"line-break") |
        (Ns::Text, b"measure") |
        (Ns::Text, b"meta") |
        (Ns::Text, b"meta-field") |
        (Ns::Text, b"modification-date") |
        (Ns::Text, b"modification-time") |
        (Ns::Text, b"note") |
        (Ns::Text, b"note-ref") |
        (Ns::Text, b"object-count") |
        (Ns::Text, b"page-continuation") |
        (Ns::Text, b"page-count") |
        (Ns::Text, b"page-number") |
        (Ns::Text, b"page-variable-get") |
        (Ns::Text, b"page-variable-set") |
        (Ns::Text, b"paragraph-count") |
        (Ns::Text, b"placeholder") |
        (Ns::Text, b"print-date") |
        (Ns::Text, b"print-time") |
        (Ns::Text, b"printed-by") |
        (Ns::Text, b"reference-mark") |
        (Ns::Text, b"reference-mark-end") |
        (Ns::Text, b"reference-mark-start") |
        (Ns::Text, b"reference-ref") |
        (Ns::Text, b"ruby") |
        (Ns::Text, b"s") |
        (Ns::Text, b"script") |
        (Ns::Text, b"sender-city") |
        (Ns::Text, b"sender-company") |
        (Ns::Text, b"sender-country") |
        (Ns::Text, b"sender-email") |
        (Ns::Text, b"sender-fax") |
        (Ns::Text, b"sender-firstname") |
        (Ns::Text, b"sender-initials") |
        (Ns::Text, b"sender-lastname") |
        (Ns::Text, b"sender-phone-private") |
        (Ns::Text, b"sender-phone-work") |
        (Ns::Text, b"sender-position") |
        (Ns::Text, b"sender-postal-code") |
        (Ns::Text, b"sender-state-or-province") |
        (Ns::Text, b"sender-street") |
        (Ns::Text, b"sender-title") |
        (Ns::Text, b"sequence") |
        (Ns::Text, b"sequence-ref") |
        (Ns::Text, b"sheet-name") |
        (Ns::Text, b"soft-page-break") |
        (Ns::Text, b"span") |
        (Ns::Text, b"subject") |
        (Ns::Text, b"tab") |
        (Ns::Text, b"table-count") |
        (Ns::Text, b"table-formula") |
        (Ns::Text, b"template-name") |
        (Ns::Text, b"text-input") |
        (Ns::Text, b"time") |
        (Ns::Text, b"title") |
        (Ns::Text, b"toc-mark") |
        (Ns::Text, b"toc-mark-end") |
        (Ns::Text, b"toc-mark-start") |
        (Ns::Text, b"user-defined") |
        (Ns::Text, b"user-field-get") |
        (Ns::Text, b"user-field-input") |
        (Ns::Text, b"user-index-mark") |
        (Ns::Text, b"user-index-mark-end") |
        (Ns::Text, b"user-index-mark-start") |
        (Ns::Text, b"variable-get") |
        (Ns::Text, b"variable-input") |
        (Ns::Text, b"variable-set") |
        (Ns::Text, b"word-count")
    )
}

fn is_hyperlink_child(namespace: Ns, local: &[u8]) -> bool {
    matches!((namespace, local),
        (Ns::Dr3d, b"scene") |
        (Ns::Draw, b"a") |
        (Ns::Draw, b"caption") |
        (Ns::Draw, b"circle") |
        (Ns::Draw, b"connector") |
        (Ns::Draw, b"control") |
        (Ns::Draw, b"custom-shape") |
        (Ns::Draw, b"ellipse") |
        (Ns::Draw, b"frame") |
        (Ns::Draw, b"g") |
        (Ns::Draw, b"line") |
        (Ns::Draw, b"measure") |
        (Ns::Draw, b"page-thumbnail") |
        (Ns::Draw, b"path") |
        (Ns::Draw, b"polygon") |
        (Ns::Draw, b"polyline") |
        (Ns::Draw, b"rect") |
        (Ns::Draw, b"regular-polygon") |
        (Ns::Office, b"annotation") |
        (Ns::Office, b"annotation-end") |
        (Ns::Presentation, b"date-time") |
        (Ns::Presentation, b"footer") |
        (Ns::Presentation, b"header") |
        (Ns::Text, b"alphabetical-index-mark") |
        (Ns::Text, b"alphabetical-index-mark-end") |
        (Ns::Text, b"alphabetical-index-mark-start") |
        (Ns::Text, b"author-initials") |
        (Ns::Text, b"author-name") |
        (Ns::Text, b"bibliography-mark") |
        (Ns::Text, b"bookmark") |
        (Ns::Text, b"bookmark-end") |
        (Ns::Text, b"bookmark-ref") |
        (Ns::Text, b"bookmark-start") |
        (Ns::Text, b"change") |
        (Ns::Text, b"change-end") |
        (Ns::Text, b"change-start") |
        (Ns::Text, b"chapter") |
        (Ns::Text, b"character-count") |
        (Ns::Text, b"conditional-text") |
        (Ns::Text, b"creation-date") |
        (Ns::Text, b"creation-time") |
        (Ns::Text, b"creator") |
        (Ns::Text, b"database-display") |
        (Ns::Text, b"database-name") |
        (Ns::Text, b"database-next") |
        (Ns::Text, b"database-row-number") |
        (Ns::Text, b"database-row-select") |
        (Ns::Text, b"date") |
        (Ns::Text, b"dde-connection") |
        (Ns::Text, b"description") |
        (Ns::Text, b"editing-cycles") |
        (Ns::Text, b"editing-duration") |
        (Ns::Text, b"execute-macro") |
        (Ns::Text, b"expression") |
        (Ns::Text, b"file-name") |
        (Ns::Text, b"hidden-paragraph") |
        (Ns::Text, b"hidden-text") |
        (Ns::Text, b"image-count") |
        (Ns::Text, b"initial-creator") |
        (Ns::Text, b"keywords") |
        (Ns::Text, b"line-break") |
        (Ns::Text, b"measure") |
        (Ns::Text, b"meta") |
        (Ns::Text, b"meta-field") |
        (Ns::Text, b"modification-date") |
        (Ns::Text, b"modification-time") |
        (Ns::Text, b"note") |
        (Ns::Text, b"note-ref") |
        (Ns::Text, b"object-count") |
        (Ns::Text, b"page-continuation") |
        (Ns::Text, b"page-count") |
        (Ns::Text, b"page-number") |
        (Ns::Text, b"page-variable-get") |
        (Ns::Text, b"page-variable-set") |
        (Ns::Text, b"paragraph-count") |
        (Ns::Text, b"placeholder") |
        (Ns::Text, b"print-date") |
        (Ns::Text, b"print-time") |
        (Ns::Text, b"printed-by") |
        (Ns::Text, b"reference-mark") |
        (Ns::Text, b"reference-mark-end") |
        (Ns::Text, b"reference-mark-start") |
        (Ns::Text, b"reference-ref") |
        (Ns::Text, b"ruby") |
        (Ns::Text, b"s") |
        (Ns::Text, b"script") |
        (Ns::Text, b"sender-city") |
        (Ns::Text, b"sender-company") |
        (Ns::Text, b"sender-country") |
        (Ns::Text, b"sender-email") |
        (Ns::Text, b"sender-fax") |
        (Ns::Text, b"sender-firstname") |
        (Ns::Text, b"sender-initials") |
        (Ns::Text, b"sender-lastname") |
        (Ns::Text, b"sender-phone-private") |
        (Ns::Text, b"sender-phone-work") |
        (Ns::Text, b"sender-position") |
        (Ns::Text, b"sender-postal-code") |
        (Ns::Text, b"sender-state-or-province") |
        (Ns::Text, b"sender-street") |
        (Ns::Text, b"sender-title") |
        (Ns::Text, b"sequence") |
        (Ns::Text, b"sequence-ref") |
        (Ns::Text, b"sheet-name") |
        (Ns::Text, b"soft-page-break") |
        (Ns::Text, b"span") |
        (Ns::Text, b"subject") |
        (Ns::Text, b"tab") |
        (Ns::Text, b"table-count") |
        (Ns::Text, b"table-formula") |
        (Ns::Text, b"template-name") |
        (Ns::Text, b"text-input") |
        (Ns::Text, b"time") |
        (Ns::Text, b"title") |
        (Ns::Text, b"toc-mark") |
        (Ns::Text, b"toc-mark-end") |
        (Ns::Text, b"toc-mark-start") |
        (Ns::Text, b"user-defined") |
        (Ns::Text, b"user-field-get") |
        (Ns::Text, b"user-field-input") |
        (Ns::Text, b"user-index-mark") |
        (Ns::Text, b"user-index-mark-end") |
        (Ns::Text, b"user-index-mark-start") |
        (Ns::Text, b"variable-get") |
        (Ns::Text, b"variable-input") |
        (Ns::Text, b"variable-set") |
        (Ns::Text, b"word-count")
    )
}
